//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ChartEnvSetupDlgAddIn.rc
//
#define IDS_MSG_LINE_SHAPE              1
#define IDS_MSG_LINE_THICK              2
#define IDS_MSG_PRICECHART_ADD          3
#define IDS_MSG_PRICECHART_DEL          4
#define IDS_COLOR_SET                   5
#define IDS_MSG_SETTING_98              6
#define IDS_MSG_ENV_SETTING             7
#define IDS_COLOR_START                 8
#define IDS_COLOR_END                   9
#define IDS_STANDART_HL                 10
#define IDS_STANDART_HLC                11
#define IDS_STRING_SIMPLE               12
#define IDS_STRING_INDEX                13
#define IDS_STRING_WEIGHTED             14
#define IDS_STRING_FITNESS              15
#define IDS_STRING_COLOR                16
#define IDS_HORZ_LINE                   17
#define IDS_VERT_LINE                   18
#define IDS_STRING_SETTING              19
#define IDS_STRING_DESCRIPT             20
#define IDS_CURRENT_STYLE               21
#define IDS_STRING_UP                   22
#define IDS_STRING_DOWN                 23
#define IDS_STRING_STEADY               24
#define IDS_MSG_SAME_NAME               25
#define IDS_MSG_EXIST_MIN               26
#define IDS_TAB_INDICATOR_SET           27
#define IDS_TAB_BASE_SET                28
#define IDS_TAB_STYLE_SET               29
#define IDS_TAB_ANAL_SET                30
#define IDS_STRING_STANDARD             31
#define IDS_STRING_CALC                 32
#define IDS_STRING_SWING_LINE           33
#define IDS_STRING_KAGI_LINE            34
#define IDS_LINE_COLOR                  35
#define IDS_BAR_COLOR                   36
#define IDS_BASIC_OFFER                 37
#define IDS_BASIC_OFFER_TEXT            38
#define IDS_CUR_OFFER                   39
#define IDS_CUR_OFFER_TEXT              40
#define IDS_BUY_TEXT                    41
#define IDS_BUY                         42
#define IDS_SELL_TEXT                   43
#define IDS_SELL                        44
#define IDS_STRING_FILL                 45
#define IDS_STRING_FONT                 46
#define IDS_MA_PERIOD                   47
#define IDS_PERIOD                      48
#define IDS_INC_INTERVAL                49
#define IDS_MA_LINE_NUM                 50
#define IDS_INTERVAL_NUM                51
#define IDS_STANDARD_PERIOD             52
#define IDS_CONVERSE_PERIOD             53
#define IDS_SD_MULTI                    54
#define IDS_BULK_NUM                    55
#define IDS_UPPER_PER                   56
#define IDS_LOWER_PER                   57
#define IDS_REVERSE_PER                 58
#define IDS_DISPARITY                   59
#define IDS_DISPARITY_PERIOD            60
#define IDS_SHORT_TERM                  61
#define IDS_LONG_TERM                   62
#define IDS_STRING_SD                   63
#define IDS_SHORT_MA                    64
#define IDS_LONG_MA                     65
#define IDS_MOMENTUM_PERIOD             66
#define IDS_MOMENTUM                    67
#define IDS_COMPARE_PERIOD              68
#define IDS_PSYCHOLOGY_PERIOD           69
#define IDS_SE_MULTI                    70
#define IDS_ACC_VARIABLE                71
#define IDS_MAX_VALUE                   72
#define IDS_CUMULATIVE_PERIOD           73
#define IDS_BASE_LINE                   74
#define IDS_HORIZONTAL_LINE             76
#define IDS_MSG_INIT                    77
#define IDS_MSG_INIT_TITLE              78
#define IDS_USED_INDICATOR              79
#define IDS_OVERHANGING_BAR_COUNT       80
#define IDS_COUNT                       81
#define IDS_OVERHANGING_BAR_WIDTH       82
#define IDS_PRICE_UNIT                  83
#define IDS_MAX_TEXT                    84
#define IDS_TOTAL_TEXT                  85
#define IDS_LOWHIGH_MARK_STR_1          86
#define IDS_LOWHIGH_MARK_STR_2          87
#define IDS_LOWHIGH_MARK_STR_3          88
#define IDS_LOWHIGH_MARK_STR_4          89
#define IDS_LOWHIGH_MARK_STR_5          90
#define IDS_PRE                         91
#define IDS_POST                        92
#define IDD_MAINTAB_PAGE_BASE_ENV_HTS   101
#define IDD_SUBTAB_PAGE_EXP             105
#define IDC_HORIZONTAL                  1000
#define IDD_GRAPH_SETTING               1002
#define IDC_SPIN1                       1004
#define IDD_PRICE                       1006
#define IDD_VOLUME                      1007
#define IDC_INSERT                      1007
#define IDC_DELETE                      1008
#define IDC_ALLDELETE                   1009
#define IDC_HORIZONTAL_LIST             1012
#define IDC_FILL_UP                     1015
#define IDB_SPECIAL_STYLE               1015
#define IDC_USE_REVISED_PRICE           1015
#define IDC_EACH_BUY_SELL               1015
#define IDB_BONG_STYLE                  1016
#define IDC_SHOW_MIN_MAX_PRICE          1016
#define IDC_LOG                         1017
#define IDB_LINE_STYLE                  1017
#define IDC_HIDE_ALL_TITLE              1017
#define IDC_INVERT                      1018
#define IDC_SPIN                        1018
#define IDB_PIE_STYLE                   1018
#define IDC_FIX_INTERVAL                1018
#define IDB_BAR_STYLE                   1019
#define IDC_DRAWSTYLE                   1021
#define IDC_THICKNESS                   1022
#define IDC_SHOW_LOWHIGH_MARKER         1023
#define IDC_FILL                        1024
#define IDC_INDICATORLIST               1030
#define IDC_DISPLAY_BASELINE            1032
#define IDC_CHK_LH_LC_HC                1033
#define IDC_CHECK_SHOWARROW             1035
#define IDC_FILL_DOWN                   1035
#define IDD_INDICATOR_LIST              1035
#define IDC_COLOR_BUTTON                1038
#define IDC_SIGNAL                      1039
#define IDC_ALL_DELETE                  1040
#define IDC_SIMPLE_VOLUME               1043
#define IDC_UPDOWN_VOLUME               1044
#define IDC_BONG_CHART                  1045
#define IDC_SAME_BONG                   1045
#define IDC_BAR_CHART                   1046
#define IDC_UPDOWN_PRICE                1046
#define IDC_LINE_CHART                  1047
#define IDC_FLOW_CHART                  1048
#define IDC_NEWBAR_CHART                1049
#define IDC_CANDLEVOLUME_CHART          1050
#define IDC_DRAWSTYLE_STATIC            1051
#define IDC_THICKNESS_STATIC            1052
#define IDD_PRICEMA                     1053
#define IDC_EQUIVOLUME_CHART            1053
#define IDC_NOT_CANDLE                  1054
#define IDC_STEADY_NORMAL               1075
#define IDC_STEADY_BEFORECLOSE          1076
#define IDC_STEADY_SAMECLOSE            1077
#define IDC_CHK_WITH_DEFAULT            1097
#define IDC_CANDLE_ONLY                 2011
#define IDC_IMAGENARY_CANDLE            2012
#define IDC_TRENDLINE_COLOR             2014
#define IDC_SHOW_HIGH_LOW_BOUND         2023
#define IDC_SHOW_EXRIGHT_DIVIDEND       2027
#define IDC_SHOW_CURRENT_PRICE          2032
#define IDC_INDICATOR_VARIABLE          2033
#define IDC_INDICATOR_VALUE             2034
#define IDC_Y_SCALE_POSITION_LEFTSIDE   2035
#define IDC_Y_SCALE_POSITION_RIGHTSIDE  2036
#define IDC_MAINTAB_ALL                 5000
#define IDC_BTN_TOP_INDICATOR           5004
#define IDC_BTN_USE_INDICATOR           5005
#define IDD_ENV_SETUP_ALL               6000
#define IDD_MAINTAB_PAGE_STYLE          6001
#define IDD_MAINTAB_PAGE_INDICATOR      6002
#define IDB_LINE_THICKNESS              6007
#define IDD_MAINTAB_PAGE_ANALYSIS       6008
#define IDB_LINE_STYLE2                 6008
#define IDD_SPECIAL_TYPE_B              6012
#define IDD_SPECIAL_TYPE_A              6013
#define IDD_COMMON_TYPE_A               6015
#define IDD_GLANCEBALANCE               6022
#define IDC_INQUIRYDATA_WINDOW_SHOW     6024
#define IDD_SPECIAL_TYPE_C              6026
#define IDC_INQUIRYDATA_WINDOW_MOVETYPE_MANUAL 6026
#define IDD_SPECIAL_TYPE_D              6027
#define IDC_INQUIRYDATA_WINDOW_MOVETYPE_MANUAL2 6027
#define IDC_STATIC_INDICATOR_NAME       6028
#define IDD_SPECIAL_TYPE_E              6034
#define IDD_COMMON_TYPE_B               6035
#define IDC_BTN_UP                      6036
#define IDC_BTN_DOWN                    6037
#define IDC_STATIC_UP                   6038
#define IDC_STATIC_DOWN                 6039
#define IDC_INITILIZE_ALLINDICATOR      6045
#define IDC_DEFAULT_INDICATORDATA       6046
#define IDC_STATIC_VALUE                6055
#define IDC_STATIC_DATA_TITLE           6057
#define IDC_CMB_DATA                    6059
#define IDC_COMPOSITION                 6060
#define IDC_COMPOSITION_EACH            6062
#define IDC_COMPOSITION_TITLE           6063
#define IDC_BTN_COMPOSITION_COLOR       6069
#define IDC_CMB_THICKNESS               6070
#define IDC_CMB_LINETYPE                6071
#define IDC_BASELINE                    6072
#define IDC_CMB_THICKNESS2              6073
#define IDC_CMB_LINETYPE2               6074
#define IDC_COMPOSITION_LINETITLE       6092
#define IDC_EDIT_COMPOSITION_TITLEDATA  6095
#define IDC_EDIT_VALUE1                 6096
#define IDC_EDIT_VALUE2                 6097
#define IDC_EDIT_VALUE3                 6098
#define IDC_EDIT_VALUE4                 6099
#define IDC_EDIT_VALUE5                 6100
#define IDC_LIST_COMPOSITION            6101
#define IDC_STATIC_VALUE1               6102
#define IDC_STATIC_VALUE2               6103
#define IDC_STATIC_VALUE3               6104
#define IDC_STATIC_VALUE4               6105
#define IDC_STATIC_VALUE5               6106
#define IDC_SPIN_VALUE1                 6107
#define IDC_SPIN_VALUE2                 6108
#define IDC_SPIN_VALUE3                 6109
#define IDC_SPIN_VALUE4                 6110
#define IDC_SPIN_VALUE5                 6111
#define IDC_STATIC_VALUE6               6112
#define IDC_STATIC_VALUE7               6113
#define IDC_EDIT_VALUE6                 6114
#define IDC_SPIN_VALUE6                 6115
#define IDC_BTN_SAVE                    6116
#define IDC_EDIT_VALUE7                 6116
#define IDC_BTN_PREVIEW                 6117
#define IDC_SPIN_VALUE7                 6117
#define IDC_BTN_RECOVER                 6118
#define IDC_EDIT_RIGHT_MARGIN           6129
#define IDC_SPIN_IDC_EDIT_RIGHT_MARGIN  6130
#define IDC_EDIT_UPDOWN_SPACE           6131
#define IDC_SPIN_IDC_EDIT_UPDOWN_SPACE  6132
#define IDC_USE_CROSS_LINE              6133
#define IDC_SUBDLG_SETUP                6134
#define IDC_USE_TOOLTIP_SHOW            6134
#define IDC_STATIC_STEADY               6135
#define IDC_STATIC_CUR_PRICE            6135
#define IDC_CUR_PRICE_1                 6136
#define IDC_CUR_PRICE_2                 6137
#define IDC_BTN_STEADY                  6138
#define ID_BTN_PREVIEW                  6138
#define IDC_EDT_FUTURE_TIME             6138
#define IDC_SPIN_FUTURE_TIME            6139
#define IDC_BTN_UP_COLOR                6140
#define IDC_USE_GAP_REVISION            6140
#define IDC_STATIC_SAME_CANDLE          6141
#define IDC_BTN_DOWN_COLOR              6141
#define IDC_USE_GAP_MONTHREV            6141
#define IDC_CHECK_UP                    6142
#define IDC_BTN_STEADY_COLOR            6142
#define IDC_DAY_YEAR_GUBUN              6142
#define IDC_CHECK_DOWN                  6143
#define IDC_BTN_UP1                     6143
#define IDC_WEEK_YEAR_GUBUN             6143
#define IDC_BTN_DOWN1                   6144
#define IDC_WEEK_MON_GUBUN              6144
#define IDC_MON_YEAR_GUBUN              6145
#define IDC_TICK_GUBUN                  6146
#define IDC_DAY_WEEK_GUBUN              6147
#define IDC_DAY_MON_GUBUN               6148
#define IDC_FILL_LINE                   6150
#define IDC_FILL_COLOR                  6151
#define IDC_CHK_FILL_COLOR              6155
#define IDC_CHECK_FILLUP                6155
#define IDC_BTN_COLOR                   6156
#define IDC_RADIO1                      6156
#define IDC_EDIT1                       6157
#define IDC_EDIT_BLOCKSIZE              6158
#define IDC_RADIO2                      6158
#define IDC_RADIO3                      6159
#define IDC_RADIO4                      6160
#define IDC_LINE_TYPE                   6161
#define IDC_BTN_COLOR1                  6162
#define IDC_BTN_COLOR2                  6163
#define IDC_BTN_COLOR3                  6164
#define IDC_BTN_COLOR4                  6165
#define IDC_BTN_COLOR5                  6166
#define IDC_BTN_COLOR6                  6167
#define IDC_STATIC_TEXT_TYPE            6168
#define IDC_EDIT_BLOCKCHANGE            6169
#define IDC_STATIC_BLOCKCHANGE          6170
#define IDC_STATIC_BLOCKSIZE            6171
#define IDC_UPFILL                      7009
#define IDC_DOWNFILL                    7010
#define IDC_GRID_WIDTH                  7014
#define IDC_GRID_HEIGHT                 7015
#define IDC_ADD_STYLE                   7016
#define IDC_DEL_STYLE                   7017
#define IDC_STYLECOMBO                  7019
#define IDC_RESET_STYLE                 7020
#define IDC_UPBUTTON                    7022
#define IDC_DOWNBUTTON                  7023
#define IDC_EQUALBUTTON                 7024
#define IDC_GRAPH_BACKGROUND            7034
#define IDC_GRAPH_BORDER                7037
#define IDC_SCALE_BACKGROUND            7038
#define IDC_SCALE_BORDER                7039
#define IDC_GRAPH_GRID                  7040
#define IDC_ANALYZE_COLOR               7041
#define IDC_NUMERICAL_COLOR             7042
#define IDC_DIVIDE_RADIO                7044
#define IDC_DIVIDE_R1                   7045
#define IDC_DIVIDE_R2                   7046
#define IDC_DIVIDE_R3                   7047
#define IDC_INDICESCOMBO                7048
#define IDC_AVERAGECOMBO                7049
#define IDC_AVERAGE_BT                  7050
#define IDC_SCALE_TEXT                  7051
#define IDC_SCALE_GRID                  7052
#define IDC_DIVIDECOMBO                 7053
#define IDC_DRAW_STATIC                 7054
#define IDC_BTN_HSCALE_GRIDCOLOR_DAY    7055
#define IDC_BTN_HSCALE_GRIDCOLOR_WEEK   7056
#define IDC_BTN_HSCALE_GRIDCOLOR_MON    7057
#define IDC_BTN_HSCALE_GRIDCOLOR_YEAR   7058
#define IDC_CMB_HSCALE_GRIDTYPE_DAY     7059
#define IDC_CMB_HSCALE_GRIDTYPE_WEEK    7060
#define IDC_CMB_HSCALE_GRIDTYPE_MON     7061
#define IDC_CMB_HSCALE_GRIDTYPE_YEAR    7062
#define IDC_SCALELINE_THICKNESS_DAY     7063
#define IDC_SCALELINE_THICKNESS_WEEK    7064
#define IDC_SCALELINE_THICKNESS_MON     7065
#define IDC_SCALELINE_THICKNESS_YEAR    7066
#define IDC_STC_THICKNESS               8000
#define IDC_STC_COLOR                   8001
#define IDD_SUBTAB_PAGE_SETUP           8001
#define IDC_CHECK_FILLDOWN              8002
#define IDC_GUGAN_RADIO                 8003
#define IDC_HOGA_RADIO                  8004
#define IDC_SUBTAB_ALL                  8004
#define IDD_PRICEMA_CONDITION           8004
#define IDC_COND_TITLE                  8005
#define IDD_VOLUMEMA_CONDITION          8006
#define IDC_BY_STATIC                   8006
#define IDC_SELL_STATIC                 8007
#define IDD_VOLUMEMA                    8008
#define IDC_MAX_STATIC                  8008
#define IDC_BYFONT_STATIC               8009
#define IDD_MAINTAB_PAGE_BASE_ENV_DEV   8009
#define IDC_SELLFONT_STATIC             8010
#define IDD_MAINTAB_PAGE_BASE_ENV_FX    8010
#define IDC_CHECK_ALL                   8011
#define IDC_MAXFONT_STATIC              8011
#define IDD_MAINTAB_PAGE_BASE_ENV_WORLDON 8011
#define IDC_PRICEMA_CONDITION           8012
#define IDC_STATIC_INDICATOR_INFO       8012
#define IDC_SHOW_TREND                  8013
#define IDC_BTN_DELETE_ALL              8013
#define IDC_BTN_DELETE                  8014
#define IDC_COND_UNIT                   8014
#define IDC_SHOW_VERTICAL               8015
#define IDC_BTN_ADD                     8015
#define IDC_SHOW_HORIZON                8016
#define IDC_BTN_ADD_ALL                 8016
#define IDC_SHOW_THREE                  8017
#define IDC_BTN_WITH_DEFAULT            8017
#define IDC_SHOW_FOUR                   8018
#define IDC_SHOW_FIBO                   8019
#define IDC_SHOW_HORIZON_RIGHT          8020
#define IDC_CANDLETYPE_ONSIZE1          8026
#define IDC_CANDLETYPE_ONSIZE2          8027
#define IDC_CUR_PRICE_3                 8031
#define IDC_CUR_PRICE_4                 8032
#define IDC_CMB_COMPCOLOR               8033
#define IDC_STATIC_COMPCOLOR            8034
#define IDC_NOT_CANDLE_TYPE             8035
#define IDC_NOT_CANDLE_STYLE            8036
#define IDC_BARTYPE_STATIC              8036
#define IDC_STC_FUTURE_TIME             8037
#define IDC_FILL_NONE                   8038
#define IDC_RDO_LH_LC_HC                8039
#define IDC_RDO_OHLC                    8040
#define IDC_RDO_NONE                    8041
#define IDC_USE_TOOLTIP_SHOW_ALL        8042
#define IDC_CUR_PRICE_TYPE_COMBO        8043
#define IDC_CUR_PRICE_TYPE_PREDAY       8044
#define IDC_CUR_PRICE_TYPE_PREBONG      8045
#define IDC_COMBO_MOUSEWHEEL            8046
#define IDC_RDO_CURPRICE                8047
#define IDC_RDO_STANDPRICE              8048
#define IDC_THICKNESS_ALL               8108
#define IDC_DRAWSTYLE_ALL               8109
#define IDC_STATIC_PACKET_ALL           8113
#define IDC_STATIC_CALCMETHOD_ALL       8114
#define IDC_VOLUMEMA_CONDITION          8115
#define IDC_CMB_PACKET0                 9000
#define IDC_CMB_PACKET1                 9001
#define IDC_CMB_PACKET2                 9002
#define IDC_CMB_PACKET3                 9003
#define IDC_CMB_PACKET4                 9004
#define IDC_CMB_PACKET5                 9005
#define IDC_CMB_PACKET6                 9006
#define IDC_CMB_PACKET7                 9007
#define IDC_CMB_PACKET8                 9008
#define IDC_CMB_PACKET9                 9009
#define IDC_CMB_PACKET10                9010
#define IDC_CMB_PACKET11                9011
#define IDC_CMB_PACKET12                9012
#define IDC_CMB_PACKET13                9013
#define IDC_CMB_PACKET14                9014
#define IDC_CMB_PACKET15                9015
#define IDC_CMB_PACKET16                9016
#define IDC_CMB_PACKET17                9017
#define IDC_CMB_PACKET18                9018
#define IDC_CMB_PACKET19                9019
#define IDC_CMB_CALCMETHOD0             9030
#define IDC_CMB_CALCMETHOD1             9031
#define IDC_CMB_CALCMETHOD2             9032
#define IDC_CMB_CALCMETHOD3             9033
#define IDC_CMB_CALCMETHOD4             9034
#define IDC_CMB_CALCMETHOD5             9035
#define IDC_CMB_CALCMETHOD6             9036
#define IDC_CMB_CALCMETHOD7             9037
#define IDC_CMB_CALCMETHOD8             9038
#define IDC_CMB_CALCMETHOD9             9039
#define IDC_CMB_CALCMETHOD10            9040
#define IDC_CMB_CALCMETHOD11            9041
#define IDC_CMB_CALCMETHOD12            9042
#define IDC_CMB_CALCMETHOD13            9043
#define IDC_CMB_CALCMETHOD14            9044
#define IDC_CMB_CALCMETHOD15            9045
#define IDC_CMB_CALCMETHOD16            9046
#define IDC_CMB_CALCMETHOD17            9047
#define IDC_CMB_CALCMETHOD18            9048
#define IDC_CMB_CALCMETHOD19            9049
#define IDC_DRAWSTYLE0                  9060
#define IDC_DRAWSTYLE1                  9061
#define IDC_DRAWSTYLE2                  9062
#define IDC_DRAWSTYLE3                  9063
#define IDC_DRAWSTYLE4                  9064
#define IDC_DRAWSTYLE5                  9065
#define IDC_DRAWSTYLE6                  9066
#define IDC_DRAWSTYLE7                  9067
#define IDC_DRAWSTYLE8                  9068
#define IDC_DRAWSTYLE9                  9069
#define IDC_DRAWSTYLE10                 9070
#define IDC_DRAWSTYLE11                 9071
#define IDC_DRAWSTYLE12                 9072
#define IDC_DRAWSTYLE13                 9073
#define IDC_DRAWSTYLE14                 9074
#define IDC_DRAWSTYLE15                 9075
#define IDC_DRAWSTYLE16                 9076
#define IDC_DRAWSTYLE17                 9077
#define IDC_DRAWSTYLE18                 9078
#define IDC_DRAWSTYLE19                 9079
#define IDC_CHECK_SHOW_GRAPH0           9100
#define IDC_CHECK_SHOW_GRAPH1           9101
#define IDC_CHECK_SHOW_GRAPH2           9102
#define IDC_CHECK_SHOW_GRAPH3           9103
#define IDC_CHECK_SHOW_GRAPH4           9104
#define IDC_CHECK_SHOW_GRAPH5           9105
#define IDC_CHECK_SHOW_GRAPH6           9106
#define IDC_CHECK_SHOW_GRAPH7           9107
#define IDC_CHECK_SHOW_GRAPH8           9108
#define IDC_CHECK_SHOW_GRAPH9           9109
#define IDC_CHECK_SHOW_GRAPH10          9110
#define IDC_CHECK_SHOW_GRAPH11          9111
#define IDC_CHECK_SHOW_GRAPH12          9112
#define IDC_CHECK_SHOW_GRAPH13          9113
#define IDC_CHECK_SHOW_GRAPH14          9114
#define IDC_CHECK_SHOW_GRAPH15          9115
#define IDC_CHECK_SHOW_GRAPH16          9116
#define IDC_CHECK_SHOW_GRAPH17          9117
#define IDC_CHECK_SHOW_GRAPH18          9118
#define IDC_CHECK_SHOW_GRAPH19          9119
#define IDC_COND_GRAPH0                 9140
#define IDC_COND_GRAPH1                 9141
#define IDC_COND_GRAPH2                 9142
#define IDC_COND_GRAPH3                 9143
#define IDC_COND_GRAPH4                 9144
#define IDC_COND_GRAPH5                 9145
#define IDC_COND_GRAPH6                 9146
#define IDC_COND_GRAPH7                 9147
#define IDC_COND_GRAPH8                 9148
#define IDC_COND_GRAPH9                 9149
#define IDC_COND_GRAPH10                9150
#define IDC_COND_GRAPH11                9151
#define IDC_COND_GRAPH12                9152
#define IDC_COND_GRAPH13                9153
#define IDC_COND_GRAPH14                9154
#define IDC_COND_GRAPH15                9155
#define IDC_COND_GRAPH16                9156
#define IDC_COND_GRAPH17                9157
#define IDC_COND_GRAPH18                9158
#define IDC_COND_GRAPH19                9159
#define IDC_THICKNESS0                  9180
#define IDC_THICKNESS1                  9181
#define IDC_THICKNESS2                  9182
#define IDC_THICKNESS3                  9183
#define IDC_THICKNESS4                  9184
#define IDC_THICKNESS5                  9185
#define IDC_THICKNESS6                  9186
#define IDC_THICKNESS7                  9187
#define IDC_THICKNESS8                  9188
#define IDC_THICKNESS9                  9189
#define IDC_THICKNESS10                 9190
#define IDC_THICKNESS11                 9191
#define IDC_THICKNESS12                 9192
#define IDC_THICKNESS13                 9193
#define IDC_THICKNESS14                 9194
#define IDC_THICKNESS15                 9195
#define IDC_THICKNESS16                 9196
#define IDC_THICKNESS17                 9197
#define IDC_THICKNESS18                 9198
#define IDC_THICKNESS19                 9199
#define IDC_SPIN_COND0                  9220
#define IDC_SPIN_COND1                  9221
#define IDC_SPIN_COND2                  9222
#define IDC_SPIN_COND3                  9223
#define IDC_SPIN_COND4                  9224
#define IDC_SPIN_COND5                  9225
#define IDC_SPIN_COND6                  9226
#define IDC_SPIN_COND7                  9227
#define IDC_SPIN_COND8                  9228
#define IDC_SPIN_COND9                  9229
#define IDC_SPIN_COND10                 9230
#define IDC_SPIN_COND11                 9231
#define IDC_SPIN_COND12                 9232
#define IDC_SPIN_COND13                 9233
#define IDC_SPIN_COND14                 9234
#define IDC_SPIN_COND15                 9235
#define IDC_SPIN_COND16                 9236
#define IDC_SPIN_COND17                 9237
#define IDC_SPIN_COND18                 9238
#define IDC_SPIN_COND19                 9239
#define IDC_COLOR_BUTTON0               9260
#define IDC_COLOR_BUTTON1               9261
#define IDC_COLOR_BUTTON2               9262
#define IDC_COLOR_BUTTON3               9263
#define IDC_COLOR_BUTTON4               9264
#define IDC_COLOR_BUTTON5               9265
#define IDC_COLOR_BUTTON6               9266
#define IDC_COLOR_BUTTON7               9267
#define IDC_COLOR_BUTTON8               9268
#define IDC_COLOR_BUTTON9               9269
#define IDC_COLOR_BUTTON10              9270
#define IDC_COLOR_BUTTON11              9271
#define IDC_COLOR_BUTTON12              9272
#define IDC_COLOR_BUTTON13              9273
#define IDC_COLOR_BUTTON14              9274
#define IDC_COLOR_BUTTON15              9275
#define IDC_COLOR_BUTTON16              9276
#define IDC_COLOR_BUTTON17              9277
#define IDC_COLOR_BUTTON18              9278
#define IDC_COLOR_BUTTON19              9279
#define IDC_BTN_COLOR_START             10000
#define IDC_BTN_COLOR_END               10001
#define IDC_BTN_COLOR_TURN_DOWN         10002
#define IDC_BTN_COLOR_TURN_UP           10003
#define IDC_BTN_COLOR_SELL              10004
#define IDC_BTN_COLOR_BUY               10005
#define IDC_BTN_COLOR_KEEP_SELL         10006
#define IDC_BTN_COLOR_KEEP_BUY          10007
#define IDC_BTN_COLOR_HOLD_SELL         10008
#define IDC_BTN_COLOR_HOLD_BUY          10009

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        8008
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         8049
#define _APS_NEXT_SYMED_VALUE           8000
#endif
#endif
