//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by D:\User\BaeSeungWon\~$Chart Working Folder\Project6\CHARTFORMULATE\RES\ChartFormulate_Eng\ChartFormulate_Eng.rc
//
#define IDS_EX_RIGHTS                   1
#define IDS_EX_DIVIDEND                 2
#define IDS_EX_RIGHTS_AND_DIVIDEND      3
#define IDS_EX_DOUBLE_DIVIDEND          4
#define IDS_EX_RIGHTS_AND_DOUBLE_DIVIDEND 5
#define IDS_FACE_VALUE_PARTITIOIN       6
#define IDS_FACE_VALUE_PARTITIOIN_EX_RIGHTS 7
#define IDS_FACE_VALUE_PARTITIOIN_EX_DIVIDEND 8
#define IDS_FACE_VALUE_PARTITIOIN_EX_RIGHTS_AND_DIVIDEND 9
#define IDS_FACE_VALUE_PARTITIOIN_INTERIM_DIVIDEND 10
#define IDS_FACE_VALUE_PARTITIOIN_EX_RIGHTS_AND_INTERIM_DIVIDEND 11
#define IDS_FACE_VALUE_ANNEXATION_EX_RIGHTS 12
#define IDS_FACE_VALUE_ANNEXATION_EX_DIVIDEND 13
#define IDS_FACE_VALUE_ANNEXATION_EX_RIGHTS_AND_DIVIDEND 14
#define IDS_FACE_VALUE_ANNEXATION_INTERIM_DIVIDEND 15
#define IDS_FACE_VALUE_ANNEXATION_EX_RIGHTS_AND_INTERIM_DIVIDEND 16
#define IDS_INTERIM_DIVIDEND            17
#define IDS_EX_RIGHTS_AND_INTERIM_DIVIDEND 18
#define IDS_FACE_VALUE_PARTITIOIN_REDUCTION_OF_CAPITAL 19
#define IDS_FACE_VALUE_PARTITIOIN_STOCKS_ANNEXATION 20
#define IDS_FACE_VALUE_ANNEXATION_REDUCTION_OF_CAPITAL 21
#define IDS_FACE_VALUE_ANNEXATION_STOCKS_ANNEXATION 22
#define IDS_REDUCTION_OF_CAPITAL        23
#define IDS_STOCKS_ANNEXATION           24
#define IDS_ENTERPRISE_PARTITION        25
#define IDS_MUTUAL_FUND                 26
#define IDS_FACE_VALUE_ANNEXATION       27

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1000
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           1000
#endif
#endif
