#define XTP_IDS_DOCKINGPANE_AUTOHIDE	9900
#define XTP_IDS_DOCKINGPANE_CLOSE		9901
#define XTP_IDB_DOCKINGPANE_VISIOGRIPPER 9902

#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40012
#define _APS_NEXT_CONTROL_VALUE         1008
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
