//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ChartPatternAddin_Eng.rc
//
#define IDS_STRING1                     1
#define IDS_DRAWING_METHOD              1
#define IDS_AUTOTREND                   2
#define IDOK2                           3
#define IDS_TREND_PATTERN               3
#define IDS_CANDLE_PATTERN              4
#define IDS_COLOR_SET                   5
#define IDS_UPWARD_REVERSE              6
#define IDS_DOWNWARD_REVERSE            7
#define IDS_UPWARD_CONTINUE             8
#define IDS_DOWNWARD_CONTINUE           9
#define IDS_HEADNSHOULDER               10
#define IDS_R_HEADNSHOULDER             11
#define IDS_DOUBLETOP                   12
#define IDS_R_DOUBLETOP                 13
#define IDS_BULL_ISOTRIANGLE            14
#define IDS_BEAR_ISOTRIANGLE            15
#define IDS_BULL_TRIANGLE               16
#define IDS_BEAR_TRIANGLE               17
#define IDS_BULLISH_WIDETRIANGLE        18
#define IDS_BEARISH_WIDETRIANGLE        19
#define IDS_BULL_WEDGE                  20
#define IDS_BEAR_WEDGE                  21
#define IDS_BULL_SQUAREFLAG             22
#define IDS_BEAR_SQUAREFLAG             23
#define IDS_BULL_TRIANGLEFLAG           24
#define IDS_BEAR_TRIANGLEFLAG           25
#define IDS_BULL_RECTANGLE              26
#define IDS_BEAR_RECTANGLE              27
#define IDS_V_TOP                       28
#define IDS_V_BOTTOM                    29
#define IDS_HAMMER                      30
#define IDS_HANGINGMAN                  31
#define IDS_INVERTEDHAMMER              32
#define IDS_SHOOTINGSTAR                33
#define IDS_BULLISH_BELTHOLDLINE        34
#define IDS_BEARISH_BELTHOLDLINE        35
#define IDS_LONG_WHITEBODY              36
#define IDS_LONG_BLACKBODY              37
#define IDS_BULLISH_HARAMI              38
#define IDS_BEARISH_HARAMI              39
#define IDS_BULLISH_ENGULFING           40
#define IDS_BEARISH_ENGULFING           41
#define IDS_BULLISH_COUNTERATTACKLINE   42
#define IDS_BEARISH_COUNTERATTACKLINE   43
#define IDS_PIERCINGPATTERN             44
#define IDS_DARKCLOUDCOVER              45
#define IDS_MORNINGSTAR                 46
#define IDS_EVENINGSTAR                 47
#define IDS_MORNINTDOJISTAR             48
#define IDS_EVENINGDOJISTAR             49
#define IDS_ABANDONEDBABY_INDOWNTREND   50
#define IDS_ABANDONEDBABY_INUPTREND     51
#define IDS_THREE_INSIDEUP              52
#define IDS_THREE_INSIDEDOWN            53
#define IDS_THREE_OUTSIDEUP             54
#define IDS_THREE_OUTSIDEDOWN           55
#define IDS_UPSIDEGAPTWOCROWS_INUPTREND 56
#define IDS_THREE_WHITESOLDIER          57
#define IDS_THREE_BLACKCROW             58
#define IDS_STALLEDPATTERN              59
#define IDS_ADVANCEBLOCK                60
#define IDS_UPSIDEGAP_TASUKI            61
#define IDS_DNSIDEGAP_TASUKI            62
#define IDS_MATHOLD                     63
#define IDS_BULLISH_TRISTAR             64
#define IDS_BEARISH_TRISTAR             65
#define IDS_UNIQUETHREERIVERBOTTOM      66
#define IDS_IDENTICAL_THREECROWS        67
#define IDS_BULLISH_BREAKAWAY           68
#define IDS_BEARISH_BREAKAWAY           69
#define IDS_TWOCORWS                    70
#define IDS_THREESTARS_INTHESOUTH       71
#define IDS_CONCEALINGBABY_SWALLOW      72
#define IDS_STICKSANDWICH               73
#define IDS_BULLISH_KICKING             74
#define IDS_BEARISH_KICKING             75
#define IDS_HOMINGPIGEON                76
#define IDS_LADDERBOTTOM                77
#define IDS_MATCHINGLOW                 78
#define IDS_BULLISH_SIDEBYSIDE_WHITELINE 79
#define IDS_BEARISH_SIDEBYSIDE_WHITELINE 80
#define IDS_RISING_THREEMETHODS         81
#define IDS_FALLING_THREEMETHODS        82
#define IDS_BULLISH_SEPARATINGLINES     83
#define IDS_BEARISH_SEPARATINGLINES     84
#define IDS_BULLISH_THREELINESTRIKE     85
#define IDS_BEARISH_THREELINESTRIKE     86
#define IDS_UPSIDEGAP_THREEMETHODS      87
#define IDS_DNSIDEGAP_THREEMETHODS      88
#define IDS_ON_NECK                     89
#define IDS_IN_NECK                     90
#define IDS_MSG_SCROLL                  91
#define IDS_STRING_FONT                 92
#define IDS_N1                          93
#define IDS_N2                          94
#define IDS_N3                          95
#define IDD_DLG_PATTERNENVSETUP         2000
#define IDC_CHK_MMA                     2000
#define IDC_CHK_HIGHLOWPTLINE           2001
#define IDC_CHK_HIGHPTHLINE             2002
#define IDC_CHK_LOWPTHLINE              2003
#define IDD_DLG_ANALYSIS                2003
#define IDC_CHK_HIGHPTREGISTLINE        2004
#define IDC_CHK_AUTOPATTERN             2004
#define IDC_CHK_LOWPTSUPPORTLINE        2005
#define IDC_EDIT_HLPT_ALLOWABLE         2006
#define IDC_EDIT_NEXTPT_ALLOWABLE       2007
#define IDC_CHK_NOTDRAWALL              2008
#define IDD_DLG_HTML                    2008
#define IDC_RADIO_MMA                   2009
#define IDC_RADIO_CANDLE                2010
#define IDC_EDIT_MMA                    2011
#define IDC_EDIT_CANDLE                 2012
#define IDC_EDIT_CANDLE2                2013
#define IDC_STATIC_GRIDBASE             2014
#define IDC_TIT_COND1                   2015
#define IDC_TIT_COND2                   2016
#define IDC_TIT_CONDPER1                2017
#define IDC_TIT_CONDPER2                2018
#define IDC_TIT_COND3                   2018
#define IDC_BTN_WAVE                    2019
#define IDC_BTN_CANDLE                  2020
#define IDC_STATIC_TIT_PERIOD           2021
#define IDC_TIT_PERIOD                  2021
#define IDC_STATIC_STARTDATE            2022
#define IDC_STATIC_ENDDATE              2023
#define IDC_STATIC_DATACNT              2024
#define IDC_STATIC_TIT_BONG             2025
#define IDC_TIT_BONG                    2025
#define IDC_STATIC_TIT_BASE             2026
#define IDC_TIT_BASE                    2026
#define IDC_RDO_CANDLE                  2027
#define IDC_RDO_WAVE                    2028
#define IDC_BTN_ENVSETUP                2029
#define IDC_CHK_DISPLAYNAME             2030
#define IDC_BTN_WAVE_CLR                2032
#define IDC_CB_WAVE_THICK               2033
#define IDC_BUTTON_ALLCHECK             2034
#define IDC_BUTTON_ALLUNCHECK           2035
#define IDC_STATIC_TEXT                 2037
#define IDC_TREE_ITEMLIST               3058
#define IDC_MOVE                        12015
#define IDC_MOVING                      12016
#define IDC_TAB1                        21000
#define IDD_DLG_SETUP                   21000
#define IDD_DLG_TABENVSETUP1            21001
#define IDD_DLG_TABENVSETUP2            21002
#define IDD_DLG_TABENVSETUP3            21003
#define IDD_DLG_TABENVSETUP4            21004
#define IDB_LINE_THICKNESS              21009
#define IDC_CB_HIGH_THICK               21026
#define IDC_CB_LOW_THICK                21027
#define IDC_BTN_HIGH_CLR                21028
#define IDC_BTN_LOW_CLR                 21029
#define IDC_ST_THICK                    29006
#define IDC_ST_THICK2                   29007
#define IDC_ST_THICK3                   29008

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2010
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         2038
#define _APS_NEXT_SYMED_VALUE           2032
#endif
#endif
