
	// IB191000.idl : IDL source for IB191000.exe
//
// This file will be processed by the MIDL tool to
// produce the type library (IB191000.tlb) and marshalling code.
import "oaidl.idl";
import "ocidl.idl";
[
	uuid(0A8F9CAB-0AA7-42FB-BCB5-112727A6A569),
	version(1.0),
	helpstring("IB191000 1.0 Type Library")
]
library IB191000Lib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");
};

	