//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// axis.rc에서 사용되고 있습니다.
//
#define IDC_MAP                         2
#define IDC_CONFIG                      2
#define IDC_CLEAR                       3
#define IDC_ACTION                      3
#define IDCANCEL2                       3
#define IDC_OSETUP                      4
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDD_PHONEPAD_DIALOG             110
#define IDC_SECUREDLG_YES               111
#define IDC_SECUREDLG_NO                112
#define IDR_MAINFRAME                   128
#define IDR_AXISTYPE                    129
#define IDB_PIN                         130
#define IDD_CONNECT                     131
#define IDB_HELP                        132
#define IDB_PIN_                        133
#define IDB_HELP_                       137
#define IDI_CLIENT                      139
#define IDD_MODALPOPUP                  140
#define IDD_LOCK                        141
#define IDD_FULLNAME                    142
#define IDD_SCREEN                      150
#define IDB_RESTORE_                    162
#define IDB_ALL                         171
#define IDB_ALL_                        172
#define IDB_N                           173
#define IDB_N_                          174
#define IDB_RESTORE                     175
#define IDB_5_                          178
#define IDB_1                           179
#define IDB_1_                          180
#define IDB_2                           181
#define IDB_2_                          182
#define IDB_3                           183
#define IDB_3_                          184
#define IDB_4                           185
#define IDB_4_                          186
#define IDB_5                           187
#define IDI_ICON1                       190
#define IDD_PROGRESS                    191
#define IDD_SAVEPASS                    192
#define IDD_SETUP                       198
#define IDD_CERTIFY                     201
#define IDD_NOTICE                      203
#define IDB_CHECK_ON                    210
#define IDB_CHECK_OFF                   211
#define IDB_REGISTER_ON                 212
#define IDB_CHELP_OFF                   213
#define IDB_CHELP_ON                    214
#define IDB_JUMUN_OFF                   215
#define IDB_JUMUN_ON                    216
#define IDB_REGISTER_OFF                217
#define IDD_EXIT                        218
#define IDD_PROGRAM                     220
#define IDD_SETPRINT                    221
#define IDD_ESETUP                      226
#define IDD_CONCLUSIONLIST              227
#define IDD_CONCLUSION                  228
#define IDB_TCPBMP                      231
#define IDB_INETBMP                     232
#define IDB_CHECKBOXES                  235
#define IDB_TOP_                        236
#define IDB_TOP                         237
#define IDB_DUAL                        238
#define IDB_DUAL_                       239
#define IDB_TIMER                       240
#define IDB_M3                          241
#define IDB_M1                          242
#define IDB_M2                          243
#define IDD_GLB                         247
#define IDD_NEWALARM                    248
#define IDD_RTS                         250
#define IDD_NEWCUSTOMER                 252
#define IDD_KONG                        257
#define IDD_MISUNOTIFY                  260
#define IDB_NEWCUSTOMER                 273
#define IDB_FONT_                       284
#define IDB_COPY                        285
#define IDB_COPY_                       286
#define IDB_FONT                        287
#define IDD_EDITSERVER                  289
#define IDB_BITMAP1                     306
#define IDD_USEINFO                     307
#define IDB_GROUP                       309
#define IDB_CLOSE                       314
#define IDB_MAX                         315
#define IDB_MIN                         316
#define IDB_SINGLE                      318
#define IDB_VSCREEN                     319
#define IDB_MAINFUNC                    320
#define IDD_NEWSVIEWER                  339
#define IDD_STOPLOSS                    346
#define IDD_ACCSAVE                     350
#define IDD_REMOTEHELP                  351
#define IDD_DT_CONNECT                  353
#define IDD_DT_EXIT                     357
#define IDD_SETUP_CUST                  365
#define IDI_HAXIS                       369
#define IDB_DAETOO                      371
#define IDB_IBK                         371
#define IDB_HANA                        372
#define IDI_HCLIENT                     374
#define IDD_STOPLOSSWARNNING            382
#define IDD_MNGINFO                     384
#define IDD_DTINFO                      385
#define IDB_HAVESCREEN                  394
#define IDD_DLGMISU                     398
#define IDD_DLG_EMERGENCY2              399
#define IDD_TESTDLG                     400
#define IDB_BITMAPTEST                  403
#define IDB_MENUSIDE_BK                 405
#define IDB_BAR1SIDE_BK                 406
#define IDB_TICKER2SIDE_RBK             407
#define IDB_TICKER1SIDE_BK              408
#define IDB_TICKER2SIDE_LBK             409
#define IDR_MAINFRAME_SAVE              410
#define IDD_ACCTCONFIG                  411
#define IDB_LOGIN_CHECK_OFF             414
#define IDB_LOGIN_CHECK_ON              415
#define IDB_CLOCK_SAT                   416
#define IDB_CLOCK_FRI                   417
#define IDB_CLOCK_THU                   418
#define IDB_CLOCK_WED                   419
#define IDB_CLOCK_TUE                   420
#define IDB_CLOCK_MON                   421
#define IDB_CLOCK_SUN                   422
#define IDB_CLOCK_AM                    423
#define IDB_CLOCK_PM                    424
#define IDB_CLOCK_BG                    425
#define IDB_CLOCK_BG_MINI               426
#define IDB_LOGOUT_BG                   427
#define IDB_LOGOUT_BTN_OK               428
#define IDB_LOGOUT_BTN_CANCEL           429
#define IDD_DUPLOGIN_CONFIRM            430
#define IDB_VERUP                       433
#define IDD_LOGO_DLG                    435
#define IDB_LOGO_ICO1                   436
#define IDB_LOGO_ICO2                   438
#define IDI_CUSTOMER                    439
#define IDI_STAFF                       442
#define IDB_CUSTOM                      442
#define IDD_INFO_INTEREST               449
#define IDD_SECURE_DLG                  450
#define IDD_KOBA_NOTIFY                 451
#define IDB_EMPPASSCHANGENOTIFY         454
#define IDD_EMPPASSCHANAGENOTIFY        455
#define IDD_EMPPASSCHANGE               456
#define IDB_EMPPASSCHANGE               458
#define IDB_CLOCK_CAL_OVER              459
#define IDB_CLOCK_CAL                   460
#define IDD_IMAGE_NOTICE                461
#define IDD_DT_NEO_CONNECT              462
#define IDB_BITMAP2                     463
#define IDB_NEW_LOGOUT_BTN_OK           463
#define IDB_BITMAP3                     464
#define IDD_TOP10                       469
#define IDB_NEW_LOGOUT_BTN_CANCEL       470
#define IDD_DLG_CERTERR                 471
#define IDD_LOCK_PASS                   472
#define IDD_DLGPB                       475
#define IDB_BITMAP_EVENT                477
#define IDD_DLG_SLIDEWND                478
#define IDD_DLG_SERVERORDER             480
#define IDD_DLG_NOTICEPOPUP             482
#define IDD_DLG_MSGBOX                  484
#define IDC_USER                        1001
#define IDC_PASS                        1002
#define IDC_CPASS                       1003
#define IDC_RUN                         1004
#define IDC_NAME                        1005
#define IDC_MSG                         1006
#define IDC_SETUP                       1007
#define IDC_NEWUSER                     1008
#define IDC_PROXY                       1009
#define IDC_TOTPROGRESS                 1010
#define IDC_CURPROGRESS                 1012
#define IDC_PROGRESS                    1013
#define IDC_FILE                        1014
#define IDC_TOTALFILE                   1015
#define IDC_TOTALSIZE                   1016
#define IDC_USERNAME                    1017
#define IDC_TRANSENDFILE                1017
#define IDC_USETIME                     1018
#define IDOKX                           1019
#define IDC_SEARCHP                     1020
#define IDC_ENDTIME                     1020
#define IDC_PNAME                       1021
#define IDC_STARTTIME                   1021
#define IDC_PLIST                       1022
#define IDC_ALIST                       1024
#define IDC_DEL                         1024
#define IDC_ANAME                       1025
#define IDC_FNAME                       1025
#define IDC_ANUM                        1026
#define IDC_CHANGE                      1028
#define IDC_STATUS                      1029
#define IDC_STATIC1                     1029
#define IDC_STATIC2                     1030
#define IDC_STATIC3                     1031
#define IDC_STATIC4                     1032
#define IDC_STATIC5                     1033
#define IDC_USERID                      1034
#define IDC_STATIC6                     1034
#define IDC_USERIP                      1035
#define IDC_STATIC7                     1035
#define IDC_SERVERNAME                  1036
#define IDC_STATIC8                     1036
#define IDC_SNAME                       1037
#define IDC_SERVERIP                    1037
#define IDC_STATIC9                     1037
#define IDC_ADD                         1038
#define IDC_CPUUSE                      1038
#define IDC_STATIC10                    1038
#define IDC_DELETE                      1039
#define IDC_RTS                         1039
#define IDC_STATIC11                    1039
#define IDC_SHARE                       1040
#define IDC_OPERATOR                    1041
#define IDC_STATION                     1042
#define IDC_T1                          1043
#define IDC_BOX3                        1044
#define IDC_T2                          1045
#define IDC_BOX1                        1046
#define IDC_BOX2                        1047
#define IDC_INETIMG                     1049
#define IDC_TCPIMG                      1050
#define IDC_BORDER                      1051
#define IDC_ERRMSG                      1058
#define IDC_UP                          1059
#define IDC_DOWN                        1060
#define IDC_DIRECTCONNECT               1061
#define IDC_SERVERLIST                  1062
#define IDC_PORTLIST                    1063
#define IDC_SAVEID                      1064
#define IDC_CURSERVER                   1065
#define IDC_INFOLIST                    1074
#define IDC_MAPF                        1075
#define IDC_DEVF                        1076
#define IDC_HELPF                       1077
#define IDC_IMAGEF                      1078
#define IDC_MTBLF                       1079
#define IDC_TABF                        1080
#define IDC_EXEF                        1081
#define IDC_PLATFORMF                   1082
#define IDC_BITMAP                      1085
#define IDC_ALL                         1106
#define IDC_ENSETUPINFO                 1107
#define IDC_SETTICKERINFO               1108
#define IDC_TOOLEDITINFO                1109
#define IDC_GUIDEMSG                    1110
#define IDC_WORKSPACEINFO               1113
#define IDC_SPASS                       1113
#define IDC_LPASS                       1114
#define IDC_CHARTINFO                   1114
#define IDC_CODEMEMO                    1115
#define IDC_CAPTION                     1130
#define IDC_NOTICESKIN                  1131
#define IDC_HBITMAP                     1133
#define IDC_DBITMAP                     1134
#define IDC_DRUNX                       1135
#define IDC_DUSER                       1136
#define IDC_DPASS                       1137
#define IDC_DCPASS                      1138
#define IDC_DNEWUSER                    1139
#define IDC_DEXIT                       1140
#define IDC_DSETUP                      1141
#define IDC_DMSG                        1142
#define IDC_DRUN                        1143
#define IDC_DSAVEID                     1144
#define IDC_DONLYSISE                   1145
#define IDC_DSAVEPASS                   1146
#define IDC_DCURRECEIVE                 1147
#define IDC_EVENT1                      1147
#define IDC_DALLRECEIVE                 1148
#define IDC_EVENT2                      1148
#define IDC_DALLFILECNT                 1149
#define IDC_EVENT3                      1149
#define IDC_DTRANSFILECNT               1150
#define IDC_CERT                        1150
#define IDC_DFILENAME                   1151
#define IDC_GEN                         1151
#define IDC_DTRANSFILESIZE              1152
#define IDC_DCSTART                     1152
#define IDC_DTRANSRATE                  1153
#define IDC_BANNER                      1153
#define IDC_DSTATIC1                    1154
#define IDC_DSTATIC2                    1155
#define IDC_DSTATIC3                    1156
#define IDC_BN_CA                       1157
#define IDC_BN_REMOTE                   1158
#define IDC_BN_BREAK                    1159
#define IDC_RECEIVE_RESOURCE            1159
#define IDC_PROXY_CUST                  1160
#define IDC_DSTATIC                     1160
#define IDC_HSTATIC                     1161
#define IDC_BN_BRANCH                   1162
#define IDC_DNAMESTATIC                 1162
#define IDC_NAMESTATIC                  1162
#define IDC_HNAMESTATIC                 1163
#define IDC_BN_VIRUS                    1164
#define IDC_DCOPYRIGHTSTATIC            1164
#define IDC_COPYRIGHTSTATIC             1164
#define IDC_HCOPYRIGHTSTATIC            1165
#define IDC_WARNMSG                     1168
#define IDC_RED1                        1169
#define IDC_SERVERTIME                  1171
#define IDC_CHANGEINFO                  1172
#define IDC_RSCINFO                     1172
#define IDC_USE_FIREWALL                1172
#define IDC_ONLYGUEST                   1172
#define IDC_EMERGENCY                   1178
#define IDC_DBTEST                      1178
#define IDC_CHK_PROGRAM                 1179
#define IDC_TAB                         1179
#define IDC_CHK_RESOURCE                1180
#define IDC_SMSG                        1180
#define IDC_EMP                         1181
#define IDC_SMSG_BACK                   1181
#define IDC_CUST                        1182
#define IDC_PCFIREWALL                  1183
#define IDC_KEYPROTECT                  1184
#define IDC_FORCELOGIN                  1184
#define IDC_USESERVERTIME               1185
#define IDC_SISEONLY                    1185
#define IDC_ALLRESOURCEDOWNLOAD         1186
#define IDC_BUTTON1                     1186
#define IDC_MODE                        1187
#define IDC_EDIT1                       1187
#define IDC_AOS                         1187
#define IDC_STATIC_MSG                  1188
#define IDC_PROXY2                      1190
#define IDC_STATIC_INFO                 1191
#define IDC_NORETRY                     1192
#define IDC_VIEW_KOBAELW                1193
#define IDC_PHOLDER_1                   1195
#define IDC_PHOLDER_2                   1196
#define IDC_INFORMATION1                1197
#define IDC_INFORMATION2                1198
#define IDC_OLD_PSWD                    1198
#define IDC_PHOLDER_3                   1199
#define IDC_NEW_PSWD                    1199
#define IDC_CFR_PSWD                    1200
#define IDC_PHOLDER                     1202
#define IDC_PHOLDER2                    1203
#define IDC_LOGIN_BANNER                1204
#define IDC_TOP10BG                     1205
#define IDC_STATIC_L1                   1210
#define IDC_STATIC_L2                   1211
#define IDC_STATIC_L3                   1212
#define IDC_STATIC_L4                   1213
#define IDC_STATIC_L5                   1214
#define IDC_STATIC_L6                   1215
#define IDC_STATIC_L7                   1216
#define IDC_STATIC_L8                   1217
#define IDC_STATIC_L9                   1218
#define IDC_STATIC_L10                  1219
#define IDC_BUTTON_L1                   1220
#define IDC_BUTTON_L2                   1221
#define IDC_BUTTON_L3                   1222
#define IDC_BUTTON_L4                   1223
#define IDC_BUTTON_L5                   1224
#define IDC_BUTTON_L6                   1225
#define IDC_BUTTON_L7                   1226
#define IDC_BUTTON_L8                   1227
#define IDC_BUTTON_L9                   1228
#define IDC_BUTTON_L10                  1229
#define IDC_STATIC_DATE                 1230
#define IDC_BUTTON_HELP                 1231
#define IDC_BUTTON_L11                  1232
#define IDC_BUTTON_L12                  1233
#define IDC_BUTTON_L13                  1234
#define IDC_BUTTON_L14                  1235
#define IDC_BUTTON_L15                  1236
#define IDC_BUTTON_L16                  1237
#define IDC_BUTTON_L17                  1238
#define IDC_BUTTON_L18                  1239
#define IDC_BUTTON_L19                  1240
#define IDC_BUTTON_L20                  1241
#define IDC_BUTTON_L21                  1242
#define IDC_BUTTON_L22                  1243
#define IDC_BUTTON_L23                  1244
#define IDC_BUTTON_L24                  1245
#define IDC_BUTTON_L25                  1246
#define IDC_BUTTON_L26                  1247
#define IDC_BUTTON_L27                  1248
#define IDC_BUTTON_L28                  1249
#define IDC_BUTTON_L29                  1250
#define IDC_BUTTON_L30                  1251
#define IDC_STATIC_L11                  1252
#define IDC_STATIC_L12                  1253
#define IDC_STATIC_L13                  1254
#define IDC_STATIC_L14                  1255
#define IDC_STATIC_L15                  1256
#define IDC_STATIC_L16                  1257
#define IDC_STATIC_L17                  1258
#define IDC_STATIC_L18                  1259
#define IDC_STATIC_L19                  1260
#define IDC_STATIC_L20                  1261
#define IDC_BUTTON_CLOSE                1262
#define IDC_BUTTON_L31                  1263
#define IDC_BUTTON_L32                  1264
#define IDC_BUTTON_L33                  1265
#define IDC_BUTTON_L34                  1266
#define IDC_BUTTON_L35                  1267
#define IDC_BUTTON_L36                  1268
#define IDC_BUTTON_L37                  1269
#define IDC_BUTTON_L38                  1270
#define IDC_BUTTON_L39                  1271
#define IDC_BUTTON_L40                  1272
#define IDC_STATIC_RCHG                 1273
#define IDC_STATIC_RCHG2                1274
#define IDC_STATIC_RCHG3                1275
#define IDC_STATIC_RCHG4                1276
#define IDC_STATIC_RCHG5                1277
#define IDC_STATIC_RCHG6                1278
#define IDC_STATIC_RCHG7                1279
#define IDC_STATIC_RCHG8                1280
#define IDC_STATIC_RCHG9                1281
#define IDC_STATIC_RCHG10               1282
#define IDC_STATIC_RCHG11               1283
#define IDC_STATIC_RCHG12               1284
#define IDC_STATIC_RCHG13               1285
#define IDC_STATIC_RCHG14               1286
#define IDC_STATIC_RCHG15               1287
#define IDC_STATIC_RCHG16               1288
#define IDC_STATIC_RCHG17               1289
#define IDC_STATIC_RCHG18               1290
#define IDC_STATIC_RCHG19               1291
#define IDC_STATIC_RCHG20               1292
#define IDC_BUTTON_L41                  1293
#define IDC_BUTTON_L42                  1294
#define IDC_CERTCNT                     1294
#define IDC_BUTTON_L43                  1295
#define IDC_STATIC_PASS                 1295
#define IDC_BUTTON_L44                  1296
#define IDC_ORIREC                      1296
#define IDC_BTN_CERT                    1296
#define IDC_BUTTON_L45                  1297
#define IDC_BTN_AXIS                    1297
#define IDC_BUTTON_L46                  1298
#define IDC_CLOUDE                      1298
#define IDC_BUTTON_L47                  1299
#define IDC_CLOUDE_CERTUP               1299
#define IDC_BUTTON_L48                  1300
#define IDC_CLOUDE_DOWN                 1300
#define IDC_BUTTON_L49                  1301
#define IDC_BUTTON5                     1301
#define IDC_CLOUDE_PSCHANGE             1301
#define IDC_BUTTON_L50                  1302
#define IDC_CLOUDE_PCBTN                1302
#define IDC_BUTTON_L51                  1303
#define IDC_SSETUP                      1303
#define IDC_CHK1_CONFIRM                1303
#define IDC_BUTTON_L52                  1304
#define IDC_ORIRECT                     1304
#define IDC_CHK2_CONFIRM                1304
#define IDC_BUTTON_L53                  1305
#define IDC_SCLEAR                      1305
#define IDC_BTN_DEVCLOSE                1305
#define IDC_BUTTON_L54                  1306
#define IDC_BUTTON_L55                  1307
#define IDC_BUTTON_L56                  1308
#define IDC_BUTTON_L57                  1309
#define IDC_BUTTON_L58                  1310
#define IDC_BUTTON_L59                  1311
#define IDC_BUTTON_L60                  1312
#define IDD_ACCTOOLBAR                  7001
#define IDC_NEWSHIDECOUNT               7027
#define IDC_NEWSHIDESPIN                7028
#define IDD_SELECTSKIN                  7056
#define IDD_DT_NEW_CONNECT              7058
#define IDD_NEW_PROGRESS                7059
#define IDD_NEW_DT_EXIT                 7060
#define ID_MENU_BASE                    10000
#define ID_MENU_TB                      14000
#define ID_MENU_USERTOOL                15000
#define ID_MENU_USER                    19000
#define ID_MENU_END                     20000
#define ID_GROUP_BASE                   25000
#define ID_GROUP_END                    26000
#define ID_APP_BASE                     32770
#define ID_ESCAPEWINODW                 32774
#define ID_SCREENNUM                    32775
#define ID_VIEW_DB1                     32779
#define ID_VIEW_SCLIST                  32780
#define ID_FULLNAME                     32782
#define ID_VIEW_MODE                    32787
#define ID_VIEW_TICKER1                 32787
#define ID_APP_SETUP                    32788
#define ID_APP_SAVEPASS                 32789
#define ID_APP_USETUPDOWN               32790
#define ID_APP_USETUPUPLOAD             32791
#define ID_APP_LOCK                     32792
#define ID_APP_TSETUP                   32793
#define ID_APP_USERPROGRAM              32794
#define ID_APP_USERSCREEN_SAVE          32795
#define ID_APP_TRSEARCH                 32798
#define ID_APP_INTERSAVE                32799
#define ID_APP_SAVEBMP                  32801
#define ID_APP_HOTKEY                   32802
#define ID_APP_EDITHOTKEY               32802
#define ID_VIEW_VSCREEN1                32803
#define ID_VIEW_VSCREEN2                32804
#define ID_VIEW_VSCREEN3                32805
#define ID_VIEW_VSCREEN4                32806
#define ID_APP_CLOSEALL                 32807
#define ID_APP_CLOSEA                   32808
#define ID_VIEW_FULLSCREEN              32809
#define ID_RELOADMAP                    32810
#define ID_APP_PRINT                    32811
#define ID_FIRSTTAB                     32813
#define ID_VIEW_CASCADE                 32814
#define ID_VIEW_TILE_VERT               32815
#define ID_VIEW_TILE_HORZ               32816
#define ID_APP_RECONNECT                32817
#define ID_VIEW_JCONTROL                32818
#define ID_APP_PRINT_SETUP              32819
#define ID_APP_ORDERSETUP               32820
#define ID_APP_ACCSETTING               32821
#define ID_APP_CALC                     32824
#define ID_APP_MEMO                     32825
#define ID_APP_SAVEBMP_A                32827
#define ID_VIEW_FITMONITOR              32829
#define ID_RTS                          32830
#define ID_SHOWTRACER                   32830
#define ID_APP_NEWSETUP                 32831
#define ID_APP_CERTIFY                  32832
#define ID_APP_ESETUP                   32833
#define ID_APP_EDITTOOL                 32834
#define ID_APP_TICKERSETUP              32835
#define ID_VIEW_CLOCK                   32836
#define ID_APP_CHANGEPASSWORD           32837
#define ID_VIEW_TICKER2                 32838
#define ID_VIEW_TICKER3                 32839
#define ID_VIEW_VSCREEN5                32840
#define ID_VIEW_VSCREEN6                32841
#define ID_VIEW_ACCTOOL                 32842
#define ID_VIEW_MDI                     32843
#define ID_VIEW_SDI                     32844
#define ID_VIEW_TRAY                    32845
#define ID_APP_HELPCOM                  32846
#define ID_APP_LINKEXCEL                32847
#define ID_APP_CATCH                    32849
#define ID_APP_FIREWALL                 32850
#define ID_APP_CONNECT                  32851
#define ID_APP_STOCK_STOPLOSS           32852
#define ID_APP_FO_STOPLOSS              32853
#define ID_APP_CLOSEALLWITHOUTTHIS      32854
#define ID_APP_ACCTGROUP                32855
#define ID_APP_ACCTPASSWORD             32856
#define ID_APP_TOTALSETUP               32858
#define ID_APP_MNGSETUP                 32859
#define ID_APP_THEMESETUP               32860
#define ID_APP_TOOLBARSETUP             32861
#define ID_MENUITEM32862                32862
#define ID_STAFF_PWD                    32864
#define ID_SETACCOUNT                   32865
#define ID_APP_FOCONF                   32866
#define ID_APP_CHEGEQUAL                32868
#define ID_CLEARCHART                   32869
#define ID_APP_RECOM                    32870
#define ID_TRANSUP                      32871
#define ID_TRANSDOWN                    32872
#define ID_VIEW_HISTORY                 32874
#define ID_NATINGTEL                    32876
#define ID_CODEFOCUS                    32878
#define ID_APP_END                      32900
#define ID_VIEW_KOBAELW_SCREEN          32901
#define AXIS_ST_BASE                    40000
#define ST_FONTNAME_DEFAULT             40001
#define ST_FONTNAME_DEFAULT2            40002
#define ST_TEXT_HOUR                    40003
#define ST_TEXT_MINUTE                  40004
#define ST_TEXT_SECOND                  40005
#define ST_MSG_FIND_OPTIMUM_SERVER      40006
#define ST_TEXT_AUTOCONNECT             40007
#define ST_MSG_CANCEL_AUTOCONNECT       40008
#define ST_MSG_FAIL_CONNECT             40009
#define ST_MSG_TRY_CONNECT              40010
#define ST_MSG_INPUT_CORRECT_USERID     40011
#define ST_TEXT_OK                      40012
#define ST_MSG_RECONNECT_OTHERUSER      40013
#define ST_TEXT_RECONNECT_OTHERUSER     40014
#define ST_MSG_DISCONNECT_EXIT          40015
#define ST_MSG_DISCONNECT_RETRY         40016
#define ST_TEXT_PROGRAMEXIT             40017
#define ST_MSG_NOTHING_SELECTED         40018
#define ST_TEXT_MMGB                    40019
#define ST_TEXT_CONFIRM_CNT             40020
#define ST_TEXT_ORDER_PRICE             40021
#define ST_MSG_FAIL_WINDOWCREATE        40022
#define ST_TEXT_STOP                    40023
#define ST_TEXT_RECEIVE                 40024
#define ST_SYMBOL_LEFT                  40025
#define ST_SYMBOL_RIGHT                 40026
#define ST_MSG_INPUT_SCREENNAME         40027
#define ST_TEXT_USERWORKSPACELIST       40028
#define ST_MSG_CHANGE_WORKSPACENAME     40029
#define ST_MSG_NOSERVERNAME             40030
#define ST_MSG_OVERWRITESERVERNAME      40031
#define ST_MSG_EXISTPORT                40032
#define ST_TEXT_ACCNAME                 40033
#define ST_TEXT_ACCOUNTNO               40034
#define ST_TEXT_ACCPASS                 40035
#define ST_MSG_NOACCINFO                40036
#define ST_MSG_SAVEACCOK                40037
#define ST_MSG_SAVEACCFAIL              40038
#define ST_SAVEID_TEXT                  40039
#define ST_TEXT_CLOCKFONT               40040
#define ST_TEXT_HIDECLOCK               40041
#define ST_USEINFO_UPTITLE              40042
#define ST_USEINFO_DOWNTITLE            40043
#define ST_USEINFO_STARTUPGUIDE         40044
#define ST_USEINFO_STARTDOWNGUIDE       40045
#define ST_USEINFO_MSGTITLE             40046
#define ST_USEINFO_TEXT_NOFILELIST      40047
#define ST_USEINFO_TEXT_QUERYFILELIST   40048
#define ST_USEINFO_TEXT_NOCHECKFILE     40049
#define ST_USEINFO_TEXT_UPLOADDING      40050
#define ST_USEINFO_TEXT_DOWNLOADDING    40051
#define ST_USEINFO_TEXT_ENDWORK         40052
#define ST_USEINFO_TEXT_ERRORMSG        40053
#define ST_SETUP_SERVERNAME             40054
#define ST_SETUP_PORT                   40055
#define ST_SETUP_TEST                   40056
#define ST_TEXT_MINICLOCK               40057
#define ST_TEXT_NORMCLOCK               40058
#define ID_MAP_HELP                     57670

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        487
#define _APS_NEXT_COMMAND_VALUE         32879
#define _APS_NEXT_CONTROL_VALUE         1306
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
