//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by IB202700.rc
//
#define IDS_GUIDE1                      1
#define IDS_GUIDE2                      2
#define IDC_GETNAME                     3
#define IDS_GUIDE3                      3
#define ID_BTN_CHKALL                   3
#define IDS_GUIDE4                      4
#define ID_BTN_ALLCANCEL                4
#define IDS_GUIDE5                      5
#define IDS_TITLE                       6
#define IDS_EXPECT                      7
#define IDS_AUTO                        8
#define IDS_ORDER                       9
#define ID_BTN_CHKKOSPI                 9
#define IDS_SAVE                        10
#define ID_BTN_CHKKOSDAQ                10
#define IDS_CONFIG                      11
#define IDS_EXCEL                       12
#define IDS_DEFAULTFONT                 13
#define IDS_GH_RCOD                     100
#define IDS_GH_CODE                     101
#define IDS_GH_NAME                     102
#define IDS_GH_CURR                     103
#define IDS_GH_DIFF                     104
#define IDS_GH_RATE                     105
#define IDS_GH_VOL                      106
#define IDS_GH_ASK                      107
#define IDS_GH_BID                      108
#define IDS_GH_OPEN                     109
#define IDS_GH_HIGH                     110
#define IDS_GH_LOW                      111
#define IDS_GH_TPRC                     112
#define IDS_GH_TVOL                     113
#define IDS_GH_ASKSIZE                  114
#define IDS_GH_BIDSIZE                  115
#define IDS_GH_TASKSIZE                 116
#define IDS_GH_TBIDSIZE                 117
#define IDS_GH_UPLIMIT                  118
#define IDS_GH_ANDIFF                   118
#define IDS_GH_LOLIMIT                  119
#define IDS_GH_ANRATE                   119
#define IDS_GH_AVOFS                    120
#define IDS_GH_ANTIPRC                  121
#define IDS_GH_ANTIVOL                  122
#define IDS_GH_CAPTURE                  123
#define IDS_GH_CONDITION                124
#define IDS_GH_CONFIGVAL                125
#define IDS_GH_SIGN                     125
#define IDS_GH_ASK1                     126
#define IDS_GH_BID1                     127
#define IDS_GH_52HIGH                   128
#define IDS_GH_52LOW                    129
#define IDS_GH_YHIGH                    130
#define IDS_GH_ASKRATE                  131
#define IDS_GH_BIDRATE                  132
#define IDS_GH_CHESTRENGTH              133
#define IDS_GH_ROTATION                 134
#define IDS_GH_PREVOL                   135
#define IDS_GH_FOREIGNER                136
#define IDS_GH_YLOW                     137
#define IDS_GH_POSSNUM                  138
#define IDS_GH_POSSPRC                  139
#define IDS_GH_POSSPROFIT               140
#define IDS_GH_POSSRATE                 141
#define IDS_GH_PRECURR                  142
#define IDS_GH_PREHIGH                  143
#define IDS_GH_PRELOW                   144
#define IDS_GH_HOGARATE                 145
#define IDS_GH_OPENRATEW                146
#define IDS_GH_OPENRATEP                147
#define IDS_GH_HIGHRATEW                148
#define IDS_GH_HIGHRATEP                149
#define IDS_GH_LOWRATEW                 150
#define IDS_GH_LOWRATEP                 151
#define IDS_GH_PREOPEN                  154
#define IDS_GH_FORERATE                 155
#define IDS_GH_CAPITAL                  156
#define IDS_GH_STOCKCOUNT               157
#define IDS_GH_PRETPRC                  158
#define IDS_GH_UPDNRANGE                159
#define IDS_GH_LIMITRANGE               160
#define IDS_GH_PRETRATE                 161
#define IDS_GH_REGLINE2                 162
#define IDS_GH_REGLINE1                 163
#define IDS_GH_PIVOT                    164
#define IDS_GH_SUPLINE1                 165
#define IDS_GH_SUPLINE2                 166
#define IDS_GH_MAX52                    167
#define IDS_GH_MIN52                    168
#define IDS_GH_MAXYEAR                  169
#define IDS_GH_MINYEAR                  170
#define IDS_GH_MAXVOL52                 171
#define IDS_GH_MINVOL52                 172
#define IDS_GH_MAXVOLYEAR               173
#define IDS_GH_MINVOLYEAR               174
#define IDS_GH_MAXDATE52                175
#define IDS_GH_MINDATE52                176
#define IDS_GH_MAXDATEYEAR              177
#define IDS_GH_MINDATEYEAR              178
#define IDS_GH_MAXVOLDATE52             179
#define IDS_GH_MINVOLDATE52             180
#define IDS_GH_MAXVOLDATEYEAR           181
#define IDS_GH_MINVOLDATEYEAR           182
#define IDS_GH_MAXDIFF52                183
#define IDS_GH_MINDIFF52                184
#define IDS_GH_MAXDIFFYEAR              185
#define IDS_GH_MINDIFFYEAR              186
#define IDS_GH_MAXRATE52                187
#define IDS_GH_MINRATE52                188
#define IDS_GH_MAXRATEYEAR              189
#define IDS_GH_MINRATEYEAR              190
#define IDS_GH_CONTUPLIMIT              191
#define IDS_GH_CONTUP                   192
#define IDS_GH_CONTDNLIMIT              193
#define IDS_GH_CONTDN                   194
#define IDS_GH_PCR                      195
#define IDS_GH_PBR                      196
#define IDS_GH_ELWLEFTDATE              197
#define IDS_GH_ELWLASTDATE              198
#define IDS_GH_ELWCRATE                 199
#define IDS_GH_DATEBONG                 200
#define IDS_GH_EPSFULL                  201
#define IDS_GH_EPSHALF                  202
#define IDS_GH_PERFULL                  203
#define IDS_GH_PERHALF                  204
#define IDS_GH_PERHALF2                 205
#define IDS_GH_EXPECT                   206
#define IDS_GH_OPEN_P                   207
#define IDS_GH_HIGH_P                   208
#define IDS_GH_LOW_P                    209
#define IDS_GH_INFO                     210
#define IDS_GH_P_OPEN                   210
#define IDS_GH_P_HIGH                   211
#define IDS_GH_P_LOW                    212
#define IDS_GH_EQUALIZER                213
#define IDS_GH_RECOMMDATE               214
#define IDS_GH_RECOMBASICCOST           215
#define IDS_GH_RECOMSUIKRATE            216
#define IDS_GH_RECOMBMJISU              217
#define IDS_GH_RECOMBMRATE              218
#define IDS_GH_RECOMBMGOAL              219
#define IDS_GH_JISUGUBN                 220
#define IDS_GH_UPJONGCODE               221
#define IDS_GH_NEWCURR                  222
#define IDS_GH_PREVOL2                  223
#define IDS_GH_7852                     224
#define IDS_GH_7853                     225
#define IDS_GH_7854                     226
#define IDS_GH_7855                     227
#define IDS_GH_MPRICE                   228
#define IDS_GH_MPRICEPER                229
#define IDD_POPUP                       3000
#define IDD_ROW_MOVE                    3001
#define IDD_DLG_CODDULICATE             3003
#define IDC_RADIO_DISP                  7003
#define IDC_RADIO_SAVE                  7004
#define IDC_STATIC_ALERT                7006
#define IDC_CHECK_ALERT                 7008

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        3004
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         3000
#define _APS_NEXT_SYMED_VALUE           3000
#endif
#endif
