[platform]
01 = axis.exe
02 = axwizard.ocx
03 = axsock.ocx
04 = axislib.dll
05 = axisform.dll
06 = axisvbs.dll
07 = axissm.dll
08 = axisver.exe
09 = axislogin.dll
10 = axcertify.ocx
11 = axiscp.dll
12 = axiscm.dll
13 = axisglb.dll
14 = SKCOMDCM.DLL
15 = SKCOMDEM.DLL
16 = SKCOMDIF.DLL
17 = SKCOMDSC.DLL
18 = SKCOMMIC.DLL
19 = SKCOMMWB.EXE
20 = SKSMARTCARD32.DLL
21 = SKCOMMIF.DLL
22 = Trs5klib.dll
23 = prolific.dll
24 = AtPassRsaMD.dll
25 = AtPassRsaMDd.dll
26 = AtPassRsaMDu.dll
27 = AtPassRsaMDud.dll
28 = libcryptoMD.dll
29 = libcryptoMDd.dll
30 = msvcm90d.dll
31 = msvcp90d.dll
32 = msvcr90d.dll


; workshop files
24 = axiswork.exe
25 = awbuild.dll
26 = awcommon.dll
27 = awdlg.dll
28 = awobject.dll
29 = awsock.dll
30 = awtool.dll
31 = awuser.dll
32 = awwcc.dll
33 = axisgw.dll
34 = awcnv.dll
35 = axisform.dll
36 = axisvbs.dll
37 = axsock.ocx
38 = axwizard.ocx
39 = axisbuilder.exe
40 = IBKSCONNECTOR.OCX
41 = UPDATEAGENT.EXE
42 = KDFAPI2.DLL
43 = npenkAppInstall5Message.xml
44 = npenkapp5policy_ibkscs.xml
45 = npenkAppInstall5.dll
46 = npe55kb.npn
47 = klib.dll
48 = KDFAPI3.DLL
49 = 
50 = npenkMain5.npn
51 = AOSSDK.DLL
52 = AOSSDKRAD.DLL
53 = BZ32EX.DLL
54 = SUIPRE.DLL
55 = V3HUNT.DLL
56 = ASPLNCHR.EXE
57 = SKCOMMAD.DLL
58 = SKCOMMCM.DLL
59 = SKCOMMEM.DLL
60 = SKCOMMJV.DLL
61 = SKCOMMSC.DLL
62 = SKCOMMTM.EXE
63 = NSLDAP32V11.DLL
64 = AOSSDK64.DLL
65 = AOSSDKJNI64.DLL
66 = AOSSDKJNI.DLL
67 = AOSSDKRAD64.DLL
68 = CX_PCIDENTITY.DLL
69 = StSdkEx.DLL
70 = StSdkEx64.DLL
