//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ChartPeriodSummaryAddIn.rc
//
#define IDB_LINE_THICKNESS              1034
#define IDB_LINE_STYLE                  1035
#define IDB_NEWS_FOLDER                 2000
#define IDC_EDIT1                       2000
#define IDR_MENU1                       2001
#define IDC_EDIT2                       2001
#define IDR_MENUPS                      2001
#define IDD_DLG_PS                      2002
#define IDC_DATETIMEPICKER1             2003
#define IDC_CURSOR1                     2003
#define IDC_DATETIMEPICKER2             2004
#define IDD_DLG_OL_CONFIG               2004
#define IDC_RADIO1                      2005
#define IDD_DLG_OL_MAN                  2005
#define IDC_BUTTON1                     2006
#define IDC_CMB_ACCT                    2007
#define IDC_COMBO1                      2007
#define IDD_DIALOG1                     2007
#define IDC_COMBO2                      2008
#define IDC_RADIO2                      2009
#define IDC_CURSOR2                     2009
#define IDC_CHECK1                      2010
#define IDC_CHECK2                      2011
#define IDR_MENUOL                      2011
#define IDC_CHECK3                      2012
#define IDD_DLG_CONFIRM                 2012
#define IDC_CHECK4                      2013
#define IDD_DLG_CONFIRMLIST             2013
#define IDC_CHECK5                      2014
#define IDC_CHECK6                      2015
#define IDC_CHECK7                      2016
#define IDC_CHECK8                      2017
#define IDC_CHECK9                      2018
#define IDC_CHECK10                     2019
#define IDC_CHECK11                     2020
#define IDC_CHECK12                     2021
#define IDC_CHECK13                     2022
#define IDC_BTN_DEL                     2024
#define IDC_LIST1                       2025
#define IDC_BTN_SAVE                    2026
#define IDC_ACOUNT_NAME                 2028
#define IDC_BUTTON2                     2029
#define IDC_BTN_COLOR                   2029
#define IDC_COMBO3                      2030
#define IDC_LINE_THICKNESS              2030
#define IDC_LINE_STYLE                  2031
#define IDC_SEMIAUTO_SELL               2032
#define IDC_SEMI_AUTO_BUY               2033
#define IDC_CODE                        2034
#define IDC_ACOUNT                      2035
#define IDC_SEMIAUTO_SELL2              2035
#define IDC_SEMI_AUTO_BUY2              2036
#define IDC_STATIC_TYPE                 2036
#define IDC_STATIC_NAME                 2037
#define IDC_STATIC_PRICE                2038
#define IDC_CHECK_Y_SIGA                6000
#define IDD_DLG_GLINE                   6000
#define IDC_CHECK_Y_JEOGA               6001
#define IDC_CHECK_Y_GOGA                6002
#define IDC_CHECK_Y_ZONGA               6003
#define IDC_CHECK_Y_SGJ_D2              6004
#define IDC_CHECK_HIGH_LIMIT            6005
#define IDC_CHECK_LOW_LIMIT             6006
#define IDC_COMBO_Y_SIGA                6007
#define IDC_COMBO_Y_GOGA                6008
#define IDC_COMBO_Y_JEOGA               6009
#define IDC_CHECK_T_SIGA                6010
#define IDC_CHECK_T_JEOGA               6011
#define IDC_CHECK_T_GOGA                6012
#define IDC_CHECK_T_ZONGA               6013
#define IDC_CHECK_T_SGJ_D2              6014
#define IDC_CHECK_T_GJ_D2               6015
#define IDC_CHECK_T_GJZ_D4              6016
#define IDC_COMBO_T_SIGA                6017
#define IDC_EDIT_1YP                    6018
#define IDC_CHECK_2_RSST                6020
#define IDC_CHECK_PIVOT_GLINE           6021
#define IDC_CHECK_1_RSST                6022
#define IDC_CHECK_1_GG                  6023
#define IDC_CHECK_2_GG                  6024
#define IDC_COMBO_2_RSST                6025
#define IDC_CHECK_PREGOGA               6026
#define IDC_CHECK_PREJEOGA              6027
#define IDC_CHECK_DMK_GLINE             6028
#define IDC_COMBO_Y_ZONGA               6029
#define IDC_COMBO_HIGH_LIMIT            6030
#define IDC_COMBO_PREGOGA               6031
#define IDC_CHECK_1YP                   6032
#define IDC_CHECK_3YP                   6033
#define IDC_CHECK_2YP                   6034
#define IDC_CHECK_4YP                   6035
#define IDC_COMBO_Y_SGJ_D2              6036
#define IDC_COMBO_1YP                   6037
#define IDC_EDIT_2YP                    6038
#define IDC_EDIT_3YP                    6039
#define IDC_EDIT_4YP                    6040
#define IDC_CHECK_PMD                   6041
#define IDC_CHECK_PMPD                  6042
#define IDC_CHECK_PMMD                  6043
#define IDC_COMBO_PMMD                  6044
#define IDC_EDIT_PLUS_RATIO             6045
#define IDC_EDIT_MINUS_RATIO            6046
#define IDC_COMBO_LOW_LIMIT             6048
#define IDC_COMBO_T_GOGA                6049
#define IDC_COMBO_T_JEOGA               6050
#define IDC_COMBO_T_ZONGA               6051
#define IDC_COMBO_T_GJ_D2               6052
#define IDC_COMBO_T_SGJ_D2              6053
#define IDC_COMBO_T_GJZ_D4              6054
#define IDC_COMBO_PMM_PD                6056
#define IDC_COMBO_PMMD_MD               6057
#define IDC_COMBO_1_RSST                6059
#define IDC_COMBO_PIVOT_GLINE           6060
#define IDC_COMBO_1_GG                  6061
#define IDC_COMBO_2_GG                  6062
#define IDC_COMBO_DMKGLINE              6063
#define IDC_COMBO_PREJEOGA              6064
#define IDC_COMBO_2YP                   6065
#define IDC_COMBO_3YP                   6066
#define IDC_COMBO_4YP                   6067
#define IDC_BTNCLR_Y_GOGA               6100
#define IDC_BTNCLR_Y_JEOGA              6101
#define IDC_BTNCLR_Y_ZONGA              6102
#define IDC_BTNCLR_HIGH_LIMIT           6103
#define IDC_BTNCLR_Y_SGJ_D2             6104
#define IDC_BTNCLR_LOW_LIMIT            6105
#define IDC_BTNCLR_T_SIGA               6106
#define IDC_BTNCLR_T_GOGA               6107
#define IDC_BTNCLR_T_JEOGA              6108
#define IDC_BTNCLR_T_ZONGA              6109
#define IDC_BTNCLR_T_GJ_D2              6110
#define IDC_BTNCLR_T_SGJ_D2             6111
#define IDC_BTNCLR_T_GJZ_D4             6112
#define IDC_BTNCLR_PMMD                 6113
#define IDC_BTNCLR_2_RSST               6114
#define IDC_BTNCLR_1_RSST               6115
#define IDC_BTNCLR_PIVOT_GLINE          6116
#define IDC_BTNCLR_1_GG                 6117
#define IDC_BTNCLR_2_GG                 6118
#define IDC_BTNCLR_PREGOGA              6119
#define IDC_BTNCLR_DMK_GLINE            6120
#define IDC_BTNCLR_PREJEOGA             6121
#define IDC_BTNCLR_PMMD2                6122
#define IDC_BTNCLR_PMMD3                6123
#define IDC_BTNCLR_1YP                  6124
#define IDC_BTNCLR_2YP                  6125
#define IDC_BTNCLR_3YP                  6126
#define IDC_BTNCLR_4YP                  6127
#define IDC_BTNCLR_Y_SIGA               6128
#define IDC_CHECK_GLINEDRAW             8000
#define IDC_AP_INDICATOR                29000
#define IDC_AP_HIGHLIGHT                29001
#define IDS_AVERAGE_PRICE               41309
#define IDS_NUMBER                      41310
#define IDS_BASIC_BONG                  41311
#define IDS_DELETE                      41312
#define IDS_STARTING_CLOSE_NUMBERS      41313
#define IDS_POSITIVE_BONG_NUMBERS       41314
#define IDS_POSITIVE_NEGATIVE_PERCENTAGE 41315
#define IDS_NEGATIVE_BONG_NUMBERS       41316
#define IDS_ENDING_CLOSE_PRIVE          41317
#define IDS_ISSUE_NAME                  41318
#define IDS_ISSUE_CODE                  41319
#define IDS_MAX_VOLUME                  41320
#define IDS_MIN_VOLUME                  41321
#define IDS_COLOR_SET                   41322
#define IDS_AVERAGE_VOLUME              41323
#define IDS_HIGH_PRICE                  41324
#define IDS_LOW_PRICE                   41325
#define IDS_CANDLE                      41326
#define IDS_STRING_FONT                 41327
#define IDS_STRING_RISE                 41328
#define IDS_STRING_FALL                 41329
#define IDS_STRING_SELL                 41330
#define IDS_STRING_BUY                  41331
#define IDS_STRING_YEAR                 41332
#define IDS_STRING_MONTH                41333
#define IDS_STRING_DAY                  41334
#define IDS_STRING_HOUR                 41335
#define IDS_STRING_MINUTE               41336
#define IDS_STRING_SECOND               41337

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2014
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         2040
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
