#ifndef _RAWDATA_DEF_H_
#define _RAWDATA_DEF_H_

#define RAWOPENDATA		1
#define RAWHIGHDATA		2
#define RAWLOWDATA		3
#define RAWCLOSEDATA	4
#define RAWVOLUMEDATA	5
#define RAWAMOUNTDATA	6
#define RAWDATEDATA		7
#define RAWINDEX		8
#define RAWCURRENTBAR	9
#define RAWBARINTERVAL	10
#define RAWCODECATEGORY	11
#define RAWCURRENTDATE	12
#define RAWCURRENTTIME	13
#define RAWDATACOMPRESS	14
#define RAWDATETYPE		15
//KHD : 2006.12.12 
#define RAWPREVOPENDATA		16
#define RAWPREVCLOSEDATA		17
#define RAWPREVHIGHDATA		18
#define RAWPREVLOWDATA		19
#endif // _RAWDATA_DEF_H_