//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by axisWork.rc
//
#define IDD_ABOUTBOX                    100
#define ID_WORKSPACEBAR                 101
#define ID_PROPERTIESBAR                102
#define ID_PRO_CTLLISTCBO               103
#define ID_EDITCTL                      104
#define ID_COMBOCTL                     105
#define ID_BUTTONCTL                    106
#define ID_WRK_RELOADBTN                107
#define ID_WRK_TAB                      108
#define ID_WRK_CLIENT                   109
#define ID_WRK_SERVER                   110
#define ID_WRK_FNAMES                   111
#define ID_WRK_OPENBTN                  112
#define ID_SCRIPTBAR                    113
#define IDR_TREEFILECTRL_POPUP          114
#define ID_SRP_CTRLLIST                 114
#define ID_SRP_EVENTLIST                115
#define ID_SRP_RICHEDIT                 116
#define ID_WRK_TABLIST                  117
#define ID_WRK_GROUPCBOSYM              118
#define ID_WRK_GROUPCBOTMP              119
#define ID_WRK_LISTSYM                  120
#define ID_WRK_LISTTMP                  121
#define ID_WRK_TREEBTN                  124
#define ID_WRK_LISTBTN                  125
#define ID_WRK_LISTSVR                  126
#define ID_WRK_GROUPCBOSVR              127
#define IDR_MAINFRAME                   128
#define ID_WRK_TEMPLATE                 128
#define IDR_AXISWORTYPE                 129
#define ID_PREVIEWBAR                   129
#define IDR_DRAWBAR                     130
#define ID_WRK_PROJECTCBOSYM            130
#define IDR_ALIGNBAR                    131
#define ID_WRK_IOCBOSYM                 131
#define IDR_TREEFILECTRL_NO_DROPMOVE    132
#define ID_SCR_PINBTN                   132
#define IDR_TREEFILECTRL_NO_DROPCOPY    133
#define ID_SRP_LINESTATIC               133
#define IDR_EXBAR                       134
#define IDR_TREEFILECTRL_DROPCOPY       135
#define ID_TRACEBAR                     135
#define ID_TRC_RICHEDIT                 136
#define IDB_FILETREECTRL_NETWORK        137
#define ID_WRK_SYMBOL                   137
#define ID_WRK_DEPTHBTN                 138
#define ID_SELECTIONBAR                 139
#define IDD_QUICK                       141
#define ID_SCR_PYBTN                     142
#define ID_CV_PYBTN                      143
#define IDI_MAP                         156
#define IDI_TEMPLATE                    157
#define IDI_PROCEDURES                  158
#define IDB_TREEBTN                     160
#define IDB_LISTBTN                     161
#define IDB_PINBTNNOPUSH                162
#define IDB_PINBTNPUSH                  163
#define IDD_AUTOCOMPLETE                164
#define IDB_AUTOCMPLIMG                 167
#define IDB_TABIMG                      168
#define IDB_OPENBTN                     169
#define IDB_RELOADBTN                   170
#define IDB_MAPONLYBTN                  175
#define IDB_MAINBAR_DISABLE             176
#define IDB_ALIGNBAR_DISABLE            178
#define ID_WRK_MAPONLYBTN               180
#define IDB_DRAWBAR_DISABLE             180
#define IDB_EXBAR_DISABLE               182
#define IDD_AUTOTIP                     188
#define IDB_UPDATEBMP                   197
#define IDB_TWODEPTHBTN                 198
#define IDB_SELECTIONBAR                199
#define IDB_MARGIN_BKG                  200
#define IDC_RADIO1                      1007
#define IDC_RADIO2                      1008
#define IDC_COMBO1                      1010
#define IDC_EDIT1                       1011
#define IDC_BUTTON1                     1012
#define IDC_EDIT2                       1013
#define IDC_EDIT3                       1014
#define IDC_SPIN1                       1015
#define IDC_COMBO2                      1016
#define IDC_CHECK1                      1017
#define IDC_EDIT4                       1018
#define IDC_SPIN2                       1019
#define IDC_EDIT5                       1020
#define IDC_CHECK2                      1021
#define IDC_BUTTON2                     1022
#define IDC_MONTHCALENDAR1              1024
#define IDC_TAB1                        1029
#define IDC_ACLIST                      1030
#define IDD_MYFINDDLG                   1540
#define IDB_SERVERTREE                  4002
#define IDD_EDIT_FIND                   8601
#define IDD_EDIT_REPLACE                8602
#define IDC_EDIT_WHOLE_WORD             8603
#define IDC_EDIT_MATCH_CASE             8604
#define IDC_EDIT_TEXT                   8605
#define IDS_EDIT_TEXT_NOT_FOUND         8606
#define IDC_EDIT_REPLACE                8607
#define IDC_EDIT_REPLACE_ALL            8608
#define IDC_EDIT_REPLACE_WITH           8609
#define IDC_EDIT_SKIP                   8610
#define IDC_EDIT_DIRECTION_UP           8611
#define IDC_EDIT_DIRECTION_DOWN         8612
#define IDC_EDIT_SCOPE_SELECTION        8613
#define IDC_EDIT_SCOPE_WHOLE_FILE       8614
#define IDS_MENU_UNDO_FORMAT            8615
#define IDS_MENU_REDO_FORMAT            8616
#define IDS_MENU_UNDO_DEFAULT           8617
#define IDS_MENU_REDO_DEFAULT           8618
#define IDS_EDITOP_UNKNOWN              8619
#define IDS_EDITOP_PASTE                8620
#define IDS_EDITOP_DELSELECTION         8621
#define IDS_EDITOP_CUT                  8622
#define IDS_EDITOP_DELETE               8623
#define IDS_EDITOP_TYPING               8624
#define IDS_EDITOP_BACKSPACE            8625
#define IDS_EDITOP_INDENT               8626
#define IDS_EDITOP_DRAGDROP             8627
#define IDS_EDITOP_REPLACE              8628
#define IDS_EDITOP_AUTOINDENT           8629
#define IDR_MARGIN_CURSOR               22900
#define IDR_DEFAULT_ACCEL               22901
#define IDR_MARGIN_ICONS                22902
#define ID_DROPDOWNBASE                 32600
#define ID_APP_NEW                      32700
#define ID_APP_LISTNEW                  32701
#define ID_APP_TABLENEW                 32702
#define ID_APP_OPENPC                   32703
#define ID_APP_OPENSERVER               32704
#define ID_APP_SAVEPC                   32705
#define ID_APP_SAVEPATH                 32706
#define ID_APP_MAPCLOSE                 32707
#define ID_APP_COPY                     32708
#define ID_APP_PASTE                    32709
#define ID_APP_SOURCE                   32710
#define ID_APP_COMPILE                  32711
#define ID_APP_MOVE_AXIS                32712
#define ID_VIEW_MAINBAR                 32713
#define ID_VIEW_DRAWBAR                 32714
#define ID_VIEW_ALIGNBAR                32715
#define ID_VIEW_EXBAR                   32716
#define ID_APP_RELOAD                   32717
#define ID_HIDE_FORM                    32718
#define ID_VIEW_SOURCE_VIEWER           32719
#define ID_VIEW_SOURCE                  32720
#define ID_APP_ORDER                    32721
#define ID_APP_MAPINFO                  32722
#define ID_APP_SERVER                   32723
#define ID_APP_SAVESERVER               32724
#define ID_VIEW_ALLSELECT               32725
#define ID_APP_CUT                      32726
#define ID_APP_REFRESH                  32727
#define ID_APP_BATCH                    32728
#define ID_APP_USERM                    32729
#define ID_VIEW_PROPERTIES              32730
#define ID_VIEW_WORKSPACE               32731
#define ID_EDIT_SCRIPT                  32732
#define ID_APP_SETBOOKMARK              32733
#define ID_APP_GOBOOKMARK               32734
#define ID_APP_ALLCOMPILE               32735
#define ID_APP_ALLMOVEAXIS              32736
#define ID_APP_PREVIEW                  32737
#define ID_FILE_SAVETMPL                32738
#define ID_EDIT_TABORDER                32739
#define ID_EDIT_IOORDER                 32740
#define ID_FILE_SETPATH                 32741
#define ID_VIEW_RUN                     32742
#define ID_APP_NEWTMPL                  32743
#define ID_APP_NEWSC                    32744
#define ID_APP_SETTING                  32745
#define ID_EDIT_GOTO                    32746
#define ID_EDIT_MAPUNDO                 32747
#define ID_EDIT_MAPREDO                 32748
#define ID_VIEW_WNDTAB                  32749
#define ID_CONVERT_30                   32750
#define ID_VIEW_DEBUG                   32751
#define ID_APP_EDITTABORDER             32752
#define ID_APP_SAVETOOLBAR              32753
#define ID_APP_DEFAULTTOOLBAR           32754
#define ID_VIEW_SELECTIONBAR            32755
#define ID_EX_FORMAT                    32771
#define ID_EX_RGB                       32772
#define ID_TREEFILECTRL_OPEN            32782
#define ID_TREEFILECTRL_DELETE          32783
#define ID_TREEFILECTRL_RENAME          32784
#define ID_TREEFILECTRL_PROPERTIES      32785
#define ID_TOOL_BASE                    32801
#define ID_TOOL_POINTER                 32801
#define ID_TOOL_SYS                     32802
#define ID_TOOL_LABEL                   32803
#define ID_TOOL_BOX                     32804
#define ID_TOOL_GROUP                   32805
#define ID_TOOL_PANEL                   32806
#define ID_TOOL_PUSH                    32807
#define ID_TOOL_RADIO                   32808
#define ID_TOOL_CHECK                   32809
#define ID_TOOL_EDIT                    32810
#define ID_TOOL_COMBO                   32811
#define ID_TOOL_OUT                     32812
#define ID_TOOL_MEMO                    32813
#define ID_TOOL_GRID                    32814
#define ID_TOOL_TABLE                   32815
#define ID_TOOL_TREE                    32816
#define ID_TOOL_AVI                     32817
#define ID_TOOL_GRAPH                   32818
#define ID_TOOL_OBJECT                  32819
#define ID_TOOL_TAB                     32820
#define ID_TOOL_USERTAB                 32821
#define ID_TOOL_SHEET                   32822
#define ID_TOOL_BROWSER                 32823
#define ID_TOOL_CONTROL                 32824
#define ID_AL_LEFT                      32851
#define ID_AL_RIGHT                     32852
#define ID_AL_TOP                       32853
#define ID_AL_BOTTOM                    32854
#define ID_BLK_HCENTER                  32855
#define ID_BLK_VCENTER                  32856
#define ID_WIN_HCENTER                  32857
#define ID_WIN_VCENTER                  32858
#define ID_SPC_HEQUAL                   32859
#define ID_SPC_VEQUAL                   32860
#define ID_SZ_HEQUAL                    32861
#define ID_SZ_VEQUAL                    32862
#define ID_TREEFILECTRL_REFRESH         32900
#define ID_TREEFILECTRL_BACK            32901
#define ID_TREEFILECTRL_FORWARD         32902
#define ID_TREEFILECTRL_UPONELEVEL      32903
#define ID_EDIT_GAP                     32913
#define ID_RSENDTOFIRST                 32920
#define ID_RSENDTOEND                   32921
#define ID_SHOWSCRIPT                   32922
#define ID_SHOWATTRIBUTE                32923
#define ID_COLUMNEDIT                   32924
#define ID_GROUPMAKE                    32925
#define ID_DISGROUPING                  32926
#define ID_ADDITEM                      32927
#define ID_SELECTCOLUMN                 32928
#define ID_COLUMNFIT                    32929
#define ID_EXTMENUID                    32930
#define ID_MENUITEM32936                32936
#define ID_APP_AXHELP                   32941
#define ID_APP_VBHELP                   32942
#define ID_APP_HELP                     32950
#define ID_EDIT_DELETE                  37000
#define ID_EDIT_DELETE_BACK             37001
#define ID_EDIT_DELETE_WORD_BACK        37002
#define ID_EDIT_TAB                     37003
#define ID_EDIT_UNTAB                   37004
#define ID_EDIT_SWITCH_OVRMODE          37005
#define ID_EDIT_CHAR_LEFT               37100
#define ID_EDIT_EXT_CHAR_LEFT           37101
#define ID_EDIT_CHAR_RIGHT              37102
#define ID_EDIT_EXT_CHAR_RIGHT          37103
#define ID_EDIT_WORD_LEFT               37104
#define ID_EDIT_EXT_WORD_LEFT           37105
#define ID_EDIT_WORD_RIGHT              37106
#define ID_EDIT_EXT_WORD_RIGHT          37107
#define ID_EDIT_LINE_UP                 37108
#define ID_EDIT_EXT_LINE_UP             37109
#define ID_EDIT_LINE_DOWN               37110
#define ID_EDIT_EXT_LINE_DOWN           37111
#define ID_EDIT_SCROLL_UP               37112
#define ID_EDIT_SCROLL_DOWN             37113
#define ID_EDIT_PAGE_UP                 37114
#define ID_EDIT_EXT_PAGE_UP             37115
#define ID_EDIT_PAGE_DOWN               37116
#define ID_EDIT_EXT_PAGE_DOWN           37117
#define ID_EDIT_LINE_END                37118
#define ID_EDIT_EXT_LINE_END            37119
#define ID_EDIT_HOME                    37120
#define ID_EDIT_EXT_HOME                37121
#define ID_EDIT_TEXT_BEGIN              37122
#define ID_EDIT_EXT_TEXT_BEGIN          37123
#define ID_EDIT_TEXT_END                37124
#define ID_EDIT_EXT_TEXT_END            37125
#define ID_EDIT_FIND_PREVIOUS           37126
#define ID_EDIT_LINECUT                 37127
#define ID_EDIT_TOGGLE_BOOKMARK0        37200
#define ID_EDIT_TOGGLE_BOOKMARK1        37201
#define ID_EDIT_TOGGLE_BOOKMARK2        37202
#define ID_EDIT_TOGGLE_BOOKMARK3        37203
#define ID_EDIT_TOGGLE_BOOKMARK4        37204
#define ID_EDIT_TOGGLE_BOOKMARK5        37205
#define ID_EDIT_TOGGLE_BOOKMARK6        37206
#define ID_EDIT_TOGGLE_BOOKMARK7        37207
#define ID_EDIT_TOGGLE_BOOKMARK8        37208
#define ID_EDIT_TOGGLE_BOOKMARK9        37209
#define ID_EDIT_GO_BOOKMARK0            37210
#define ID_EDIT_GO_BOOKMARK1            37211
#define ID_EDIT_GO_BOOKMARK2            37212
#define ID_EDIT_GO_BOOKMARK3            37213
#define ID_EDIT_GO_BOOKMARK4            37214
#define ID_EDIT_GO_BOOKMARK5            37215
#define ID_EDIT_GO_BOOKMARK6            37216
#define ID_EDIT_GO_BOOKMARK7            37217
#define ID_EDIT_GO_BOOKMARK8            37218
#define ID_EDIT_GO_BOOKMARK9            37219
#define ID_EDIT_TOGGLE_BOOKMARK         37223
#define ID_EDIT_GOTO_NEXT_BOOKMARK      37224
#define ID_EDIT_GOTO_PREV_BOOKMARK      37225
#define ID_EDIT_CLEAR_ALL_BOOKMARKS     37226


#define ID_VIEW_APPLOOK_WIN_2000	205
#define ID_VIEW_APPLOOK_OFF_XP		206
#define ID_VIEW_APPLOOK_WIN_XP		207
#define ID_VIEW_APPLOOK_OFF_2003	208
#define ID_VIEW_APPLOOK_VS_2005		209
#define ID_VIEW_APPLOOK_VS_2008		210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE	215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK	216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER	217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA	218
#define ID_VIEW_APPLOOK_WINDOWS_7	219

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32947
#define _APS_NEXT_CONTROL_VALUE         1031
#define _APS_NEXT_SYMED_VALUE           140
#endif
#endif
