//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by D:\00Project\114Solomon\ProjSrc\SrcChartEx\ChartAddIn\ChartDesignPropertyAddIn\ChartDesignPropertyAddIn\res\ChartDesignPropertyAddIn_Eng\ChartDesignPropertyAddIn_Eng.rc
//
#define IDS_MOUSE_POSITION              1
#define IDS_GLANCEBALANCE_CURSOR        2
#define IDS_CORSS_OVER                  3
#define IDS_NIDLG_OVER                  4
#define IDS_PAN                         5
#define IDC_BTN_DELETE                  5
#define IDS_DRAG_Y_ZOOM                 6
#define IDC_BTN_UPDATE                  6
#define IDS_CROSS_TOOL                  7
#define IDS_NIDLG_TOOL                  8
#define IDS_ORDER_LINE                  9
#define IDS_ANALYSIS_TOOL               10
#define IDS_SYMBOL_TOOL                 11
#define IDS_PEIOD_SUMMARY               12
#define IDS_ST_INDICATOR                13
#define IDS_OBJECT_TOOL                 14
#define IDS_ASKED_PRICE                 15
#define IDS_TIME_MARKER                 16
#define IDS_TOOL_TIP                    17
#define IDS_NIDLG_DRAG                  18
#define IDS_CROSS_DRAG                  19
#define IDS_DRAG_ZOOM                   20
#define IDS_KBD_SCROLL                  21
#define IDS_EXCEL_IMPORT                22
#define IDS_AUTO_SCROLL                 23
#define IDS_PRICE_YSCALE_SETUP          24
#define IDS_RELPSA                      25
#define IDS_SAVE_IMAGE                  26
#define IDS_ADD_INDICATOR_CMD           27
#define IDS_DATA_VIEWER                 28
#define IDS_STYLE_DATA                  29
#define IDS_ENV_SETUP                   30
#define IDS_DRDS_REAL                   31
#define IDS_DIRECT_REAL                 32
#define IDS_LOG                         33
#define IDD_PROPPAGE_SHARED             107
#define IDC_COMBO_FONTLIST              204
#define IDC_COMBO_FONTSIZE              210
#define IDC_FONT_BOLD                   223
#define IDC_USE_REALDATA                228
#define IDR_CONTEXT                     229
#define IDC_REAL_LIST                   231
#define IDC_FONT_UNDERLINE              231
#define IDC_FONT_ITALY                  235
#define IDC_FONT_CANCELLINE             237
#define IDC_FONT_PREVIEW                238
#define IDC_EDIT_FONT                   239
#define IDC_PACKET_TREE                 248
#define IDC_LSHARELIST                  257
#define IDC_LSHAREDEDIT                 258
#define IDC_BTNADD                      259
#define IDC_BTNDEL                      260
#define IDC_BTNMODIFY                   261
#define IDC_GSHARELIST                  262
#define IDC_GSHAREDEDIT                 263
#define IDC_SHARENAME                   264
#define IDC_GBTNADD                     265
#define IDC_CHKSTART                    265
#define IDC_CHKSET                      266
#define IDC_GBTNDEL                     267
#define IDC_CHKGET                      267
#define IDC_SHAREDTYPE                  268
#define IDC_GBTNMODIFY                  269
#define IDC_INDEX                       269
#define IDC_CMB_SHAREDNAME              273
#define IDC_SHARE_LIST                  275
#define IDC_BTN_ADD                     276
#define IDC_BTN_DEL                     277
#define IDC_TOOLTIP                     321
#define IDS_HORIZONTAL                  1000
#define IDS_VERTICAL                    1001
#define IDS_CHECKERS                    1002
#define IDS_SEPARATOR                   1003
#define IDS_GAP                         1004
#define IDS_BORDER                      1005
#define IDS_ENTER_20TO20                1006
#define IDS_ENTER_0TO20                 1007
#define IDS_BLOCK_COUNT_OVER            1008
#define IDS_BLOCKSHAPE_TOOLTIP_1        1009
#define IDS_BLOCKSHAPE_TOOLTIP_2        1010
#define IDS_BLOCKSHAPE2_TOOLTIP_1       1011
#define IDS_BLOCKSHAPE2_TOOLTIP_2       1012
#define IDS_BLOCKSET_STATIC3_TOOLTIP_1  1013
#define IDS_BLOCKSET_STATIC3_TOOLTIP_2  1014
#define IDS_BLOCKSET_STATIC3_TOOLTIP_3  1015
#define IDS_BLOCKSET_STATIC3_TOOLTIP_4  1016
#define IDS_BLOCKSET_STATIC3_TOOLTIP_5  1017
#define IDS_BLOCKSET_STATIC3_TOOLTIP_6  1018
#define IDS_BLOCKSET_STATIC3_TOOLTIP_7  1019
#define IDS_BLOCKSET_STATIC3_TOOLTIP_8  1020
#define IDS_BLOCKSET_STATIC3_TOOLTIP_9  1021
#define IDS_BLOCKWIDTH_TOOLTIP_1        1022
#define IDS_BLOCKGAP_TOOLTIP_1          1023
#define IDS_BLOCKGAP_TOOLTIP_2          1024
#define IDS_BLOCKGAP_TOOLTIP_3          1025
#define IDS_BLOCKGAP_TOOLTIP_4          1026
#define IDS_BLOCKGAP_TOOLTIP_5          1027
#define IDS_BLOCKGAP_TOOLTIP_6          1028
#define IDS_BLOCKGAP_TOOLTIP_7          1029
#define IDS_CANNOT_BE_NEGATIVE          1036
#define IDS_BLOCKNUMBER_OVER            1037
#define IDS_LIST_CHART_TOOLTIP_1        1038
#define IDS_LIST_CHART_TOOLTIP_2        1039
#define IDS_LIST_CHART_TOOLTIP_3        1040
#define IDS_LIST_CHART_TOOLTIP_4        1041
#define IDS_LIST_CHART_TOOLTIP_5        1042
#define IDS_LIST_CHART_TOOLTIP_6        1043
#define IDS_LIST_CHART_TOOLTIP_7        1044
#define IDS_LIST_CHART_TOOLTIP_8        1045
#define IDS_BACKGROUNDCOLOR_TOOLTIP     1047
#define IDS_BACKBORDERCOLOR_TOOLTIP     1048
#define IDS_HORIZONTAL_GRIDCOLOR_TOOLTIP 1049
#define IDS_VERTICAL_GRIDCOLOR_TOOLTIP  1050
#define IDS_SCALETEXTCOLOR_TOOLTIP      1051
#define IDS_BLOCKCOLOR_TOOLTIP          1052
#define IDS_BLOCKBORDERCOLOR_TOOLTIP    1053
#define IDS_ANALYZETOOLCOLOR_TOOLTIP    1054
#define IDS_6_LINE_COLOR_TOOLTIP        1055
#define IDS_SCALEPOSITION_TOOLTIP_1     1056
#define IDS_SCALEPOSITION_TOOLTIP_2     1057
#define IDS_HORIZONSACLESTYLE_TOOLTIP   1058
#define IDS_DATADATESCALESTYLE_TOOLTIP  1059
#define IDS_DATAHOURSCALESTYLE_TOOLTIP  1060
#define IDS_TEXTSCALESTYLE_TOOLTIP      1061
#define IDS_INDICATORFUNCTIONNAME_TOOLTIP 1062
#define IDS_PACKETLIST_TOOLTIP          1063
#define IDS_SACLESTYLE_TOOLTIP          1064
#define IDS_GRAPHSET_STATIC13_TOOLTIP_1 1065
#define IDS_GRAPHSET_STATIC13_TOOLTIP_2 1066
#define IDS_SUBGRAPHSET_TITLE_TOOLTIP   1067
#define IDS_SUBGRAPHSET_GRAPHTYPE_TOOLTIP 1068
#define IDS_SUBGRAPHSET_UPFILLCOLOR_TOOLTIP 1069
#define IDS_SUBGRAPHSET_UPBORDERCOLOR_TOOLTIP 1070
#define IDS_SUBGRAPHSET_UPFILLCHECK_TOOLTIP 1071
#define IDS_SUBGRAPHSET_UPBORDERTHICK_TOOLTIP 1072
#define IDS_SUBGRAPHSET_DOWNFILLCOLOR_TOOLTIP 1073
#define IDS_SUBGRAPHSET_DOWNBORDERCOLOR_TOOLTIP 1074
#define IDS_SUBGRAPHSET_DOWNFILLCHECK_TOOLTIP 1075
#define IDS_SUBGRAPHSET_DOWNBORDERTHICK_TOOLTIP 1076
#define IDS_SUBGRAPHSET_STEADYFILLCOLOR_TOOLTIP 1077
#define IDS_SUBGRAPHSET_STEADYBORDERTHICK_TOOLTIP 1078
#define IDS_SUBGRAPHSET_HIDECHECK_TOOLTIP 1079
#define IDS_BLOCKCOLORFONT_TOOLTIP_1    1080
#define IDS_BLOCKCOLORFONT_TOOLTIP_2    1081
#define IDS_BLOCKCOLORFONT_TOOLTIP_3    1082
#define IDS_BLOCKCOLORFONT_TOOLTIP_4    1083
#define IDS_PACKETSET_TOOLTIP_1         1084
#define IDS_PACKETSET_TOOLTIP_2         1085
#define IDS_PACKETSET_TOOLTIP_3         1086
#define IDS_PACKETSET_TOOLTIP_4         1087
#define IDS_PACKETSET_TOOLTIP_5         1088
#define IDS_PACKETSET_TOOLTIP_6         1089
#define IDS_PACKETSET_TOOLTIP_7         1090
#define IDS_PACKETSET_TOOLTIP_8         1091
#define IDS_PACKETSET_TOOLTIP_9         1092
#define IDS_TOOLLIST_TOOLTIP_1          1093
#define IDS_TOOLLIST_TOOLTIP_2          1094
#define IDS_TOOLLIST_TOOLTIP_3          1095
#define IDS_TOOLLIST_TOOLTIP_4          1096
#define IDS_TOOLLIST_TOOLTIP_5          1097
#define IDS_TOOLLIST_TOOLTIP_6          1099
#define IDS_TOOLLIST_TOOLTIP_7          1100
#define IDS_TOOLLIST_TOOLTIP_8          1102
#define IDS_VIEWDESIGN_STATIC31_TOOLTIP 1103
#define IDS_VIEWDESIGN_STATIC32_TOOLTIP 1104
#define IDS_DISPLAYTOTALDATA_TOOLTIP    1105
#define IDS_DATACOUNTPERONEPAGE_TOOLTIP 1106
#define IDS_VIEWDESIGN_STATIC34_TOOLTIP 1107
#define IDS_USERINSERTEDBLOCKCOUNT_TOOLTIP 1108
#define IDS_CHARTRBUTTONMENU_TOOLTIP_1  1109
#define IDS_CHARTRBUTTONMENU_TOOLTIP_2  1110
#define IDS_GRAPHDRAGANDDROP_TOOLTIP    1111
#define IDS_CONTROLHIDE_TOOLTIP         1112
#define IDS_INPUT_REQUIRE_TOOLTIP       1113
#define IDS_INDICATOR_SAVE_FILE_NAME_TOOLTIP 1114
#define IDS_ENVIRONMENT_SAVE_FILE_NAME_TOOLTIP 1115
#define IDS_YEAR_MONTH_DAY              1116
#define IDS_HOUR_MINUTE_SECOND          1117
#define IDS_BLOCK_SETTING_SET_ALL       1118
#define IDS_BLOCK_SETTING               1119
#define IDS_INDENT_LIMIT_90             1120
#define IDS_PACKETGRID_ITEMNAME         1121
#define IDS_PACKETGRID_FIELDNAME        1122
#define IDS_PACKETGRID_LENGTH           1123
#define IDS_PACKETGRID_TYPE             1124
#define IDS_PACKETGRID_REALTYPE         1125
#define IDS_INVALID_BASE_PACKET         1126
#define IDS_TOOLSET_FUNCTION            1127
#define IDS_TOOLSET_LIMIT_1             1128
#define IDS_TOOLSET_LIMIT_2             1129
#define IDS_TOOLBAR                     1130
#define IDS_NUMERICAL_INQUIRY           1131
#define IDS_FORMAT_FILE_NOT_FOUND       1132
#define IDS_ENTER_LESS_THAN_VIEW_COUNT  1133
#define IDS_MSG_APPLY_ALL_SCALE_LINE    1134
#define IDS_ENTER_NUMBER_1TO10          1135
#define IDC_LST_ADDIN                   2000
#define IDD_LOCAL_LANGUAGE_TABLE        2000
#define IDC_STC_COMMENT                 2001
#define IDC_BTN_CLEAR_ALL               2002
#define IDD_GLOBAL_LANGUAGE_TABLE       2002
#define IDC_BTN_SELECT_ALL              2003
#define IDC_BTN_RESET_DEFAULT           2004
#define IDC_BTN_RESET_UNDO              2005
#define IDC_CHK_LOCK                    2007
#define IDC_EDT_MIN                     2008
#define IDC_BTN_NEXT_SUBGRAPH           2009
#define IDC_EDT_DSPACE                  2009
#define IDC_BTN_PREV_SUBGRAPH           2010
#define IDC_BTN_GRIDSHAPE_LINE          2010
#define IDC_INVERT                      2010
#define IDC_BTN_GRIDSHAPE_CUTTEDLINE    2011
#define IDC_LST_LANGUAGE_TABLE          2011
#define IDC_BTN_GRIDSHAPE_DOTLINE       2012
#define IDC_EDT_META_TEXT               2012
#define IDC_BTN_GRIDSHAPE_NONE          2013
#define IDC_EDT_LANGUAGE_TEXT           2013
#define IDC_LST_META_TABLE              2014
#define IDC_EDT_SEARCH_TEXT             2017
#define IDC_EDT_COPY_BUFFER             2018
#define IDC_CMB_TABLE_TYPE              2019
#define IDC_BTN_REVERSE                 2020
#define IDC_BTN_RESET                   2021
#define IDC_CMB_GLOBAL                  2023
#define IDC_BTN_REDEFINE_GLOBAL         2024
#define IDC_STATIC_SELGROUP             2025
#define IDC_BTN_SFUNC1                  2026
#define IDC_BTN_SFUNC2                  2027
#define IDC_BTN_SINSERT                 2028
#define IDC_BTN_SDELETE                 2029
#define IDC_CUR_PRICE_1                 2030
#define IDC_CUR_PRICE_2                 2031
#define IDC_CUR_PRICE_3                 2032
#define IDC_CUR_PRICE_4                 2033
#define IDC_CUR_PRICE_5                 2034
#define IDC_CUR_PRICE_6                 2035
#define IDC_CUR_PRICE_7                 2036
#define IDC_CUR_PRICE_8                 2037
#define IDD_PROPPAGE_CHARTLIST          7000
#define IDB_FOLDERS                     7000
#define IDC_TREE_CHART                  7001
#define IDB_LIST                        7001
#define IDC_BLOCKCOLORFONT              7002
#define IDD_DLGSHARESET                 7002
#define IDC_BLOCKSHAPE                  7003
#define IDD_PROPPAGE_PACKET             7003
#define IDC_BLOCKSHAPE2                 7004
#define IDD_USERDEFINE_PACKET           7004
#define IDC_BLOCKGAP                    7005
#define IDD_PROPPAGE_REALPACKET         7006
#define IDC_BLOCKWIDTH                  7007
#define IDD_PROPPAGE_VIEWDESIGN         7008
#define IDC_STATIC3                     7009
#define IDD_INTIALIZECONTROL            7009
#define IDC_STATIC4                     7010
#define IDC_STATIC5                     7011
#define IDC_BACKGROUNDCOLOR             7012
#define IDD_COLORSET                    7012
#define IDC_BACKBORDERCOLOR             7013
#define IDC_STATIC19                    7014
#define IDB_ROWBLOCKEDGESPACE           7014
#define IDC_DISPLAYTOTALDATA            7014
#define IDC_DATACOUNTPERONEPAGE         7015
#define IDC_MINDATACOUNT                7016
#define IDD_DIALOG_GRAPHSETTING         7016
#define IDC_DATADATESCALESTYLE          7016
#define IDC_DATAHOURSCALESTYLE          7017
#define IDB_BLOCK                       7022
#define IDR_ITEMMENU                    7023
#define IDB_COLUMNBLOCKSHAPE            7025
#define IDB_MULTIBLOCKSHAPE             7026
#define IDB_BLOCKCOLOR                  7027
#define IDC_SCALEPOS                    7028
#define IDD_DIGTOOLTIP                  7029
#define IDD_BLOCKSET1                   7030
#define IDD_PROPPAGE_FONT               7031
#define IDD_DLGBLOCKSCALE               7032
#define IDC_UPCOLOR                     7032
#define IDC_DOWNCOLOR                   7033
#define IDR_BLOCKMENU                   7034
#define IDC_EQUALCOLOR                  7034
#define IDC_UPEDGECOLOR                 7035
#define IDD_DIALOG_SUBGRAPHSETTING      7035
#define IDC_DOWNEDGECOLOR               7036
#define IDC_EQUALEDGECOLOR              7037
#define IDC_FILLUPCOLOR                 7038
#define IDC_FILLDOWNCOLOR               7039
#define IDD_PROPPAGE_TOOL_RBUTTOL_MENU  7041
#define IDC_TITLE                       7041
#define IDC_STATIC7                     7042
#define IDD_DLG_TOOL_RBUTTON            7042
#define IDC_STATIC6                     7043
#define IDC_STATIC8                     7044
#define IDD_DLG_VERTSCALE               7044
#define IDC_STATIC9                     7045
#define IDD_PROPPAGE_VIEWDESIGN2        7045
#define IDR_VERT_SCALE_MENU             7045
#define IDC_STATIC25                    7046
#define IDC_STATIC_EDGEWIDTH            7046
#define IDC_STATIC40                    7047
#define IDC_BORDERWIDTH                 7047
#define IDC_STATIC10                    7048
#define IDC_STATIC11                    7049
#define IDC_STATIC12                    7050
#define IDD_CHART_INVERT                7050
#define IDD_DIALOG_NUMERICALINQUIRYOPTION 7051
#define IDC_STATIC13                    7051
#define IDC_STATIC14                    7053
#define IDD_DIALOG_GRAPHSETTING2        7053
#define IDC_STATIC15                    7054
#define IDD_PROPPAGE_ADDINLOAD          7054
#define IDC_STATIC16                    7055
#define IDC_STATIC17                    7056
#define IDC_STATIC18                    7057
#define IDC_STATIC21                    7058
#define IDC_STATIC22                    7059
#define IDC_STATIC23                    7060
#define IDC_STATIC24                    7061
#define IDC_STATIC34                    7062
#define IDC_STATIC41                    7063
#define IDC_STATIC27                    7064
#define IDC_STATIC28                    7065
#define IDC_STATIC29                    7066
#define IDC_RADIO_SCALEPOSITION         7069
#define IDC_RADIO                       7070
#define IDC_UP_BORDERTHICKNESS          7070
#define IDC_RADIO_HIDE                  7071
#define IDC_DOWN_BORDERTHICKNESS        7071
#define IDC_RADIO_BOTH                  7075
#define IDC_COMBO_SACLESTYLE            7076
#define IDC_COMBO_HORIZONSACLESTYLE     7077
#define IDC_STATIC20                    7078
#define IDC_STATIC30                    7079
#define IDC_STATIC31                    7080
#define IDC_STATIC32                    7081
#define IDC_STATIC33                    7082
#define IDC_STATIC35                    7083
#define IDC_STATIC37                    7085
#define IDC_STATIC38                    7086
#define IDC_STATIC26                    7086
#define IDC_STATIC39                    7087
#define IDC_SHRINKMARK                  7087
#define IDC_LESSTEXT                    7088
#define IDC_SUBFORM_FRAME               7092
#define IDC_BUTTON_FRAME                7093
#define IDC_CHECK_HIDE                  7094
#define IDC_RADIO1                      7095
#define IDC_RBUTTONTYPE_COMPLEX         7096
#define IDC_RADIO_RIGHT                 7096
#define IDC_CUT_DATA_VIEW               7096
#define IDC_GRAPH_RBUTTONTYPE_COMPLEX   7097
#define IDC_RADIO_LEFT                  7097
#define IDC_CUT_DATA_VIEW_ONLY          7097
#define IDC_RBUTTONTYPE_BASE            7098
#define IDC_TOOL_LIST                   7099
#define IDC_TAB1                        7100
#define IDC_LIST_FRAME                  7101
#define IDC_NO_COMPARTLINE              7104
#define IDC_USESHORTKEY                 7105
#define IDC_USECONDITIONTOTITLE         7108
#define IDC_USEDATATOTITLE              7109
#define IDC_LOW_HIGH_UPDOWN             7110
#define IDC_SIGNAL                      7111
#define IDC_HIGH_NOW_UPDOWN             7112
#define IDC_RBUTTONMENUTYPE             7113
#define IDC_CHECK_MESSAGEBOX            7114
#define IDC_PRE_NOW_CONTRAST            7114
#define IDC_CHECK_BLOCKCOMPART          7115
#define IDC_CUR_DATA                    7115
#define IDC_GRAPH_RBUTTONMENUTYPE       7116
#define IDC_LOW_NOW_UPDOWN              7116
#define IDC_PACKETSIZE                  7118
#define IDC_REDRAWINCASEOFAPPLYINGALLPACKET 7119
#define IDC_CHART_INVERT_CHECK          7120
#define IDC_CHECK_FIREEVENT             7121
#define IDC_INDICONDCHECK               7124
#define IDC_BONGCOUNT_MARGIN            7125
#define IDC_USESKIN                     7125
#define IDC_SAVE_MAPNAME                7126
#define IDC_CHECK_CROSSLINEVIEW         7126
#define IDC_CUT_DATA_PREV               7127
#define IDC_ETCSET_BT                   7128
#define IDC_CUT_DATA_CLOSE              7128
#define IDC_DISPLAY_TRDATA              7129
#define IDC_RDO_NUMERICALINQUIRY        7129
#define IDC_RDO_DRAGZOOM                7130
#define IDC_CHK_USE_OUTER               7131
#define IDC_EDIT1                       10000
#define IDC_EDIT7                       10001
#define IDC_EDT_MAX                     10001
#define IDC_EDIT10                      10002
#define IDC_EDT_USPACE                  10002
#define IDC_ROW                         10003
#define IDC_COLUMN                      10004
#define IDC_STATIC_FRAME                10004
#define IDC_ROW2                        10005
#define IDC_COLUMN2                     10006
#define IDC_BORDERSHAPE                 10007
#define IDC_RADIO2                      10008
#define IDC_RADIO3                      10009
#define IDC_RADIO4                      10010
#define IDC_GRIDSHAPE                   10011
#define IDC_RADIO_NOSCALE               10011
#define IDC_DOT_COMPARTLINE             10012
#define IDC_GRID_SHAPE                  10012
#define IDC_LONGDOT_COMPARTLINE         10013
#define IDC_RADIO7                      10013
#define IDC_STATIC2                     10014
#define IDC_MARGIN_BORDERSHAPE          10014
#define IDC_RADIO11                     10014
#define IDC_RADIO5                      10015
#define IDC_RADIO13                     10015
#define IDC_CHECK1                      10015
#define IDC_RADIO8                      10016
#define IDC_CHECK_BLOCK                 10016
#define IDC_GRID_EXPRESSIONTYPE         10016
#define IDC_USERINSERTEDBLOCKCOUNT      10017
#define IDC_RADIO14                     10017
#define IDC_GRAPHDRAGANDDROP            10018
#define IDC_CHECK_TOOLTIP               10018
#define IDC_RDO_MINMAX_TYPE0            10018
#define IDC_LEFTSPACE                   10019
#define IDC_CHECK_SCALE                 10019
#define IDC_RDO_MINMAX_TYPE1            10019
#define IDC_RIGHTSPACE                  10020
#define IDC_CHECK_GRAPHTITLE            10020
#define IDC_RDO_MINMAX_TYPE2            10020
#define IDC_TOPSPACE                    10021
#define IDC_CHECK_GRAPH                 10021
#define IDC_RDO_USERHOGATYPE0           10021
#define IDC_BOTTOMSPACE                 10022
#define IDC_ENVIRONMENTCHECK            10022
#define IDC_RDO_USERHOGATYPE1           10022
#define IDC_HORZGAP                     10023
#define IDC_CHARTRBUTTONMENU            10023
#define IDC_USERSCALE_EDIT              10023
#define IDC_RADIO10                     10024
#define IDC_HOGASCALE_EDIT              10024
#define IDC_VERTGAP                     10025
#define IDC_INDICATOR_SAVE_FILE_NAME    10025
#define IDC_HIDE                        10027
#define IDC_INPUT_REQUIRE               10028
#define IDC_ENVIRONMENT_SAVE_FILE_NAME  10029
#define IDC_INDICATORFUNCTIONNAME       10029
#define IDC_COMBO_BASEPACKET            10029
#define IDC_GRAPH_TYPE                  10029
#define IDC_COMBO_PACKETLIST            10030
#define IDC_PACKETTYPE                  10030
#define IDC_GRAPHSTYLE                  10030
#define IDC_TEXTSCALESTYLE              10031
#define IDC_DETAIL_PACKETTYPE           10031
#define IDC_GRAPHDRAWSTYLE              10032
#define IDC_BUTTON_CLOSE                10033
#define IDC_BTN_EDIT                    10033
#define IDC_BLOCKCOLOR                  10035
#define IDC_ADVISE_LIST                 10035
#define IDC_BLOCKBORDERCOLOR            10036
#define IDC_LIST_CHART                  10036
#define IDC_ONELINE                     10037
#define IDC_GRIDCOLOR                   10038
#define IDC_ANALYZETOOLCOLOR            10039
#define IDC_SCALETEXTCOLOR              10040
#define IDC_TWOLINE                     10041
#define IDC_THREELINE                   10042
#define IDC_FOURLINE                    10043
#define IDC_FIVELINE                    10044
#define IDC_SIXLINE                     10045
#define IDC_VERTICALGRID                10046
#define IDC_NUMERICALCOLOR              10047
#define IDC_LATTICE                     10048
#define IDR_TITLESCALECOLOR             32771
#define IDR_DELETE                      32772
#define IDR_HORIZONSCALE                32773
#define IDR_VERT_SCALE                  32774
#define IDR_VERT_DELETE                 32775
#define IDR_CHARTINVERT                 32780

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2003
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         2030
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
