// CX_NEWPHONEPAD.idl: CX_NEWPHONEPAD.dll의 형식 라이브러리 소스
// 이 파일은 MIDL 컴파일러에 의해 처리되어
// 형식 라이브러리(CX_NEWPHONEPAD.tlb)입니다.

[ uuid(e2703dbe-e48f-4ac6-b5f7-644637ca9268), version(1.0) ]
library CXNEWPHONEPAD
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");
};
