//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ConditionSearch.rc
//
#define IDC_TAB_CONDITION               3000
#define IDC_COMBO_TAB_FIND              3010
#define IDC_BTN_TAB_SEARCH              3020
#define IDC_BTN_TAB_PRE                 3030
#define IDC_BTN_TAB_NEXT                3040
#define IDC_BTN_TAB_EXP                 3050
#define IDC_BTN_FOLDEREDIT              3060
#define IDC_BTN_FILEADD                 3070
#define IDC_BTN_TREETYPE_SORT           3080
#define IDC_BTN_TREETYPE_NORMAL         3090
#define IDC_TREEXML_ORDER               3110
#define IDC_TREEXML_COMMON              3120
#define IDC_TREEXML_COMMON_SORT         3130
#define IDC_TREEXML_ORDER_SORT          3140
#define IDC_TREEXML_EXCAVATION          3145
#define IDC_EDIT_ITEMHELP               3150
#define IDC_BTN_ITEMHELP                3160
#define IDC_VIEW_HELPHTML               3170
#define IDC_RESULT_GROUPBOX             4000
#define IDC_BTNCHK_BACKTEST             4010
#define IDC_COMBO_BACKTEST_DAY          4020
#define IDC_COMBO_BACKTEST_TIME         4030
#define IDC_BTN_SEARCH                  4040
#define IDC_COMBO_SEARCH_TIME           4060
#define IDC_BTN_ROLLSEARCH              4070
#define IDC_BTN_FIELDEDIT               4080
#define IDC_BTN_REALSEARCH              4090
#define IDC_BTN_RESULTCTRL              4100
#define IDC_BTN_RESULTEXPAND            4110
#define IDI_EXPAND_OVER                 4111
#define IDI_EXPAND                      4112
#define IDI_EXPAND_DISABLE              4113
#define IDC_STATIC_CONDITIONTITLE       4120
#define IDC_PROGRESS_PASS               4121
#define IDC_BTN_PRINT                   4122
#define IDC_RESULT_GRID                 4130
#define IDC_CODEVIEW_GRID               4140
#define IDD_SAVE_DLG                    4500
#define IDC_TREE_USER                   4510
#define IDC_BTN_SAVEDEL                 4515
#define IDC_BTN_SAVEOK                  4520
#define IDC_BTN_SAVECANCEL              4530
#define IDC_EDIT_FILENAME               4540
#define IDC_EDIT_FOLDERNAME             4550
#define IDC_USERQUICK_BTN               5000
#define IDC_QUICK_TAB                   5010
#define IDC_CONDITION_TABCTRL           5020
#define IDC_CONDITIONLIST_WND           5021
#define IDC_CONDITIONRESULT_WND         5030
#define IDC_CONDITIONMAKE_WND           5040
#define IDC_LEFTEXP_BTN                 5100
#define IDC_GRIDTIP_BTN                 5120
#define IDC_DETAIL_BTN                  5135
#define IDC_INITIAL_BTN                 5140
#define IDC_TARGETBASE_COMBO            5150
#define IDC_CONDITIONMAKE_GRID          5160
#define IDC_TAB_SET                     5165
#define IDC_BRACKET_GROUPBOX            5170
#define IDC_BRACKET_BTN                 5180
#define IDC_BRACKETDEL_BTN              5190
#define IDC_PORTDEL_BTN                 5200
#define IDC_LOGICTIP_BTN                5210
#define IDC_COMMON_EDIT                 5220
#define IDC_ORDER_EDIT                  5230
#define IDC_PORTFOLIO_EDIT              5240
#define IDC_COMMONEXSIZE_BTN            5250
#define IDC_ORDEREXSIZE_BTN             5260
#define IDC_USERSAVE_BTN                5270
#define IDC_PORTCHECK_BTN               5280
#define IDC_MAPLOAD                     5290
#define IDC_BTN_MATCHVALCHECK           5300
#define IDC_EDIT_MATCHVAL               5310
#define IDC_BTN_MATCHVALEDIT            5320
#define IDC_BTN_ALERTCHK                5330
#define IDC_STATIC_FUNBAR               5340
#define IDD_FOLDEREDIT_DLG              6100
#define IDC_BTN_FOLDERADD               6110
#define IDC_BTN_FOLDERINSERT            6120
#define IDC_BTN_FOLDERMODIFY            6130
#define IDC_BTN_FOLDERDEL               6140
#define IDC_BTN_OK                      6150
#define IDC_BTN_APPLY                   6155
#define IDC_BTN_CANCEL                  6160
#define IDC_TREE_FILE                   6170
#define IDC_LISTBOX_FILE                6180
#define IDC_BTN_IMPORT                  6190
#define IDC_BTN_EXPORT                  6200
#define IDC_BTN_FILEMODIFY              6210
#define IDC_BTN_FILEDEL                 6220
#define IDC_BTN_RIGHT                   6230
#define IDC_BTN_ALLRIGHT                6240
#define IDC_EDIT_INPUT                  6250
#define IDC_BTN_EDITOK                  6260
#define IDC_BTN_EDITCANCEL              6270
#define ID_GRID_FILE                    6280
#define ID_GRID_FOLDER                  6290
#define IDC_BTN_UPFOLDER                6290
#define IDC_BTN_DOWNFOLDER              6300
#define IDC_BTN_TOPFOLDER               6310
#define IDC_BTN_BOTTOMFOLDER            6320
#define IDC_BTN_UPFILE                  6330
#define IDC_BTN_DOWNFILE                6340
#define IDC_BTN_TOPFILE                 6350
#define IDC_BTN_BOTTOMFILE              6360
#define IDC_BTN_INIT                    6370
#define IDC_BTN_OUTFILEMOVE             6380
#define ID_GRID_MATCHSOURCE             6500
#define IDD_MATCHVALEDIT_DLG            6501
#define ID_GRID_MATCHDEST               6510
#define IDC_BTN_LEFTMOVE                6520
#define IDC_BTN_LEFTMOVE_ALL            6530
#define IDC_BTN_RIGHTMOVE               6540
#define IDC_BTN_RIGHTMOVE_ALL           6550
#define IDC_BTN_UPPOS                   6560
#define IDC_BTN_TOPPOS                  6570
#define IDC_BTN_DOWNPOS                 6580
#define IDC_BTN_BOTTOMPOS               6590
#define IDC_EDIT_MATCH                  6600
#define IDC_BTN_MATCH_OK                6610
#define IDC_BTN_MATCH_CANCEL            6620
#define IDC_BTN_MATCH_EXP               6630
#define IDC_GRID_DEST                   6700
#define IDC_GRID_SOURCE                 6710
#define IDD_QUICKMAKE_DLG               6711
#define ID_GRID_FIELD_SOURCE            6900
#define IDD_FIELDEDIT_DLG               6901
#define ID_GRID_FIELD_DEST              6910
#define IDC_EDIT_FIXCOL                 6920
#define IDC_SPIN_FIXLINE                6930
#define IDC_PORTDEL_DLGLISTBOX          6940
#define IDD_PORTDEL_DLG                 6941
#define IDC_BTN_PORTDEL_OK              6950
#define IDC_BTN_PORTDEL_CANCEL          6960
#define IDB_BTN_SEARCH                  7001
#define IDB_BTN_NEXT                    7002
#define IDB_BTN_PRE                     7003
#define IDB_TREEEXP_O                   7004
#define IDB_TREEEXP_X                   7005
#define IDB_EXP_UP                      7006
#define IDB_EXP_BOTTOM                  7007
#define IDB_EXP_LEFT                    7008
#define IDB_EXP_RIGHT                   7009
#define IDB_BRACKET_DEL                 7010
#define IDB_BRACKET                     7012
#define IDB_MATCHVAL                    7013
#define IDB_EXP_LOGIC_O                 7014
#define IDB_EXP_LOGIC_X                 7015
#define IDB_SEARCH_RUN                  7016
#define IDB_SEARCH_STOP                 7017
#define IDI_ICON_TREE01                 7018
#define IDI_ICON_TREE00                 7020
#define IDD_DIALOGPW                    7026
#define IDI_ICON_TREE00_FILE            7030
#define IDC_STATIC_ACCT                 7031
#define IDC_STATIC_PSWD                 7032
#define IDC_STATIC_ACCT2                7033
#define IDI_ICON_TREE01_FILE            7040
#define IDI_ICON_TREE10                 7050
#define IDI_ICON_TREE11                 7060
#define IDI_ICON_TREE_NORMAL            7070
#define IDI_ICON_TREE_NONALERT          7080
#define IDI_ICON_TREE                   7090
#define IDI_ICON_TREE_UNIT              7100
#define IDI_ICON_TREE_ALERT             7110
#define IDI_ICON_TREE_ALERTUNIT         7120
#define IDC_SEARCHRNG                   7999
#define IDC_BACK_GROUND                 8000
#define IDC_TOP_RECT                    8001
#define IDC_BOTTOM_RECT                 8002
#define IDC_TOP_BTN                     8003
#define IDC_BOTTOM_BTN                  8004
#define IDC_NOTICE                      8005
#define IDC_ISSUES_FOR_ADMINISTRATION   8006
#define IDC_DEAL_STOP                   8007
#define IDC_INVESTMENT_ATTENTION        8008
#define IDC_PREFERENCE_STOCK            8009
#define IDC_OVER                        8010
#define IDC_TIDY_DEAL                   8011
#define IDC_INSINCERITY_NOTICE          8012
#define IDC_EQUITY_CAPITAL              8013
#define IDC_PRICE_RANGE                 8014
#define IDC_AGGREGATE_VALUE_OF_LISTED_STOCKS 8015
#define IDC_TRADING_VOLUME              8016
#define IDC_PAR_VALUE                   8017
#define IDC_EQUITY_CAPITAL_ABOVE        8018
#define IDC_EQUITY_CAPITAL_BELOW        8019
#define IDC_PRICE_RANGE_ABOVE           8020
#define IDC_PRICE_RANGE_BELOW           8021
#define IDC_AGGREGATE_VALUE_OF_LISTED_STOCKS_ABOVE 8022
#define IDC_AGGREGATE_VALUE_OF_LISTED_STOCKS_BELOW 8023
#define IDC_TRADING_VOLUME_ABOVE        8024
#define IDC_TRADING_VOLUME_BELOW        8025
#define IDC_PAR_VALUE_ABOVE             8026
#define IDC_PAR_VALUE_BELOW             8027
#define IDC_EQUITY_CAPITAL_ABOVE_TEXT   8028
#define IDC_EQUITY_CAPITAL_BELOW_TEXT   8029
#define IDC_PRICE_RANGE_ABOVE_TEXT      8030
#define IDC_PRICE_RANGE_BELOW_TEXT      8031
#define IDC_AGGREGATE_VALUE_OF_LISTED_STOCKS_ABOVE_TEXT 8032
#define IDC_AGGREGATE_VALUE_OF_LISTED_STOCKS_BELOW_TEXT 8033
#define IDC_TRADING_VOLUME_ABOVE_TEXT   8034
#define IDC_TRADING_VOLUME_BELOW_TEXT   8035
#define IDC_PAR_VALUE_ABOVE_TEXT        8036
#define IDC_PAR_VALUE_BELOW_TEXT        8037
#define IDC_STATIC_BACKGROUND           8038
#define IDC_TAB                         8039
#define IDC_NODROP_CURSOR               9201
#define IDC_NORMAL_CURSOR               9202
#define IDC_DRAG_CURSOR                 9203
#define IDC_WAIT_CURSOR                 9204
#define IDC_CURSOR_ANDOR                9205
#define IDC_CURSOR_SELECT               9206
#define IDC_HAND_CURSOR                 9207
#define IDD_STD_DIALOG                  10000
#define IDC_STATIC_SCREENTYPE           10100
#define IDD_LOGICHELP                   10121
#define IDD_TARGETEDIT                  10122
#define IDD_SEARCHTNG                   10123
#define IDD_SEARCHRNG                   10123
#define IDD_DIALOG2                     10124
#define IDD_DIALOG3                     10125
#define IDD_NO_ITEM                     10125
#define IDC_CURSOR1                     10126
#define IDD_EDITSUBJECT                 10128
#define IDI_ICON1                       10128
#define IDD_HELP                        10131
#define IDC_LIST1                       10300
#define IDC_EDIT1                       10301
#define IDC_TARGET_EDIT                 10302
#define IDC_BUTTON1                     10302
#define IDC_TARGET_STATIC_INDICATE      10303
#define IDC_CHANGE_SUBJECT              10304
#define IDC_BTN_RADIO_MARKET            10400
#define IDC_BTN_RADIO_PORTFOLIO         10401
#define IDC_BTN_RADIO_RECOMMENDATION    10402
#define IDC_BTN_EXCEPTSTOCK             10405
#define IDC_BTN_CHECK_ISSUESFORADMINISTRATION 10406
#define IDC_BTN_CHECK_DEALSTOP          10407
#define IDC_BTN_CHECK_TIDYDEAL          10408
#define IDC_BTN_CHECK_INSINCERITYNOTICE 10409
#define IDC_BTN_CHECK_ATTENTIONINVESTMENT 10410
#define IDC_BTN_CHECK_NOTICEATTENTIONINVESTMENT 10411
#define IDC_BTN_CHECK_PREFERENCESTOCK   10412
#define IDC_BTN_CHECK_DEPOSIT           10413
#define IDC_BTN_CHECK_DANGERINVESTMENT  10414
#define IDC_BTN_CHECK_WARNINGINVESTMENT 10415
#define IDC_BTN_CHECK_ETF               10416
#define IDC_BTN_CHECK_ETN               10417
#define IDC_BTN_MONTHSETTLEMENT         10450
#define IDC_BTN_RADIO_ALL               10451
#define IDC_BTN_RADIO_MARCH             10452
#define IDC_BTN_RADIO_JUNE              10453
#define IDC_BTN_RADIO_SEPTEMBER         10454
#define IDC_BTN_RADIO_DECEMBER          10455
#define IDC_BTN_RADIO_ESTIVAL           10456
#define IDC_COMBO_MONTHS                10457
#define IDC_TREE_MARKET                 10458
#define IDC_TREE_PORTFOLIO              10459
#define IDC_TREE_RECOMMENDATION         10460
#define IDC_STATIC_GUIDE                10461
#define WM_GRID_REDRAW                  10500
#define IDC_INVEST_ATTENTION            10600
#define IDC_INVEST_WARNING              10601
#define IDC_INVEST_RISK                 10602
#define IDC_PRE_INVEST_RISK             10603
#define IDC_BTN_NEXT_CONDITION          10604
#define IDC_BTN_PRE_CONDITION           10605
#define IDC_BTN_DEFAULT_VALUE           10606
#define IDC_BTN_LANGUAGE                10607
#define IDC_STC_COMMON_LOGIC            10608
#define IDC_STC_ORDER_LOGIC             10609
#define IDC_STC_PORTFOLIO               10610
#define IDC_STC_MATCH_VAL               10611
#define IDC_TAB_CONDITION_ITEMEXCAVATION 10700
#define IDC_CHANGE_SUBJECT_INIT         10710
#define IDC_STMESSAGE                   12000
#define IDD_DLGREQUEST                  12001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        10135
#define _APS_NEXT_COMMAND_VALUE         10200
#define _APS_NEXT_CONTROL_VALUE         10303
#define _APS_NEXT_SYMED_VALUE           10400
#endif
#endif
