//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by IB611000.rc
//
#define TOOLGAP                         1
#define GAP_WIDTH_MIN                   2
#define GAP_WIDTH                       3
#define VERT_GAP                        3
#define HORI_GAP                        3
#define IDS_REGISTERINTER               4
#define REALBACK_INDEX                  5
#define GAP_WIDTH_L                     6
#define BOT_GAP                         6
#define TXTGAP_S                        10
#define HDRLINEHEIGHT                   12
#define LINEH                           14
#define GUIDE_HEIGHT                    18
#define LINEHEIGHT                      20
#define CONTROL_HEIGHT                  20
#define GRIDROWHEIGHT                   20
#define TOOL_HEIGHT                     25
#define GUIDCOLOR_INDEX                 34
#define GRIDHEADER_HEIGHT               45
#define BUTTON_WIDTH                    56
#define BACKCOLOR_INDEX                 64
#define TOOLCOLOR_INDEX                 66
#define PANELBACK_INDEX                 66
#define GRIDROWCOLOR1_INDEX             68
#define COLW                            68
#define GRIDHDRCOLOR_INDEX              74
#define GRIDLINECOLOR_INDEX             75
#define GRIDHDRTXTCOLOR_INDEX           76
#define GRIDROWCOLOR2_INDEX             77
#define GRIDFOCUSCOLOR_INDEX            78
#define ACCNAME_WIDTH                   85
#define LABELBORDER_INDEX               89
#define UPCOLOR_INDEX                   94
#define DOWNCOLOR_INDEX                 95
#define BUTTONTXTCOLOR_INDEX            97
#define IDS_GH_RCOD                     100
#define TIMER_CREATE                    100
#define IDS_GH_CODE                     101
#define TIMER_QUERY                     101
#define IDS_GH_NAME                     102
#define IDS_GH_CURR                     103
#define DANGA_TXTINDEX                  103
#define IDS_GH_DIFF                     104
#define DANGA_BGINDEX                   104
#define IDS_GH_RATE                     105
#define IDS_GH_VOL                      106
#define IDS_GH_ASK                      107
#define IDS_GH_BID                      108
#define IDS_GH_OPEN                     109
#define IDS_GH_HIGH                     110
#define IDS_GH_LOW                      111
#define IDS_GH_TPRC                     112
#define IDS_GH_TVOL                     113
#define IDS_GH_ASKSIZE                  114
#define IDS_GH_BIDSIZE                  115
#define IDS_GH_TASKSIZE                 116
#define IDS_GH_TBIDSIZE                 117
#define IDS_GH_UPLIMIT                  118
#define IDS_GH_LOLIMIT                  119
#define IDS_GH_AVOFS                    120
#define PASS_WIDTH                      120
#define IDS_GH_ANTIPRC                  121
#define IDS_GH_ANTIVOL                  122
#define IDS_GH_POSSNUM                  123
#define IDS_GH_POSSPRC                  124
#define IDS_GH_SIGN                     125
#define IDS_GH_52HIGH                   126
#define IDS_GH_52LOW                    127
#define IDS_GH_YHIGH                    128
#define IDS_GH_ASKRATE                  129
#define IDS_GH_BIDRATE                  130
#define GUIDTXTCOLOR_INDEX              130
#define TXTCOLOR_INDEX                  130
#define IDS_GH_CHESTRENGTH              131
#define PANELBORDER_INDEX               131
#define IDS_GH_ROTATION                 132
#define IDS_GH_PREVOL                   133
#define IDS_GH_FOREIGNER                134
#define IDS_GH_YLOW                     135
#define IDS_GH_POSSPROFIT               136
#define IDS_GH_POSSRATE                 137
#define IDS_GH_HOGARATE                 138
#define IDS_GH_OPENRATEW                139
#define IDS_GH_OPENRATEP                140
#define IDS_GH_HIGHRATEW                141
#define IDS_GH_HIGHRATEP                142
#define IDS_GH_LOWRATEW                 143
#define IDS_GH_LOWRATEP                 144
#define IDS_GH_PRECURR                  147
#define IDS_GH_FORERATE                 148
#define IDS_GH_CAPITAL                  156
#define IDS_GH_STOCKCOUNT               157
#define IDS_GH_PRETPRC                  158
#define IDS_GH_UPDNRANGE                159
#define IDS_GH_LIMITRANGE               160
#define LABELBACK_INDEX                 160
#define ACCOUNT_WIDTH                   160
#define IDS_GH_PRETRATE                 161
#define IDS_GH_REGLINE2                 162
#define MAESU_BACKINDEX                 162
#define IDS_GH_REGLINE1                 163
#define MAESU_LINEINDEX                 163
#define IDS_GH_PIVOT                    164
#define MAEDO_BACKINDEX                 164
#define IDS_GH_SUPLINE1                 165
#define MAEDO_LINEINDEX                 165
#define IDS_GH_SUPLINE2                 166
#define IDS_GH_MAX52                    167
#define IDS_GH_MIN52                    168
#define IDS_GH_MAXYEAR                  169
#define IDS_GH_MINYEAR                  170
#define MAESU_BOXBGINDEX2               170
#define IDS_GH_MAXVOL52                 171
#define MAEDO_BOXBGINDEX2               171
#define IDS_GH_MINVOL52                 172
#define IDS_GH_MAXVOLYEAR               173
#define IDS_GH_MINVOLYEAR               174
#define MAESU_BOXBGINDEX1               174
#define IDS_GH_MAXDATE52                175
#define MAEDO_BOXBGINDEX1               175
#define IDS_GH_MINDATE52                176
#define IDS_GH_MAXDATEYEAR              177
#define IDS_GH_MINDATEYEAR              178
#define IDS_GH_MAXVOLDATE52             179
#define IDS_GH_MINVOLDATE52             180
#define IDS_GH_MAXVOLDATEYEAR           181
#define BODYCOLOR_INDEX                 181
#define IDS_GH_MINVOLDATEYEAR           182
#define IDS_GH_MAXDIFF52                183
#define IDS_GH_MINDIFF52                184
#define IDS_GH_MAXDIFFYEAR              185
#define IDS_GH_MINDIFFYEAR              186
#define IDS_GH_MAXRATE52                187
#define IDS_GH_MINRATE52                188
#define IDS_GH_MAXRATEYEAR              189
#define IDS_GH_MINRATEYEAR              190
#define IDS_GH_CONTUPLIMIT              191
#define IDS_GH_CONTUP                   192
#define IDS_GH_CONTDNLIMIT              193
#define IDS_GH_CONTDN                   194
#define IDS_GH_ELWLEFTDATE              197
#define IDS_GH_ELWLASTDATE              198
#define IDS_GH_ELWCRATE                 199
#define IDS_GH_DATEBONG                 200
#define IDS_GH_EPSFULL                  201
#define IDS_GH_EPSHALF                  202
#define IDS_GH_PERFULL                  203
#define IDS_GH_PERHALF                  204
#define IDS_GH_PERHALF2                 205
#define IDS_GUIDE1                      601
#define IDS_GUIDE2                      602
#define IDS_GUIDE3                      603
#define IDS_GUIDE4                      604
#define IDS_GUIDE5                      605
#define IDS_GUIDE6                      606
#define IDS_GUIDE7                      607
#define IDS_GUIDE8                      608
#define IDS_GUIDE9                      609
#define IDS_ENOGROUP                    609
#define IDS_GH_OPEN_P                   610
#define IDS_GH_HIGH_P                   611
#define IDS_GH_LOW_P                    612
#define IDS_GH_P_OPEN                   613
#define IDS_GH_P_HIGH                   614
#define IDS_GH_P_LOW                    615
#define CONFIGWINDOW_W                  640
#define IDC_TEST                        2100
#define IDC_CONFIGGRID                  2200
#define IDC_ADDCASE                     2301
#define IDC_ACCN                        2302
#define IDC_PASSEDIT                    2303
#define IDC_AUTOBUTTON                  2304
#define IDC_QUERYBUTTON                 2310
#define IDC_ALLSETUPBUTTON              2311
#define IDC_ALLFREEBUTTON               2312
#define IDC_ITEMFREEBUTTON              2313
#define IDC_VIEWLOGBUTTON               2314
#define IDC_HELPBUTTON                  2315
#define IDC_HOGA                        2402
#define IDD_IBSETUP                     5000
#define IDC_INPUT                       5000
#define IDD_NEWGROUP                    5001
#define IDC_GROUPSELECT                 5002
#define IDD_GROUPEDIT                   5002
#define IDC_LIST1                       5003
#define IDC_ADD                         5004
#define IDC_DELETE                      5005
#define IDC_ALLADD                      5006
#define IDC_ALLDELETE                   5007
#define IDC_LINEADD                     5008
#define IDC_UP                          5009
#define IDC_DOWN                        5010
#define IDC_LIST2                       5011
#define IDC_NEWGROUP                    5012
#define IDC_GROUPEDIT                   5013
#define IDC_GROUPNAME                   5013
#define IDC_UP_BTN                      5017
#define IDC_DOWN_BTN                    5018
#define IDC_DEL_BTN                     5019
#define IDC_RENAME_BTN                  5020
#define IDCOK                           5021
#define IDCCANCEL                       5022
#define IDC_OK                          5022
#define IDC_FDTYPE                      5023
#define IDC_GUBN                        5024
#define IDC_IVGRADE                     5025
#define IDC_RT06CHECK                   5026
#define IDC_RATECHECK                   5027
#define IDC_SETRT06                     5028
#define IDC_SETRATE                     5029
#define IDC_SEARCH                      5030
#define IDC_LIST4                       5032
#define IDC_ERRORMSG                    5033


#define MAP_WIDTH						1120
#define MAP_HEIGHT						514
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        5003
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         5034
#define _APS_NEXT_SYMED_VALUE           5000
#endif
#endif
