//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HWStrategyConfigureWizard.rc
//
#define IDB_BITMAP1                     1000
#define IDB_BITMAP_ANALDIS              1001
#define IDB_BITMAP_ANALNOR              1002
#define IDB_BITMAP_ANALSEL              1003
#define IDB_BITMAP_ANDDIS               1004
#define IDB_BITMAP_ANDNOR               1005
#define IDB_BITMAP_ANDSEL               1006
#define IDB_BITMAP_CANCELDIS            1007
#define IDB_BITMAP_CANCELNOR            1008
#define IDB_BITMAP_CANCELSEL            1009
#define IDB_BITMAP_DELDIS               1010
#define IDC_STCONFIGURE                 1010
#define IDB_BITMAP_DELNOR               1011
#define IDC_BUTTON1                     1011
#define IDC_BTN_FINDST                  1011
#define IDC_BTN_                        1011
#define IDC_BTN_SYSTEMTRADING           1011
#define IDB_BITMAP_DELSEL               1012
#define IDB_BITMAP_DOWNDIS              1013
#define IDC_BTN_STCONFIGDLG             1013
#define IDB_BITMAP_DOWNNOR              1014
#define IDC_BTN_STRUN                   1014
#define IDB_BITMAP_DOWNSEL              1015
#define IDC_EDIT1                       1015
#define IDC_EDIT_FINDST                 1015
#define IDC_STNAME                      1015
#define IDB_BITMAP_EDITDIS              1016
#define IDC_BUTTON2                     1016
#define IDC_BTN_NEXTST                  1016
#define IDB_BITMAP_EDITNOR              1017
#define IDC_BTN_STCLOSE                 1017
#define IDB_BITMAP_EDITSEL              1018
#define IDC_STATIC_NAME                 1018
#define IDB_BITMAP_ENVDIS               1019
#define IDC_VARLIST                     1019
#define IDB_BITMAP_ENVNOR               1020
#define IDC_BT_CLR_BULL                 1020
#define IDB_BITMAP_ENVSEL               1021
#define IDC_BT_CLR_BEAR                 1021
#define IDB_BITMAP_INITDIS              1022
#define IDB_BITMAP_INITNOR              1023
#define IDB_BITMAP_INITSEL              1024
#define IDB_BITMAP_NEXTDIS              1025
#define IDB_BITMAP_NEXTNOR              1026
#define IDB_BITMAP_NEXTSEL              1027
#define IDB_BITMAP_NOTDIS               1028
#define IDB_BITMAP_NOTNOR               1029
#define IDB_BITMAP_NOTSEL               1030
#define IDB_BITMAP_NPARDIS              1031
#define IDB_BITMAP_NPARNOR              1032
#define IDB_BITMAP_NPARSEL              1033
#define IDB_BITMAP_OKDIS                1034
#define IDB_BITMAP_OKNOR                1035
#define IDB_BITMAP_OKSEL                1036
#define IDB_BITMAP_ORDIS                1037
#define IDB_BITMAP_ORNOR                1038
#define IDB_BITMAP_ORSEL                1039
#define IDB_BITMAP_PARDIS               1040
#define IDB_BITMAP_PARNOR               1041
#define IDB_BITMAP_PARSEL               1042
#define IDB_BITMAP_SAVEDIS              1043
#define IDB_BITMAP_SAVENOR              1044
#define IDB_BITMAP_SAVESEL              1045
#define IDB_BITMAP_STEDITDIS            1046
#define IDB_BITMAP_STEDITNOR            1047
#define IDB_BITMAP_STEDITSEL            1048
#define IDB_BITMAP_TRUEDIS              1049
#define IDB_BITMAP_TRUENOR              1050
#define IDB_BITMAP_TRUESEL              1051
#define IDB_BITMAP_UPDIS                1052
#define IDB_BITMAP_UPNOR                1053
#define IDB_BITMAP_UPSEL                1054
#define IDB_SIGNAL                      1055
#define IDC_DRAGGING                    1056
#define IDD_OUTLOOKBARDLG               1057
#define IDC_NODRAGGING                  1058
#define IDC_DRAGGING2                   1059
#define IDC_HANDCUR                     1061
#define IDB_IL_STICON                   1062
#define IDD_DLGSYSVAROPTION             1063
#define IDC_EDIT_STNAME                 21002
#define IDC_BT_CLR_BUY                  21008
#define IDC_BT_CLR_EXITSHORT            21016
#define IDC_CB_BUY                      21017
#define IDC_CB_EXITLONG                 21018
#define IDC_CB_SELL                     21019
#define IDC_CB_EXITSHORT                21020
#define IDC_BT_CLR_EXITLONG             21021
#define IDC_BT_CLR_SELL                 21022
#define IDC_CHK_SHOWNAME                21029
#define IDC_CHK_SHOWQTY                 21030
#define IDC_TAB1                        27000
#define IDD_DLG_CONFIGURE               27000
#define IDC_EDIT_TICK                   27001
#define IDD_DLG_STLIST                  27001
#define IDC_EDIT_NAME                   27001
#define IDD_DLG_TAB_SINGLE              27002
#define IDD_DLG_TAB_COMPOUND            27003
#define IDC_BTN_INIT                    27003
#define IDD_DLG_TRADEOPTION             27004
#define IDC_BTN_UP                      27006
#define IDC_BTN_DOWN                    27007
#define IDC_BTN_AND                     27009
#define IDC_BTN_OR                      27010
#define IDC_BTN_NEXT                    27011
#define IDC_BTN_PARENTHESIS             27012
#define IDC_BTN_X                       27013
#define IDC_BTN_TEST                    27014
#define IDC_BTN_STDELETE                27014
#define IDC_BTN_OPTION                  27015
#define IDC_GRID                        27016
#define IDD_DLG_TIMESELECTOR            27017
#define IDC_GRIDALL                     27017
#define IDD_DLG_SIGNAL                  27019
#define IDC_BTN_EDIT                    27020
#define IDC_LIST_COMPOUND               27021
#define IDC_RADIO_EQUITYBUY             27022
#define IDC_RADIO_EQUITYEXITLONG        27023
#define IDD_DLG_SAVE                    27024
#define IDC_RADIO_FUTUREBUY             27026
#define IDC_RADIO_FUTURESELL            27027
#define IDC_RADIO_FUTUREALL             27028
#define IDC_RADIO_COMPLETECANDLE        27029
#define IDC_COMBO_ORDERPRICE            27030
#define IDC_COMBO_EXITPRICE             27031
#define IDC_COMBO_FORCEDEXITPRICE       27032
#define IDC_LIST_STFILE                 27034
#define IDC_STATIC_FORMULA              27049
#define IDC_BTN_NOT                     27050
#define IDC_RADIO_DAY                   27051
#define IDC_RADIO_MINUTE                27054
#define IDC_EDIT_MINUTE                 27056
#define IDC_CTRLLOGIC                   27061
#define IDC_EDIT_FOMULA                 27061
#define IDC_BTN_TRUE                    27062
#define IDC_EDIT_ST_TITLE               27063
#define IDC_BT_SAVE                     27064
#define IDC_BTN_DELETE                  27067
#define IDC_ST_STEP2                    27068
#define IDC_RADIO_EVENTSIGNAL           27069
#define IDC_ST_STEP1                    27069
#define IDC_CHECK_ENABLECONTINUTY       27072
#define IDC_EDIT_CNTMAXIMUN             27073
#define IDC_CHECK_MINIMUMCHANGE         27074
#define IDC_EDIT_MINEQUITY              27075
#define IDC_EDIT_MINFUTURE              27076
#define IDC_CHECK_PROFITTARGETRATE      27077
#define IDC_CHECK_PROFITREVERSERATE     27078
#define IDC_CHECK_DAMAELIMITATIONRATE   27079
#define IDC_EDIT_PROFITTARGETRATE       27080
#define IDC_EDIT_PROFITREVERSERATE      27081
#define IDC_EDIT_DAMAELIMITATIONRATE    27082
#define IDC_SPIN_PROFITTARGETRATE       27083
#define IDC_SPIN_PROFITREVERSERATE      27084
#define IDC_SPIN_DAMAELIMITATIONRATE    27085
#define IDC_CHECK_SELLATUPPERPRICE      27086
#define IDC_CHECK_SELLATLOWERPRICE      27087
#define IDC_CHECK_EXITATTODAY           27088
#define IDC_DATETIMEPICKEREXIT          27090
#define IDC_RADIO_TICK                  27092
#define IDC_LIST_STVARIABLES            29007
#define IDC_BUTTON_SAVECONFIG           29008

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1064
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1022
#define _APS_NEXT_SYMED_VALUE           1058
#endif
#endif
