//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by awDlg.rc
//
#define IDC_INSERT                      3
#define IDC_NOEDIT                      3
#define IDC_DEL                         3
#define IDC_DELETE                      4
#define IDC_DELETEALL                   4
#define IDC_MODIFY                      4
#define IDC_REG                         4
#define IDC_DELETE_ONE                  5
#define IDC_ADD                         5
#define IDC_SHIFTL                      5
#define IDC_IDELETE                     6
#define IDC_SHIFTR                      6
#define IDC_UP_BTN                      6
#define IDC_DOWN_BTN                    7
#define IDC_IDUP                        7
#define IDC_IDDOWN                      8
#define IDD_PROPPAGE_BASEINFO           106
#define IDR_NO_DROPMOVE                 300
#define IDR_DROPMOVE                    301
#define IDC_EDITGAP                     1011
#define IDD_UP                          4001
#define IDB_TREE                        4002
#define IDC_STATUS                      4003
#define IDD_BATCH                       4003
#define IDC_SOURCEN                     4004
#define IDC_OBJECTN                     4005
#define IDC_RSCLIST                     4006
#define IDC_EXPORT                      4007
#define IDC_PROGRESS                    4008
#define IDC_NICKN                       4009
#define IDC_ERR                         4012
#define IDC_BATCH                       4013
#define IDC_TREE                        4014
#define IDD_STATIC                      9000
#define IDD_GPROP                       9000
#define IDC_WINT                        9001
#define IDD_GOPTION                     9001
#define IDC_FONT                        9002
#define IDD_GSCRIPT                     9002
#define IDC_MAPH                        9003
#define IDC_FONTS                       9004
#define IDC_MAPW                        9005
#define IDD_RESOURCE                    9005
#define IDC_VERD                        9006
#define IDD_SYS                         9006
#define IDC_FONTN                       9007
#define IDC_MAPN                        9008
#define IDD_LABEL                       9008
#define IDC_FH                          9009
#define IDC_REGPROC                     9009
#define IDC_TOPATH                      9010
#define IDD_BOX                         9010
#define IDC_FW                          9011
#define IDC_NICK                        9012
#define IDD_EDIT                        9012
#define IDC_TRCD                        9013
#define IDC_AUXTRCD                     9014
#define IDD_OUTPUT                      9014
#define IDC_TRXH                        9015
#define IDC_AUXM                        9016
#define IDD_COMBO                       9016
#define IDC_HELPN                       9017
#define IDC_MAPM                        9018
#define IDD_RADIO                       9018
#define IDC_WAVEN                       9019
#define IDC_WAVEB                       9020
#define IDD_BUTTON                      9020
#define IDC_REPEAT                      9021
#define IDC_TIMEOUT                     9022
#define IDD_PANEL                       9022
#define IDC_IDLE                        9023
#define IDC_GROUP1                      9024
#define IDD_GROUP                       9024
#define IDC_BG                          9025
#define IDC_BG1                         9026
#define IDD_BRUSH                       9026
#define IDC_BG2                         9027
#define IDD_IMAGE                       9027
#define IDC_BG3                         9028
#define IDC_GROUP2                      9029
#define IDD_REG                         9029
#define IDC_OPT01                       9030
#define IDD_LINE                        9031
#define IDC_OPT02                       9031
#define IDD_OBJECT                      9032
#define IDC_OPT03                       9032
#define IDD_GRAPH                       9033
#define IDC_OPT04                       9033
#define IDC_OPT05                       9034
#define IDD_MEMO                        9035
#define IDC_OPT06                       9035
#define IDC_OPT07                       9036
#define IDD_TAB                         9037
#define IDC_OPT08                       9037
#define IDC_OPT8                        9037
#define IDC_OPT09                       9038
#define IDD_UTAB                        9039
#define IDC_OPT10                       9039
#define IDC_OPT11                       9040
#define IDC_OPT12                       9041
#define IDD_TABLE                       9041
#define IDC_OPT13                       9042
#define IDD_SCROLL                      9043
#define IDC_OPT14                       9043
#define IDC_OPT15                       9044
#define IDD_GRID                        9045
#define IDC_OPT16                       9045
#define IDC_OPT17                       9046
#define IDC_OPT18                       9047
#define IDD_TABITEM                     9048
#define IDC_OPT19                       9048
#define IDD_UTABITEM                    9049
#define IDC_OPT20                       9049
#define IDD_ORDER                       9050
#define IDC_OPT21                       9050
#define IDD_COMBOITEM                   9051
#define IDC_OPT22                       9051
#define IDD_CELL                        9052
#define IDC_OPT23                       9052
#define IDC_OPT24                       9053
#define IDC_OPT25                       9054
#define IDD_TABLECELL                   9054
#define IDC_OPT26                       9055
#define IDC_OPT27                       9056
#define IDC_OPT28                       9057
#define IDC_OPT29                       9058
#define IDC_OPT30                       9059
#define IDC_OPT31                       9060
#define IDC_OPT32                       9061
#define IDC_OPT33                       9062
#define IDC_OPT34                       9063
#define IDC_OPT35                       9064
#define IDC_OPT36                       9065
#define IDC_OPT37                       9066
#define IDC_OPT38                       9067
#define IDC_OPT39                       9068
#define IDC_OPT40                       9069
#define IDC_OPT41                       9070
#define IDC_OPT42                       9071
#define IDC_OPT43                       9072
#define IDC_DEV1                        9073
#define IDI_NORMAL                      9073
#define IDC_DEV2                        9074
#define IDC_EVENT                       9074
#define IDI_SPLIT01                     9074
#define IDC_DEV3                        9075
#define IDC_SCRIPT                      9075
#define IDI_SPLIT02                     9075
#define IDC_DEV4                        9076
#define IDC_SYMBOL                      9076
#define IDI_SPLIT03                     9076
#define IDC_DEV5                        9077
#define IDI_SPLIT04                     9077
#define IDC_DEV6                        9078
#define IDI_SPLIT05                     9078
#define IDC_DEV7                        9079
#define IDC_APPLY                       9079
#define IDI_SPLIT06                     9079
#define IDC_DEV8                        9080
#define IDI_SPLIT07                     9080
#define IDI_SPLIT08                     9081
#define IDC_LEFT                        9082
#define IDI_SPLIT09                     9082
#define IDC_TOP                         9083
#define IDI_SPLIT10                     9083
#define IDC_RIGHT                       9084
#define IDI_SPLIT11                     9084
#define IDC_BOTTOM                      9085
#define IDI_SPLIT12                     9085
#define IDI_LISTB                       9086
#define IDC_TYPE                        9087
#define IDD_ADDR                        9087
#define IDC_COMBO                       9088
#define IDC_KEYMAP                      9088
#define IDD_PATH                        9088
#define IDC_ALIGN                       9089
#define IDC_KIND                        9089
#define IDD_ATTR                        9089
#define IDD_FORMAT                      9090
#define IDD_CORGB                       9092
#define IDD_CEDIT                       9093
#define IDC_PRGB                        9094
#define IDC_TRGB                        9095
#define IDD_LIST1                       9095
#define IDC_ERGB                        9095
#define IDC_PRGBE                       9096
#define IDD_LIST2                       9096
#define IDC_TRGBE                       9097
#define IDD_LIST3                       9097
#define IDC_ERGBE                       9097
#define IDC_PRGBS                       9098
#define IDD_LITEM                       9098
#define IDC_TRGBS                       9099
#define IDD_TREE                        9099
#define IDC_ERGBS                       9099
#define IDC_HINT                        9100
#define IDC_VISIBLE                     9101
#define IDD_DTAB                        9101
#define IDC_SHOWHINT                    9102
#define IDC_SORT                        9102
#define IDC_STR                         9103
#define IDC_INNER                       9103
#define IDC_POS                         9103
#define IDC_HEADS                       9103
#define IDC_FLEX                        9103
#define IDC_LENE                        9104
#define IDC_BRGB                        9104
#define IDC_INIT                        9104
#define IDC_LENS                        9105
#define IDC_BRGBE                       9105
#define IDC_NOHEAD                      9105
#define IDD_MULTI                       9105
#define IDC_MODE                        9106
#define IDC_OUTER                       9106
#define IDC_BRGBS                       9106
#define IDC_WRAP                        9106
#define IDC_CURSOR                      9107
#define IDC_INNER2                      9107
#define IDC_3DINNER                     9107
#define IDC_DROP                        9107
#define IDI_USEROB                      9107
#define IDC_CUT                         9107
#define IDC_FOCUS                       9108
#define IDC_OUTER2                      9108
#define IDC_3DOUTER                     9108
#define IDC_VARIANT                     9108
#define IDC_TRANSPARENT                 9109
#define IDC_XVLINE                      9109
#define IDC_HTEXT                       9110
#define IDC_TRANSPARENT2                9110
#define IDD_SHEET                       9110
#define IDC_ORGB                        9110
#define IDC_DOMINOC                     9111
#define IDC_ORGBE                       9111
#define IDD_BROWSER                     9111
#define IDC_DOMINO                      9112
#define IDC_ORGBS                       9112
#define IDC_3DC                         9113
#define IDC_PAGE                        9113
#define IDC_HSCROLL                     9114
#define IDC_DOMINOC2                    9114
#define IDC_TABLE                       9114
#define IDC_ENABLE                      9115
#define IDC_THUMB                       9115
#define IDD_USERM                       9115
#define IDC_ATTR                        9116
#define IDC_FLOAT                       9117
#define IDC_COUNT                       9118
#define IDC_CHECKSTR                    9118
#define IDC_DELTA                       9118
#define IDD_GRIDCOLUMN                  9118
#define IDC_FLOAT3                      9119
#define IDC_DATA                        9119
#define IDC_TITLE                       9120
#define IDC_VALID                       9120
#define IDC_CHECK                       9121
#define IDC_CELLH                       9121
#define IDC_GROUP                       9122
#define IDC_RCOUNT                      9122
#define IDD_LINEDLG                     9122
#define IDC_AUX                         9123
#define IDC_FIXED                       9123
#define IDD_PUBLIC                      9123
#define IDC_FILE                        9124
#define IDD_CONTROL                     9124
#define IDC_BTYPE                       9125
#define IDC_FILEN                       9126
#define IDC_REF                         9126
#define IDD_INPUTKEYDLG                 9126
#define IDC_3D                          9127
#define IDD_LOGIN                       9127
#define IDC_REFC                        9128
#define IDC_RROW                        9128
#define IDD_LOGINSETDLG                 9128
#define IDC_SHOWTOOL                    9129
#define IDC_XHLINE                      9129
#define IDC_INDEX                       9130
#define IDC_OBJECT                      9131
#define IDB_LOGINBMP                    9131
#define IDC_BORDER                      9132
#define IDC_TABH                        9132
#define IDB_CANCELBTN_ON                9132
#define IDC_HEAD                        9133
#define IDB_CANCELBTN_OFF               9133
#define IDC_BORDERS                     9134
#define IDB_CONNECTBTN_ON               9134
#define IDB_CONNECTBTN_OFF              9135
#define IDB_SETUPBTN_ON                 9136
#define IDC_CHECK01                     9137
#define IDB_SETUPBTN_OFF                9137
#define IDC_CHECK02                     9138
#define IDC_OLDLIST                     9138
#define IDB_SETUPBTN_EN                 9138
#define IDC_CHECK03                     9139
#define IDC_NEWLIST                     9139
#define IDB_CLOSEBTN                    9139
#define IDC_CHECK04                     9140
#define IDC_COPYALL                     9140
#define IDB_CLOSEBTN_DN                 9140
#define IDC_CHECK05                     9141
#define IDC_COPY                        9141
#define IDB_CLOSEBTN_EN                 9141
#define IDC_CHECK06                     9142
#define IDC_DISPLAY                     9142
#define IDB_CONNECTBTN                  9142
#define IDC_CHECK07                     9143
#define IDB_CONNECTBTN_DN               9143
#define IDC_CHECK08                     9144
#define IDC_IDISPLAY                    9144
#define IDB_CONNECTBTN_EN               9144
#define IDC_CHECK09                     9145
#define IDC_IDATA                       9145
#define IDB_SETUPBTN                    9145
#define IDC_CHECK10                     9146
#define IDC_MULTI                       9146
#define IDB_SETUPBTN_DN                 9146
#define IDC_CHECK11                     9147
#define IDC_CHECK12                     9148
#define IDC_CHECK13                     9149
#define IDC_NUMBER                      9149
#define IDC_CHECK14                     9150
#define IDC_CHECK15                     9151
#define IDC_ALIGNH                      9151
#define IDC_CHECK16                     9152
#define IDC_ALIGND                      9152
#define IDC_HPRGB                       9153
#define IDC_HTRGB                       9154
#define IDC_HPRGBE                      9155
#define IDC_HPRGBS                      9156
#define IDC_HTRGBE                      9157
#define IDC_HTRGBS                      9158
#define IDC_BMPE                        9159
#define IDC_COLORE                      9160
#define IDC_CHOOSE                      9161
#define IDC_HOVER                       9161
#define IDC_CDATA                       9162
#define IDC_ADDR                        9163
#define IDC_PATH                        9164
#define IDC_FORMAT                      9170
#define IDC_DEFINED                     9171
#define IDC_UP                          9172
#define IDC_DOWN                        9173
#define IDC_DEFAULT                     9174
#define IDC_UPE                         9175
#define IDC_DOWNE                       9176
#define IDC_DEFAULTE                    9177
#define IDC_UPS                         9178
#define IDC_DOWNS                       9179
#define IDC_IE1                         9179
#define IDC_DEFAULTS                    9180
#define IDC_IE2                         9180
#define IDC_IE3                         9181
#define IDC_CORGB                       9182
#define IDC_EDIT                        9183
#define IDC_HEADER                      9184
#define IDC_SENTENCE                    9185
#define IDC_ITEM                        9187
#define IDC_SAVEPC                      9189
#define IDC_SAVESERVER                  9190
#define IDC_ENTRY                       9192
#define IDC_ACTION                      9193
#define IDC_CHECKED                     9194
#define IDC_STRING                      9195
#define IDC_LINES                       9195
#define IDC_CAPTION                     9195
#define IDC_LBOX                        9196
#define IDC_SEND                        9196
#define IDC_MAP                         9196
#define IDC_DRAG                        9197
#define IDC_GUIDE                       9197
#define IDC_DSYMBOL                     9198
#define IDC_NOR                         9198
#define IDC_PREV                        9198
#define IDC_NEXT                        9199
#define IDC_USER                        9203
#define IDC_SHOWHELP                    9204
#define IDC_TAB                         9204
#define IDC_FONTSZ                      9205
#define IDC_SPIN                        9206
#define IDC_SUM                         9206
#define IDC_CODE                        9207
#define IDC_TABPASS                     9208
#define IDC_BACK                        9209
#define IDC_BROWSER                     9210
#define IDC_XDELETE                     9211
#define IDC_BROWSER2                    9211
#define IDC_PROC                        9215
#define IDC_FPRGB                       9216
#define IDC_ADDBTN                      9216
#define IDC_FPRGBE                      9217
#define IDC_DELBTN                      9217
#define IDC_FPRGBS                      9218
#define IDC_MULTILINE                   9218
#define IDC_FTRGB                       9219
#define IDC_OFFLINECHK                  9219
#define IDC_INSERTBTN                   9219
#define IDC_FTRGBE                      9220
#define IDC_OLDTREE                     9220
#define IDC_FTRGBS                      9221
#define IDC_NEWTREE                     9221
#define IDC_EDITLINE                    9222
#define IDC_INBTN                       9225
#define IDC_OUTBTN                      9226
#define IDC_HELPSTATIC                  9227
#define IDC_PROPERTIES                  9231
#define IDC_NAMELIST                    9232
#define IDC_DESC                        9233
#define IDC_INPUT                       9234
#define IDC_SETFONTBTN                  9235
#define IDC_FONTNAME                    9236
#define IDC_FONTPNT                     9237
#define IDC_MAPPATH                     9238
#define IDC_NONEBTN                     9240
#define IDC_USERIDEDIT                  9242
#define IDC_PASSEDIT                    9243
#define IDC_SETBTN                      9245
#define IDC_PROJECTNAME                 9246
#define IDC_IPADDR                      9247
#define IDC_LOCALRDO                    9250
#define IDC_INETRDO                     9251
#define IDC_UPRGB                       9251
#define IDC_PROXYRDO                    9252
#define IDC_DNRGB                       9253
#define IDC_DNRGBSPIN                   9254
#define IDC_UPRGBSPIN                   9255
#define IDC_CLRTAB                      9257
#define IDC_CLRTAB2                     9258
#define IDC_CLRTAB3                     9259
#define IDC_FLOAT_CHK                   9259
#define IDC_COLORLIST_CBO               9260
#define IDC_SETCOLOR_CBO                9261
#define IDC_DEFAULT_BUTTON              9264
#define IDC_DISPLAYDATA_RDO             9266
#define IDC_DISPLAYSYMBOL_RDO           9267
#define IDC_DSPLAYNONE_RDO              9268
#define IDD_PREVIEW                     13000
#define IDD_SETTING                     13001
#define IDD_MGRIDCOLUMN                 13002
#define IDC_TABCTRL                     16000
#define IDD_COLOR                       16000
#define IDD_PREVIEW_RUN                 16001
#define IDD_EDITORDER                   16002
#define IDD_PROPPAGE_DEFAULT            16003
#define IDD_PROPPAGE_SCRIPT             16004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        9148
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         9267
#define _APS_NEXT_SYMED_VALUE           9000
#endif
#endif
