#pragma once

#define DF_CONFIG_FILE  "cx_grid.ini"

#define	IGAT_COMMA	0x00000001
#define	IGAT_CONTRAST	0x00000002
#define	IGAT_CONDITION	0x00000004
#define	IGAT_CONDITIONx	0x00000008
#define	IGAT_ZEROSUP	0x00000010
#define	IGAT_ZEROSUPx	0x00000020
#define	IGAT_EDITFORMAT	0x00000040

#define	IGAT_LEFT	0x10000000
#define	IGAT_CENTER	0x20000000
#define	IGAT_RIGHT	0x40000000

//
//	GVITEM.format
//
#define GVFM_HEADER		(DT_CENTER|DT_VCENTER|DT_SINGLELINE|DT_NOPREFIX|DT_WORDBREAK)
#define	GVFM_RIGHT		(DT_RIGHT |DT_VCENTER|DT_SINGLELINE|DT_NOPREFIX)
#define	GVFM_LEFT		(DT_LEFT  |DT_VCENTER|DT_SINGLELINE|DT_NOPREFIX)
#define	GVFM_CENTER		(DT_CENTER|DT_VCENTER|DT_SINGLELINE|DT_NOPREFIX)
#define	GVFM_MULTI		(DT_CENTER|DT_NOPREFIX|DT_EXTERNALLEADING|DT_WORDBREAK)

static struct	_gridHdr {
	CString m_sHeadCaption;
	char	symbol[8];	// nonfixed symbol
	DWORD		m_dAttr;
	CString editFormat;
} gridHdr[] =
{
	{"시간",							"11034",	IGAT_EDITFORMAT | IGAT_CENTER,	_T("99:99:99")},
	{"체결가",						"2023",		IGAT_CONDITION | IGAT_COMMA | IGAT_RIGHT,	""},
	{"전일비",						"11024",	 IGAT_COMMA | IGAT_CONTRAST | IGAT_RIGHT,	""},
	{"체결량",						"11032",	 IGAT_CONDITION | IGAT_COMMA | IGAT_RIGHT,	""},
	{"거래량",						"2027",		 IGAT_COMMA | IGAT_RIGHT,	""},
};