//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// TestDlg.rc에서 사용되고 있습니다.
//
#define IDS_STRING102                   4
#define IDS_GH_RCOD                     5
#define IDS_GH_CODE                     6
#define IDS_GH_NAME                     7
#define IDS_GH_CURR                     8
#define IDS_GH_DIFF                     9
#define IDS_GH_RATE                     10
#define IDS_GH_VOL                      11
#define IDS_GH_ASK                      12
#define IDS_GH_BID                      13
#define IDS_GH_TASKSIZE                 14
#define IDS_GH_TBIDSIZE                 15
#define IDM_ABOUTBOX                    0x0010
#define IDS_GH_OPEN                     16
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TESTDLG_DIALOG              102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_DLG_CHART                   130
#define IDB_BITMAP1                     132
#define IDI_WEBVIEW2_BACKGROUND         132
#define IDD_DIALOG1                     133
#define IDD_DLG_IMG                     133
#define IDD_DLG_PLAYER                  135
#define IDD_DLG_SLIDER                  138
#define IDD_DLG_THREAD                  140
#define IDD_DLGSSIB                     142
#define IDD_DLG_EDGE                    144
#define IDD_DLG_LOAD                    146
#define IDD_DLG_IE                      148
#define IDD_DLG_WMIC                    150
#define IDD_DIALOG2                     152
#define IDD_DLG_LOGIN                   152
#define IDD_DLG_CHOLBOOK                154
#define IDD_DLG_SOCK                    157
#define IDD_DLG_CALENDAR                159
#define IDD_DLGNOTE                     161
#define IDD_DLG_SHARED                  163
#define IDB_TOOL_IMGLIST                168
#define IDD_DIALOG4                     169
#define IDD_DLG_STD                     171
#define IDC_BRN_BIT                     1000
#define IDC_BRN_BIT2                    1001
#define IDC_BTN_mfc140                  1002
#define IDC_EDIT_DATA                   1003
#define IDC_BTN_FORMAT                  1004
#define IDC_BUTTON1                     1004
#define IDC_BTN_MAP                     1005
#define IDC_BTN_MUITABLE                1005
#define IDC_BUTTON2                     1005
#define IDC_BTN_RACE                    1006
#define IDC_BTN_STATIC                  1006
#define IDC_BTN_CONSUMER                1007
#define IDC_BTN_OVER                    1007
#define IDC_BTN_CONSUMER2               1008
#define IDC_BTN_TSTATIC                 1008
#define IDC_BTN_FUTURE                  1009
#define IDC_BTN_BBSORT                  1009
#define IDC_BTN_FUTURE2                 1010
#define IDC_BTN_INHERI                  1010
#define IDC_BTN_ASYNC                   1011
#define IDC_BTN_RLEF                    1012
#define IDC_BTN_PAIR                    1013
#define IDC_BTN_TUPLE                   1014
#define IDC_BTN_LAMDA                   1015
#define IDC_BTN_LAMDA_FIND              1016
#define IDC_BTN_MANGLING                1016
#define IDC_BTN_PAIR2                   1017
#define IDC_BTN_FILE                    1017
#define IDC_BTN_OS                      1017
#define IDC_BTN_STFUNC                  1017
#define IDC_BTN_OSVERSION               1018
#define IDC_BTN_TEMPLETE                1018
#define IDC_BTN_HASHKEY                 1019
#define IDC_BTN_WIN                     1020
#define IDC_BTN_ICON                    1021
#define IDC_BTN_PRSFIND                 1022
#define IDC_BTN_STDCOPY                 1023
#define IDC_BTN_HEX                     1024
#define IDC_BTN_CODE                    1025
#define IDC_BTN_IE                      1026
#define IDC_BTN_INT2STR                 1027
#define IDC_BTN_REMOVEICON              1028
#define IDC_BTN_CEF                     1029
#define IDC_BTN_SERIAL                  1030
#define IDC_BTN_SERIAL2                 1031
#define IDC_BTN_SERIAL3                 1032
#define IDC_BTN_HANGUL                  1033
#define IDC_BTN_LOADOCX                 1034
#define IDC_BTN_CHART                   1035
#define IDC_BTN_RECT                    1036
#define IDC_BTN_REGREAD                 1037
#define IDC_BTN_SHARED                  1038
#define IDC_BTN_TIME                    1039
#define IDC_BTN_IPC                     1040
#define IDC_STATIC_WND                  1041
#define IDC_BTN_TEST                    1042
#define IDC_BTN_FINDPS                  1043
#define IDC_BTN_TEST2                   1043
#define IDC_EDIT_SHARED                 1044
#define IDC_BTN_TEST3                   1044
#define IDC_BTN_SHARED_WRITE            1045
#define IDC_BTN_TEST4                   1045
#define IDC_BTN_SHARED_READ             1046
#define IDC_OCX1                        1046
#define IDC_BTN_PLAYSOUND               1047
#define IDC_SLIDER_RATE                 1047
#define IDC_BTN_KEYMAKE                 1048
#define IDC_EDIT_SLIDER                 1048
#define IDC_BTN_FILECHECK               1049
#define IDC_SLIDER1                     1049
#define IDC_EDIT_SLIDER2                1049
#define IDC_BTN_CALCWINDOWRECT          1050
#define IDC_EDIT_SLIDER3                1050
#define IDC_BTN_SCROLLDLG               1051
#define IDC_COMBO1                      1051
#define IDC_UNORDEREDMAP                1052
#define IDC_COMBO2                      1052
#define IDC_BTN_PLYER                   1053
#define IDC_BTN_SLIDER                  1054
#define IDC_BTN_INTFLOAT                1055
#define IDC_CB_TEST                     1056
#define IDC_BTN_INTFLOAT2               1057
#define IDC_BTN_TCP                     1058
#define IDC_BTN_REF                     1059
#define IDC_BTN_AFXEX                   1060
#define IDC_BTN_FRIEND                  1060
#define IDC_BTN_VECTOR                  1061
#define IDC_BTN_VECTOR2                 1062
#define IDC_BTN_IME                     1063
#define IDC_BTN_THREAD                  1064
#define IDC_BTN_THREAD2                 1065
#define IDC_CK_TRHEAD                   1065
#define IDC_BTN_THREAD3                 1066
#define IDC_BTN_THREAD4                 1067
#define IDC_BTN_CRITICAL                1068
#define IDC_BTN_CRITICAL2               1069
#define IDC_BTN_CRI1                    1070
#define IDC_BTN_CRI2                    1071
#define IDC_BTN_THREAD5                 1072
#define IDC_BTN_EDGEDLG                 1073
#define IDC_EDIT_PROCESS                1074
#define IDC_BTN_LOADLIB                 1074
#define IDC_BTN_WEBVIEW2                1075
#define IDC_BTN_WEBVIEW3                1076
#define IDC_BTN_UPDOWN                  1077
#define IDC_BTN_REMOVIF                 1078
#define IDC_BTN_TRANS                   1079
#define IDC_BTN_FIND                    1080
#define IDC_BTN_IEBROWSER               1081
#define IDC_BTN_IME2                    1082
#define IDC_EDIT_PROCESS2               1083
#define IDC_BTN_CMD                     1083
#define IDC_CHECK1                      1084
#define IDC_BTN_ENDIAN                  1084
#define IDC_CHECK2                      1085
#define IDC_BTN_CMDPACKAGE              1085
#define IDC_CHECK3                      1086
#define IDC_BTN_WMIC                    1086
#define IDC_EDIT_WMIC                   1086
#define IDC_CHECK4                      1087
#define IDC_BTN_REDIS                   1087
#define IDC_BTN_DLGWMIC                 1087
#define IDC_CHECK5                      1088
#define IDC_BTN_INTERFILE               1088
#define IDC_BTN_DLGWMIC2                1088
#define IDC_CHECK6                      1089
#define IDC_BTN_INTERFILE2              1089
#define IDC_CHECK7                      1090
#define IDC_BTN_URLENCODE1              1090
#define IDC_CHECK8                      1091
#define IDC_BTN_JUNG                    1091
#define IDC_BTN_LOGIN                   1091
#define IDC_CHECK9                      1092
#define IDC_BTN_SIGNR                   1092
#define IDC_BTN_THREAD6                 1092
#define IDC_CHECK10                     1093
#define IDC_BTN_CHECK                   1093
#define IDC_BTN_STDMAP                  1093
#define IDC_BTN_TESTSEND                1093
#define IDC_CHECK11                     1094
#define IDC_BTN_DOWM                    1094
#define IDC_BTN_CAL1                    1094
#define IDC_CHECK12                     1095
#define IDC_BTN_QSORT                   1095
#define IDC_BTN_CAL2                    1095
#define IDC_CHECK13                     1096
#define IDC_BTN_EDGESELF                1096
#define IDC_STATIC_CAL                  1096
#define IDC_CHECK14                     1097
#define IDC_BTN_INTSTR                  1097
#define IDC_BTN_CAL3                    1097
#define IDC_CHECK15                     1098
#define IDC_BTN_URLEN2                  1098
#define IDC_CHECK16                     1099
#define IDC_BTN_GETSECTION              1099
#define IDC_BTN_CMD2                    1100
#define IDC_EDIT_CMD                    1101
#define IDC_BTN_SOCK                    1102
#define IDC_BTN_SESSION                 1103
#define IDC_BTN_COMPRESS                1104
#define IDC_BTN_CALENDER                1105
#define IDC_BTN_CALENDER2               1106
#define IDC_BTN_EXCUTE                  1107
#define IDC_BTN_OSVER                   1108
#define IDC_BTN_ANY                     1109
#define IDC_BTN_POP                     1110
#define IDC_BTN_MAC                     1111
#define IDC_BTN_IPCONFIGALL             1112
#define IDC_BTN_FILELOAD                1113
#define IDC_BTN_ROUND                   1114
#define IDC_BTN_RE                      1115
#define IDC_BTN_CLEAR                   1116
#define IDC_BTN_ROUND2                  1117
#define IDC_BTN_MEMO                    1117
#define IDC_BTN_CMAP                    1117
#define IDC_BTN_FORTHREAD               1118
#define IDC_BTN_COMMARCO                1119
#define IDC_BTN_KEY                     1120
#define IDC_BTN_KEY2                    1121
#define IDC_BTN_LOCAL                   1122
#define IDC_BTN_BIT                     1123
#define IDC_BTN_MUTEXWRITE              1124
#define IDC_BTN_MUTEXWRITE2             1125
#define IDC_BTN_MUTEXWRITE3             1126
#define IDC_BTN_MUTEXWRITE4             1127
#define IDC_BTN_MUTEXWRITE5             1128
#define IDC_BTN_MUTEXWRITE6             1129
#define IDC_BTN_LOCAL2                  1130
#define IDC_BTN_LOCAL3                  1131
#define IDC_BTN_LOCAL4                  1132
#define IDC_BTN_HEN                     1133
#define IDC_BTN_ENC                     1134
#define IDC_BTN_EDGEPOP                 1135
#define IDC_RECT_IMG                    1135
#define IDC_BTN_DEC                     1136
#define IDC_ST_IMG1                     1136
#define IDC_BTN_HEXENC                  1137
#define IDC_ST_IMG2                     1137
#define IDC_BTN_HEXDEC                  1138
#define IDC_BTN_SHARED2                 1139
#define IDC_BTN_SHARED_WRITE2           1140
#define IDC_BTN_LISTBOX                 1141
#define IDC_BTN_LISTBOX2                1142
#define IDC_BTN_MONITOR                 1143
#define IDC_BTN_MONITOR2                1144
#define IDC_BTN_WRITE32                 1145
#define IDC_BTN_MONITOR3                1146
#define IDC_BTN_CHKIME                  1147
#define IDC_BTN_CHKBIT                  1148
#define IDC_BTN_CHKBIT2                 1149
#define IDC_BTN_CHKBIT3                 1150
#define IDC_BTN_LAMDASETTIMER           1151
#define IDC_BTN_LAMDASETTIMER2          1152
#define IDC_AES_ENC                     1153
#define IDC_AES_ENC2                    1154
#define IDC_FDS                         1155
#define IDC_FDS_SEND                    1156
#define IDC_FDS_CLOSE                   1157
#define IDC_DPI                         1158
#define IDC_SFCODE                      1159
#define IDC_SFCODE2                     1160
#define IDC_NXT_MID                     1161
#define IDC_GRID                        1162
#define IDC_GRID2                       1163
#define IDC_FDSFILE                     1164
#define IDC_FDSFILE2                    1165
#define IDC_PUBIP                       1166
#define IDC_CREATE_PROCESS              1167
#define IDC_SHA                         1168
#define IDC_PCINFO                      1169
#define IDC_MAP_LIST                    1170
#define IDC_MAP_LIST2                   1171
#define IDC_VECTOR                      1171
#define IDC_WINPOP                      1172
#define IDC_COMBOPOP                    1173
#define IDC_BTN_ALGO                    1174
#define IDC_STD                         1175
#define IDC_MSG                         1175
#define IDC_TEST                        1176
#define IDC_SFCODE3                     1176
#define IDC_DUMP                        1176
#define IDC_FUNC_TEMP                   1177
#define IDC_BTN_FILEMOVE                1177
#define IDC_STATIC_PAINT                1178
#define IDC_DRAW_THREAD                 1179
#define IDC_DRAW_THREAD2                1180
#define IDC_FUNC_CB                     1181
#define IDC_CAL                         1182
#define IDC_MFC_REGE                    1183
#define IDC_MFC_REGE2                   1184
#define IDC_DRAW_STOP                   1184
#define IDC_MFC_SEARCH                  1185
#define IDC_QUE_START                   1185
#define IDC_CHK_VM                      1186

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        173
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1187
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
