// AxisAgent.idl: AxisAgent.exe의 형식 라이브러리 소스

// 이 파일은 MIDL 컴파일러에 의해 처리되어
// 형식 라이브러리(AxisAgent.tlb)입니다.

[ uuid(b0af1f1d-af01-4788-94fc-ed24f9137de3), version(1.0) ]
library AxisAgent
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	//  CAxisAgentDoc의 기본 디스패치 인터페이스

	[ uuid(dfd75f25-bcd8-4c1f-b686-b305d73fba67) ]
	dispinterface IAxisAgent
	{
		properties:

		methods:
	};

	//  CAxisAgentDoc에 대한 클래스 정보

	[ uuid(f67dc37b-5139-450a-9a14-d0bad2e406bf) ]
	coclass AxisAgent
	{
		[default] dispinterface IAxisAgent;
	};
};
