//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by awWcc.rc
//
#define IDD_COMPILE                     8000
#define IDB_BMPV                        8001
#define IDC_MAPN                        8002
#define IDC_ERROR                       8003
#define IDC_LIST                        8004
#define IDC_STEP                        8005
#define IDC_MSG1                        8006
#define IDC_MSG2                        8007
#define IDC_MSG3                        8008
#define IDC_MSG4                        8009
#define IDC_BMP1                        8010
#define IDC_BMP2                        8011
#define IDC_BMP3                        8012
#define IDC_BMP4                        8013

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        8002
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         8011
#define _APS_NEXT_SYMED_VALUE           8000
#endif
#endif
