//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by D:\~$KTBChart\ProjSrc\OCX2\ChartAddIn\ChartGuideLineAddIn\RES\ChartGuideLineAddIn_Eng\ChartGuideLineAddIn_Eng.rc
//
#define IDS_STRING1                     1
#define IDS_COLORSET                    1
#define IDS_BEFOREOPENPRICE             2
#define IDS_AFTERHOUR                   3
#define IDS_ENDSESSION                  4
#define IDS_ENDSESSIONCLOSE             5
#define IDS_BEFORESESSIONCLOSE          6
#define IDS_T_THOUSAND                  7
#define IDS_H_THOUSAND                  8
#define IDS_MILLION                     9
#define IDS_T_MILLION                   10
#define IDS_H_MILLION                   11
#define IDS_BILLION                     12
#define IDS_T_BILLION                   13
#define IDS_H_BILLION                   14
#define IDS_TRILLION                    15
#define IDS_OHLC_TITLE_O                16
#define IDS_OHLC_TITLE_H                17
#define IDS_OHLC_TITLE_L                18
#define IDS_OHLC_TITLE_C                19
#define IDB_LINE_THICKNESS              1034
#define IDD_DLG_PATTERNENVSETUP         2000
#define IDC_CHK_MMA                     2000
#define IDC_CHK_HIGHLOWPTLINE           2001
#define IDC_CHK_HIGHPTHLINE             2002
#define IDC_CHK_LOWPTHLINE              2003
#define IDC_CHK_HIGHPTREGISTLINE        2004
#define IDC_CHK_LOWPTSUPPORTLINE        2005
#define IDC_EDIT_HLPT_ALLOWABLE         2006
#define IDC_EDIT_NEXTPT_ALLOWABLE       2007
#define IDC_CMB_ACCT                    2007
#define IDC_CHECK_Y_SIGA                6000
#define IDD_DLG_GLINE                   6000
#define IDC_CHECK_Y_JEOGA               6001
#define IDC_CHECK_Y_GOGA                6002
#define IDC_CHECK_Y_ZONGGA              6003
#define IDC_CHECK_Y_ZONGA               6003
#define IDC_CHECK_Y_SGJ_D2              6004
#define IDC_CHECK_Y_GJ_D2               6005
#define IDC_CHECK_HIGH_LIMIT            6005
#define IDC_CHECK_Y_GJZ_D4              6006
#define IDC_CHECK_LOW_LIMIT             6006
#define IDC_COMBO_Y_SIGA                6007
#define IDC_COMBO_Y_GOGA                6008
#define IDC_COMBO_Y_JEOGA               6009
#define IDC_CHECK_T_SIGA                6010
#define IDC_CHECK_T_JEOGA               6011
#define IDC_CHECK_T_GOGA                6012
#define IDC_CHECK_T_ZONGGA              6013
#define IDC_CHECK_T_ZONGA               6013
#define IDC_CHECK_T_SGJ_D2              6014
#define IDC_CHECK_T_GJ_D2               6015
#define IDC_CHECK_T_GJZ_D4              6016
#define IDC_COMBO_T_SIGA                6017
#define IDC_EDIT_1YP                    6018
#define IDC_BTN_INIT                    6019
#define IDC_CHECK_2_RSST                6020
#define IDC_CHECK_PIVOT_GLINE           6021
#define IDC_CHECK_1_RSST                6022
#define IDC_CHECK_1_GG                  6023
#define IDC_CHECK_2_GG                  6024
#define IDC_COMBO_2_RSST                6025
#define IDC_CHECK_PRE_GOGA              6026
#define IDC_CHECK_PREGOGA               6026
#define IDC_CHECK_PRE_JEOGA             6027
#define IDC_CHECK_PREJEOGA              6027
#define IDC_CHECK_DMK_GLINE             6028
#define IDC_COMBO_Y_ZONGA               6029
#define IDC_COMBO_Y_GJ_D2               6030
#define IDC_COMBO_HIGH_LIMIT            6030
#define IDC_COMBO_PREGOGA               6031
#define IDC_CHECK_1YP                   6032
#define IDC_CHECK_3YP                   6033
#define IDC_CHECK_2YP                   6034
#define IDC_CHECK_4YP                   6035
#define IDC_COMBO_Y_SGJ_D2              6036
#define IDC_COMBO_1YP                   6037
#define IDC_EDIT_2YP                    6038
#define IDC_EDIT_3YP                    6039
#define IDC_EDIT_4YP                    6040
#define IDC_CHECK_PPMDANGA              6041
#define IDC_CHECK_PMD                   6041
#define IDC_CHECK_PLUS_DANGA            6042
#define IDC_CHECK_PMPD                  6042
#define IDC_CHECK_MINUS_DANGA           6043
#define IDC_CHECK_PMMD                  6043
#define IDC_COMBO_PMMD                  6044
#define IDC_EDIT_PLUS_RATIO             6045
#define IDC_EDIT_MINUS_RATIO            6046
#define IDC_BTN_APPLY                   6047
#define IDC_CHECK_CHEGYUL               6047
#define IDC_COMBO_Y_GJZ_D4              6048
#define IDC_COMBO_LOW_LIMIT             6048
#define IDC_COMBO_T_GOGA                6049
#define IDC_COMBO_T_JEOGA               6050
#define IDC_COMBO_T_ZONGA               6051
#define IDC_COMBO_T_GJ_D2               6052
#define IDC_COMBO_T_SGJ_D2              6053
#define IDC_COMBO_T_GJZ_D4              6054
#define IDC_COMBO_PMM_PD                6056
#define IDC_COMBO_PMMD_MD               6057
#define IDC_COMBO_1_RSST                6059
#define IDC_COMBO_PIVOT_GLINE           6060
#define IDC_COMBO_1_GG                  6061
#define IDC_COMBO_2_GG                  6062
#define IDC_COMBO_DMKGLINE              6063
#define IDC_COMBO_PREJEOGA              6064
#define IDC_COMBO_2YP                   6065
#define IDC_COMBO_3YP                   6066
#define IDC_COMBO_4YP                   6067
#define IDC_BTNCLR_Y_GOGA               6100
#define IDC_BTNCLR_Y_JEOGA              6101
#define IDC_BTNCLR_Y_ZONGA              6102
#define IDC_BTNCLR_Y_GJ_D2              6103
#define IDC_BTNCLR_HIGH_LIMIT           6103
#define IDC_BTNCLR_Y_SGJ_D2             6104
#define IDC_BTNCLR_Y_GJZ_D4             6105
#define IDC_BTNCLR_LOW_LIMIT            6105
#define IDC_BTNCLR_T_SIGA               6106
#define IDC_BTNCLR_T_GOGA               6107
#define IDC_BTNCLR_T_JEOGA              6108
#define IDC_BTNCLR_T_ZONGA              6109
#define IDC_BTNCLR_T_GJ_D2              6110
#define IDC_BTNCLR_T_SGJ_D2             6111
#define IDC_BTNCLR_T_GJZ_D4             6112
#define IDC_BTNCLR_PMMD                 6113
#define IDC_BTNCLR_2_RSST               6114
#define IDC_BTNCLR_1_RSST               6115
#define IDC_BTNCLR_PIVOT_GLINE          6116
#define IDC_BTNCLR_1_GG                 6117
#define IDC_BTNCLR_2_GG                 6118
#define IDC_BTNCLR_PREGOGA              6119
#define IDC_BTNCLR_DMK_GLINE            6120
#define IDC_BTNCLR_PREJEOGA             6121
#define IDC_BTNCLR_PMMD2                6122
#define IDC_BTNCLR_PMMD3                6123
#define IDC_BTNCLR_1YP                  6124
#define IDC_BTNCLR_2YP                  6125
#define IDC_BTNCLR_3YP                  6126
#define IDC_BTNCLR_4YP                  6127
#define IDC_BTNCLR_Y_SIGA               6128
#define IDC_CHECK_GLINEDRAW             8000
#define IDC_AP_INDICATOR                29000
#define IDC_AP_HIGHLIGHT                29001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2002
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         2009
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
