// axisBuilder.idl : axisBuilder.exe에 대한 형식 라이브러리 소스

// 이 파일은 MIDL 컴파일러에 의해 처리되어
// 형식 라이브러리(axisBuilder.tlb)를 생성합니다.

[ uuid(C16DAB37-2322-4C2E-9980-F0778B554E77), version(1.0) ]
library axisBuilder
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	//  CaxisBuilderDoc의 기본 디스패치 인터페이스
	
	[ uuid(35564F01-A868-49F1-86AC-C58847CF97E7) ]
	dispinterface IaxisBuilder
	{
		properties:
			
		methods:
	};

};
