// cx_shared.idl: cx_shared.dll의 형식 라이브러리 소스
// 이 파일은 MIDL 컴파일러에 의해 처리되어
// 형식 라이브러리(cx_shared.tlb)입니다.

[ uuid(f6c9a9e8-6886-4683-9112-7f3c408e5cac), version(1.0) ]
library cxshared
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");
};
