#if !defined(AFX_IBKSCONNECTOR_H__8288B00D_0F06_4E14_AA28_A54EFC18752B__INCLUDED_)
#define AFX_IBKSCONNECTOR_H__8288B00D_0F06_4E14_AA28_A54EFC18752B__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CIBKSConnector wrapper class

class CIBKSConnector : public CWnd
{
protected:
	DECLARE_DYNCREATE(CIBKSConnector)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xcdadd338, 0xc7ab, 0x4977, { 0xb6, 0x5d, 0x8e, 0x98, 0x8b, 0x59, 0x58, 0xe3 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	BOOL Initialize();
	void Uninitialize();
	BOOL Login(LPCTSTR user_id, LPCTSTR user_pw, LPCTSTR cert_pw, LPCTSTR svr_ip, long svr_port);
	CString GetLastErrMsg();
	CString GetUserName_();
	CString GetHome();
	CString GetUserID();
	void Logout();
	BOOL TR1001(long key, LPCTSTR code);
	BOOL TR1201(long key, long mmgb, LPCTSTR acno, LPCTSTR pswd, long ojno, LPCTSTR code, long jqty, long jprc, long hogb, long mdgb);
	BOOL TR1211(long key, LPCTSTR acno, LPCTSTR pswd, LPCTSTR code, long dsgb, long sygb, long dlgb, long sort, LPCTSTR nkey);
	BOOL TR1221(long key, LPCTSTR acno, LPCTSTR pswd, long allf, LPCTSTR nkey);
	BOOL TR1231(long key, LPCTSTR acno, LPCTSTR pswd, LPCTSTR code, long mmgb, double jprc);
	BOOL TR3001(long key, LPCTSTR code);
	BOOL TR3201(long key, long mmgb, LPCTSTR acno, LPCTSTR pswd, long ojno, LPCTSTR code, long jqty, long jprc, long hogb, long mdgb);
	BOOL TR3211(long key, LPCTSTR acno, LPCTSTR pswd, long dlgb, long sort, LPCTSTR code, long cpgb, long dsgb, LPCTSTR nkey);
	BOOL TR3221(long key, LPCTSTR acno, LPCTSTR pswd, LPCTSTR nkey);
	BOOL TR3231(long key, LPCTSTR acno, LPCTSTR pswd, LPCTSTR code, long mmgb, double jprc, long hogb, long qtpy, double jamt, double jrat);
	BOOL TR1801(long key, LPCTSTR code);
	BOOL TR1802(long key, LPCTSTR code);
	BOOL TR1803(long key, LPCTSTR code);
	BOOL TR1804(long key, LPCTSTR jidx);
	CString GetAccounts();
	BOOL TR1002(long key, LPCTSTR code, LPCTSTR symb);
	BOOL TR1003(long key, LPCTSTR code, long type, LPCTSTR symb, LPCTSTR nkey);
	BOOL TR3002(long key, LPCTSTR code, LPCTSTR symb);
	BOOL TR3003(long key, LPCTSTR code, long type, LPCTSTR symb, LPCTSTR nkey);
	BOOL GetCode(long key, LPCTSTR reqtype);
	BOOL TR1202(long key, long mmgb, LPCTSTR acno, LPCTSTR pswd, long ojno, LPCTSTR code, long jqty, long jprc, long hogb, long mdgb, long id);
	BOOL TR3202(long key, long mmgb, LPCTSTR acno, LPCTSTR pswd, long ojno, LPCTSTR code, long jqty, long jprc, long hogb, long mdgb, long id);
	BOOL TR4224(long key, LPCTSTR acno, LPCTSTR pswd, double zKpi200Idx);
	BOOL TR4223(long key, LPCTSTR acno, LPCTSTR pswd, LPCTSTR zSrtDt, LPCTSTR zEndDt);
	BOOL TR4303(long key, LPCTSTR acno, LPCTSTR pswd, LPCTSTR zQrySrtDt, LPCTSTR zQryEndDt, long zQryTp, long zStnlnSeqTp, long zBalEvalTp, LPCTSTR nkey);
	BOOL TR4201(long key, LPCTSTR acno, LPCTSTR pswd, long zFnoClssCode, LPCTSTR nkey);
	BOOL TR4101(long key, LPCTSTR acno, LPCTSTR pswd);
	BOOL TR4221(long key, LPCTSTR acno, LPCTSTR pswd);
	BOOL TR4401(long key, LPCTSTR acno, LPCTSTR pswd, long zQryTp, LPCTSTR zQrySrtDt, LPCTSTR zQryEndDt, LPCTSTR zIsuNo, LPCTSTR nkey);
	BOOL TR4202(long key, LPCTSTR acno, LPCTSTR pswd, long zBalEvalTp, long zPrcEvalTp, LPCTSTR nkey);
	BOOL TR4003(long key, LPCTSTR acno, LPCTSTR pswd, long zMprcOrdTp, LPCTSTR zRoopData);
	BOOL TR4004(long key, LPCTSTR acno, LPCTSTR pswd, LPCTSTR zRoopData);
	void SetPTS();
	BOOL TR4501(long key, LPCTSTR zMnyoutAcntno, LPCTSTR zMnyoutPswd, long zlMnyoutAmt, LPCTSTR zMnyinBnkCode, LPCTSTR zMnyinBnkAcntNo, LPCTSTR zAskpsnNm, LPCTSTR zTelExno, LPCTSTR zTelRgno, LPCTSTR zTelSeqno);
	BOOL TR4502(long key, LPCTSTR acno, LPCTSTR pswd, long lBkeepAmt, LPCTSTR zMnyinAcntNo);
	BOOL TR4503(long key, LPCTSTR zMnyinAcntNo, LPCTSTR zBnkCode, LPCTSTR zBnkAcntNo, LPCTSTR zBnkPwd, long zMnyinAmt);
	BOOL TR4511(long key, LPCTSTR acno, LPCTSTR pswd, LPCTSTR zQrySrtDt, LPCTSTR zQryEndDt, LPCTSTR nkey);
	BOOL TR4512(long key, LPCTSTR acno, LPCTSTR pswd, LPCTSTR zQrySrtDt, LPCTSTR zQryEndDt, LPCTSTR nkey);
	BOOL TR4521(long key);
	BOOL TR4522(long key, LPCTSTR acno, LPCTSTR pswd, LPCTSTR zBankCode);
	BOOL TR4523(long key, LPCTSTR nkey);
	BOOL TR4524(long key);
	BOOL TR4525(long key, LPCTSTR zMnyoutAcntno);
	BOOL TR4526(long key, LPCTSTR acno, LPCTSTR pswd, LPCTSTR nkey);
	BOOL TR4527(long key, LPCTSTR acno);
	void SaveConfig(LPCTSTR sSendName, LPCTSTR sKey, LPCTSTR sValue);
	BOOL TR8001(long key, LPCTSTR acno);
	void GoURL(long nType);
	BOOL TR1222(long key, LPCTSTR acno, LPCTSTR pswd, long allf);
	BOOL TR3222(long key, LPCTSTR acno, LPCTSTR pswd);
	BOOL TR4403(long key, LPCTSTR acno, LPCTSTR pswd, long zFnoClssCode, LPCTSTR zCmsnAmtAddupCode, LPCTSTR zStrDt, LPCTSTR zEndDt, LPCTSTR nkey);
	BOOL TR3411(long key, LPCTSTR mymd);
	CString GetGreeksData(LPCTSTR sData);
	BOOL TR3232(long key, LPCTSTR acno, LPCTSTR pswd, long fstp, long ertp);

};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_IBKSCONNECTOR_H__8288B00D_0F06_4E14_AA28_A54EFC18752B__INCLUDED_)
