
	// Testdlg.idl : IDL source for Testdlg.exe
//
// This file will be processed by the MIDL tool to
// produce the type library (Testdlg.tlb) and marshalling code.
import "oaidl.idl";
import "ocidl.idl";
[
	uuid(AF0BF8BE-D4C2-47F0-9740-4DEC43D66615),
	version(1.0),
	helpstring("IB192100 1.0 Type Library")
]
library TestdlgLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");
};

	