#if !defined(AFX_SMSCHART_H__D9F7C9F1_1144_42FC_988A_E5BD1AD284C6__INCLUDED_)
#define AFX_SMSCHART_H__D9F7C9F1_1144_42FC_988A_E5BD1AD284C6__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CDRChartOcx wrapper class
#include "../ForSite/FS_Env.h"
#include "../inc/ProgIDInfo.h"

// #define	__MULTI_LANG__

// #ifdef __MULTI_LANG__
	class CDRChartOcx : public CWnd
	{
	protected:
		DECLARE_DYNCREATE(CDRChartOcx)
	public:
		CLSID const& GetClsid()
		{
			static CLSID const clsid
				= {0xb98261e1, 0xb73d, 0x4bb1, { 0x90, 0xd6, 0xe6, 0xc8, 0xba, 0xae, 0xeb, 0xd5} };
				//= { 0xf2914299, 0xfb2c, 0x4165, { 0xae, 0xb4, 0x80, 0x8, 0x51, 0x44, 0x90, 0xd6 } };
			return clsid;
		}
		virtual BOOL Create(LPCTSTR lpszClassName,
			LPCTSTR lpszWindowName, DWORD dwStyle,
			const RECT& rect,
			CWnd* pParentWnd, UINT nID,
			CCreateContext* pContext = NULL)
		{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

		BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
			const RECT& rect, CWnd* pParentWnd, UINT nID,
			CFile* pPersist = NULL, BOOL bStorage = FALSE,
			BSTR bstrLicKey = NULL)
		{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
			pPersist, bStorage, bstrLicKey); }

	// Attributes
	public:
		BOOL GetEnabled();
		void SetEnabled(BOOL);
		OLE_HANDLE GetHWnd();
		void SetHWnd(OLE_HANDLE);
		short GetNChartMode();
		void SetNChartMode(short);
		BOOL GetBNormalizedMinuteTimeRule();
		void SetBNormalizedMinuteTimeRule(BOOL);
		long GetNBlockType();
		void SetNBlockType(long);
		long GetNBlockCompart();
		void SetNBlockCompart(long);
		long GetNBlockRowCount();
		void SetNBlockRowCount(long);
		long GetNBlockColumnCount();
		void SetNBlockColumnCount(long);
		long GetNBlockGap();
		void SetNBlockGap(long);
		long GetNBlockBorderThickness();
		void SetNBlockBorderThickness(long);
		CString GetStrAddInLoadList();
		void SetStrAddInLoadList(LPCTSTR);
		long GetNBorderType();
		void SetNBorderType(long);
		long GetNScaleLineType();
		void SetNScaleLineType(long);
		BOOL GetBWholeView();
		void SetBWholeView(BOOL);
		long GetNOnePageDataCount();
		void SetNOnePageDataCount(long);
		long GetNUserBlockAddCount();
		void SetNUserBlockAddCount(long);
		BOOL GetBGraphDragDrop();
		void SetBGraphDragDrop(BOOL);
		long GetNLeftMargin();
		void SetNLeftMargin(long);
		long GetNRightMargin();
		void SetNRightMargin(long);
		long GetNTopMargin();
		void SetNTopMargin(long);
		long GetNBottomMargin();
		void SetNBottomMargin(long);
		BOOL GetBAddGraphMenuShow();
		void SetBAddGraphMenuShow(BOOL);
		CString GetStrUserEnvironmentFileName();
		void SetStrUserEnvironmentFileName(LPCTSTR);
		CString GetStrUserIndicatorListFileName();
		void SetStrUserIndicatorListFileName(LPCTSTR);
		CString GetStrUserSeriesListFileName();
		void SetStrUserSeriesListFileName(LPCTSTR);
		BOOL GetBHide();
		void SetBHide(BOOL);
		BOOL GetBIsInput();
		void SetBIsInput(BOOL);
		CString GetStrToolbarOption();
		void SetStrToolbarOption(LPCTSTR);
		CString GetStrPacketOption();
		void SetStrPacketOption(LPCTSTR);
		CString GetStrLocalSharedList();
		void SetStrLocalSharedList(LPCTSTR);
		BOOL GetBUseRealData();
		void SetBUseRealData(BOOL);
		CString GetStrRealList();
		void SetStrRealList(LPCTSTR);
		short GetNMarginBorderType();
		void SetNMarginBorderType(short);
		long GetNRowDoubleSizeBlock();
		void SetNRowDoubleSizeBlock(long);
		BOOL GetBUseInquiryDlgWhenUseCrossLine();
		void SetBUseInquiryDlgWhenUseCrossLine(BOOL);
		long GetNColumnDoubleSizeBlock();
		void SetNColumnDoubleSizeBlock(long);
		BOOL GetBUseShortKey();
		void SetBUseShortKey(BOOL);
		BOOL GetBUseConditiontoTitle();
		void SetBUseConditiontoTitle(BOOL);
		BOOL GetBUseDatatoTitle();
		void SetBUseDatatoTitle(BOOL);
		short GetNHorzGap();
		void SetNHorzGap(short);
		short GetNVertGap();
		void SetNVertGap(short);
		short GetNRButtonMenuType();
		void SetNRButtonMenuType(short);
		BOOL GetBShowWarningMessageBox();
		void SetBShowWarningMessageBox(BOOL);
		BOOL GetBControlBlockSize();
		void SetBControlBlockSize(BOOL);
		BOOL GetBBlockMoveDelete();
		void SetBBlockMoveDelete(BOOL);
		BOOL GetBSelectTitle();
		void SetBSelectTitle(BOOL);
		BOOL GetBSelectGraph();
		void SetBSelectGraph(BOOL);
		BOOL GetBUseScaleRButtonMenu();
		void SetBUseScaleRButtonMenu(BOOL);
		short GetNGraphRButtonType();
		void SetNGraphRButtonType(short);
		short GetNHoldingPacketSize();
		void SetNHoldingPacketSize(short);
		CString GetSzBasePacketName();
		void SetSzBasePacketName(LPCTSTR);
		BOOL GetBRedrawAfterUpdatedAllPackets();
		void SetBRedrawAfterUpdatedAllPackets(BOOL);
		short GetNMinDataCountOnOnePage();
		void SetNMinDataCountOnOnePage(short);
		BOOL GetBFireRealEvent();
		void SetBFireRealEvent(BOOL);
		short GetNInquiryType();
		void SetNInquiryType(short);
		BOOL GetBOcxAreaNumericalInquiry();
		void SetBOcxAreaNumericalInquiry(BOOL);
		long GetNNumericalInquiryOption();
		void SetNNumericalInquiryOption(long);
		CString GetStrGlobalSharedList();
		void SetStrGlobalSharedList(LPCTSTR);
		short GetNUseInquiryWithCrossline();
		void SetNUseInquiryWithCrossline(short);
		BOOL GetBShowPriceRateInquiry();
		void SetBShowPriceRateInquiry(BOOL);
		BOOL GetBDoesUseSkinColor();
		void SetBDoesUseSkinColor(BOOL);
		CString GetStrMapName();
		void SetStrMapName(LPCTSTR);
		short GetNBongCountMargin();
		void SetNBongCountMargin(short);
		BOOL GetBOnePageDataCountInTRCount();
		void SetBOnePageDataCountInTRCount(BOOL);
		BOOL GetBIsMapDefault();
		void SetBIsMapDefault(BOOL);
		short GetNPacketCountDataSize();
		void SetNPacketCountDataSize(short);
		short GetNLanguageID();
		void SetNLanguageID(short);
		BOOL GetBFreezedPageState();
		void SetBFreezedPageState(BOOL);
		BOOL GetIsShowInneerToolBar();
		void SetIsShowInneerToolBar(BOOL);
		CString GetStrChartList();
		void SetStrChartList(LPCTSTR);
		unsigned long GetClrBackground();
		void SetClrBackground(unsigned long);
		unsigned long GetClrBackBorder();
		void SetClrBackBorder(unsigned long);
		unsigned long GetClrBlock();
		void SetClrBlock(unsigned long);
		unsigned long GetClrBlockBorder();
		void SetClrBlockBorder(unsigned long);
		unsigned long GetClrScaleLine();
		void SetClrScaleLine(unsigned long);
		unsigned long GetClrScaleText();
		void SetClrScaleText(unsigned long);
		unsigned long GetClrGraphBase1();
		void SetClrGraphBase1(unsigned long);
		unsigned long GetClrGraphBase2();
		void SetClrGraphBase2(unsigned long);
		unsigned long GetClrGraphBase3();
		void SetClrGraphBase3(unsigned long);
		unsigned long GetClrGraphBase4();
		void SetClrGraphBase4(unsigned long);
		unsigned long GetClrGraphBase5();
		void SetClrGraphBase5(unsigned long);
		unsigned long GetClrGraphBase6();
		void SetClrGraphBase6(unsigned long);
		unsigned long GetClrAnalysisTool();
		void SetClrAnalysisTool(unsigned long);
		CString GetStrBlockRegion();
		void SetStrBlockRegion(LPCTSTR);
		unsigned long GetClrScaleLine2();
		void SetClrScaleLine2(unsigned long);
		unsigned long GetClrInquiryWindow();
		void SetClrInquiryWindow(unsigned long);
		CString GetCustomFont();
		void SetCustomFont(LPCTSTR);
		unsigned long GetClrLattice();
		void SetClrLattice(unsigned long);
		CString GetStrStartDateOfData();
		void SetStrStartDateOfData(LPCTSTR);
		BOOL GetOnRunningOneChart();
		void SetOnRunningOneChart(BOOL);
		BOOL GetEnableHorizontalLineInNIDLG();
		void SetEnableHorizontalLineInNIDLG(BOOL);
		BOOL GetBShowPriceMinMaxText();
		void SetBShowPriceMinMaxText(BOOL);
		BOOL GetBHideAllTitle();
		void SetBHideAllTitle(BOOL);
		CString GetStrMapIndicatorInfo();
		void SetStrMapIndicatorInfo(LPCTSTR);
		BOOL GetBEnableIndicatorCalculation();
		void SetBEnableIndicatorCalculation(BOOL);
		CString GetStrPagePathWithPrefix();
		void SetStrPagePathWithPrefix(LPCTSTR);
		long GetNCurrentDrawCount();
		void SetNCurrentDrawCount(long);
		short GetNRealTimeTruncationType();
		void SetNRealTimeTruncationType(short);
		BOOL GetBUseGapRevision();
		void SetBUseGapRevision(BOOL);
		long GetNFullDataCount();
		void SetNFullDataCount(long);

	// Operations
	public:
		BOOL SetAllProperties2(long dwData);
		void SetBaseDesk(long lKey);
		long GetBase(LPCTSTR szKey);
		short SetChartData(long pChartData, short nCount, short nType);
		short SetChartDataStr(LPCTSTR szChartData, short nCount, short nType);
		short testGetPacketdatasize(LPCTSTR pIn);
		void testLoadAnalysisTools(short nToolOption, short nOption);
		void MakeSaveShortKey(LPCTSTR szFileName, short nFlag);
		short ChangeChart(short nBlockRowPosition, short nBlockColumnPosition, LPCTSTR strGraphTitle, LPCTSTR strGraphName, LPCTSTR strPacketName, LPCTSTR strGraphType, LPCTSTR strGraphStyle, short nLineWidth, unsigned long clrLineColor);
		short ClearChartData(short nOption);
		short SetGraphHide(short nRow, short nColumn, LPCTSTR strTitle, BOOL bHide);
		BOOL AddChartBlock(LPCTSTR strChartName);
		void SetOnePageDataCount(long nOnePageDataCount);
		long GetOnePageDataCount();
		BOOL SaveandOpenFromFile(LPCTSTR strOpenFileName, LPCTSTR strSaveFileName, BOOL bOpenOption, BOOL bSaveOption);
		BOOL JoinandDevisionforCompareChart(long nRowCount, long nColumnCount, BOOL bJoin);
		BOOL ChangeGraphTitle(short nRowIndex, short nColumnIndex, short nGraphIndex, LPCTSTR strNewTitle);
		short SetChartDataFromFile(LPCTSTR szFileName, short nType);
		BOOL RemoveChart(LPCTSTR strChartName);
		BOOL ChangeGraphType(LPCTSTR strGraphName, LPCTSTR strGraphType, LPCTSTR strGraphStyle, LPCTSTR strPacketNameList, BOOL bRunatOnce);
		void SetChartAllInfo();
		CString GetData(LPCTSTR strPacketName, short nDataIndex);
		BOOL SetDrdsAdvise(BOOL bOnAdvise);
		short GetDataCount();
		BOOL ChangeChartItem(LPCTSTR strGraphName, short nSubGraphIndex, LPCTSTR strNewTitle, LPCTSTR strNewPacketName, LPCTSTR strNewGraphType, LPCTSTR strNewGraphStyle, short nNewUpLineWidth, short nNewDownLineWidth, short nNewEqualLineWidth, 
			BOOL bRunatOnce);
		BOOL SetStopLossPrice(BOOL bIsStopLoss, double dStopLossPrice, BOOL bIsProfit, double dProfitPrice);
		BOOL RestoreMinMax(LPCTSTR strPacketName);
		BOOL RestoreMin(LPCTSTR strPacketName);
		BOOL RestorMax(LPCTSTR strPacketName);
		BOOL SetMin(LPCTSTR strPacketName, double dMin);
		BOOL SetMax(LPCTSTR strPacketName, double dMax);
		BOOL SetMinMax(LPCTSTR strPacketName, double dMin, double dMax);
		BOOL SetHorzScaleData(short nRowIndex, short nColumnIndex, LPCTSTR strScaleData);
		double GetMin(LPCTSTR strPacketName);
		double GetMax(LPCTSTR strPacketName);
		BOOL SetGraphHide2(short nRowIndex, short nColumnIndex, short nVerticalIndex, short nGraphIndex, short nSubGraphIndex, BOOL bHide);
		BOOL ChangeGraphDatas(short nRowIndex, short nColumnIndex, short nVerticalIndex, short nGraphIndex, LPCTSTR strNewGraphName, LPCTSTR strNewTitle, LPCTSTR strNewPacketName, LPCTSTR strNewGraphType, LPCTSTR strNewGraphStyle, 
			short nNewUpLineWidth, short nNewDownLineWidth, short nNewEqualLineWidth, BOOL bRunatOnce);
		void SaveandApplyGraphStyle(short nSaveDataType, short nChangeDataType);
		void SetDataRegionInBlock(short nDataStartIndex);
		void SetItemInfo(LPCTSTR lpstrCode, LPCTSTR lpstrName);
		void AddandDeleteIndicator(LPCTSTR strGraphName);
		long GetAllProperties2(long lpData);
		long GetBasePropIf();
		BOOL SetVertScaleData(short nRowIndex, short nColumnIndex, short nVertScaleGroupIndex, LPCTSTR strVertScaleData);
		BOOL ChangeBlockType(short nBlockType, short nRowCount, short nColumnCount);
		BOOL ChangeHorzScalePosition(short nScalePosition, short nRowIndex, short nColumnIndex);
		BOOL ResetChart();
		void SetRealData(LPCTSTR strPacketName, double dData, short nOption);
		BOOL SetGraphTitle(LPCTSTR strGraphName, short nSubGraphIndex, LPCTSTR strNewGraphTitle, BOOL bGraphShowing);
		CString GetIndicatorNameList(LPCTSTR p_strGroup);
		void AddGraph(short nRow, short nColumn, short nVertScaleGroup, LPCTSTR szGraphOption, BOOL bCreateBlock, BOOL bCreateVertScaleGroup, BOOL bUseAutoScale);
		void AddPacket(LPCTSTR szPacketOption);
		long RemovePacket(LPCTSTR szPacketName);
		void SetContainerDllInfo(long p_lDllWnd, short p_nID);
		BOOL SetPacketData(LPCTSTR szPacketName, long szData, long lLength, BOOL bReset);
		void SetBackgroundColors(unsigned long p_rgbBlockArea, unsigned long p_rgbScaleArea);
		BOOL AddRealItem(LPCTSTR szRealInfo);
		void ShowIndicatorConfigDlg();
		void ResetChartCfgWith(short p_nIndex);
		BOOL EmptyChart(BOOL bIsDeleteAllPacket, BOOL bIsDefault);
		BOOL HasGraph(LPCTSTR p_szGraphName);
		void RemoveRealItem(LPCTSTR szRealInfo);
		void ShowInnerToolBar(BOOL p_bShow);
		BOOL ChangeVertScalePosition(short nScalePosition, short nRowIndex, short nColumnIndex, short nVSGroupIndex);
		short GetRowBlockCount();
		short GetColumnBlockCount();
		BOOL SetStartPeriodOfPacket(LPCTSTR p_szPacketName, long p_lStartPeriod, long p_bAddSpace);
		long GetStartPeriodOfPacket(LPCTSTR p_szPacketName);
		BOOL GetStartEndDateOnView(double* p_pStartDate, double* p_pEndDate);
		BOOL SetStartEndDateOfView(double p_dStartDate, double p_dEndDate);
		BOOL ScrollToDataOfEnd(double p_dData);
		short ZoomToWithRightFix(short p_nZoomValue, BOOL p_bWithRightFix);
		void ClearTimeMark();
		void ShowEnvironmentDlg();
		void SetTimeMark(LPCTSTR p_szMarkTime, BOOL p_bWithScroll);
		short GetVertScalePosition(short p_nRowIndex, short p_nColumnIndex, short p_nVSGroupIndex);
		void EnableBoundMark(BOOL p_bEnable);
		void EnableReceivingTimeShare(BOOL p_bEnable);
		BOOL ChangePacketType(LPCTSTR p_szPacketName, LPCTSTR p_szPacketType);
		BOOL ChangeGraphDrawingData(LPCTSTR p_szGraphName, BOOL p_bLowHigh, BOOL p_bLowCur, BOOL p_bHighCur, BOOL p_bPrevCur, short p_nCurData);
		BOOL ChangePriceGraphDrawingData(BOOL p_bLowHigh, BOOL p_bLowCur, BOOL p_bHighCur, BOOL p_bPrevCur, short p_nCurData, short p_nDefaultType);
		void ShowAnalysisToolText(BOOL p_bTimeLine, BOOL p_bPriceLineLeft, BOOL p_bPriceLineRight, BOOL p_bTrendLine, BOOL p_bTrisectionLine, BOOL p_bQuadrisectionLine, BOOL p_bFibonacciRetraceLine);
		BOOL HasGraphInSpecialBack(LPCTSTR p_szGraphName);
		BOOL LoadAddIn(LPCTSTR p_szAddInDllName);
		BOOL InvokeAddIn(LPCTSTR p_szAddInDllName, short p_nCommandType, long p_lData);
		void SetDragModeType(short p_nDragModeType);
		BOOL ResetRealListString(LPCTSTR p_szRealList, BOOL p_bAdviseNow);
		BOOL AddOrRemoveChart(LPCTSTR strGraphName);
		void SetHtsPath(LPCTSTR pcszHtsPath);
		CString GetRealSettingInfo();
		void SetAllLogScale(BOOL bLogScale);
		void GetListViewerData(BSTR* bstrTitle, BSTR* bstrHorzScale, BSTR* bstrPacketNamesPerBlock, BSTR* bstrPacketNames, BSTR* bstrSaveFilePath, BOOL* bViewPacketSequence, long* lpPacketList);
		void SetDataIndexByDate(LPCTSTR pcszStartDate, LPCTSTR pcszEndDate);
		void SetRunTimeMode(BOOL bRunTimeMode);
		CString GetPacketOption();
		void SetPacketOption(LPCTSTR strPacketOption);
		void SetOutsideCommonInterface(long lpOutsideCommonInterface);
		BOOL RemoveGraph_Title(short nRowIndex, short nColumnIndex, LPCTSTR szGraphTitle, BOOL bIsOnlyNoTRData, BOOL bIsAutoHorzScalePosition);
		CString GetGraphPacketName(short nRowIndex, short nColumnIndex, LPCTSTR szGraphTitle);
		BOOL ChangeGraphTitle2(LPCTSTR szTargetTitle, LPCTSTR szSourceTitle);
		BOOL PartitionAllGraph();
		BOOL JoinAllGraph(BOOL bIsOneVertScaleGroup);
		BOOL ChangeAllFunctionName(LPCTSTR szTargetGraphName, LPCTSTR szSourceGraphName, BOOL bKeepOldGraphColor);
		BOOL ChangeIndicatorPacketName(LPCTSTR strGraphName, short nSubGraphIndex, LPCTSTR strNewPacketName);
		void RunEnvironmentDlg(short nOption);
		BOOL SetIndicatorCondition(LPCTSTR strGraphName, short nConditionType, short nConditionIndex, double dConditionValue, BOOL bReCalculate);
		BOOL SetPacketData2(LPCTSTR strPacketName, LPCTSTR strPacketType, LPCTSTR strPacketData, short nDataCount, BOOL bReCalculate);
		BOOL SetLogScale(LPCTSTR strGraphName, BOOL bLogScale);
		BOOL GetLogScale(LPCTSTR strGraphName);
		BOOL SetPacketHelpMessage(LPCTSTR strHelpMsg, BOOL bIsAllRemove);
		BOOL InvokeAddInStr(LPCTSTR p_szAddInDllName, LPCTSTR p_szCommandName, LPCTSTR p_szData);
		BOOL SetHelpMessageRealDataRate(LPCTSTR strHelpMessageData, BOOL bIsRemove);
		void SetBongCountMargin(short nBongCountMargin);
		BOOL SetAllPropertiesFromFile(LPCTSTR strFilePath, LPCTSTR strFileName);
		BOOL SetGraphHide3(LPCTSTR strTitle, BOOL bIsHide);
		BOOL GetBoundMarkFlag();
		BOOL UnloadAddIn(LPCTSTR p_szAddInDllName);
		void SetOnePageDataCount2(long nOnePageDataCount, BOOL bIncludeBongCountMargin);
		BOOL ClearPacketData(LPCTSTR strPacketName, BOOL bIsAbsoluteClear);
		void SetAllGraphHide(short nRowIndex, short nColumnIndex, short bHide);
		void InitStaticIndiCond(LPCTSTR p_szBasePath);
		void SetAllGraphsHide(short nRowIndex, short nColumnIndex, BOOL bHide);
		CString GetPacketData2(LPCTSTR strPacketName, short nDataIndex, BOOL bIsFullDataSize);
		CString GetSelectedSubGraphData(short nPoint_x, short nPoint_y);
		short GetPacketIndex(LPCTSTR szPacketName, double dKeyValue);
		short GetCurrentPriceChartType();
		BOOL RemoveBlock(short nPoint_x, short nPoint_y);
		BOOL RemoveGraph(short nRowIndex, short nColumnIndex, LPCTSTR strGraphTitle);
		BOOL SetGraphColor(short nRowIndex, short nColumnIndex, short nVertScaleGroupIndex, short nGraphIndex, short nSubGraphIndex, LPCTSTR strNewColor);
		BOOL SetPacketDataInIndex(LPCTSTR strPacketName, short nIndex, LPCTSTR strData, BOOL bIsRealData);
		BOOL SetVertScaleLogType(short nRowIndex, short nColumnIndex, BOOL bIsLogType);
		BOOL OpenFileOfEnvAndIndi(LPCTSTR strFileName_Env, LPCTSTR strFileName_Indi, BOOL bIsCurrentSave);
		BOOL SetPacketDataInAdditionPacket(LPCTSTR szPacketName, long szData, long lLength, BOOL bReset);
		void SetOnePageDataCountInTRCount(BOOL bIsTRCount, BOOL bIsNowChange);
		void PrintChatImage();
		void ExportToExcel();
		BOOL RunToolFunction(short nToolCommand, short nOption);
		BOOL SetSubIndicatorCondition(LPCTSTR strGraphName, short nConditionType, short nSubGraphIndex, short nConditionIndex, double dConditionValue, BOOL bReCalculate);
		BOOL SetGraphHide4(LPCTSTR strGraphName, short nSubGraphIndex, BOOL bHide);
		BOOL SetMapDefaultInCurrent(BOOL bIsNewMapDefault);
		BOOL ChangeFunctionName(LPCTSTR p_szTargetFName, LPCTSTR p_szNewFName, LPCTSTR p_szNewSGName);
		BOOL GetHeadAndTailData(LPCTSTR strPacketName, double* pHeadData, double* pTailData);
		LPUNKNOWN GetAddInCustomInterface(LPCTSTR p_szAddInName);
		BOOL LoadAddInWithOverExclusive(LPCTSTR p_szAddInName);
		BOOL OpenFromFile(LPCTSTR p_szFileName, BOOL p_bAutoPrevSave);
		BOOL SaveandOpenFromFileWithMSave(LPCTSTR strOpenFileName, LPCTSTR strSaveFileName, BOOL bOpenOption, BOOL bSaveOption);
		BOOL AddRealItemWithSeparator(LPCTSTR szRealInfo, LPCTSTR szSeparatorChar);
		void RemoveRealItemWithSeparator(LPCTSTR szRealInfo, LPCTSTR szSeparatorChar);
		long GetAllProperties3(long p_lIPropertyMap);
		long SetAllProperties3(long p_lIPropertyMap);
		BOOL ShowIndicatorConfigDlgWithName(LPCTSTR p_szGraphName);
		BOOL RemoveBlockWithIndex(short p_nRowIndex, short p_nColumnIndex);
		BOOL SetBinTrHelpMsg(LPCTSTR p_szHelpMessage);
		BOOL SetBinTrDoubleData(LPCTSTR p_szPacketName, long p_nCount, double* p_pdData);
		BOOL SetBinTrStringData(LPCTSTR p_szPacketName, long p_nCount, long p_lData);
		BOOL SetBinTrEnd();
		BOOL EmptyChart2(LPCTSTR p_szChartList, BOOL p_bIsDeleteAllPacket, BOOL p_bIsDefault);
		short GetHorzScalePosition(short p_nRowIndex, short p_nColumnIndex);
		BOOL HasIndicator(LPCTSTR p_szIndicatorName);
		BOOL HasIndicatorInSpecialBack(LPCTSTR p_szIndicatorName);
		BOOL LockWindowUpdate();
		void UnlockWindowUpdate();
		CString AddChartItem(LPCTSTR lpszItemCode, LPCTSTR lpszItemName, BOOL bBuiltChart);
		void SetRealDataCode(LPCTSTR strCode, LPCTSTR strPacketName, double dData, short nOption);
		void ShowIndicator(LPCTSTR p_szIndicatorName, BOOL p_bShow, BOOL p_bRecalculate);
		void SetPacketAutoScaleType(LPCTSTR p_szPacketName, BOOL p_bAutoScaleType);
		BOOL SetPacketTypeWithAutoScale(LPCTSTR p_szPacketName, LPCTSTR p_szPacketType, BOOL p_bAutoScale);
		void ShowBaseText(BOOL p_bShow);
		BOOL ChangeGraphColor(LPCTSTR p_szGraphTitle, LPCTSTR p_szColors);
		void AddPacketRQ(LPCTSTR lpszRQ, LPCTSTR lpszPacketOption);
		BOOL SetPacketDataRQ(LPCTSTR lpszRQ, LPCTSTR lpszPacketName, long nData, long nLength, BOOL bReset);
		BOOL AddChartItemRQ(LPCTSTR lpszRQ, LPCTSTR lpszItemCode, LPCTSTR lpszItemName);
		void SetCurrentRQ(LPCTSTR lpszRQ);
		void SetResetTotalCountWhileDraw(BOOL bReset);
		void SetFutureScaleVisible(long nScaleVisible);
		void SetMultiItemMode(BOOL bMultiItem);
		void SetVertScaleType(short nBlockRow, short nBlockCol, short nScaleGroup, short nScaleType, double dTypeValue);
		void OpenFromPage(LPCTSTR p_szPagePath, BOOL p_bIsVirtualPage, short p_nVirtualPageIndex, short p_nDuplicateIndex);
		void SaveToPage(LPCTSTR p_szPagePath, BOOL p_bIsVirtualPage, short p_nVirtualPageIndex, short p_nDuplicateIndex);
		BOOL ZoomTo(long p_nZoomValue, BOOL p_bRelative);
		BOOL ShiftPacket(LPCTSTR p_szPacketNames, long p_szShiftCount);
		BOOL SaveandOpenFromAnalToolFile(LPCTSTR lpszOpenFileName, LPCTSTR lpszSaveFileName, BOOL bOpenOption, BOOL bSaveOption);
		void SetHorizontalScaleHeight(long nHeight);
		void ChangeGraphPropertyAtOnce(LPCTSTR lpszRQ, LPCTSTR lpszTargetTitle, LPCTSTR lpszNewTitle, short nGraphType, short nGraphStyle, short nDrawStyle, LPCTSTR lpszColors, short nThickness1, short nThickness2, short nThickness3);
		BOOL EmptyChart3(LPCTSTR lpszChartList, BOOL bIsDeleteAllPacket, BOOL bIsDefault, short nBlockCount);
		BOOL AddChartAllBlock(LPCTSTR strChartName);
		BOOL RemoveGraphRQ(LPCTSTR lpszRQ, LPCTSTR lpszTitle);
		CString AddPairItem(LPCTSTR lpszItemCode, LPCTSTR lpszItemName, BOOL bBuiltChart);
		BOOL HasIndicatorWithRQ(LPCTSTR p_szIndicatorName2, LPCTSTR p_szRQ);
		void RemoveAllGraphOfRQ(LPCTSTR p_szRQ);
		short GetRowOfGraphWithRQ(LPCTSTR p_szIndicatorName2, LPCTSTR p_szRQ);
		BOOL SetGraphColorWithRQ(LPCTSTR p_szRQ, LPCTSTR p_szIndicatorName2, LPCTSTR p_szColor);
		void SetUseSTExtData(LPCTSTR lpszExtDataName);
		BOOL ShowGraphDataDrawingData(LPCTSTR lpszRQ, LPCTSTR lpszIndicatorName, BOOL bShow, short nShowType);
		void ShowSelEnvironmentDlg(short nPage);
		long GetVertScaleGroupCount(short nRow, short nColumn);
		void SetSyncPacketData(LPCTSTR strSyncPacketNames);
		void SetEmptyChart();
		void SetDrawVerticalBox(double dHorzValue, LPCTSTR strColor, BOOL bFill);
		void UseDummyPacketData(BOOL bUse);
		void SetDoubleSizeBlock(short nRowIndex, short nColIndex);
		long AddHorizontalLine(LPCTSTR lpszTitle, unsigned long clrLine, short nLine, double dPrice);
		void DeleteHorizontalLine(long nIndex);
		void DeleteAllHorizontalLine();
		void UpdateHorizontalLine(long nIndex, LPCTSTR lpszTitle, unsigned long clrLine, short nLine, double dPrice);
		CString GetPacketTypeFromKrxCmeCode(LPCTSTR p_szKrxCmeCode);
		void SetEncUserID(LPCTSTR strUserID);
		void ReCalculateAllGraphs();
		CString GetGraphPropertyAtOnce(LPCTSTR lpszRQ, LPCTSTR lpszTargetTitle);
		void ChangeVertScaleMinMaxType(short nRowIndex, short nColumnIndex, short nVertScaleGroupIndex, short nScaleType, double dMinValue, double dMaxValue);
		void SetAvgUnitPrice(double dAvgPrice);
		long GetPacketCount(LPCTSTR strPacketName);
		BOOL FindRQ(LPCTSTR lpszRQ);
		short GetPacketNearIndex(LPCTSTR szPacketName, double dKeyValue);
		BOOL ChangePacketTypeRQ(LPCTSTR lpszRQ, LPCTSTR p_szPacketName, LPCTSTR p_szPacketType);
		void SetDrawBaseLine(BOOL bDraw);
		BOOL GetGraphHide4(LPCTSTR strGraphName, short nSubGraphIndex);
		// (2011/2/28 - Seung-Won, Bae) to set the item name for DEFAULT RQ of Single Chart.
		void SetItemCode( LPCTSTR lpszRQ, LPCTSTR lpszItemCode, LPCTSTR lpszItemName);

		// 가로 scale 위치
		enum HORZSCALEPOSITION
		{
			HORZ_TOP,
				HORZ_BOTTOM,
				HORZ_BOTH,
				HORZ_HIDE,
				HORZ_NONE
		};
		
		// 세로 scale 위치
		enum VERTSCALEPOSITION
		{
			VERT_LEFT,
				VERT_RIGHT,
				VERT_BOTH,
				VERT_NONE
		};
	};

// 	#else
// 		class CDRChartOcx : public CWnd
// 		{
// 		protected:
// 			DECLARE_DYNCREATE(CDRChartOcx)
// 		public:
// 			BOOL GetClsid(CLSID &clsid)
// 			{
// 				CString szProgID;
// 				{
// 					CString szCFG;
// 					GetDir_DrfnData(szCFG); szCFG+="\\chartmetatable.dat";
// 					char aProgID[100]={0,};
// 					if(::GetPrivateProfileString("Chart Version", "ProgID", "", aProgID, 100, szCFG)==0)
// 						return FALSE;
// 					szProgID = aProgID;
// 				}
// 
// 				HRESULT hr = AfxGetClassIDFromString(szProgID, &clsid);
// 				if (FAILED(hr))		return FALSE;
// 					return TRUE;
// 
// 		//		static CLSID const clsid
// 		//			//= { 0xf624b2a5, 0x70be, 0x4db6, {0x9b, 0x84, 0x8e, 0x9b, 0xd5, 0x35, 0x6f, 0x3 } };		// HMC
// 		//			= { 0x88f2fcd7, 0xa82b, 0x4486, { 0xac, 0x73, 0xd6, 0xec, 0xbb, 0xf7, 0xe3, 0xdf } };	//SMS
// 		//		return clsid;
// 			}
// 
// 			CDRChartOcx();
// 			virtual ~CDRChartOcx();
// 
// 			BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
// 				const RECT& rect, CWnd* pParentWnd, UINT nID,
// 				CFile* pPersist = NULL, BOOL bStorage = FALSE,
// 				BSTR bstrLicKey = NULL);
// 
// 			//===========================================================================================
// 			// 2007. 01. 05 추가
// 			// 입력 data를 binary로  처리
// 			BOOL SetBinTrHelpMsg(LPCTSTR p_szHelpMessage);
// 			BOOL SetBinTrDoubleData(LPCTSTR p_szPacketName, long p_nCount, double* p_pdData);
// 			BOOL SetBinTrStringData(LPCTSTR p_szPacketName, long p_nCount, long p_lData);
// 			BOOL SetBinTrEnd();
// 
// 		protected:
// 			DISPID *			m_pdID;
// 
// 		// Attributes
// 		public:
// 			BOOL GetEnabled();
// 			void SetEnabled(BOOL);
// 			OLE_HANDLE GetHWnd();
// 			void SetHWnd(OLE_HANDLE);
// 		// Operations
// 		public:
// 
// 			//-->090902-alzioyes OCX CLSID 생성.
// 			//CDRChartOcx::Create에서 "c:\\Logs\\DRChartOcx.txt"에 자동으로 생성한 값임.
// 			typedef enum {
// 		//--> 2009.11.16월 KTB포팅버전.
// 		/*		IIx_SetBaseDesk                   =   0,
// 				IIx_GetBase                       =   1,
// 				IIx_AddGraph                      =   2,
// 				IIx_AddPacket                     =   3,
// 				IIx_RemovePacket                  =   4,
// 				IIx_GetIndicatorNameList          =   5,
// 				IIx_SetContainerDllInfo           =   6,
// 				IIx_SetChartData                  =   7,
// 				IIx_SetPacketData                 =   8,
// 				IIx_AddChartBlock                 =   9,
// 				IIx_ResetChart                    =  10,
// 				IIx_SetBackgroundColors           =  11,
// 				IIx_SetDrdsAdvise                 =  12,
// 				IIx_AddRealItem                   =  13,
// 				IIx_ShowIndicatorConfigDlg        =  14,
// 				IIx_NOnePageDataCount             =  15,
// 				IIx_StrStartDateOfData            =  16,
// 				IIx_ResetChartCfgWith             =  17,
// 				IIx_EmptyChart                    =  18,
// 				IIx_HasGraph                      =  19,
// 				IIx_RemoveRealItem                =  20,
// 				IIx_SaveandOpenFromFile           =  21,
// 				IIx_ClearChartData                =  22,
// 				IIx_ShowInnerToolBar              =  23,
// 				IIx_ChangeVertScalePosition       =  24,
// 				IIx_GetRowBlockCount              =  25,
// 				IIx_GetColumnBlockCount           =  26,
// 				IIx_ChangeHorzScalePosition       =  27,
// 				IIx_RemoveChart                   =  28,
// 				IIx_SetStartPeriodOfPacket        =  29,
// 				IIx_GetStartPeriodOfPacket        =  30,
// 				IIx_StrUserIndicatorListFileName  =  31,
// 				IIx_StrUserEnvironmentFileName    =  32,
// 				IIx_GetStartEndDateOnView         =  33,
// 				IIx_SetStartEndDateOfView         =  34,
// 				IIx_ScrollToDataOfEnd             =  35,
// 				IIx_ZoomToWithRightFix            =  36,
// 				IIx_ClearTimeMark                 =  37,
// 				IIx_ShowEnvironmentDlg            =  38,
// 				IIx_SetTimeMark                   =  39,
// 				IIx_BOcxAreaNumericalInquiry      =  40,
// 				IIx_OnRunningOneChart             =  41,
// 				IIx_EnableBoundMark               =  42,
// 				IIx_EnableReceivingTimeShare      =  43,
// 				IIx_ChangePacketType              =  44,
// 				IIx_ChangePriceGraphDrawingData   =  45,
// 				IIx_NUseInquiryWithCrossline      =  46,
// 				IIx_BShowPriceRateInquiry         =  47,
// 				IIx_BNormalizedMinuteTimeRule     =  48,
// 				IIx_HasGraphInSpecialBack         =  49,
// 				IIx_InvokeAddIn                   =  50,
// 				IIx_LoadAddIn                     =  51,
// 				IIx_SetDragModeType               =  52,
// 				IIx_SetHtsPath                    =  53,
// 				IIx_SetAllLogScale                =  54,
// 				IIx_GetListViewerData             =  55,
// 				IIx_SetDataIndexByDate            =  56,
// 				IIx_SetRunTimeMode                =  57,
// 				IIx_GetPacketOption               =  58,
// 				IIx_SetPacketOption               =  59,
// 				IIx_SetOutsideCommonInterface     =  60,
// 				IIx_RemoveGraph_Title             =  61,
// 				IIx_RemoveGraph                   =  62,
// 				IIx_GetGraphPacketName            =  63,
// 				IIx_ChangeGraphTitle2             =  64,
// 				IIx_PartitionAllGraph             =  65,
// 				IIx_JoinAllGraph                  =  66,
// 				IIx_SetBSelectTitle               =  67,
// 				IIx_ChangeAllFunctionName         =  68,
// 				IIx_ChangeIndicatorPacketName     =  69,
// 				IIx_RunEnvironmentDlg             =  70,
// 				IIx_SetIndicatorCondition         =  71,
// 				IIx_SetLogScale                   =  72,
// 				IIx_GetLogScale                   =  73,
// 				IIx_SetHelpMessageRealDataRate    =  74,
// 				IIx_InvokeAddInStr                =  75,
// 				IIx_SetGraphHide3                 =  76,
// 				IIx_SetOnePageDataCount2          =  77,
// 				IIx_SetPacketDataInAdditionPacket =  78,
// 				IIx_SetOnePageDataCount           =  79,
// 				IIx_SetPacketHelpMessage          =  80,
// 				IIx_SetRealData                   =  81,
// 				IIx_PrintChatImage                =  82,
// 				IIx_ExportToExcel                 =  83,
// 				IIx_LoadAddInWithOverExclusive    =  84,
// 				IIx_GetAllProperties2             =  85,
// 				IIx_SetAllProperties2             =  86,
// 				IIx_GetAllProperties3             =  87,
// 				IIx_SetAllProperties3             =  88,
// 				IIx_GetAddInCustomInterface       =  89,
// 				IIx_SetBinTrHelpMsg               =  90,
// 				IIx_SetBinTrDoubleData            =  91,
// 				IIx_SetBinTrStringData            =  92,
// 				IIx_SetBinTrEnd                   =  93,
// 				IIx_ShowIndicatorConfigDlgWithName=  94,
// 				IIx_bEnableIndicatorCalculation   =  95,
// 				IIx_StrChartList                  =  96,
// 				IIx_bWholeView                    =  97,
// 				IIx_EmptyChart2                   =  98,
// 				IIx_AddChartItem                  =  99,
// 				IIx_SetRealDataCode               = 100,
// 				IIx_AddPacketRQ                   = 101,
// 				IIx_SetPacketDataRQ               = 102,
// 				IIx_AddChartItemRQ                = 103,
// 				IIx_SetCurrentRQ                  = 104,
// 				IIx_RemoveGraphRQ                 = 105,
// 				IIx_SetResetTotalCountWhileDraw   = 106,
// 				IIx_SetMultiItemMode              = 107,
// 				IIx_ChangeGraphDrawingData        = 108,
// 				IIx_ChangeGraphTitle              = 109,
// 				IIx_AddChartAllBlock              = 110,
// 				IIx_ChangeGraphPropertyAtOnce     = 111,
// 				IIx_ShowGraphDataDrawingData      = 112,
// 				IIx_ShowSelEnvironmentDlg         = 113,
// 				IIx_GetVertScaleGroupCount        = 114,
// 				IIx_nNumericalInquiryOption       = 115,
// 				IIx_SaveandOpenFromAnalToolFile   = 116,
// 				IIx_UseDummyPacketData            = 117,
// 				IIx_ChangeVertScaleMinMaxType     = 118,
// 				IIx_nRButtonMenuType              = 119,
// 				IIx_SetAvgUnitPrice               = 120,
// 				IIx_GetData                       = 121,
// 				IIx_GetPacketCount                = 122,
// 				IIx_GetPacketIndex                = 123,
// 				IIx_SetPacketData2                = 124,
// 				IIx_AddPopupMenuItem              = 125,
// 				IIx_ActionPopupMenuItem           = 126,
// 				IIx_SetGraphColor                 = 127,
// 				IIx_ChangeGraphColor              = 128,
// 				IIx_SetDrawBaseLine               = 129,
// 				IIx_GetPacketNearIndex            = 130,
// 				IIx_GetPacketData2                = 131,
// 				IIx_FindRQ                        = 132,
// 				IIx_NNumericalInquiryOption       = 133,
// 				IIx_BEnableIndicatorCalculation   = 134,
// 				IIx_BWholeView                    = 135,
// 				IIx_NRButtonMenuType              = 136,
// 		*/
// 		//<-- 2009.11.16월 KTB포팅버전.
// 
// 		//--> 2009.11.16월 솔로몬에 적용해서 잘 돌아가는 버전.
// 				IIx_SetBaseDesk                   =  92,
// 				IIx_GetBase                       =  93,
// 				IIx_AddGraph                      = 141,
// 				IIx_AddPacket                     = 142,
// 				IIx_RemovePacket                  = 143,
// 				IIx_GetIndicatorNameList          = 140,
// 				IIx_SetContainerDllInfo           = 144,
// 				IIx_SetChartData                  =  94,
// 				IIx_SetPacketData                 = 145,
// 				IIx_AddChartBlock                 = 102,
// 				IIx_ResetChart                    = 137,
// 				IIx_SetBackgroundColors           = 146,
// 				IIx_SetDrdsAdvise                 = 113,
// 				IIx_AddRealItem                   = 147,
// 				IIx_ShowIndicatorConfigDlg        = 148,
// 				IIx_NOnePageDataCount             =  12,
// 				IIx_StrStartDateOfData            =  83,
// 				IIx_ResetChartCfgWith             = 149,
// 				IIx_EmptyChart                    = 150,
// 				IIx_HasGraph                      = 151,
// 				IIx_RemoveRealItem                = 152,
// 				IIx_SaveandOpenFromFile           = 105,
// 				IIx_ClearChartData                = 100,
// 				IIx_ShowInnerToolBar              = 153,
// 				IIx_ChangeVertScalePosition       = 154,
// 				IIx_GetRowBlockCount              = 155,
// 				IIx_GetColumnBlockCount           = 156,
// 				IIx_ChangeHorzScalePosition       = 136,
// 				IIx_RemoveChart                   = 109,
// 				IIx_SetStartPeriodOfPacket        = 157,
// 				IIx_GetStartPeriodOfPacket        = 158,
// 				IIx_StrUserIndicatorListFileName  =  21,
// 				IIx_StrUserEnvironmentFileName    =  20,
// 				IIx_GetStartEndDateOnView         = 159,
// 				IIx_SetStartEndDateOfView         = 160,
// 				IIx_ScrollToDataOfEnd             = 161,
// 				IIx_ZoomToWithRightFix            = 162,
// 				IIx_ClearTimeMark                 = 163,
// 				IIx_ShowEnvironmentDlg            = 164,
// 				IIx_SetTimeMark                   = 165,
// 				IIx_BOcxAreaNumericalInquiry      =  53,
// 				IIx_OnRunningOneChart             =  84,
// 				IIx_EnableBoundMark               = 167,
// 				IIx_EnableReceivingTimeShare      = 168,
// 				IIx_ChangePacketType              = 169,
// 				IIx_ChangePriceGraphDrawingData   = 171,
// 				IIx_NUseInquiryWithCrossline      =  56,
// 				IIx_BShowPriceRateInquiry         =  57,
// 				IIx_BNormalizedMinuteTimeRule     =   1,
// 				IIx_HasGraphInSpecialBack         = 173,
// 				IIx_InvokeAddIn                   = 175,
// 				IIx_LoadAddIn                     = 174,
// 				IIx_SetDragModeType               = 176,
// 				IIx_SetHtsPath                    = 179,
// 				IIx_SetAllLogScale                = 181,
// 				IIx_GetListViewerData             = 182,
// 				IIx_SetDataIndexByDate            = 183,
// 				IIx_SetRunTimeMode                = 184,
// 				IIx_GetPacketOption               = 185,
// 				IIx_SetPacketOption               = 186,
// 				IIx_SetOutsideCommonInterface     = 187,
// 				IIx_RemoveGraph_Title             = 188,
// 				IIx_RemoveGraph                   = 219,
// 				IIx_GetGraphPacketName            = 189,
// 				IIx_ChangeGraphTitle2             = 190,
// 				IIx_PartitionAllGraph             = 191,
// 				IIx_JoinAllGraph                  = 192,
// 				IIx_SetBSelectTitle               =  -1,
// 				IIx_ChangeAllFunctionName         = 193,
// 				IIx_ChangeIndicatorPacketName     = 194,
// 				IIx_RunEnvironmentDlg             = 195,
// 				IIx_SetIndicatorCondition         = 196,
// 				IIx_SetLogScale                   = 198,
// 				IIx_GetLogScale                   = 199,
// 				IIx_SetHelpMessageRealDataRate    = 202,
// 				IIx_InvokeAddInStr                = 201,
// 				IIx_SetGraphHide3                 = 205,
// 				IIx_SetOnePageDataCount2          = 208,
// 				IIx_SetPacketDataInAdditionPacket = 224,
// 				IIx_SetOnePageDataCount           = 103,
// 				IIx_SetPacketHelpMessage          = 200,
// 				IIx_SetRealData                   = 138,
// 				IIx_PrintChatImage                = 226,
// 				IIx_ExportToExcel                 = 227,
// 				IIx_LoadAddInWithOverExclusive    = 235,
// 				IIx_GetAllProperties2             = 132,
// 				IIx_SetAllProperties2             =  91,
// 				IIx_GetAllProperties3             = 240,
// 				IIx_SetAllProperties3             = 241,
// 				IIx_GetAddInCustomInterface       = 234,
// 				IIx_SetBinTrHelpMsg               = 244,
// 				IIx_SetBinTrDoubleData            = 245,
// 				IIx_SetBinTrStringData            = 246,
// 				IIx_SetBinTrEnd                   = 247,
// 				IIx_ShowIndicatorConfigDlgWithName= 242,
// 				IIx_bEnableIndicatorCalculation   =  89,
// 				IIx_StrChartList                  =  64,
// 				IIx_bWholeView                    =  11,
// 				IIx_EmptyChart2                   = 248,
// 				IIx_AddChartItem                  = 254,
// 				IIx_SetRealDataCode               = 255,
// 				IIx_AddPacketRQ                   = 261,
// 				IIx_SetPacketDataRQ               = 262,
// 				IIx_AddChartItemRQ                = 263,
// 				IIx_SetCurrentRQ                  = 264,
// 				IIx_RemoveGraphRQ                 = 273,
// 				IIx_SetResetTotalCountWhileDraw   = 265,
// 				IIx_SetMultiItemMode              = 267,
// 				IIx_ChangeGraphDrawingData        = 170,
// 				IIx_ChangeGraphTitle              = 107,
// 				IIx_AddChartAllBlock              = 271,
// 				IIx_ChangeGraphPropertyAtOnce     = 272,
// 				IIx_ShowGraphDataDrawingData      = 275,
// 				IIx_ShowSelEnvironmentDlg         = 276,
// 				IIx_GetVertScaleGroupCount        = 277,
// 				IIx_nNumericalInquiryOption       =  54,
// 				IIx_SaveandOpenFromAnalToolFile   = 281,
// 				IIx_UseDummyPacketData            = 282,
// 				IIx_ChangeVertScaleMinMaxType     = 283,
// 				IIx_nRButtonMenuType              =  39,
// 				IIx_SetAvgUnitPrice               = 284,
// 				IIx_GetData                       = 112,
// 				IIx_GetPacketCount                = 285,
// 				IIx_GetPacketIndex                = 215,
// 				IIx_SetPacketData2                = 197,
// 				IIx_AddPopupMenuItem              = 286,
// 				IIx_ActionPopupMenuItem           = 287,
// 				IIx_SetGraphColor                 = 220,
// 				IIx_ChangeGraphColor              = 260,
// 				IIx_SetDrawBaseLine               = 288,
// 				IIx_GetPacketNearIndex            = 216,
// 				IIx_GetPacketData2                = 213,
// 				IIx_FindRQ                        = 289,
// 				IIx_FindRQ                        = 289,
// 				IIx_NNumericalInquiryOption       =  54,
// 				IIx_BEnableIndicatorCalculation   =  89,
// 				IIx_BWholeView                    =  11,
// 				IIx_NRButtonMenuType              =  39,
// 		//<-- 2009.11.16월 솔로몬에 적용해서 잘 돌아가는 버전.
// 				};
// 				//<--090902-alzioyes OCX CLSID 생성.
// 
// 		// 	typedef enum {
// 		// 		IIx_SetBaseDesk,
// 		// 		IIx_GetBase,
// 		// 		IIx_AddGraph,
// 		// 		IIx_AddPacket,
// 		// 		IIx_RemovePacket,
// 		// 		IIx_GetIndicatorNameList,
// 		// 		IIx_SetContainerDllInfo,
// 		// 		IIx_SetChartData,
// 		// 		IIx_SetPacketData,
// 		// 		IIx_AddChartBlock,
// 		// 		IIx_ResetChart,
// 		// 		IIx_SetBackgroundColors,
// 		// 		IIx_SetDrdsAdvise,
// 		// 		IIx_AddRealItem,
// 		// 		IIx_ShowIndicatorConfigDlg,
// 		// 		IIx_NOnePageDataCount,
// 		// 		IIx_StrStartDateOfData,
// 		// 		IIx_ResetChartCfgWith,
// 		// 		IIx_EmptyChart,
// 		// 		IIx_HasGraph,
// 		// 		IIx_RemoveRealItem,
// 		// 		IIx_SaveandOpenFromFile,
// 		// 		IIx_ClearChartData,
// 		// 		IIx_ShowInnerToolBar,
// 		// 		IIx_ChangeVertScalePosition,
// 		// 		IIx_GetRowBlockCount,
// 		// 		IIx_GetColumnBlockCount,
// 		// 		IIx_ChangeHorzScalePosition,
// 		// 		IIx_RemoveChart,
// 		// 		IIx_SetStartPeriodOfPacket,
// 		// 		IIx_GetStartPeriodOfPacket,
// 		// 		IIx_StrUserIndicatorListFileName,
// 		// 		IIx_StrUserEnvironmentFileName,
// 		// 		IIx_GetStartEndDateOnView,
// 		// 		IIx_SetStartEndDateOfView,
// 		// 		IIx_ScrollToDataOfEnd,
// 		// 		IIx_ZoomToWithRightFix,
// 		// 		IIx_ClearTimeMark,
// 		// 		IIx_ShowEnvironmentDlg,
// 		// 		IIx_SetTimeMark,
// 		// 		IIx_BOcxAreaNumericalInquiry,
// 		// 		IIx_OnRunningOneChart,
// 		// 		IIx_EnableBoundMark,
// 		// 		IIx_EnableReceivingTimeShare,
// 		// 		IIx_ChangePacketType,
// 		// 		IIx_ChangePriceGraphDrawingData,
// 		// 		IIx_NUseInquiryWithCrossline,
// 		// 		IIx_BShowPriceRateInquiry,
// 		// 		IIx_BNormalizedMinuteTimeRule,
// 		// 		IIx_HasGraphInSpecialBack,
// 		// 		IIx_InvokeAddIn,
// 		// 		IIx_LoadAddIn,
// 		// 		IIx_SetDragModeType,
// 		// 		IIx_SetHtsPath,
// 		// 		IIx_SetAllLogScale,
// 		// 		IIx_GetListViewerData,
// 		// 		IIx_SetDataIndexByDate,
// 		// 		IIx_SetRunTimeMode,				//2005. 07. 15 이후 추가 
// 		// 		IIx_GetPacketOption,
// 		// 		IIx_SetPacketOption,
// 		// 		IIx_SetOutsideCommonInterface,
// 		// 		IIx_RemoveGraph_Title,
// 		// 		IIx_RemoveGraph,
// 		// 		IIx_GetGraphPacketName,
// 		// 		IIx_ChangeGraphTitle2,
// 		// 		IIx_PartitionAllGraph,
// 		// 		IIx_JoinAllGraph,
// 		// 		IIx_SetBSelectTitle,
// 		// 		IIx_ChangeAllFunctionName,
// 		// 		IIx_ChangeIndicatorPacketName,
// 		// 		IIx_RunEnvironmentDlg,
// 		// 		IIx_SetIndicatorCondition,
// 		// 		IIx_SetLogScale,
// 		// 		IIx_GetLogScale,
// 		// 		IIx_SetHelpMessageRealDataRate,
// 		// 		IIx_InvokeAddInStr,
// 		// 		IIx_SetGraphHide3,
// 		// 		IIx_SetOnePageDataCount2,
// 		// 		IIx_SetPacketDataInAdditionPacket,
// 		// 		IIx_SetOnePageDataCount,
// 		// 		IIx_SetPacketHelpMessage,
// 		// 		IIx_SetRealData,
// 		// 		IIx_PrintChatImage,
// 		// 		IIx_ExportToExcel,
// 		// 		IIx_LoadAddInWithOverExclusive,
// 		// 		IIx_GetAllProperties2,
// 		// 		IIx_SetAllProperties2,
// 		// 		IIx_GetAllProperties3,
// 		// 		IIx_SetAllProperties3,
// 		// 		IIx_GetAddInCustomInterface,
// 		// 		IIx_SetBinTrHelpMsg,
// 		// 		IIx_SetBinTrDoubleData,
// 		// 		IIx_SetBinTrStringData,
// 		// 		IIx_SetBinTrEnd,
// 		// 		IIx_ShowIndicatorConfigDlgWithName,
// 		// 		IIx_BEnableIndicatorCalculation,
// 		// 		IIx_StrChartList,
// 		// 		IIx_BWholeView,
// 		// 		IIx_EmptyChart2,
// 		// 		IIx_AddChartItem,		// 복수종목에 사용되는 인터페이스 : 복수종목 - ojtaso (20070206)
// 		// 		IIx_SetRealDataCode,	// 복수종목에 사용되는 인터페이스 : 복수종목 - ojtaso (20070206)
// 		// 		IIx_AddPacketRQ,		// 복수종목 불러오기 : 복수종목 - ojtaso (20070514)
// 		// 		IIx_SetPacketDataRQ,	// 복수종목 불러오기 : 복수종목 - ojtaso (20070514)
// 		// 		IIx_AddChartItemRQ,		// 복수종목 불러오기 : 복수종목 - ojtaso (20070514)
// 		// 		IIx_SetCurrentRQ,		// 복수종목 불러오기 : 복수종목 - ojtaso (20070514)
// 		// 		IIx_RemoveGraphRQ,		// RQ로 차트제거.
// 		// 		IIx_SetResetTotalCountWhileDraw,		// xScaleManager : xScaleManager - ojtaso (20070529)
// 		// 		IIx_SetMultiItemMode,	//복수종목을 사용할지 : 복수종목 - ojtaso (20070904)
// 		// 		IIx_ChangeGraphDrawingData,
// 		// 		IIx_ChangeGraphTitle,
// 		// 		IIx_AddChartAllBlock,	// 모든 RQ의 그래프의 차트 변경 - ojtaso (20080516)
// 		// 		IIx_ChangeGraphPropertyAtOnce,	// 차트속성변경.
// 		// 		IIx_ShowGraphDataDrawingData,	// 현재가표시여부 속성변경.
// 		// 		IIx_ShowSelEnvironmentDlg,
// 		// 		IIx_GetVertScaleGroupCount,		// 현재 마지막 VertScaleGroup Index
// 		// 		IIx_NNumericalInquiryOption,
// 		// 		IIx_SaveandOpenFromAnalToolFile,	// 분석툴 종목별 저장 - ojtaso (20080728)
// 		// 		IIx_UseDummyPacketData,				// 복수종목 TR없는 패킷에 처음 Real 처리 수정 - ojtaso (20080804)
// 		// 		IIx_ChangeVertScaleMinMaxType,		// 세로스케일 변경가능한 Method 추가 - ojtaso (20081013)
// 		// 		IIx_NRButtonMenuType,
// 		// 		IIx_SetAvgUnitPrice,	// 평균단가 세팅 - ojtaso (20081104)
// 		// 		IIx_GetData,
// 		// 		IIx_GetPacketCount,		// 지정한 패킷의 크기를 구함 - ojtaso (20081106)
// 		// 		IIx_GetPacketIndex,
// 		// 		IIx_SetPacketData2,
// 		// 		IIx_AddPopupMenuItem,		// HMC 플랫폼 팝업메뉴 처리 - ojtaso (20081113)
// 		// 		IIx_ActionPopupMenuItem,		// HMC 플랫폼 팝업메뉴 처리 - ojtaso (20081113)
// 		// 		IIx_SetGraphColor,
// 		// 		IIx_ChangeGraphColor,
// 		// 		IIx_SetDrawBaseLine,			// BaseLine Draw 여부 - ojtaso (20081204)
// 		// 		IIx_GetPacketNearIndex,
// 		// 		IIx_GetPacketData2,
// 		// 		IIx_FindRQ
// 		// 	};
// 			// 가로 scale 위치
// 			enum HORZSCALEPOSITION
// 			{
// 				HORZ_TOP,
// 				HORZ_BOTTOM,
// 				HORZ_BOTH,
// 				HORZ_HIDE,
// 				HORZ_NONE
// 			};
// 			
// 			// 세로 scale 위치
// 			enum VERTSCALEPOSITION
// 			{
// 				VERT_LEFT,
// 				VERT_RIGHT,
// 				VERT_BOTH,
// 				VERT_NONE
// 			};
// 
// 			long GetNNumericalInquiryOption();
// 			void SetNNumericalInquiryOption(long);
// 			CString GetStrGlobalSharedList();
// 			void SetStrGlobalSharedList(LPCTSTR);
// 			void SetStrStartDateOfData(LPCTSTR);
// 			
// 			void SetOnRunningOneChart(BOOL);
// 			BOOL GetBDoesUseSkinColor();
// 			void SetBDoesUseSkinColor(BOOL);
// 
// 		// Operations
// 		public:
// 			void SetBaseDesk(long lKey);
// 			long GetBase(LPCTSTR szKey);
// 			void AddGraph(short nRow, short nColumn, short nVertScaleGroup, LPCTSTR szGraphOption, BOOL bCreateBlock, BOOL bCreateVertScaleGroup, BOOL bUseAutoScale);
// 			void AddPacket(LPCTSTR szPacketOption);
// 			void RemovePacket(LPCTSTR szPacketName);
// 			CString GetIndicatorNameList(LPCTSTR p_strGroup);
// 			void SetContainerDllInfo(long p_lDllWnd, short p_nID);
// 			short SetChartData(long pChartData, short nCount, short nType);
// 			BOOL SetPacketData(LPCTSTR szPacketName, long szData, long nLength, BOOL bReset);
// 			BOOL AddChartBlock(LPCTSTR strChartName);
// 			// 모든 RQ의 그래프의 차트 변경 - ojtaso (20080516)
// 			BOOL AddChartAllBlock(LPCTSTR strChartName);
// 			void ChangeGraphPropertyAtOnce(LPCTSTR lpszRQ, LPCTSTR lpszTargetTitle, LPCTSTR lpszNewTitle, short nGraphType, short nGraphStyle, short nDrawStyle, LPCTSTR lpszColors, short nThickness1, short nThickness2, short nThickness3);
// 
// 			BOOL ResetChart();
// 			void SetBackgroundColors(unsigned long p_rgbBlockArea, unsigned long p_rgbScaleArea);
// 			BOOL SetDrdsAdvise(BOOL bOnAdvise);
// 			void AddRealItem(LPCTSTR szRealInfo);
// 			void ShowIndicatorConfigDlg();
// 			long GetNOnePageDataCount();
// 			void SetNOnePageDataCount(long propVal);
// 			CString GetStrStartDateOfData();
// 			void ResetChartCfgWith(short p_nIndex);
// 			BOOL EmptyChart(BOOL bIsDeleteAllPacket, BOOL bIsDefault);	// JSR 20060119 Modify (From ResetOCX())
// 			BOOL HasGraph(LPCTSTR p_szGraphName);
// 			void RemoveRealItem(LPCTSTR szRealInfo);
// 			BOOL SaveandOpenFromFile(LPCTSTR strOpenFileName, LPCTSTR strSaveFileName, BOOL bOpenOption, BOOL bSaveOption);
// 			short ClearChartData(short nOption);
// 			void ShowInnerToolBar(BOOL p_bShow);
// 			BOOL ChangeVertScalePosition(short nScalePosition, short nRowIndex, short nColumnIndex, short nVSGroupIndex);
// 			short GetRowBlockCount();
// 			short GetColumnBlockCount();
// 			BOOL ChangeHorzScalePosition(short nScalePosition, short nRowIndex, short nColumnIndex);
// 			BOOL RemoveChart(LPCTSTR strChartName);
// 			BOOL SetStartPeriodOfPacket(LPCTSTR p_szPacketName, long p_lStartPeriod, long p_bAddSpace);
// 			long GetStartPeriodOfPacket(LPCTSTR p_szPacketName);
// 			void SetStrUserIndicatorListFileName(LPCTSTR propVal);
// 			void SetStrUserEnvironmentFileName(LPCTSTR propVal);
// 			BOOL GetStartEndDateOnView(double* p_pStartDate, double* p_pEndDate);
// 			BOOL SetStartEndDateOfView(double p_dStartDate, double p_dEndDate);
// 			BOOL ScrollToDataOfEnd(double p_dData);
// 			short ZoomToWithRightFix(short p_nZoomValue, BOOL p_bWithRightFix);
// 			void ClearTimeMark();
// 			void ShowEnvironmentDlg();
// 			void ShowSelEnvironmentDlg(short nPage);
// 			void SetTimeMark(LPCTSTR p_szMarkTime, BOOL p_bWithScroll);
// 			void SetBOcxAreaNumericalInquiry(BOOL propVal);
// 			BOOL GetOnRunningOneChart();
// 			void EnableBoundMark(BOOL p_bEnable);
// 			void EnableReceivingTimeShare(BOOL p_bEnable);
// 			BOOL ChangePacketType(LPCTSTR p_szPacketName, LPCTSTR p_szPacketType);  
// 			BOOL ChangePriceGraphDrawingData(BOOL p_bLowHigh, BOOL p_bLowCur, BOOL p_bHighCur, BOOL p_bPrevCur, short p_nCurData, short p_nDefaultType);
// 			void SetNUseInquiryWithCrossline(short propVal);
// 			short GetNUseInquiryWithCrossline();
// 			BOOL GetBShowPriceRateInquiry();
// 			void SetBShowPriceRateInquiry(BOOL propVal);
// 			BOOL GetBNormalizedMinuteTimeRule();
// 			void SetBNormalizedMinuteTimeRule(BOOL);
// 			BOOL HasGraphInSpecialBack(LPCTSTR p_szGraphName);
// 			BOOL InvokeAddIn(LPCTSTR p_szAddInDllName, short p_nCommandType, long p_lData);
// 			BOOL LoadAddIn(LPCTSTR p_szAddInDllName);
// 			void SetDragModeType(short p_nDragModeType);
// 			void SetHtsPath(LPCTSTR pcszHtsPath);	
// 			void SetAllLogScale(BOOL bLogScale);
// 
// 			//2005. 06. 28 add ===================================================================
// 			//데이터 리스트 뷰에 보일 값을 조회한다.
// 			void GetListViewerData(	BSTR* bstrTitle,
// 									BSTR* bstrHorzScale,
// 									BSTR* bstrPacketNamesPerBlock,
// 									BSTR* bstrPacketNames, 
// 									BSTR* bstrSaveFilePath,
// 									BOOL* bViewPacketSequence,
// 									long* lpPacketList); 
// 			//chart에 보이는 범위를 해당 매개변수의 값으로 셋한다. YYYYMMDDHHMMSS 형태로 넘긴다.
// 			void SetDataIndexByDate(LPCTSTR pcszStartDate, LPCTSTR pcszEndDate); 
// 
// 			//2005. 07. 15 추가 =========================================================================		
// 			void	SetRunTimeMode(BOOL bRunTimeMode);
// 			CString GetPacketOption();
// 			void	SetPacketOption(LPCTSTR strPacketOption);
// 			void	SetOutsideCommonInterface(long lpOutsideCommonInterface);
// 			//===========================================================================================
// 			void	SetBSelectTitle(BOOL);
// 
// 
// 			//2005. 07. 19 추가 =========================================================================	
// 			BOOL	RemoveGraph_Title(short nRowIndex, short nColumnIndex, LPCTSTR szGraphTitle, BOOL bIsOnlyNoTRData, BOOL bIsAutoHorzScalePosition);
// 			BOOL	RemoveGraph(short nRowIndex, short nColumnIndex, LPCTSTR strGraphTitle);
// 
// 			CString GetGraphPacketName(short nRowIndex, short nColumnIndex, LPCTSTR szGraphTitle);
// 			BOOL	ChangeGraphTitle2(LPCTSTR szTargetTitle, LPCTSTR szSourceTitle);
// 			BOOL	PartitionAllGraph();
// 			BOOL	JoinAllGraph(BOOL bIsOneVertScaleGroup);
// 			//===========================================================================================
// 
// 
// 			//2005. 07. 27 추가 =========================================================================
// 			// 비교차트 분할비교<->중첩비교<->누적등락률 중첩비교 간 전환을 알리는 Method
// 			BOOL ChangeAllFunctionName(LPCTSTR szTargetFunctionName, LPCTSTR szSourceFunctionName, BOOL bKeepOldGraphColor);
// 			//===========================================================================================
// 
// 			//2005. 08. 11 추가 =========================================================================	
// 			BOOL ChangeIndicatorPacketName(LPCTSTR strIndicatorName, short nSubGraphIndex, LPCTSTR strNewPacketName);
// 			void RunEnvironmentDlg(short nOption);// 환경 설정 창 띄우는 
// 			BOOL SetIndicatorCondition(LPCTSTR strIndicatorName, short nConditionType, short nConditionIndex, short dValue, BOOL bReCalculate);
// 			//===========================================================================================
// 			
// 
// 
// 			//2005. 08. 23 추가 =========================================================================	
// 			BOOL SetLogScale(LPCTSTR strIndicatorName, BOOL bLogScale);
// 			BOOL GetLogScale(LPCTSTR strIndicatorName);	
// 			//===========================================================================================
// 
// 
// 			//2005. 09. 06 추가 =========================================================================
// 			//비교차트에 리얼 처리 방식이 바뀌어서 호출되는 메소드 
// 			// 나누기 100을 하라는 의미
// 			BOOL SetHelpMessageRealDataRate(LPCTSTR strHelpMessageData, BOOL bIsRemove);
// 			//===========================================================================================
// 
// 			//2005. 09. 08 추가 =========================================================================
// 			BOOL InvokeAddInStr(LPCTSTR p_szAddInDllName, LPCTSTR p_szCommandName, LPCTSTR p_szData);
// 			//===========================================================================================
// 
// 			//2005. 09. 14 추가 =========================================================================
// 			//비교차트에서 체크박스로 종목 해제시 화면에만 안 보이도록 처리.
// 			BOOL SetGraphHide3(LPCTSTR strTitle, BOOL bIsHide);
// 			//===========================================================================================
// 
// 
// 			//2005. 11. 02 추가 =========================================================================
// 			//주 차트에서 차트 여백을 포함한 형태(bIncludeRightMargin로 판단)로 보이게 하기위해..
// 			void SetOnePageDataCount2(long nOnePageDataCount, BOOL bIncludeRightMargin);
// 			//===========================================================================================
// 
// 			//2005. 11. 09 추가 =========================================================================
// 			//시장 지표 TR을 차트에 보내기 위해 추가 
// 			BOOL SetPacketDataInAdditionPacket(LPCTSTR szPacketName, long szData, long nLength, BOOL bReset);
// 			//===========================================================================================
// 
// 			//2005. 11. 09 추가 =========================================================================
// 			//페이지 데이터 카운트 수를 변경시킨다.
// 			//기존 SetNOnePageDataCount를 SetOnePageDataCount로 적용
// 			void SetOnePageDataCount(long nOnePageDataCount);
// 			//===========================================================================================
// 
// 
// 			//2005. 12. 06 추가 =========================================================================
// 			//복기 리얼 처리 
// 			BOOL SetPacketHelpMessage(LPCTSTR strHelpMsg, BOOL bIsAllRemove);
// 			void SetRealData(LPCTSTR strPacketName, double dData, short nOption);	
// 			//===========================================================================================
// 			//2006. 04. 05 추가 =========================================================================
// 			void PrintChatImage();
// 			void ExportToExcel();
// 			//===========================================================================================
// 
// 			//===========================================================================================
// 			// 2006. 08. 24 추가
// 			BOOL LoadAddInWithOverExclusive(LPCTSTR p_szAddInName);
// 			long GetAllProperties2(long lpData);
// 			long SetAllProperties2(long lpData);	
// 			long GetAllProperties3(long p_lIPropertyMap);
// 			long SetAllProperties3(long p_lIPropertyMap);
// 			LPUNKNOWN GetAddInCustomInterface(LPCTSTR p_szAddInName);
// 			//===========================================================================================
// 
// 			//===========================================================================================
// 			// 2006. 10. 27 추가
// 			BOOL ShowIndicatorConfigDlgWithName(LPCTSTR p_szIndicatorName);
// 			//===========================================================================================
// 
// 			//===========================================================================================
// 			// 2006. 12. 12 추가
// 			BOOL GetBEnableIndicatorCalculation();
// 			void SetBEnableIndicatorCalculation(BOOL propVal);
// 			CString GetStrChartList();
// 			void SetStrChartList(LPCTSTR);
// 			BOOL GetBWholeView();
// 			void SetBWholeView(BOOL propVal);
// 			short GetNRButtonMenuType();
// 			void SetNRButtonMenuType(short propVal);
// 			//===========================================================================================
// 			BOOL EmptyChart2(LPCTSTR p_szChartList, BOOL p_bIsDeleteAllPacket, BOOL p_bIsDefault);
// 			// 복수종목에 사용되는 인터페이스 : 복수종목 - ojtaso (20070206)
// 			CString AddChartItem(LPCTSTR lpszItemCode, LPCTSTR lpszItemName, BOOL bBuiltChart);
// 			void SetRealDataCode(LPCTSTR strCode, LPCTSTR strPacketName, double dData, short nOption);
// 
// 			// 복수종목 불러오기 : 복수종목 - ojtaso (20070514)
// 			void AddPacketRQ(LPCTSTR lpszRQ, LPCTSTR lpszPacketOption);
// 			BOOL SetPacketDataRQ(LPCTSTR lpszRQ, LPCTSTR lpszPacketName, long nData, long nLength, BOOL bReset);
// 			BOOL AddChartItemRQ(LPCTSTR lpszRQ, LPCTSTR lpszItemCode, LPCTSTR lpszItemName);
// 			void SetCurrentRQ(LPCTSTR lpszRQ);
// 			BOOL RemoveGraphRQ(LPCTSTR lpszRQ, LPCTSTR lpszTitle);
// 			// xScaleManager : xScaleManager - ojtaso (20070529)
// 			void SetResetTotalCountWhileDraw(BOOL bReset);
// 			// 차트DLL에서 복수종목을 사용할지 : 복수종목 - ojtaso (20070904)
// 			void SetMultiItemMode(BOOL bMultiItem);
// 
// 			BOOL ChangeGraphDrawingData(LPCTSTR p_szGraphName, BOOL p_bLowHigh, BOOL p_bLowCur, BOOL p_bHighCur, BOOL p_bPrevCur, short p_nCurData);
// 			BOOL ChangeGraphTitle(short nRowIndex, short nColumnIndex, short nGraphIndex, LPCTSTR strNewTitle);
// 
// 			void SetBAddGraphMenuShow(BOOL);	//Menu셋팅
// 
// 			// 현재가 표시여부 변경
// 			// bShow : LC/HC/LH 보여줄지 여부
// 			// nShowType : 그래프 yScal관련 보여줄지 여부.
// 			//		0 - Hide
// 			//		1 - 현재가 + 전일종가대비
// 			//		2 - 현재가 + 이전종가대비
// 			//		3 - 현재가
// 			//		4 - 화면상 종가
// 			BOOL ShowGraphDataDrawingData(LPCTSTR lpszRQ, LPCTSTR lpszIndicatorName, BOOL bShow, short nShowType);
// 
// 			// 현재 마지막 VertScaleGroup Index
// 			long GetVertScaleGroupCount(short nRow, short nColumn);
// 			
// 			// 분석툴 종목별 저장 - ojtaso (20080728)
// 			BOOL SaveandOpenFromAnalToolFile(LPCTSTR lpszOpenFileName, LPCTSTR lpszSaveFileName, BOOL bOpenOption, BOOL bSaveOption);
// 			// 복수종목 TR없는 패킷에 처음 Real 처리 수정 - ojtaso (20080804)
// 			void UseDummyPacketData(BOOL bUse);
// 			// 세로스케일 변경가능한 Method 추가 - ojtaso (20081013)
// 			void ChangeVertScaleMinMaxType(short nRowIndex, short nColumnIndex, short nVertScaleGroupIndex, short nScaleType, double dMinValue, double dMaxValue);
// 			// 평균단가 세팅 - ojtaso (20081104)
// 			void SetAvgUnitPrice(double dAvgPrice);
// 			// 지정한 패킷의 크기를 구함 - ojtaso (20081106)
// 			long GetPacketCount(LPCTSTR strPacketName);
// 
// 			CString GetData(LPCTSTR strPacketName, short nDataIndex);
// 			short GetPacketIndex(LPCTSTR szPacketName, double dKeyValue);
// 			BOOL SetPacketData2(LPCTSTR strPacketName, LPCTSTR strPacketType, LPCTSTR strPacketData, short nDataCount, BOOL bReCalculate);
// 
// 			// HMC 플랫폼 팝업메뉴 처리 - ojtaso (20081113)
// 			void AddPopupMenuItem(long pPopupMeun, long ptPoint);
// 			void ActionPopupMenuItem(long nMenuID);
// 
// 			BOOL SetGraphColor(short nRowIndex, short nColumnIndex, short nVertScaleGroupIndex, short nGraphIndex, short nSubGraphIndex, LPCTSTR strNewColor);
// 			BOOL ChangeGraphColor(LPCTSTR p_szGraphTitle, LPCTSTR p_szColors);
// 
// 			// BaseLine Draw 여부 - ojtaso (20081204)
// 			void SetDrawBaseLine(BOOL bDraw);
// 			short GetPacketNearIndex(LPCTSTR szPacketName, double dKeyValue);
// 
// 			CString GetPacketData2(LPCTSTR strPacketName, short nDataIndex, BOOL bIsFullDataSize);
// 
// 			BOOL FindRQ(LPCTSTR lpszRQ);
// 
// 		};
// 
// 	#endif
// // 
//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SMSCHART_H__D9F7C9F1_1144_42FC_988A_E5BD1AD284C6__INCLUDED_)
