#ifndef WM_AXUSER
#define WM_AXUSER		WM_USER+10000
#define	WM_AXDROPITEM	WM_AXUSER+1
#define	WM_AXSETCTRL	WM_AXUSER+2
#define	WM_AXGETCTRL	WM_AXUSER+3
#define	WM_AXDELKIND	WM_AXUSER+4
#define	WM_AXRELOAD		WM_AXUSER+5

#define	WM_AXRMOUSE		WM_AXUSER+6
#define	WM_AXADDUSER	WM_AXUSER+7
#define	WM_AXDELUSER	WM_AXUSER+8
#define	WM_AXGETUGRP	WM_AXUSER+9
#define	WM_AXADDGRP		WM_AXUSER+10
#define WM_AXITEMCLICK	WM_AXUSER+11
#endif
