// CX_griddata.idl : CX_griddata.dll의 형식 라이브러리 소스입니다.
// 이 파일은 MIDL 컴파일러에 의해 처리되어
// 형식 라이브러리(CX_griddata.tlb)를 생성합니다.

#include "olectl.h"
[ uuid(F4DF8973-5A75-4C66-BD86-06E4DF518BB4), version(1.0) ]
library CX_griddata
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");
	//  Controlwnd의 기본 디스패치 인터페이스입니다.
		
	[ uuid(ED3FB8E8-9CDF-4E46-8570-7E5E46469023) ]
	dispinterface IControlwnd
	{
		properties:
			[id(2)] BSTR JCode;
	methods:
			[id(1)] void SendData(void);
			[id(3)] void SetMapName(BSTR strmap);
			[id(4)] BSTR GetOubData(void);
			[id(5)] BSTR GetAlertData(void);
			[id(6)] void SetSearchDate(BSTR sdate, BSTR edate);
			[id(7)] void SetMandate(BSTR sdate, BSTR edate);
			[id(8)] BSTR GetGroupCombo(BSTR edate);
			[id(9)] void SetGroupByName(BSTR group);
			[id(10)] void SetbInter(BSTR binter);
			[id(11)] void Setsuik(BSTR bsuik);
			[id(12)] void Setmyhoga(BSTR bmyhoga);
			[id(13)] void Setcodetype(BSTR type);
			[id(14)] void Sethogatype(BSTR typehoga);
			[id(15)] BSTR GetRealDate(void);
			[id(16)] BSTR GetCodeInGroup(BSTR group);
			[id(17)] void MessangerMemoPop(BSTR userid);
			[id(18)] void SetSync(BSTR sync);
			[id(19)] BSTR GetGrouptype(BSTR groupname);
	};

	//  Controlwnd의 클래스 정보입니다.

	[ uuid(F5DD692D-7248-4D86-BC4D-6DB1F040CD3A) ]
	coclass Controlwnd
	{
		[default] dispinterface IControlwnd;
	};
};
