// CX_ANITICKER.idl: CX_ANITICKER.dll의 형식 라이브러리 소스
// 이 파일은 MIDL 컴파일러에 의해 처리되어
// 형식 라이브러리(CX_ANITICKER.tlb)입니다.

[ uuid(5d7c0677-b532-4579-be2f-fdab54ca76be), version(1.0) ]
library CXANITICKER
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");
};
