// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "koscomchart.h"

/////////////////////////////////////////////////////////////////////////////
// CKoscomChart

IMPLEMENT_DYNCREATE(CKoscomChart, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CKoscomChart properties

BOOL CKoscomChart::GetEnabled()
{
	BOOL result;
	GetProperty(DISPID_ENABLED, VT_BOOL, (void*)&result);
	return result;
}

void CKoscomChart::SetEnabled(BOOL propVal)
{
	SetProperty(DISPID_ENABLED, VT_BOOL, propVal);
}

OLE_HANDLE CKoscomChart::GetHWnd()
{
	OLE_HANDLE result;
	GetProperty(DISPID_HWND, VT_I4, (void*)&result);
	return result;
}

void CKoscomChart::SetHWnd(OLE_HANDLE propVal)
{
	SetProperty(DISPID_HWND, VT_I4, propVal);
}

long CKoscomChart::GetNNumericalInquiryOption()
{
	long result;
	GetProperty(0x36, VT_I4, (void*)&result);
	return result;
}

void CKoscomChart::SetNNumericalInquiryOption(long propVal)
{
	SetProperty(0x36, VT_I4, propVal);
}

CString CKoscomChart::GetStrGlobalSharedList()
{
	CString result;
	GetProperty(0x37, VT_BSTR, (void*)&result);
	return result;
}

void CKoscomChart::SetStrGlobalSharedList(LPCTSTR propVal)
{
	SetProperty(0x37, VT_BSTR, propVal);
}

void CKoscomChart::SetStrStartDateOfData(LPCTSTR propVal)
{
	SetProperty(0x4d, VT_BSTR, propVal);
}

void CKoscomChart::SetOnRunningOneChart(BOOL propVal)
{
	SetProperty(0x4e, VT_BOOL, propVal);
}

BOOL CKoscomChart::GetBDoesUseSkinColor()
{
	BOOL result;
	GetProperty(0x3a, VT_BOOL, (void*)&result);
	return result;
}

void CKoscomChart::SetBDoesUseSkinColor(BOOL propVal)
{
	SetProperty(0x3a, VT_BOOL, propVal);
}
/*
/////////////////////////////////////////////////////////////////////////////
// CKoscomChart operations
BOOL CKoscomChart::SetAllProperties2(long dwData)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x4f, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		dwData);
	return result;
}

void CKoscomChart::SetBaseDesk(long lKey)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x50, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 lKey);
}

long CKoscomChart::GetBase(LPCTSTR szKey)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x51, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szKey);
	return result;
}

short CKoscomChart::SetChartData(long pChartData, short nCount, short nType)
{
	short result;
	static BYTE parms[] =
		VTS_I4 VTS_I2 VTS_I2;
	InvokeHelper(0x52, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		pChartData, nCount, nType);
	return result;
}

short CKoscomChart::SetChartDataStr(LPCTSTR szChartData, short nCount, short nType)
{
	short result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2 VTS_I2;
	InvokeHelper(0x53, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		szChartData, nCount, nType);
	return result;
}

short CKoscomChart::testGetPacketdatasize(LPCTSTR pIn)
{
	short result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x54, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		pIn);
	return result;
}

void CKoscomChart::testLoadAnalysisTools(short nToolOption, short nOption)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2;
	InvokeHelper(0x55, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nToolOption, nOption);
}

void CKoscomChart::MakeSaveShortKey(LPCTSTR szFileName, short nFlag)
{
	static BYTE parms[] =
		VTS_BSTR VTS_I2;
	InvokeHelper(0x56, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 szFileName, nFlag);
}

short CKoscomChart::ChangeChart(short nBlockRowPosition, short nBlockColumnPosition, LPCTSTR strGraphTitle, LPCTSTR strIndicatorName, LPCTSTR strPacketName, LPCTSTR strGraphType, LPCTSTR strGraphStyle, short nLineWidth, unsigned long clrLineColor)
{
	short result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_I2 VTS_I4;
	InvokeHelper(0x57, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		nBlockRowPosition, nBlockColumnPosition, strGraphTitle, strIndicatorName, strPacketName, strGraphType, strGraphStyle, nLineWidth, clrLineColor);
	return result;
}

short CKoscomChart::ClearChartData(short nOption)
{
	short result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x58, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		nOption);
	return result;
}

short CKoscomChart::SetGraphHide(short nRow, short nColumn, LPCTSTR strTitle, BOOL bHide)
{
	short result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_BSTR VTS_BOOL;
	InvokeHelper(0x59, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		nRow, nColumn, strTitle, bHide);
	return result;
}

BOOL CKoscomChart::AddChartBlock(LPCTSTR strChartName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x5a, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strChartName);
	return result;
}



long CKoscomChart::GetOnePageDataCount()
{
	long result;
	InvokeHelper(0x5c, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

BOOL CKoscomChart::SaveandOpenFromFile(LPCTSTR strOpenFileName, LPCTSTR strSaveFileName, BOOL bOpenOption, BOOL bSaveOption)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BOOL VTS_BOOL;
	InvokeHelper(0x5d, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strOpenFileName, strSaveFileName, bOpenOption, bSaveOption);
	return result;
}

BOOL CKoscomChart::JoinandDevisionforCompareChart(long nRowCount, long nColumnCount, BOOL bJoin)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_BOOL;
	InvokeHelper(0x5e, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		nRowCount, nColumnCount, bJoin);
	return result;
}

BOOL CKoscomChart::ChangeGraphTitle(short nRowIndex, short nColumnIndex, short nGraphIndex, LPCTSTR strNewTitle)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2 VTS_BSTR;
	InvokeHelper(0x5f, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		nRowIndex, nColumnIndex, nGraphIndex, strNewTitle);
	return result;
}

short CKoscomChart::SetChartDataFromFile(LPCTSTR szFileName, short nType)
{
	short result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2;
	InvokeHelper(0x60, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		szFileName, nType);
	return result;
}

BOOL CKoscomChart::RemoveChart(LPCTSTR strChartName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x61, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strChartName);
	return result;
}

BOOL CKoscomChart::ChangeGraphType(LPCTSTR strIndicatorName, LPCTSTR strGraphType, LPCTSTR strGraphStyle, LPCTSTR strPacketNameList, BOOL bRunatOnce)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BOOL;
	InvokeHelper(0x62, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strIndicatorName, strGraphType, strGraphStyle, strPacketNameList, bRunatOnce);
	return result;
}

void CKoscomChart::SetChartAllInfo()
{
	InvokeHelper(0x63, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

CString CKoscomChart::GetData(LPCTSTR strPacketName, short nDataIndex)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2;
	InvokeHelper(0x64, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		strPacketName, nDataIndex);
	return result;
}

BOOL CKoscomChart::SetDrdsAdvise(BOOL bOnAdvise)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x65, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		bOnAdvise);
	return result;
}

short CKoscomChart::GetDataCount()
{
	short result;
	InvokeHelper(0x66, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

BOOL CKoscomChart::ChangeChartItem(LPCTSTR strIndicatorName, short nSubGraphIndex, LPCTSTR strNewTitle, LPCTSTR strNewPacketName, LPCTSTR strNewGraphType, LPCTSTR strNewGraphStyle, short nNewUpLineWidth, short nNewDownLineWidth, short nNewEqualLineWidth, 
		BOOL bRunatOnce)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2 VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_I2 VTS_I2 VTS_I2 VTS_BOOL;
	InvokeHelper(0x67, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strIndicatorName, nSubGraphIndex, strNewTitle, strNewPacketName, strNewGraphType, strNewGraphStyle, nNewUpLineWidth, nNewDownLineWidth, nNewEqualLineWidth, bRunatOnce);
	return result;
}

BOOL CKoscomChart::SetStopLossPrice(BOOL bIsStopLoss, double dStopLossPrice, BOOL bIsProfit, double dProfitPrice)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BOOL VTS_R8 VTS_BOOL VTS_R8;
	InvokeHelper(0x68, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		bIsStopLoss, dStopLossPrice, bIsProfit, dProfitPrice);
	return result;
}

BOOL CKoscomChart::RestoreMinMax(LPCTSTR strPacketName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x69, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strPacketName);
	return result;
}

BOOL CKoscomChart::RestoreMin(LPCTSTR strPacketName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6a, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strPacketName);
	return result;
}

BOOL CKoscomChart::RestorMax(LPCTSTR strPacketName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6b, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strPacketName);
	return result;
}

BOOL CKoscomChart::SetMin(LPCTSTR strPacketName, double dMin)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_R8;
	InvokeHelper(0x6c, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strPacketName, dMin);
	return result;
}

BOOL CKoscomChart::SetMax(LPCTSTR strPacketName, double dMax)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_R8;
	InvokeHelper(0x6d, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strPacketName, dMax);
	return result;
}

BOOL CKoscomChart::SetMinMax(LPCTSTR strPacketName, double dMin, double dMax)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_R8 VTS_R8;
	InvokeHelper(0x6e, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strPacketName, dMin, dMax);
	return result;
}

BOOL CKoscomChart::SetHorzScaleData(short nRowIndex, short nColumnIndex, LPCTSTR strScaleData)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_BSTR;
	InvokeHelper(0x6f, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		nRowIndex, nColumnIndex, strScaleData);
	return result;
}

double CKoscomChart::GetMin(LPCTSTR strPacketName)
{
	double result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x70, DISPATCH_METHOD, VT_R8, (void*)&result, parms,
		strPacketName);
	return result;
}

double CKoscomChart::GetMax(LPCTSTR strPacketName)
{
	double result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x71, DISPATCH_METHOD, VT_R8, (void*)&result, parms,
		strPacketName);
	return result;
}

BOOL CKoscomChart::SetGraphHide2(short nRowIndex, short nColumnIndex, short nVerticalIndex, short nGraphIndex, short nSubGraphIndex, BOOL bHide)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2 VTS_I2 VTS_I2 VTS_BOOL;
	InvokeHelper(0x72, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		nRowIndex, nColumnIndex, nVerticalIndex, nGraphIndex, nSubGraphIndex, bHide);
	return result;
}

BOOL CKoscomChart::ChangeGraphDatas(short nRowIndex, short nColumnIndex, short nVerticalIndex, short nGraphIndex, LPCTSTR strNewIndicatorName, LPCTSTR strNewTitle, LPCTSTR strNewPacketName, LPCTSTR strNewGraphType, LPCTSTR strNewGraphStyle, 
		short nNewUpLineWidth, short nNewDownLineWidth, short nNewEqualLineWidth, BOOL bRunatOnce)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2 VTS_I2 VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_I2 VTS_I2 VTS_I2 VTS_BOOL;
	InvokeHelper(0x73, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		nRowIndex, nColumnIndex, nVerticalIndex, nGraphIndex, strNewIndicatorName, strNewTitle, strNewPacketName, strNewGraphType, strNewGraphStyle, nNewUpLineWidth, nNewDownLineWidth, nNewEqualLineWidth, bRunatOnce);
	return result;
}

void CKoscomChart::SaveandApplyGraphStyle(short nSaveDataType, short nChangeDataType)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2;
	InvokeHelper(0x74, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nSaveDataType, nChangeDataType);
}

void CKoscomChart::SetDataRegionInBlock(short nDataStartIndex)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x75, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nDataStartIndex);
}

void CKoscomChart::SetItemInfo(LPCTSTR lpstrCode, LPCTSTR lpstrName)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x76, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 lpstrCode, lpstrName);
}

void CKoscomChart::AddandDeleteIndicator(LPCTSTR strIndicatorName)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x77, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strIndicatorName);
}

long CKoscomChart::GetAllProperties2(long lpData)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x78, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		lpData);
	return result;
}

long CKoscomChart::GetBasePropIf()
{
	long result;
	InvokeHelper(0x79, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

BOOL CKoscomChart::SetVertScaleData(short nRowIndex, short nColumnIndex, short nVertScaleGroupIndex, LPCTSTR strVertScaleData)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2 VTS_BSTR;
	InvokeHelper(0x7a, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		nRowIndex, nColumnIndex, nVertScaleGroupIndex, strVertScaleData);
	return result;
}

BOOL CKoscomChart::ChangeBlockType(short nBlockType, short nRowCount, short nColumnCount)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2;
	InvokeHelper(0x7b, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		nBlockType, nRowCount, nColumnCount);
	return result;
}

BOOL CKoscomChart::ChangeHorzScalePosition(short nScalePosition, short nRowIndex, short nColumnIndex)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2;
	InvokeHelper(0x7c, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		nScalePosition, nRowIndex, nColumnIndex);
	return result;
}

BOOL CKoscomChart::ResetChart()
{
	BOOL result;
	InvokeHelper(0x7d, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CKoscomChart::SetRealData(LPCTSTR strPacketName, double dData, short nOption)
{
	static BYTE parms[] =
		VTS_BSTR VTS_R8 VTS_I2;
	InvokeHelper(0x7e, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strPacketName, dData, nOption);
}

BOOL CKoscomChart::SetGraphTitle(LPCTSTR strIndicatorName, short nSubGraphIndex, LPCTSTR strNewGraphTitle, BOOL bGraphShowing)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2 VTS_BSTR VTS_BOOL;
	InvokeHelper(0x7f, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strIndicatorName, nSubGraphIndex, strNewGraphTitle, bGraphShowing);
	return result;
}

CString CKoscomChart::GetIndicatorNameList(LPCTSTR p_strGroup)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x80, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		p_strGroup);
	return result;
}

void CKoscomChart::AddGraph(short nRow, short nColumn, short nVertScaleGroup, LPCTSTR szGraphOption, BOOL bCreateBlock, BOOL bCreateVertScaleGroup, BOOL bUseAutoScale)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2 VTS_BSTR VTS_BOOL VTS_BOOL VTS_BOOL;
	InvokeHelper(0x81, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nRow, nColumn, nVertScaleGroup, szGraphOption, bCreateBlock, bCreateVertScaleGroup, bUseAutoScale);
}

void CKoscomChart::AddPacket(LPCTSTR szPacketOption)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x82, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 szPacketOption);
}

void CKoscomChart::RemovePacket(LPCTSTR szPacketName)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x83, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 szPacketName);
}

void CKoscomChart::SetContainerDllInfo(long p_lDllWnd, short p_nID)
{
	static BYTE parms[] =
		VTS_I4 VTS_I2;
	InvokeHelper(0x84, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_lDllWnd, p_nID);
}

BOOL CKoscomChart::SetPacketData(LPCTSTR szPacketName, long szData, long lLength, BOOL bReset)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I4 VTS_BOOL;
	InvokeHelper(0x85, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		szPacketName, szData, lLength, bReset);
	return result;
}

void CKoscomChart::SetBackgroundColors(unsigned long p_rgbBlockArea, unsigned long p_rgbScaleArea)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x86, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_rgbBlockArea, p_rgbScaleArea);
}

void CKoscomChart::AddRealItem(LPCTSTR szRealInfo)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x87, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 szRealInfo);
}

void CKoscomChart::ShowIndicatorConfigDlg()
{
	InvokeHelper(0x88, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CKoscomChart::ResetChartCfgWith(short p_nIndex)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x89, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_nIndex);
}

void CKoscomChart::EmptyChart(BOOL bIsDeleteAllPacket, BOOL bIsDefault)
{
	InvokeHelper(0x8a, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		bIsDeleteAllPacket, bIsDefault);
}

BOOL CKoscomChart::HasGraph(LPCTSTR p_szGraphName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x8b, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_szGraphName);
	return result;
}

void CKoscomChart::RemoveRealItem(LPCTSTR szRealInfo)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x8c, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 szRealInfo);
}

void CKoscomChart::ShowInnerToolBar(BOOL p_bShow)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x8d, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_bShow);
}

BOOL CKoscomChart::ChangeVertScalePosition(short nScalePosition, short nRowIndex, short nColumnIndex, short nVSGroupIndex)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2 VTS_I2;
	InvokeHelper(0x8e, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		nScalePosition, nRowIndex, nColumnIndex, nVSGroupIndex);
	return result;
}

short CKoscomChart::GetRowBlockCount()
{
	short result;
	InvokeHelper(0x8f, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

short CKoscomChart::GetColumnBlockCount()
{
	short result;
	InvokeHelper(0x90, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

BOOL CKoscomChart::SetStartPeriodOfPacket(LPCTSTR p_szPacketName, long p_lStartPeriod, long p_bAddSpace)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I4;
	InvokeHelper(0x91, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_szPacketName, p_lStartPeriod, p_bAddSpace);
	return result;
}

long CKoscomChart::GetStartPeriodOfPacket(LPCTSTR p_szPacketName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x92, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		p_szPacketName);
	return result;
}

BOOL CKoscomChart::GetStartEndDateOnView(double* p_pStartDate, double* p_pEndDate)
{
	BOOL result;
	static BYTE parms[] =
		VTS_PR8 VTS_PR8;
	InvokeHelper(0x93, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_pStartDate, p_pEndDate);
	return result;
}

BOOL CKoscomChart::SetStartEndDateOfView(double p_dStartDate, double p_dEndDate)
{
	BOOL result;
	static BYTE parms[] =
		VTS_R8 VTS_R8;
	InvokeHelper(0x94, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_dStartDate, p_dEndDate);
	return result;
}

BOOL CKoscomChart::ScrollToDataOfEnd(double p_dData)
{
	BOOL result;
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x95, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_dData);
	return result;
}

short CKoscomChart::ZoomToWithRightFix(short p_nZoomValue, BOOL p_bWithRightFix)
{
	short result;
	static BYTE parms[] =
		VTS_I2 VTS_BOOL;
	InvokeHelper(0x96, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		p_nZoomValue, p_bWithRightFix);
	return result;
}

void CKoscomChart::ClearTimeMark()
{
	InvokeHelper(0x97, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CKoscomChart::ShowEnvironmentDlg()
{
	InvokeHelper(0x98, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CKoscomChart::SetTimeMark(LPCTSTR p_szMarkTime, BOOL p_bWithScroll)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BOOL;
	InvokeHelper(0x99, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_szMarkTime, p_bWithScroll);
}

short CKoscomChart::GetVertScalePosition(short p_nRowIndex, short p_nColumnIndex, short p_nVSGroupIndex)
{
	short result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2;
	InvokeHelper(0x9a, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		p_nRowIndex, p_nColumnIndex, p_nVSGroupIndex);
	return result;
}

void CKoscomChart::EnableBoundMark(BOOL p_bEnable)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x9b, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_bEnable);
}

void CKoscomChart::EnableReceivingTimeShare(BOOL p_bEnable)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x9c, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_bEnable);
}

BOOL CKoscomChart::ChangePacketType(LPCTSTR p_szPacketName, LPCTSTR p_szPacketType)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x9d, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_szPacketName, p_szPacketType);
	return result;
}

BOOL CKoscomChart::ChangeGraphDrawingData(LPCTSTR p_szGraphName, BOOL p_bLowHigh, BOOL p_bLowCur, BOOL p_bHighCur, BOOL p_bPrevCur, BOOL p_bPrevCurRate)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BOOL VTS_BOOL VTS_BOOL VTS_BOOL VTS_BOOL;
	InvokeHelper(0x9e, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_szGraphName, p_bLowHigh, p_bLowCur, p_bHighCur, p_bPrevCur, p_bPrevCurRate);
	return result;
}

BOOL CKoscomChart::ChangePriceGraphDrawingData(BOOL p_bLowHigh, BOOL p_bLowCur, BOOL p_bHighCur, BOOL p_bPrevCur, BOOL p_bPrevCurRate, short p_nDefaultType)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BOOL VTS_BOOL VTS_BOOL VTS_BOOL VTS_BOOL VTS_I2;
	InvokeHelper(0x9f, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_bLowHigh, p_bLowCur, p_bHighCur, p_bPrevCur, p_bPrevCurRate, p_nDefaultType);
	return result;
}

void CKoscomChart::ShowAnalysisToolText(BOOL p_bTimeLine, BOOL p_bPriceLineLeft, BOOL p_bPriceLineRight, BOOL p_bTrendLine, BOOL p_bTrisectionLine, BOOL p_bQuadrisectionLine, BOOL p_bFibonacciRetraceLine)
{
	static BYTE parms[] =
		VTS_BOOL VTS_BOOL VTS_BOOL VTS_BOOL VTS_BOOL VTS_BOOL VTS_BOOL;
	InvokeHelper(0xa0, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_bTimeLine, p_bPriceLineLeft, p_bPriceLineRight, p_bTrendLine, p_bTrisectionLine, p_bQuadrisectionLine, p_bFibonacciRetraceLine);
}

BOOL CKoscomChart::HasGraphInSpecialBack(LPCTSTR p_szGraphName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0xa1, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_szGraphName);
	return result;
}

BOOL CKoscomChart::LoadAddIn(LPCTSTR p_szAddInDllName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0xa2, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_szAddInDllName);
	return result;
}

BOOL CKoscomChart::InvokeAddIn(LPCTSTR p_szAddInDllName, short p_nCommandType, long p_lData)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2 VTS_I4;
	InvokeHelper(0xa3, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_szAddInDllName, p_nCommandType, p_lData);
	return result;
}

void CKoscomChart::SetDragModeType(short p_nDragModeType)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0xa4, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_nDragModeType);
}

BOOL CKoscomChart::ResetRealListString(LPCTSTR p_szRealList, BOOL p_bAdviseNow)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BOOL;
	InvokeHelper(0xa5, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_szRealList, p_bAdviseNow);
	return result;
}

BOOL CKoscomChart::AddOrRemoveChart(LPCTSTR strIndicatorName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0xa6, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strIndicatorName);
	return result;
}*/
BOOL CKoscomChart::SetAllProperties2(long dwData)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(m_pdID[IIx_SetAllProperties2], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		dwData);
	return result;
}

void CKoscomChart::SetBaseDesk(long lKey)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(m_pdID[IIx_SetBaseDesk], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 lKey);
}


long CKoscomChart::GetBase(LPCTSTR szKey)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(m_pdID[IIx_GetBase], DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szKey);
	return result;
}

void CKoscomChart::AddGraph(short nRow, short nColumn, short nVertScaleGroup, LPCTSTR szGraphOption, BOOL bCreateBlock, BOOL bCreateVertScaleGroup, BOOL bUseAutoScale)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2 VTS_BSTR VTS_BOOL VTS_BOOL VTS_BOOL;
	InvokeHelper(m_pdID[IIx_AddGraph], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nRow, nColumn, nVertScaleGroup, szGraphOption, bCreateBlock, bCreateVertScaleGroup, bUseAutoScale);
}

void CKoscomChart::AddPacket(LPCTSTR szPacketOption)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(m_pdID[IIx_AddPacket], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 szPacketOption);
}

void CKoscomChart::RemovePacket(LPCTSTR szPacketName)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(m_pdID[IIx_RemovePacket], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 szPacketName);
}

CString CKoscomChart::GetIndicatorNameList(LPCTSTR p_strGroup)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(m_pdID[IIx_GetIndicatorNameList], DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		p_strGroup);
	return result;
}

void CKoscomChart::SetContainerDllInfo(long p_lDllWnd, short p_nID)
{
	static BYTE parms[] =
		VTS_I4 VTS_I2;
	InvokeHelper(m_pdID[IIx_SetContainerDllInfo], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_lDllWnd, p_nID);
}

short CKoscomChart::SetChartData(long pChartData, short nCount, short nType)
{
	short result;
	static BYTE parms[] =
		VTS_I4 VTS_I2 VTS_I2;
	InvokeHelper(m_pdID[IIx_SetChartData], DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		pChartData, nCount, nType);
	return result;
}


BOOL CKoscomChart::SetPacketData(LPCTSTR szPacketName, long szData, long nLength, BOOL bReset)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I4 VTS_BOOL;
	InvokeHelper(m_pdID[IIx_SetPacketData], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		szPacketName, szData, nLength, bReset);
	return result;
}

BOOL CKoscomChart::AddChartBlock(LPCTSTR strChartName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(m_pdID[IIx_AddChartBlock], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strChartName);
	return result;
}

BOOL CKoscomChart::ResetChart()
{
	BOOL result;
	InvokeHelper(m_pdID[IIx_ResetChart], DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CKoscomChart::SetBackgroundColors(unsigned long p_rgbBlockArea, unsigned long p_rgbScaleArea)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(m_pdID[IIx_SetBackgroundColors], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_rgbBlockArea, p_rgbScaleArea);
}

BOOL CKoscomChart::SetDrdsAdvise(BOOL bOnAdvise)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(m_pdID[IIx_SetDrdsAdvise], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		bOnAdvise);
	return result;
}

void CKoscomChart::AddRealItem(LPCTSTR szRealInfo)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(m_pdID[IIx_AddRealItem], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 szRealInfo);
}

void CKoscomChart::ShowIndicatorConfigDlg()
{
	InvokeHelper(m_pdID[IIx_ShowIndicatorConfigDlg], DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

long CKoscomChart::GetNOnePageDataCount()
{
	long result;
	GetProperty(m_pdID[IIx_NOnePageDataCount], VT_I4, (void*)&result);
	return result;
}

void CKoscomChart::SetNOnePageDataCount(long propVal)
{
	SetProperty(m_pdID[IIx_NOnePageDataCount], VT_I4, propVal);
}


CString CKoscomChart::GetStrStartDateOfData()
{
	CString result;
	GetProperty(m_pdID[IIx_StrStartDateOfData], VT_BSTR, (void*)&result);
	return result;
}

void CKoscomChart::ResetChartCfgWith(short p_nIndex)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(m_pdID[IIx_ResetChartCfgWith], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_nIndex);
}

// JSR 20060117 Modify Begin (From : ResetOCX() )
///////////////////////////////////////////////////////////////////////////////
/*
// Function Parameter : bIsDeleteAllPacket : true -> TRdata, 지표data 모두 삭제
											 false -> 지표data만 삭제
						bIsDefault : true -> 빈상태을 디폴트값으로 변경
									 false -> 디폴트값으로 변경 안함
*/
///////////////////////////////////////////////////////////////////////////////
BOOL CKoscomChart::EmptyChart(BOOL bIsDeleteAllPacket, BOOL bIsDefault)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BOOL VTS_BOOL;
	InvokeHelper(m_pdID[IIx_EmptyChart], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		bIsDeleteAllPacket, bIsDefault);
	return result;
}
// JSR 20060117 Modify End

BOOL CKoscomChart::HasGraph(LPCTSTR p_szGraphName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(m_pdID[IIx_HasGraph], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_szGraphName);
	return result;
}

void CKoscomChart::RemoveRealItem(LPCTSTR szRealInfo)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(m_pdID[IIx_RemoveRealItem], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 szRealInfo);
}

BOOL CKoscomChart::SaveandOpenFromFile(LPCTSTR strOpenFileName, LPCTSTR strSaveFileName, BOOL bOpenOption, BOOL bSaveOption)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BOOL VTS_BOOL;
	InvokeHelper(m_pdID[IIx_SaveandOpenFromFile], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strOpenFileName, strSaveFileName, bOpenOption, bSaveOption);
	return result;
}

short CKoscomChart::ClearChartData(short nOption)
{
	short result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(m_pdID[IIx_ClearChartData], DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		nOption);
	return result;
}

void CKoscomChart::ShowInnerToolBar(BOOL p_bShow)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(m_pdID[IIx_ShowInnerToolBar], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_bShow);
}

BOOL CKoscomChart::ChangeVertScalePosition(short nScalePosition, short nRowIndex, short nColumnIndex, short nVSGroupIndex)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2 VTS_I2;
	InvokeHelper(m_pdID[IIx_ChangeVertScalePosition], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		nScalePosition, nRowIndex, nColumnIndex, nVSGroupIndex);
	return result;
}


short CKoscomChart::GetRowBlockCount()
{
	short result;
	InvokeHelper(m_pdID[IIx_GetRowBlockCount], DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

short CKoscomChart::GetColumnBlockCount()
{
	short result;
	InvokeHelper(m_pdID[IIx_GetColumnBlockCount], DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

BOOL CKoscomChart::ChangeHorzScalePosition(short nScalePosition, short nRowIndex, short nColumnIndex)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2;
	InvokeHelper(m_pdID[IIx_ChangeHorzScalePosition], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		nScalePosition, nRowIndex, nColumnIndex);
	return result;
}

BOOL CKoscomChart::RemoveChart(LPCTSTR strChartName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(m_pdID[IIx_RemoveChart], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strChartName);
	return result;
}

BOOL CKoscomChart::SetStartPeriodOfPacket(LPCTSTR p_szPacketName, long p_lStartPeriod, long p_bAddSpace)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I4;
	InvokeHelper(m_pdID[IIx_SetStartPeriodOfPacket], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_szPacketName, p_lStartPeriod, p_bAddSpace);
	return result;
}

long CKoscomChart::GetStartPeriodOfPacket(LPCTSTR p_szPacketName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(m_pdID[IIx_GetStartPeriodOfPacket], DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		p_szPacketName);
	return result;
}

void CKoscomChart::SetStrUserIndicatorListFileName(LPCTSTR propVal)
{
	SetProperty(m_pdID[IIx_StrUserIndicatorListFileName], VT_BSTR, propVal);
}

void CKoscomChart::SetStrUserEnvironmentFileName(LPCTSTR propVal)
{
	SetProperty(m_pdID[IIx_StrUserEnvironmentFileName], VT_BSTR, propVal);
}

BOOL CKoscomChart::GetStartEndDateOnView(double* p_pStartDate, double* p_pEndDate)
{
	BOOL result;
	static BYTE parms[] =
		VTS_PR8 VTS_PR8;
	InvokeHelper(m_pdID[IIx_GetStartEndDateOnView], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_pStartDate, p_pEndDate);
	return result;
}

BOOL CKoscomChart::SetStartEndDateOfView(double p_dStartDate, double p_dEndDate)
{
	BOOL result;
	static BYTE parms[] =
		VTS_R8 VTS_R8;
	InvokeHelper(m_pdID[IIx_SetStartEndDateOfView], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_dStartDate, p_dEndDate);
	return result;
}


BOOL CKoscomChart::ScrollToDataOfEnd(double p_dData)
{
	BOOL result;
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(m_pdID[IIx_ScrollToDataOfEnd], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_dData);
	return result;
}

short CKoscomChart::ZoomToWithRightFix(short p_nZoomValue, BOOL p_bWithRightFix)
{
	short result;
	static BYTE parms[] =
		VTS_I2 VTS_BOOL;
	InvokeHelper(m_pdID[IIx_ZoomToWithRightFix], DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		p_nZoomValue, p_bWithRightFix);
	return result;
}


void CKoscomChart::ClearTimeMark()
{
	InvokeHelper(m_pdID[IIx_ClearTimeMark], DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CKoscomChart::ShowEnvironmentDlg()
{
	InvokeHelper(m_pdID[IIx_ShowEnvironmentDlg], DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CKoscomChart::SetTimeMark(LPCTSTR p_szMarkTime, BOOL p_bWithScroll)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BOOL;
	InvokeHelper(m_pdID[IIx_SetTimeMark], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_szMarkTime, p_bWithScroll);
}


void CKoscomChart::SetBOcxAreaNumericalInquiry(BOOL propVal)
{
	SetProperty(m_pdID[IIx_BOcxAreaNumericalInquiry], VT_BOOL, propVal);
}

BOOL CKoscomChart::GetOnRunningOneChart()
{
	BOOL result;
	GetProperty(m_pdID[IIx_OnRunningOneChart], VT_BOOL, (void*)&result);
	return result;
}

void CKoscomChart::EnableBoundMark(BOOL p_bEnable)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(m_pdID[IIx_EnableBoundMark], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_bEnable);
}

void CKoscomChart::EnableReceivingTimeShare(BOOL p_bEnable)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(m_pdID[IIx_EnableReceivingTimeShare], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_bEnable);
}

BOOL CKoscomChart::ChangePacketType(LPCTSTR p_szPacketName, LPCTSTR p_szPacketType)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(m_pdID[IIx_ChangePacketType], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_szPacketName, p_szPacketType);
	return result;
}

BOOL CKoscomChart::ChangePriceGraphDrawingData(BOOL p_bLowHigh, BOOL p_bLowCur, BOOL p_bHighCur, BOOL p_bPrevCur, short p_nCurData, short p_nDefaultType)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BOOL VTS_BOOL VTS_BOOL VTS_BOOL VTS_I2 VTS_I2;
	InvokeHelper(m_pdID[IIx_ChangePriceGraphDrawingData], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_bLowHigh, p_bLowCur, p_bHighCur, p_bPrevCur, p_nCurData, p_nDefaultType);
	return result;
}

void CKoscomChart::SetNUseInquiryWithCrossline(short propVal)
{
	SetProperty(m_pdID[IIx_NUseInquiryWithCrossline], VT_I2, propVal);
}

short CKoscomChart::GetNUseInquiryWithCrossline()
{
	short result;
	GetProperty(m_pdID[IIx_NUseInquiryWithCrossline], VT_I2, (void*)&result);
	return result;
}

BOOL CKoscomChart::GetBShowPriceRateInquiry()
{
	BOOL result;
	GetProperty(m_pdID[IIx_BShowPriceRateInquiry], VT_BOOL, (void*)&result);
	return result;
}

void CKoscomChart::SetBShowPriceRateInquiry(BOOL propVal)
{
	SetProperty(m_pdID[IIx_BShowPriceRateInquiry], VT_BOOL, propVal);
}

BOOL CKoscomChart::GetBNormalizedMinuteTimeRule()
{
	BOOL result;
	GetProperty(m_pdID[IIx_BNormalizedMinuteTimeRule], VT_BOOL, (void*)&result);
	return result;
}

void CKoscomChart::SetBNormalizedMinuteTimeRule(BOOL propVal)
{
	SetProperty(m_pdID[IIx_BNormalizedMinuteTimeRule], VT_BOOL, propVal);
}

BOOL CKoscomChart::HasGraphInSpecialBack(LPCTSTR p_szGraphName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(m_pdID[IIx_HasGraphInSpecialBack], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_szGraphName);
	return result;
}

BOOL CKoscomChart::InvokeAddIn(LPCTSTR p_szAddInDllName, short p_nCommandType, long p_lData)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2 VTS_I4;
	InvokeHelper(m_pdID[IIx_InvokeAddIn], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_szAddInDllName, p_nCommandType, p_lData);
	return result;
}

BOOL CKoscomChart::LoadAddIn(LPCTSTR p_szAddInDllName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(m_pdID[IIx_LoadAddIn], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_szAddInDllName);
	return result;
}

void CKoscomChart::SetDragModeType(short p_nDragModeType)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(m_pdID[IIx_SetDragModeType], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_nDragModeType);
}

void CKoscomChart::SetHtsPath(LPCTSTR pcszHtsPath)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(m_pdID[IIx_SetHtsPath], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pcszHtsPath);
}

void CKoscomChart::SetAllLogScale(BOOL bLogScale)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(m_pdID[IIx_SetAllLogScale], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 bLogScale);
}

void CKoscomChart::GetListViewerData(BSTR* bstrTitle, BSTR* bstrHorzScale, BSTR* bstrPacketNamesPerBlock, BSTR* bstrPacketNames, BSTR* bstrSaveFilePath, BOOL* bViewPacketSequence, long* lpPacketList)
{
	static BYTE parms[] =
		VTS_PBSTR VTS_PBSTR VTS_PBSTR VTS_PBSTR VTS_PBSTR VTS_PBOOL VTS_PI4;
	InvokeHelper(m_pdID[IIx_GetListViewerData], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 bstrTitle, bstrHorzScale, bstrPacketNamesPerBlock, bstrPacketNames, bstrSaveFilePath, bViewPacketSequence, lpPacketList);
}

void CKoscomChart::SetDataIndexByDate(LPCTSTR pcszStartDate, LPCTSTR pcszEndDate)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(m_pdID[IIx_SetDataIndexByDate], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pcszStartDate, pcszEndDate);
}


//2005. 07. 15 이후 추가 ================================================================
void CKoscomChart::SetRunTimeMode(BOOL bRunTimeMode)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(m_pdID[IIx_SetRunTimeMode], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 bRunTimeMode);
}

CString CKoscomChart::GetPacketOption()
{
	CString result;
	InvokeHelper(m_pdID[IIx_GetPacketOption], DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CKoscomChart::SetPacketOption(LPCTSTR strPacketOption)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(m_pdID[IIx_SetPacketOption], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strPacketOption);
}

void CKoscomChart::SetOutsideCommonInterface(long lpOutsideCommonInterface)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(m_pdID[IIx_SetOutsideCommonInterface], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 lpOutsideCommonInterface);
}


BOOL CKoscomChart::RemoveGraph_Title(short nRowIndex, short nColumnIndex, LPCTSTR szGraphTitle, BOOL bIsOnlyNoTRData, BOOL bIsAutoHorzScalePosition)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_BSTR VTS_BOOL VTS_BOOL;
	InvokeHelper(m_pdID[IIx_RemoveGraph_Title], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		nRowIndex, nColumnIndex, szGraphTitle, bIsOnlyNoTRData, bIsAutoHorzScalePosition);
	return result;
}


CString CKoscomChart::GetGraphPacketName(short nRowIndex, short nColumnIndex, LPCTSTR szGraphTitle)
{
	CString result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_BSTR;
	InvokeHelper(m_pdID[IIx_GetGraphPacketName], DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		nRowIndex, nColumnIndex, szGraphTitle);
	return result;
}

BOOL CKoscomChart::ChangeGraphTitle2(LPCTSTR szTargetTitle, LPCTSTR szSourceTitle)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(m_pdID[IIx_ChangeGraphTitle2], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		szTargetTitle, szSourceTitle);
	return result;
}

BOOL CKoscomChart::PartitionAllGraph()
{
	BOOL result;
	InvokeHelper(m_pdID[IIx_PartitionAllGraph], DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CKoscomChart::JoinAllGraph(BOOL bIsOneVertScaleGroup)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(m_pdID[IIx_JoinAllGraph], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		bIsOneVertScaleGroup);
	return result;
}

void CKoscomChart::SetBSelectTitle(BOOL propVal)
{
	SetProperty(m_pdID[IIx_SetBSelectTitle], VT_BOOL, propVal);
}

BOOL CKoscomChart::ChangeAllFunctionName(LPCTSTR szTargetFunctionName, LPCTSTR szSourceFunctionName, BOOL bKeepOldGraphColor)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BOOL;
	InvokeHelper(m_pdID[IIx_ChangeAllFunctionName], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		szTargetFunctionName, szSourceFunctionName, bKeepOldGraphColor);
	return result;
}

BOOL CKoscomChart::ChangeIndicatorPacketName(LPCTSTR strIndicatorName, short nSubGraphIndex, LPCTSTR strNewPacketName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2 VTS_BSTR;
	InvokeHelper(m_pdID[IIx_ChangeIndicatorPacketName], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strIndicatorName, nSubGraphIndex, strNewPacketName);
	return result;
}

void CKoscomChart::RunEnvironmentDlg(short nOption)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(m_pdID[IIx_RunEnvironmentDlg], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nOption);
}

BOOL CKoscomChart::SetIndicatorCondition(LPCTSTR strIndicatorName, short nConditionType, short nConditionIndex, short dValue, BOOL bReCalculate)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2 VTS_I2 VTS_I2 VTS_BOOL;
	InvokeHelper(m_pdID[IIx_SetIndicatorCondition], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strIndicatorName, nConditionType, nConditionIndex, dValue, bReCalculate);
	return result;
}

BOOL CKoscomChart::SetLogScale(LPCTSTR strIndicatorName, BOOL bLogScale)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BOOL;
	InvokeHelper(m_pdID[IIx_SetLogScale], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strIndicatorName, bLogScale);
	return result;
}

BOOL CKoscomChart::GetLogScale(LPCTSTR strIndicatorName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(m_pdID[IIx_GetLogScale], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strIndicatorName);
	return result;
}

BOOL CKoscomChart::SetHelpMessageRealDataRate(LPCTSTR strHelpMessageData, BOOL bIsRemove)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BOOL;
	InvokeHelper(m_pdID[IIx_SetHelpMessageRealDataRate], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strHelpMessageData, bIsRemove);
	return result;
}

BOOL CKoscomChart::InvokeAddInStr(LPCTSTR p_szAddInDllName, LPCTSTR p_szCommandName, LPCTSTR p_szData)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(m_pdID[IIx_InvokeAddInStr], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_szAddInDllName, p_szCommandName, p_szData);
	return result;
}

BOOL CKoscomChart::SetGraphHide3(LPCTSTR strTitle, BOOL bIsHide)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BOOL;
	InvokeHelper(m_pdID[IIx_SetGraphHide3], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strTitle, bIsHide);
	return result;
}

void CKoscomChart::SetOnePageDataCount2(long nOnePageDataCount, BOOL bIncludeRightMargin)
{
	static BYTE parms[] =
		VTS_I4 VTS_BOOL;
	InvokeHelper(m_pdID[IIx_SetOnePageDataCount2], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nOnePageDataCount, bIncludeRightMargin);
}

//BOOL CKoscomChart::SetPacketDataInAdditionPacket(LPCTSTR szPacketName, long szData, long szSize, BOOL bReset)
//{
//	BOOL result;
//	static BYTE parms[] =
//		VTS_BSTR VTS_I4 VTS_BOOL;
//	InvokeHelper(m_pdID[IIx_SetPacketDataInAdditionPacket], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
//		szPacketName, szData, bReset);
//	return result;
//}

BOOL CKoscomChart::SetPacketDataInAdditionPacket(LPCTSTR szPacketName, long szData, long nLength, BOOL bReset)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I4 VTS_BOOL;
	InvokeHelper(m_pdID[IIx_SetPacketDataInAdditionPacket], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		szPacketName, szData, nLength, bReset);
	return result;
}

void CKoscomChart::SetOnePageDataCount(long nOnePageDataCount)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(m_pdID[IIx_SetOnePageDataCount], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nOnePageDataCount);
}

BOOL CKoscomChart::SetPacketHelpMessage(LPCTSTR strHelpMsg, BOOL bIsAllRemove)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BOOL;
	InvokeHelper(m_pdID[IIx_SetPacketHelpMessage], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strHelpMsg, bIsAllRemove);
	return result;
}


void CKoscomChart::SetRealData(LPCTSTR strPacketName, double dData, short nOption)
{
	static BYTE parms[] =
		VTS_BSTR VTS_R8 VTS_I2;
	InvokeHelper(m_pdID[IIx_SetRealData], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strPacketName, dData, nOption);
}

void CKoscomChart::PrintChatImage()
{
	InvokeHelper(m_pdID[IIx_PrintChatImage], DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CKoscomChart::ExportToExcel()
{
	InvokeHelper(m_pdID[IIx_ExportToExcel], DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

//===========================================================================================
// 2006. 08. 24 추가
BOOL CKoscomChart::LoadAddInWithOverExclusive(LPCTSTR p_szAddInName)
{
	BOOL result;
	static BYTE parms[] = VTS_BSTR ;
	InvokeHelper(m_pdID[IIx_LoadAddInWithOverExclusive], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, p_szAddInName);
	return result;
}

long CKoscomChart::GetAllProperties3(long p_lIPropertyMap)
{
	long result;
	static BYTE parms[] = VTS_I4 ;
	InvokeHelper(m_pdID[IIx_GetAllProperties3], DISPATCH_METHOD, VT_I4, (void*)&result, parms, p_lIPropertyMap);
	return result;
}
long CKoscomChart::SetAllProperties3(long p_lIPropertyMap)
{
	long result;
	static BYTE parms[] = VTS_I4 ;
	InvokeHelper(m_pdID[IIx_SetAllProperties3], DISPATCH_METHOD, VT_I4, (void*)&result, parms, p_lIPropertyMap);
	return result;
}

LPUNKNOWN CKoscomChart::GetAddInCustomInterface(LPCTSTR p_szAddInName)
{
	LPUNKNOWN result;
	static BYTE parms[] = VTS_BSTR ;
	InvokeHelper(m_pdID[IIx_GetAddInCustomInterface], DISPATCH_METHOD, VT_UNKNOWN, (void*)&result, parms, p_szAddInName);
	return result;
}
//===========================================================================================

//===========================================================================================
// 2006. 08. 24 추가
BOOL CKoscomChart::ShowIndicatorConfigDlgWithName(LPCTSTR p_szIndicatorName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(m_pdID[IIx_ShowIndicatorConfigDlgWithName], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_szIndicatorName);
	return result;
}
//===========================================================================================

//===========================================================================================
// 2006. 12. 12 추가
BOOL CKoscomChart::GetBEnableIndicatorCalculation()
{
	BOOL result;
	GetProperty(m_pdID[IIx_BEnableIndicatorCalculation], VT_BOOL, (void*)&result);
	return result;
}

void CKoscomChart::SetBEnableIndicatorCalculation(BOOL propVal)
{
	SetProperty(m_pdID[IIx_BEnableIndicatorCalculation], VT_BOOL, propVal);
}

CString CKoscomChart::GetStrChartList()
{
	CString result;
	GetProperty(m_pdID[IIx_StrChartList], VT_BSTR, (void*)&result);
	return result;
}

void CKoscomChart::SetStrChartList(LPCTSTR propVal)
{
	SetProperty(m_pdID[IIx_StrChartList], VT_BSTR, propVal);
}

BOOL CKoscomChart::GetBWholeView()
{
	BOOL result;
	GetProperty(m_pdID[IIx_BWholeView], VT_BOOL, (void*)&result);
	return result;
}

void CKoscomChart::SetBWholeView(BOOL propVal)
{
	SetProperty(m_pdID[IIx_BWholeView], VT_BOOL, propVal);
}
//===========================================================================================
BOOL CKoscomChart::EmptyChart2(LPCTSTR p_szChartList, BOOL p_bIsDeleteAllPacket, BOOL p_bIsDefault)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BOOL VTS_BOOL;
	InvokeHelper(m_pdID[IIx_EmptyChart2], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_szChartList, p_bIsDeleteAllPacket, p_bIsDefault);
	return result;
}

CString CKoscomChart::AddChartItem(LPCTSTR lpszItemCode, LPCTSTR lpszItemName, BOOL bBuiltChart)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BOOL;
	InvokeHelper(m_pdID[IIx_AddChartItem], DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		lpszItemCode, lpszItemName, bBuiltChart);
	return result;
}

void CKoscomChart::SetRealDataCode(LPCTSTR strCode, LPCTSTR strPacketName, double dData, short nOption)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_R8 VTS_I2;
	InvokeHelper(m_pdID[IIx_SetRealDataCode], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		strCode, strPacketName, dData, nOption);
}

void CKoscomChart::AddPacketRQ(LPCTSTR lpszRQ, LPCTSTR lpszPacketOption)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(m_pdID[IIx_AddPacketRQ], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		lpszRQ, lpszPacketOption);
}

BOOL CKoscomChart::SetPacketDataRQ(LPCTSTR lpszRQ, LPCTSTR lpszPacketName, long nData, long nLength, BOOL bReset)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_I4 VTS_I4 VTS_BOOL;
	InvokeHelper(m_pdID[IIx_SetPacketDataRQ], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		lpszRQ, lpszPacketName, nData, nLength, bReset);
	return result;
}

BOOL CKoscomChart::AddChartItemRQ(LPCTSTR lpszRQ, LPCTSTR lpszItemCode, LPCTSTR lpszItemName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(m_pdID[IIx_AddChartItemRQ], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		lpszRQ, lpszItemCode, lpszItemName);
	return result;
}

void CKoscomChart::SetCurrentRQ(LPCTSTR lpszRQ)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(m_pdID[IIx_SetCurrentRQ], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		lpszRQ);
}

// xScaleManager : xScaleManager - ojtaso (20070529)
void CKoscomChart::SetResetTotalCountWhileDraw(BOOL bReset) 
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(m_pdID[IIx_SetResetTotalCountWhileDraw], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		bReset);
}

// 차트DLL에서 복수종목을 사용할지 : 복수종목 - ojtaso (20070904)
void CKoscomChart::SetMultiItemMode(BOOL bMultiItem) 
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(m_pdID[IIx_SetMultiItemMode], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		bMultiItem);
}
///////////////////////////////////////////////////////////////////////////////
//	작업자	:	배승원(Seung-Won, Bae)
//	E-Mail	:	radox@dooriic.co.kr
//	일자	:	2003.03.27
//
//	목적	:	CodeInput OCX의 Interface를 Dispatch하여 관리한다.
///////////////////////////////////////////////////////////////////////////////
OLECHAR *CKoscomChart::m_osInterfaceName[] = {
	L"SetAllProperties2",
	L"SetBaseDesk",
	L"GetBase",
	L"AddGraph",
	L"AddPacket",
	L"RemovePacket",
	L"GetIndicatorNameList",
	L"SetContainerDllInfo",
	L"SetChartData",
	L"SetPacketData",
	L"AddChartBlock",
	L"ResetChart",
	L"SetBackgroundColors",
	L"SetDrdsAdvise",
	L"AddRealItem",
	L"ShowIndicatorConfigDlg",
	L"NOnePageDataCount",
	L"StrStartDateOfData",
	L"ResetChartCfgWith",
	L"EmptyChart",
	L"HasGraph",
	L"RemoveRealItem",
	L"SaveandOpenFromFile",
	L"ClearChartData",
	L"ShowInnerToolBar",
	L"ChangeVertScalePosition",
	L"GetRowBlockCount",
	L"GetColumnBlockCount",
	L"ChangeHorzScalePosition",
	L"RemoveChart",
	L"SetStartPeriodOfPacket",
	L"GetStartPeriodOfPacket",
	L"StrUserIndicatorListFileName",
	L"StrUserEnvironmentFileName",
	L"GetStartEndDateOnView",
	L"SetStartEndDateOfView",
	L"ScrollToDataOfEnd",
	L"ZoomToWithRightFix",
	L"ClearTimeMark",
	L"ShowEnvironmentDlg",
	L"SetTimeMark",
	L"BOcxAreaNumericalInquiry",
	L"OnRunningOneChart",
	L"EnableBoundMark",
	L"EnableReceivingTimeShare",
	L"ChangePacketType",
	L"ChangePriceGraphDrawingData",
	L"NUseInquiryWithCrossline",
	L"BShowPriceRateInquiry",
	L"BNormalizedMinuteTimeRule",
	L"HasGraphInSpecialBack",
	L"InvokeAddIn",
	L"LoadAddIn",
	L"SetDragModeType",
	L"SetHtsPath",
	L"SetAllLogScale",
	L"GetListViewerData",
	L"SetDataIndexByDate",
	L"SetRunTimeMode",				//2005. 07. 15 이후 추가 
	L"GetPacketOption",
	L"SetPacketOption",
	L"SetOutsideCommonInterface",
	L"RemoveGraph_Title",
	L"GetGraphPacketName",
	L"ChangeGraphTitle2",
	L"PartitionAllGraph",
	L"JoinAllGraph",
	L"SetBSelectTitle",
	L"ChangeAllFunctionName",
	L"ChangeIndicatorPacketName",
	L"RunEnvironmentDlg",
	L"SetIndicatorCondition",
	L"SetLogScale",
	L"GetLogScale",
	L"SetHelpMessageRealDataRate",
	L"InvokeAddInStr",
	L"SetGraphHide3",
	L"SetOnePageDataCount2",
	L"SetPacketDataInAdditionPacket",
	L"SetOnePageDataCount",
	L"SetPacketHelpMessage",
	L"SetRealData",
	L"PrintChatImage",
	L"ExportToExcel",
	L"LoadAddInWithOverExclusive",
	L"GetAllProperties3",
	L"SetAllProperties3",
	L"GetAddInCustomInterface",
	L"ShowIndicatorConfigDlgWithName",
	L"bEnableIndicatorCalculation",
	L"StrChartList",
	L"bWholeView",
	L"EmptyChart2",
	L"AddChartItem",		// 복수종목에 사용되는 인터페이스 : 복수종목 - ojtaso (20070206)
	L"SetRealDataCode",		// 복수종목에 사용되는 인터페이스 : 복수종목 - ojtaso (20070206)
	L"AddPacketRQ",			// 복수종목 불러오기 : 복수종목 - ojtaso (20070514)
	L"SetPacketDataRQ",		// 복수종목 불러오기 : 복수종목 - ojtaso (20070514)
	L"AddChartItemRQ",		// 복수종목 불러오기 : 복수종목 - ojtaso (20070514)
	L"SetCurrentRQ",		// 복수종목 불러오기 : 복수종목 - ojtaso (20070514)
	L"SetResetTotalCountWhileDraw",			// xScaleManager : xScaleManager - ojtaso (20070529)
	L"SetMultiItemMode"			// 복수종목을 사용할지 : 복수종목 - ojtaso (20070904)
};

CKoscomChart::CKoscomChart()
{
	m_pdID = NULL;
}

CKoscomChart::~CKoscomChart()
{
	if( m_pdID)
	{
		delete m_pdID;
		m_pdID = NULL;
	}
}

BOOL CKoscomChart::Create(LPCTSTR lpszWindowName, DWORD dwStyle,
	const RECT& rect, CWnd* pParentWnd, UINT nID,
	CFile* pPersist /*= NULL*/, BOOL bStorage/* = FALSE*/,
	BSTR bstrLicKey/* = NULL*/)
{
	BOOL bResult = CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID, pPersist, bStorage, bstrLicKey);
	if( bResult)
	{
		IUnknown* pUnk = GetControlUnknown();
		if( pUnk)
		{
			IDispatch *pDisp = NULL;
			HRESULT hr = pUnk->QueryInterface( IID_IDispatch, (void**)&pDisp);
			if( !FAILED(hr))
			{
				pUnk->Release();				
				int i, nCount = sizeof( m_osInterfaceName) / sizeof( OLECHAR *);
				m_pdID = new DISPID[ nCount];
				for( i = 0; i < nCount; i++)
					pDisp->GetIDsOfNames( IID_NULL, &m_osInterfaceName[ i], 1, LOCALE_USER_DEFAULT, m_pdID + i);
			}
		}
		
	}
	return bResult;
}
