// Regester.idl: Regester.exe의 형식 라이브러리 소스

// 이 파일은 MIDL 컴파일러에 의해 처리되어
// 형식 라이브러리(Regester.tlb)입니다.

[ uuid(23e77275-bf19-4f72-ba6f-57a4f9ebd513), version(1.0) ]
library Regester
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	//  CRegesterDoc의 기본 디스패치 인터페이스

	[ uuid(b94b75ef-16d9-4cb7-b837-a111d278db64) ]
	dispinterface IRegester
	{
		properties:

		methods:
	};

	//  CRegesterDoc에 대한 클래스 정보

	[ uuid(3644d613-c69d-432b-a4fa-1d2b8da8ebb8) ]
	coclass Regester
	{
		[default] dispinterface IRegester;
	};
};
