// fx_edit.idl : fx_edit.dll의 형식 라이브러리 소스입니다.
// 이 파일은 MIDL 컴파일러에 의해 처리되어
// 형식 라이브러리(fx_edit.tlb)를 생성합니다.

#include "olectl.h"
[ uuid(78F9217D-D43B-4469-858C-65A84B10248A), version(1.0) ]
library fx_edit
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");
	//  Controlwnd의 기본 디스패치 인터페이스입니다.
		
	[ uuid(7733226F-155D-48E3-88D0-8CBBF5C5DECD) ]
	dispinterface IControlwnd
	{
		properties:
		methods:
			[id(1)] BSTR GetData(void);
			[id(2)] void SetData(BSTR strdata);
			[id(3)] void SetEnable(LONG benable);
			[id(4)] void SetName(BSTR name);
			[id(5)] void SetID(BSTR id);
			[id(6)] void SetVisible(LONG bvisible);
			[id(7)] void GetUserName(BSTR id);
	};

	//  Controlwnd의 클래스 정보입니다.

	[ uuid(A6C84D7A-D570-45CD-94FF-22378904E088) ]
	coclass Controlwnd
	{
		[default] dispinterface IControlwnd;
	};
};
