// IChartCtrl.h: interface for the IChartCtrl class.
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_ICHARTCTRL_H__804FF249_4729_49B6_8913_7CEDC34A43B0__INCLUDED_)
#define AFX_ICHARTCTRL_H__804FF249_4729_49B6_8913_7CEDC34A43B0__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include "BlockBaseEnum.h."		// for CToolOptionInfo

//-----------------------------------------------------------------------------
// Author		: Seung-Won, Bae	Date :2006/1/7
// Comments		: Interface of COleControl Class in Chart OCX
// Using way	: 
// See			: 
//-----------------------------------------------------------------------------

class CCommonInterface;
class CIndicatorList;
class CMainBlock;
class CPacketList;
class CShareInfoListHW;
interface IChartCtrl
{
protected:
	virtual ~IChartCtrl()	{}

public:
	virtual bool	AddChart_GenneralChart(const CString& strChartName) = 0;
	virtual bool	AddOrDeleteChart(const CString& strChartName) = 0;
	virtual bool	AddOrDeleteChart_Genneral(const CString& strChartName) = 0;
	virtual bool	AddOrDeleteChart_Special(const CString& strChartName) = 0;
	virtual bool	AddRemoveGraph(LPCTSTR pcszIndicatorName) = 0;
	virtual bool	ApplySkin() = 0;
//	virtual bool	CalculateAll(const CCalculateBaseData::CALCULATETYPE enumCalculateType) = 0;
//	virtual bool	CalculateIndicatorInTRData(CIndicatorInfo* pIndicatorInfo, const CList<CPacket*, CPacket*>& packetList) = 0;
	virtual bool	ChangeChart_PriceChartStyle(const CString& strChartName) = 0;
	virtual bool	ChangeChartType(CString strIndicatorName, CString strType, CString strStyle, CString strPacketNameList) = 0;
	virtual bool	ChangeOneChart( const CString& strChartName) = 0;
	virtual bool	ChangeSubGraphData(const char* pcszIndicatorName, const char* pcszSubGraphName, COLORREF clrLineColor, int nThickness, int nDrawStyle) = 0;
	virtual bool	CreateUserDirectory() = 0;
	virtual bool	DeleteChart_Genneral(const CString& strChartName) = 0;
	virtual bool	DeleteIndicator(const char* pcszIndicatorName) = 0;
	virtual bool	GetAutoSave() = 0;
	virtual bool	GetExistenceHighLowBound() const = 0;
	virtual bool	GetImaginaryCandle() = 0;
	virtual bool	GetRequestTRPacketName(const CString& strPacketNames, CString& strPacketNamesForTR) const = 0;
//	virtual bool	GetShowCrossLine() = 0;
	virtual bool	GetShowExRightDividend() = 0;
	virtual bool	GetShowHighLowBound() = 0;
	virtual bool	GetShowIndicatorValue() = 0;
	virtual bool	GetShowIndicatorVariable() = 0;
	virtual bool	GetShowMinMaxPrice() = 0;
	virtual bool	GetTimeLinkage() = 0;
	virtual bool	HasGraphAdapter(const char* szGraphName) = 0;
	virtual bool	IsExistenceBoundMark() const = 0;
	virtual bool	IsLoad_MarketChart() const = 0;
//	virtual bool	IsRealType(const CScaleBaseData::HORZSCALEDRAWERTYPE nType) const = 0;
	virtual bool	IsScrollInHorzScaleData() const = 0;
	virtual bool	IsUseToolScrollBar() = 0;
	virtual bool	IsWholeView() const = 0;
	virtual bool	OnReturnOrg2(const BOOL bIsMessageBox = TRUE) = 0;
//	virtual bool	ResetSaveChartCfg(CChartCfg* pChart, const bool bRegionRetain) = 0;
	virtual bool	ResetSaveChartCfg(int nOption, bool bRegionRetain = false) = 0;
	virtual bool	RestoreChartCfg(const int nIndex) = 0;
	virtual bool	RollbackLastNoOneChart() = 0;
	virtual bool	RunToolFuncGraphColor(const COLORREF clrGraphColor) = 0;
	virtual bool	RunToolFuncGraphStyle(const int nParam) = 0;
	virtual bool	RunToolFuncLineThickness(const int nParam) = 0;
//	virtual bool	RunToolFunction(const CToolOptionInfo::TOOLOPTION enumToolOption, const int nParam) = 0;
	virtual bool	SaveChartCfg() = 0;
	virtual bool	SaveChartCfgInCurrentOCX() = 0;
	virtual bool	SetAllPacketName(const CString& strIndicatorName, const CString& strNewPacketName) = 0;
	virtual bool	SetAllProperties_NEOCONVERT(CStringList* pPropStrList) = 0;
//	virtual bool	SetAnalysisTool_TextPosition() = 0;
//	virtual bool	SetAnaylsisToolData(const CAnalysisToolData& analysisToolData) = 0;
//	virtual bool	SetOcxDataFromChartCfg(CChartCfg* pChart, bool bRegionRetain) = 0;
	virtual bool	SetPacketDataInPacketList(LPCTSTR szPacketName, long szData, long lLength, BOOL bReset) = 0;
//	virtual bool	SetScrollData(const int nType = SETSCROLL_TR, const bool bIsHorzScaleDataCheck = true, const bool bIsRedraw = false) = 0;
//	virtual bool	SetSkinColorData(const CStyleData& sourceStyleData) = 0;
	virtual bool	SetStartIndexOfPacket(const char* pcszPacketName, int nStartDataIndex, BOOL bAddSpace) = 0;
	virtual bool	SetStartPeriodOfPacketAdapter(const char* szPacketName, long lStartPeriod, BOOL bAddSpace) = 0;
//	virtual bool	SetStyleData(const CStyleData& styleData) = 0;
	virtual bool	SetSubGraphPacketName(const CString& strIndicatorName, const int nSubGraphIndex, const CString& strNewPacketName) = 0;

public:
	virtual BOOL	AddChartBlock(LPCTSTR strChartName) = 0;
	virtual BOOL	AddOrRemoveChart(LPCTSTR strIndicatorName) = 0;
	virtual BOOL	ChangeAllFunctionName(LPCTSTR szTargetFunctionName, LPCTSTR szSourceFunctionName, BOOL bKeepOldGraphColor) = 0;
	virtual BOOL	ChangeBlockType(short nBlockType, short nRowCount, short nColumnCount) = 0;
	virtual BOOL	ChangeChartItem(LPCTSTR strIndicatorName, short nSubGraphIndex, LPCTSTR strNewTitle, LPCTSTR strNewPacketName, LPCTSTR strNewGraphType, LPCTSTR strNewGraphStyle, short nNewUpLineWidth, short nNewDownLineWidth, short nNewEqualLineWidth, BOOL bRunatOnce) = 0;
	virtual BOOL	ChangeGraphDatas(short nRowIndex, short nColumnIndex, short nVerticalIndex, short nGraphIndex, LPCTSTR strNewIndicatorName, LPCTSTR strNewTitle, LPCTSTR strNewPacketName, LPCTSTR strNewGraphType, LPCTSTR strNewGraphStyle, short nNewUpLineWidth, short nNewDownLineWidth, short nNewEqualLineWidth, BOOL bRunatOnce) = 0;
	virtual BOOL	ChangeGraphDrawingData(LPCTSTR p_szGraphName, BOOL p_bLowHigh, BOOL p_bLowCur, BOOL p_bHighCur, BOOL p_bPrevCur, short p_nCurData) = 0;
	virtual BOOL	ChangeGraphTitle(short nRowIndex, short nColumnIndex, short nGraphIndex, LPCTSTR strNewTitle) = 0;
	virtual BOOL	ChangeGraphTitle2(LPCTSTR szTargetTitle, LPCTSTR szSourceTitle) = 0;
	virtual BOOL	ChangeGraphType(LPCTSTR strIndicatorName, LPCTSTR strGraphType, LPCTSTR strGraphStyle, LPCTSTR strPacketNameList, BOOL bRunatOnce) = 0;
	virtual BOOL	ChangeHorzScalePosition(short nScalePosition, short nRowIndex, short nColumnIndex) = 0;
	virtual BOOL	ChangeIndicatorPacketName(LPCTSTR strIndicatorName, short nSubGraphIndex, LPCTSTR strNewPacketName) = 0;
	virtual BOOL	ChangePacketType(LPCTSTR p_szPacketName, LPCTSTR p_szPacketType) = 0;
	virtual BOOL	ChangePriceGraphDrawingData(BOOL p_bLowHigh, BOOL p_bLowCur, BOOL p_bHighCur, BOOL p_bPrevCur, short p_nCurData, short p_nDefaultType) = 0;
	virtual BOOL	ChangeVertScalePosition(short nScalePosition, short nRowIndex, short nColumnIndex, short nVSGroupIndex) = 0;
	virtual BOOL	CheckGSharedSetting( const char *p_szGSharedName, BOOL p_bStart, BOOL p_bGet, BOOL p_bSet) = 0;
	virtual BOOL	ClearPacketData(LPCTSTR strPacketName, BOOL bIsAbsoluteCreal) = 0;
	virtual BOOL	DestroyWindow() = 0;
//	virtual BOOL	DoAct(CToolOptionInfo::TOOLOPTION nToolOption) = 0;
//	virtual BOOL	DrawDragRect(CDC * pdc, CPoint ptFirst, CPoint ptPrev, CPoint ptCurr, int nWeight, BOOL bMouseMove = TRUE) = 0;
//	virtual BOOL	DrawRectSemiTransparent(CDC * pdc, CRect rect, CRect oldrect) = 0;
	virtual BOOL	FireGSharedData( const char *p_szGSharedName, const char *p_szGSharedData) = 0;
	virtual BOOL	FireSharedData( const char *p_szShareName, const char *p_szSharedData) = 0;
	virtual BOOL	GetBoundMarkFlag() = 0;
	virtual BOOL	GetDataStartEnd( int &p_nStartIndex, int &p_nEndIndex) = 0;
	virtual BOOL	GetLogScale(LPCTSTR strIndicatorName) = 0;
	virtual BOOL	GetScrollRange( int &p_nRange) = 0;
	virtual BOOL	GetShareInfoItem( const char *p_szShareName, int &p_nShareType, int &p_nShareArea, long &p_lCodeFilter) = 0;
	virtual BOOL	GetStartEndDateOnView(double FAR* p_pStartDate, double FAR* p_pEndDate) = 0;
	virtual BOOL	HasGraph(LPCTSTR p_szGraphName) = 0;
	virtual BOOL	HasGraphInSpecialBack(LPCTSTR p_szGraphName) = 0;
	virtual BOOL	HasToolItem( CToolOptionInfo::TOOLOPTION p_eToolItem) = 0;
	virtual BOOL	InvokeAddIn(LPCTSTR p_szAddInDllName, short p_nCommandType, long p_lData) = 0;
	virtual BOOL	InvokeAddInStr(LPCTSTR p_szAddInDllName, LPCTSTR p_szCommandName, LPCTSTR p_szData) = 0;
	virtual BOOL	IsChartType( const char *p_szChartName) const = 0;
	virtual BOOL	IsDaegimaemul() const = 0;
	virtual BOOL	IsGraphMenuShow() const = 0;
	virtual BOOL	IsOcxAreaNumericalInquiry( void) const = 0;
	virtual BOOL	IsPriceChartType( const char *p_szChartName) const = 0;
	virtual BOOL	IsRunningOneChart() const = 0;
	virtual BOOL	IsRunTimeMode() const = 0;
	virtual BOOL	IsShowPriceRateInquiry( void) const = 0;
	virtual BOOL	IsShowHorizonTextLeft( void)	const = 0;
	virtual BOOL	IsShowHorizonTextRight( void)	const = 0;
	virtual BOOL	IsShowFiboText( void)			const = 0;
	virtual BOOL	IsShowFourText( void)			const = 0;
	virtual BOOL	IsShowThreeText( void)			const = 0;
	virtual BOOL	IsShowTrendLineText( void)		const = 0;
	virtual BOOL	IsShowVerticalText( void)		const = 0;
	virtual BOOL	IsThisPacketConnected( const int nIndex, const CString strpacketname) = 0;
	virtual BOOL	IsUseInquiryData() const = 0;
	virtual BOOL	JoinAllGraph(BOOL bIsOneVertScaleGroup) = 0;
	virtual BOOL	JoinandDevisionforCompareChart(long nRowCount, long nColumnCount, BOOL bJoin) = 0;
	virtual BOOL	LoadAddIn(LPCTSTR p_szAddInDllName) = 0;
	virtual BOOL	OffRealAdvise() = 0;
//	virtual BOOL	OnAnalysisTool(CToolOptionInfo::TOOLOPTION nToolOption, int nOption = 1) = 0;
//	virtual BOOL	OnAutoTrendTool(int nOption = 1) = 0;
//	virtual BOOL	OnLButtonDown_DesignMode(const UINT nFlags, const CPoint& point) = 0;
//	virtual BOOL	OnLButtonDown_NumericalInquiryDlg(CDC* pDC, const UINT nFlags, const CPoint& point) = 0;
//	virtual BOOL	OnLButtonDown_Tool(CDC* pDC, UINT nFlags, CPoint point) = 0;
//	virtual BOOL	OnLButtonUp_DesignMode(const UINT nFlags, const CPoint& point) = 0;
//	virtual BOOL	OnLButtonUp_Tool(CDC* pDC, UINT nFlags, CPoint point) = 0;
//	virtual BOOL	OnMouseMove_Tool(CDC* pDC, UINT nFlags, CPoint point) = 0;
//	virtual BOOL	OnMouseWheel(UINT nFlags, short zDelta, CPoint pt) = 0;
	virtual BOOL	OnRealAdvise() = 0;
	virtual BOOL	OnRunningOneChart() = 0;
	virtual BOOL	OnSetCursor(CWnd* pWnd, UINT nHitTest, UINT message) = 0;
	virtual BOOL	PacketDataMaker() = 0;
	virtual BOOL	PartitionAllGraph() = 0;
	virtual BOOL	ReadUserFile(const CString& strFileName) = 0;
//	virtual BOOL	ReadUserFile( CSaveUserFile::FILETYPE nType) = 0;
	virtual BOOL	RemoveChart(LPCTSTR strChartName) = 0;
	virtual BOOL	RemoveGraph_Title(short nRowIndex, short nColumnIndex, LPCTSTR szGraphTitle, BOOL bIsOnlyNoTRData, BOOL bIsAutoHorzScalePosition) = 0;
	virtual BOOL	RemovePacket(LPCTSTR szPacketName) = 0;
	virtual BOOL	RemoveSetCapture( void) = 0;
	virtual BOOL	ResetChart() = 0;
	virtual BOOL	ResetPropertiesfromMainBlock() = 0;
	virtual BOOL	ResetRealListString(LPCTSTR p_szRealList, BOOL p_bAdviseNow) = 0;
	virtual BOOL	RestoreMin(LPCTSTR strPacketName) = 0;
	virtual BOOL	RestoreMinMax(LPCTSTR strPacketName) = 0;
	virtual BOOL	RestorMax(LPCTSTR strPacketName) = 0;
	virtual BOOL	SaveandOpenFromFile(LPCTSTR strOpenFileName, LPCTSTR strSaveFileName, BOOL bOpenOption, BOOL bSaveOption) = 0;
	virtual BOOL	ScrollTo( int p_nScrollValue, BOOL p_bRelative) = 0;
	virtual BOOL	ScrollToDataOfEnd(double p_dData) = 0;
	virtual BOOL	SetAllProperties2(long dwData) = 0;
	virtual BOOL	SetAllPropertiesFromFile(LPCTSTR strFilePath, LPCTSTR strFileName) = 0;
	virtual BOOL	SetDataStartEnd( int p_nStartIndex, int p_nEndIndex) = 0;
	virtual BOOL	SetDrdsAdvise(BOOL bOnAdvise) = 0;
	virtual BOOL	SetGraphHide2(short nRowIndex, short nColumnIndex, short nVerticalIndex, short nGraphIndex, short nSubGraphIndex, BOOL bHide) = 0;
	virtual BOOL	SetGraphHide3(LPCTSTR strTitle, BOOL bIsHide) = 0;
	virtual BOOL	SetGraphTitle(LPCTSTR strIndicatorName, short nSubGraphIndex, LPCTSTR strNewGraphTitle, BOOL bGraphShowing) = 0;
	virtual BOOL	SetHelpMessageRealDataRate(LPCTSTR strHelpMessageData, BOOL bIsRemove) = 0;
	virtual BOOL	SetHorzScaleData(short nRowIndex, short nColumnIndex, LPCTSTR strScaleData) = 0;
	virtual BOOL	SetIndicatorCondition(LPCTSTR strIndicatorName, short nConditionType, short nConditionIndex, double dConditionValue, BOOL bReCalculate) = 0;
	virtual BOOL	SetLogScale(LPCTSTR strIndicatorName, BOOL bLogScale) = 0;
	virtual BOOL	SetMax(LPCTSTR strPacketName, double dMax) = 0;
	virtual BOOL	SetMin(LPCTSTR strPacketName, double dMin) = 0;
	virtual BOOL	SetMinMax(LPCTSTR strPacketName, double dMin, double dMax) = 0;
	virtual BOOL	SetPacketData(LPCTSTR szPacketName, long szData, long lLength, BOOL bReset) = 0;
	virtual BOOL	SetPacketData2(LPCTSTR strPacketName, LPCTSTR strPacketType, LPCTSTR strPacketData, short nDataCount, BOOL bReCalculate) = 0;
	virtual BOOL	SetPacketDataInAdditionPacket(LPCTSTR szPacketName, long szData, long lLength, BOOL bReset) = 0;
	virtual BOOL	SetPacketHelpMessage(LPCTSTR strHelpMsg, BOOL bIsAllRemove) = 0;
	virtual BOOL	SetRealAdviseHW(BOOL p_bAdvise) = 0;
	virtual BOOL	SetScrollPosition(const int nPos) = 0;
	virtual BOOL	SetScrollPosToNextPage() = 0;
	virtual BOOL	SetSharedData(short p_nShareType, LPCTSTR p_szSharedName, LPCTSTR p_szData) = 0;
	virtual BOOL	SetSharedDataHW(LPCTSTR p_szShareName, LPCTSTR p_szSharedData) = 0;
	virtual BOOL	SetStartEndDateOfView(double p_dStartDate, double p_dEndDate) = 0;
	virtual BOOL	SetStartPeriodOfPacket(LPCTSTR p_szPacketName, long p_lStartPeriod, BOOL p_bAddSpace) = 0;
	virtual BOOL	SetStopLossPrice(BOOL bIsStopLoss, double dStopLossPrice, BOOL bIsProfit, double dProfitPrice) = 0;
	virtual BOOL	SetVertScaleData(short nRowIndex, short nColumnIndex, short nVertScaleGroupIndex, LPCTSTR strVertScaleData) = 0;
	virtual BOOL	UnloadAddIn(LPCTSTR p_szAddInDllName) = 0;
	virtual BOOL	ZoomTo( int p_nZoomValue, BOOL p_bRelative) = 0;

public:
	virtual BSTR	GetCustomFont() = 0;
	virtual BSTR	GetData(LPCTSTR strPacketName, short nDataIndex) = 0;
	virtual BSTR	GetGraphPacketName(short nRowIndex, short nColumnIndex, LPCTSTR szGraphTitle) = 0;
	virtual BSTR	GetIndicatorNameList(LPCTSTR p_strGroup) = 0;
	virtual BSTR	GetPacketOption() = 0;
	virtual BSTR	GetRealSettingInfo() = 0;
	virtual BSTR	GetStartDateOfData() = 0;
	virtual BSTR	GetStrBlockRegion() = 0;

public:
	virtual const char *GetBaseDeskPath( void) const = 0;
	virtual const char *GetOCXPath( void) const = 0;
	virtual const char *GetUserFilePath( void) const = 0;

//public:
//	virtual CChartCfg	GetChartCfgWithPacketReset( int nOption) = 0;

//public:
//	virtual CChartCfg*	GetChartCfg(const int nOption) = 0;
//	virtual CChartCfg*	GetLastChartCfg_NoOneChart() = 0;

public:
	virtual CCommonInterface *	GetCommonInterface( void) = 0;

public:
	virtual CFont *	GetChartFont( void) = 0;

public:
	virtual CFont *	GetRscFont() const = 0;

public:
	virtual CIndicatorList *	GetIndicatorList(void) = 0;

public:
	virtual CMainBlock *	GetMainBlock(void) = 0;

public:
	virtual COLORREF	GetAnalysisToolColor( void) const = 0;
	virtual COLORREF	GetTrendLineColor() = 0;

public:
	virtual CPacketList *	GetPacketList(void) = 0;

public:
	virtual CRect	GetMainBlockRegion() = 0;
	virtual CRect	GetOcxRegion() const = 0;
	virtual CRect	GetToolBarRegion() const = 0;
	virtual CRect	GetVirtualRegion() = 0;

public:
/*
	virtual CString	GetBlockDataForMaking( const CString& strChartName) const = 0;
	virtual CString	GetDataFromMainBlock() = 0;
	virtual CString	GetDataWindowRealPacketNames(const CString& strTitle, const CString& strPacketNames) const = 0;
	virtual CString	GetDefaultFilePathAndName(const CString& strFileName) const = 0;
	virtual CString	GetDefaultPath() const = 0;
	virtual CString	GetDesignModePath() = 0;
	virtual CString	GetFilePathAndName(const CString& strFilePath, const CString& strFileName) const = 0;
//	virtual CString	GetGraphDataForMaking( CIndicatorInfo *p_pIndicatorInfo) const = 0;
	virtual CString	GetJoinProperties(int nOption) = 0;
//	virtual CString	GetOneChartName( const CToolOptionInfo::TOOLOPTION nType) const = 0;
	virtual CString	GetPropertyValue(int nType, int nOrder) = 0;
	virtual CString	GetUserDefaultFilePath(const CString& strBaseDeskPath = "") const = 0;
	virtual CString	GetUserDefaultFilePathAndName(const CString& strFileName) const = 0;
	virtual CString	GetUserFilePathAndName(const CString& strFileName) const = 0;
	virtual CString	GetUserPath() const = 0;	
*/

//public:
//	virtual CToolOptionInfo::TOOLOPTION	GetSavedChartType() = 0;
//	virtual CToolOptionInfo::TOOLOPTION	GetToolType(CSelectMode::MOUSESELECTMODE eSelectMode, int nType) = 0;

public:
	virtual CWnd *	AddSetCapture( void) = 0;
	virtual CWnd *	GetMainWnd( void) = 0;
	virtual CWnd *	GetChartWindowPointer() const = 0;

public:
	virtual double	ConvertYPositionToData(const int nYPosition, const int nYPositionTop, const int nYPositionBottom,const double& dDataMax, const double& dDataMin, const bool bLog, const bool bReverse) = 0;
	virtual double	GetMax(LPCTSTR strPacketName) = 0;
	virtual double	GetMin(LPCTSTR strPacketName) = 0;

public:
	virtual HCURSOR	GetCursorHandle( void) = 0;
	virtual HCURSOR	SetCursorHandle( HCURSOR p_hNewCursor) = 0;

public:
	virtual HWND	GetBaseDeskHWnd() = 0;
	virtual HWND	GetSafeHwnd( void) const = 0;
	virtual HWND	GetWndHandle(void) const = 0;

public:
	virtual int	ConvertDataToYPosition( double p_dData, double p_dDataMax, double p_dDataMin, int p_nYPositionTop, int p_nYPositionBottom, BOOL p_bLog, BOOL p_bReverse) = 0;
	virtual int	GetCurrentScrollPos() = 0;
	virtual int	GetDataCountForToolBar() const = 0;
	virtual int	GetDataWindowEndIndex(const int nDataIndex, int& nHighlightIndex) = 0;
	virtual int	GetFullDataCount(const bool bIsHorzScaleDataCheck) const = 0;
//	virtual int	GetInquiryDataWindowMoveType() = 0;
//	virtual int	GetInquiryDataWindowType() = 0;
	virtual int	GetMarginInIndicatorInfo(const CString& strFunctionName) const = 0;
	virtual int	GetMaxDataCount() const = 0;
	virtual int	GetMaxRange() = 0;
	virtual int	GetMinCountPerPage() const = 0;
	virtual int	GetOnePacketSize() = 0;
	virtual int	GetOnePageDataCountForScroll() const = 0;
	virtual int	GetRightMargin() = 0;
	virtual int	GetShowCurrentPrice() = 0;
	virtual int	GetShowTrendLineValue() = 0;
	virtual int	GetSkinNumber() const = 0;
	virtual int	GetSliderMin( void) = 0;
	virtual int	GetUserMargin(void) const = 0;
	virtual int	GetViewDataIndex(CPoint ptMouse) = 0;
	virtual int	GetViewEndDataIndex(const bool bData) = 0;
	virtual int	GetYScalePosition() = 0;
	virtual int	OnCreate(LPCREATESTRUCT lpCreateStruct) = 0;
	virtual int	SaveCurrentChartCfg() = 0;
	virtual int	SetChartData2(long pChartData, int nCount, int nType) = 0;

public:
	virtual long	GetAllProperties2(long lpData) = 0;
	virtual long	GetBase(LPCTSTR szKey) = 0;
	virtual long	GetBasePropIf() = 0;
	virtual long	GetCodeFilterOfShareInfoItemHW(LPCTSTR p_szShareName) = 0;
	virtual long	GetOnePageDataCount() = 0;
	virtual long	GetStartPeriodOfPacket(LPCTSTR p_szPacketName) = 0;

public:
	virtual LPUNKNOWN	GetCtrlUnkownID(LPCTSTR szName) = 0;
	virtual LPUNKNOWN	GetDeskUnkownID() = 0;

public:
	virtual LRESULT	OnAddIndicatorFromChartList(WPARAM wParam, LPARAM lParam) = 0;
	virtual LRESULT	OnAddIndicatorFromSystem(WPARAM wParam, LPARAM lParam) = 0;
	virtual LRESULT	OnAddIndicatorInNewPacket(WPARAM wParam, LPARAM lParam) = 0;
//	virtual LRESULT	OnAnalysisFunction(WPARAM wParam, LPARAM lParam) = 0;
	virtual LRESULT	OnCursorExchange(WPARAM wParam, LPARAM lParam) = 0;
	virtual LRESULT	OnGetHWDesignUI( WPARAM wParam, LPARAM lParam) = 0;
	virtual LRESULT	OnGetRealTableManager( WPARAM wParam, LPARAM lParam) = 0;
	virtual LRESULT	OnGetUserMargin(WPARAM wParam, LPARAM lParam) = 0;
	virtual LRESULT	OnGraphMargin(WPARAM wParam, LPARAM lParam) = 0;
	virtual LRESULT	OnGraphSelectedIndex(WPARAM wParam, LPARAM lParam) = 0;
//	virtual LRESULT	OnGraphThickness(WPARAM wParam, LPARAM lParam) = 0;
//	virtual LRESULT	OnGraphTypeandStyle(WPARAM wParam, LPARAM lParam) = 0;
	virtual LRESULT	OnInitProperties(WPARAM wParam, LPARAM lParam) = 0;
	virtual LRESULT	OnPPGFont(WPARAM wParam, LPARAM lParam) = 0;
	virtual LRESULT	OnPPGProperties(WPARAM wParam, LPARAM lParam) = 0;
	virtual LRESULT	OnRealData( WPARAM wParam, LPARAM lParam) = 0;
	virtual LRESULT	OnRedrawFrSPDiscretion(WPARAM wParam, LPARAM lParam) = 0;
//	virtual LRESULT	OnReleaseSeriesDrawFromMain(WPARAM wParam, LPARAM lParam) = 0;
//	virtual LRESULT	OnRunOneChart(WPARAM wParam, LPARAM lParam) = 0;
	virtual LRESULT	OnSaveScrollInfo(WPARAM wParam, LPARAM lParam) = 0;
	virtual LRESULT	OnScroll(WPARAM wParam, LPARAM lParam) = 0;
	virtual LRESULT	OnSetEtc(WPARAM wParam, LPARAM lParam) = 0;
//	virtual LRESULT	OnToolInner(WPARAM wParam, LPARAM lParam) = 0;
	virtual LRESULT	RmsgFormStateChange( WPARAM wParam, LPARAM lParam) = 0;
	virtual LRESULT	SendEventMsgToDLL( UINT message, WPARAM wParam = NULL, LPARAM lParam = NULL) = 0;
	virtual LRESULT	WindowProc(UINT message, WPARAM wParam, LPARAM lParam) = 0;

public:
	virtual OLE_COLOR	GetClrAnalysisTool() = 0;
	virtual OLE_COLOR	GetClrBackBorder() = 0;
	virtual OLE_COLOR	GetClrBackground() = 0;
	virtual OLE_COLOR	GetClrBlock() = 0;
	virtual OLE_COLOR	GetClrBlockBorder() = 0;
	virtual OLE_COLOR	GetClrGraphBase1() = 0;
	virtual OLE_COLOR	GetClrGraphBase2() = 0;
	virtual OLE_COLOR	GetClrGraphBase3() = 0;
	virtual OLE_COLOR	GetClrGraphBase4() = 0;
	virtual OLE_COLOR	GetClrGraphBase5() = 0;
	virtual OLE_COLOR	GetClrGraphBase6() = 0;
	virtual OLE_COLOR	GetClrInquiryWindow() = 0;
	virtual OLE_COLOR	GetClrLattice() = 0;
	virtual OLE_COLOR	GetClrScaleLine() = 0;
	virtual OLE_COLOR	GetClrScaleLine2() = 0;
	virtual OLE_COLOR	GetClrScaleText() = 0;

public:
	virtual short	ChangeChart(short nBlockRowPosition, short nBlockColumnPosition, LPCTSTR strGraphTitle, LPCTSTR strIndicatorName, LPCTSTR strPacketName, LPCTSTR strGraphType, LPCTSTR strGraphStyle, short nLineWidth, OLE_COLOR clrLineColor) = 0;
	virtual short	ClearChartData(short nOption) = 0;
	virtual short	GetBongCountMargin( void) const = 0;
	virtual short	GetColumnBlockCount() = 0;
	virtual short	GetDataCount() = 0;
	virtual short	GetGraphRButtonType( void) const = 0;
	virtual short	GetRowBlockCount() = 0;
	virtual short	GetVertScalePosition(short p_nRowIndex, short p_nColumnIndex, short p_nVSGroupIndex) = 0;
	virtual short	SetChartData(long pChartData, short nCount, short nType) = 0;
	virtual short	SetChartDataFromFile(LPCTSTR szFileName, short nType) = 0;
	virtual short	SetChartDataStr(LPCTSTR szChartData, short nCount, short nType) = 0;
	virtual short	SetGraphHide(short nRow, short nColumn, LPCTSTR strTitle, BOOL bHide) = 0;
	virtual short	testGetPacketdatasize(LPCTSTR pIn) = 0;
	virtual short	ZoomToWithRightFix(short p_nZoomValue, BOOL p_bWithRightFix) = 0;

public:
	virtual UINT	OnGetDlgCode() = 0;
	virtual UINT	GetNumericalInquiryOption( void) const = 0;

public:
	virtual void	AddandDeleteIndicator(LPCTSTR strIndicatorName) = 0;
	virtual void	AddGraph(short nRow, short nColumn, short nVertScaleGroup, LPCTSTR szGraphOption, BOOL bCreateBlock, BOOL bCreateVertScaleGroup, BOOL bUseAutoScale) = 0;
	virtual void	AddGraphAdapter(short nRow, short nColumn, short nVertScaleGroup, const char* szGraphOption, BOOL bCreateBlock, BOOL bCreateVertScaleGroup, BOOL bUseAutoScale) = 0;
	virtual void	AddPacket(LPCTSTR szPacketOption) = 0;
	virtual void	AddPacketAdapter(const char* pcszPacketOption) = 0;
	virtual void	AddRealItem(LPCTSTR szRealInfo) = 0;
	virtual void	BehaviorBlock(const long pBlockBehaviorData) = 0;
	virtual void	ChartEnvSetupOk() = 0;
	virtual void	ClearTimeMark() = 0;
	virtual void	CreateBufferBitmap(CDC* pdc, const CRect& rcBounds) = 0;
	virtual void	CreateToolBar() = 0;
	virtual void	DeleteZoomInOutInquiryDlg() = 0;
//	virtual void	DoPropExchange(CPropExchange* pPX) = 0;
//	virtual void	DragMouseZoom(CDC* pDC, CPoint point) = 0;
	// (2006/2/6 - Seung-Won, Bae) DragZoomIn for DragZoom AddIn
	virtual void	DragZoomIn( const CPoint &p_ptStart, const CPoint &p_ptEnd) = 0;
	virtual void	EnableBoundMark(BOOL p_bEnable) = 0;
	virtual void	EnableReceivingTimeShare(BOOL p_bEnable) = 0;
	virtual void	FillInquiryByMouseMove() = 0;
	virtual void	FireAddInEvent(LPCTSTR p_szAddInName, short p_nEventID, LPCTSTR p_szData, double p_dData, long p_lData) = 0;
	virtual void	FireChangeOnePageDataCount(long nOnePageDataCount) = 0;
	virtual void	FireDataUpandDown(short nOption, LPCTSTR strStartDate, LPCTSTR strEndDate) = 0;
	virtual void	FireGetSettedChartInfoFromServer() = 0;
	virtual void	FireRequestBongData( short nOption, short nTemp) = 0;
	virtual void	FireRequestMapLoad(short nOption, LPCTSTR strCode, LPCTSTR strDate) = 0;
	virtual void	FireRequestNewPacket(short nOption, LPCTSTR strName, LPCTSTR strCode, LPCTSTR strDate) = 0;
	virtual void	FireRequestPacketData(LPCTSTR strDateType, LPCTSTR strStartDate, LPCTSTR strPacketNames) = 0;
	virtual void	FireRestore() = 0;
	virtual void	FireReturnOrgChart(long nOnePageDataCount) = 0;
	virtual void	FireSaveSettedChartInfoToServer() = 0;
	virtual void	FP_vSetInitFont() = 0;
	virtual void	FV_vInitFont() = 0;
//	virtual void	GetAnalysisToolData(CAnalysisToolData& analysisToolData) = 0;
//	virtual void	GetIndicatorDefaultData(CIndicatorDefaultData& indiDefaultData) const = 0;
	virtual void	GetListViewerData(BSTR FAR* bstrTitle, BSTR FAR* bstrHorzScale, BSTR FAR* bstrPacketNamesPerBlock, BSTR FAR* bstrPacketNames, BSTR FAR* bstrSaveFilePath, BOOL FAR* bViewPacketSequence, long FAR* lpPacketList) = 0;
//	virtual void	GetStyleData(CStyleData& styleData) const = 0;
	virtual void	HideTooltip( void) = 0;
//	virtual void	HideWindow() = 0;
	virtual void	InvalidateChart() = 0;
	virtual void	InvalidateControl( LPCRECT lpRect = NULL, BOOL bErase = TRUE) = 0;
	virtual void	InvalidateOCX(const bool bErase = true) = 0;
	virtual void	InvalidateOleControl() = 0;
	virtual void	InvalidateRect(const CRect& region, const bool bErase) = 0;
	virtual void	MakeSaveShortKey(LPCTSTR szFileName, short nFlag) = 0;
	virtual void	NeoAddInEvent( const char *p_szAddInName, short p_nEventID, const char *p_szData, double p_dData, long p_lData) = 0;
	virtual void	NeoChangeOnePageDataCount(int nOnePageDataCount) = 0;
	virtual void	NeoFireDataUpandDown(int nOption) = 0;
	virtual void	NeoFireGetSettedChartInfoFromServer() = 0;
	virtual void	NeoFireSaveSettedChartInfoToServer() = 0;
	virtual void	NeoRequestBongData(int nOption, int nTemp) = 0;
	virtual void	NeoRequestMapLoad(int nOption, CString strCode, CString strDate) = 0;
	virtual void	NeoRequestNewPacket(int nOption, CString strName, CString strCode, CString strDate) = 0;
	virtual void	NeoRequestPacketData(const CString& strDateType, const CString& strStartDate, const CString& strPacketNames) = 0;
	virtual void	NeoRestore() = 0;
	virtual void	NeoReturnOrgChart(const int nOnePageDataCount) = 0;
	virtual void	OnAidIndAbratio() = 0;
	virtual void	OnAidIndAdline() = 0;
	virtual void	OnAidIndAdx() = 0;
	virtual void	OnAidIndAsi() = 0;
	virtual void	OnAidIndAtr() = 0;
	virtual void	OnAidIndBalance() = 0;
	virtual void	OnAidIndBandB() = 0;
	virtual void	OnAidIndBandwidth() = 0;
	virtual void	OnAidIndBinarywave() = 0;
	virtual void	OnAidIndBollinger() = 0;
	virtual void	OnAidIndBox() = 0;
	virtual void	OnAidIndBrokenline() = 0;
	virtual void	OnAidIndCci() = 0;
	virtual void	OnAidIndCmf() = 0;
	virtual void	OnAidIndCo() = 0;
	virtual void	OnAidIndCommissionuncollected() = 0;
	virtual void	OnAidIndCustomerdeposition() = 0;
	virtual void	OnAidIndDaegi() = 0;
	virtual void	OnAidIndDemark() = 0;
	virtual void	OnAidIndDisparity() = 0;
	virtual void	OnAidIndDmi() = 0;
	virtual void	OnAidIndDpo() = 0;
	virtual void	OnAidIndEmv() = 0;
	virtual void	OnAidIndEnergy() = 0;
	virtual void	OnAidIndEnvelope() = 0;
	virtual void	OnAidIndEom() = 0;
	virtual void	OnAidIndFinancingbalance() = 0;
	virtual void	OnAidIndForeignerjibunyul() = 0;
	virtual void	OnAidIndForeignerpurebuy() = 0;
	virtual void	OnAidIndFutureoptionincomplete() = 0;
	virtual void	OnAidIndImi() = 0;
	virtual void	OnAidIndIndustrypriceindex() = 0;
	virtual void	OnAidIndInvestorForeigner() = 0;
	virtual void	OnAidIndInvestorOrg() = 0;
	virtual void	OnAidIndInvestorPerson() = 0;
	virtual void	OnAidIndLrs() = 0;
	virtual void	OnAidIndMac() = 0;
	virtual void	OnAidIndMacd() = 0;
	virtual void	OnAidIndMacdosc() = 0;
	virtual void	OnAidIndMaosc() = 0;
	virtual void	OnAidIndMarketpriceindex() = 0;
	virtual void	OnAidIndMfi() = 0;
	virtual void	OnAidIndMi() = 0;
	virtual void	OnAidIndMomentum() = 0;
	virtual void	OnAidIndNco() = 0;
	virtual void	OnAidIndNetchart() = 0;
	virtual void	OnAidIndNewpsychology() = 0;
	virtual void	OnAidIndNvi() = 0;
	virtual void	OnAidIndObv() = 0;
	virtual void	OnAidIndOcma() = 0;
	virtual void	OnAidIndOscp() = 0;
	virtual void	OnAidIndOscv() = 0;
	virtual void	OnAidIndParabolic() = 0;
	virtual void	OnAidIndPivot() = 0;
	virtual void	OnAidIndPnf() = 0;
	virtual void	OnAidIndPsychology() = 0;
	virtual void	OnAidIndPvi() = 0;
	virtual void	OnAidIndPvt() = 0;
	virtual void	OnAidIndRainbow() = 0;
	virtual void	OnAidIndReverseclock() = 0;
	virtual void	OnAidIndRoc() = 0;
	virtual void	OnAidIndRsi() = 0;
	virtual void	OnAidIndRsquared() = 0;
	virtual void	OnAidIndSigma() = 0;
	virtual void	OnAidIndSmi() = 0;
	virtual void	OnAidIndSonar() = 0;
	virtual void	OnAidIndStandarddeviation() = 0;
	virtual void	OnAidIndStandarderror() = 0;
	virtual void	OnAidIndStochasticsfast() = 0;
	virtual void	OnAidIndStochasticsfast2() = 0;
	virtual void	OnAidIndStochasticsfast3() = 0;
	virtual void	OnAidIndStochasticsosc() = 0;
	virtual void	OnAidIndStochasticsosc2() = 0;
	virtual void	OnAidIndStochasticsosc3() = 0;
	virtual void	OnAidIndStochasticsslow() = 0;
	virtual void	OnAidIndStochasticsslow2() = 0;
	virtual void	OnAidIndStochasticsslow3() = 0;
	virtual void	OnAidIndSwingindex() = 0;
	virtual void	OnAidIndThreeline() = 0;
	virtual void	OnAidIndTradeyesukm() = 0;
	virtual void	OnAidIndTrix() = 0;
	virtual void	OnAidIndTsf() = 0;
	virtual void	OnAidIndTsfosc() = 0;
	virtual void	OnAidIndTsi() = 0;
	virtual void	OnAidIndVhf() = 0;
	virtual void	OnAidIndVr() = 0;
	virtual void	OnAidIndVroc() = 0;
	virtual void	OnAidIndWeightedclose() = 0;
	virtual void	OnAidIndWill() = 0;
	virtual void	OnAidIndWilliam() = 0;
	virtual void	OnAidIndZz() = 0;
	virtual void	OnbAddGraphMenuShowChanged() = 0;
	virtual void	OnBBlockMoveDeleteChanged() = 0;
	virtual void	OnBControlBlockSizeChanged() = 0;
	virtual void	OnBDoesUseSkinColorChanged() = 0;
	virtual void	OnBFireRealEventChanged() = 0;
	virtual void	OnbGraphDragDropChanged() = 0;
	virtual void	OnbHideChanged() = 0;
	virtual void	OnbIsInputChanged() = 0;
	virtual void	OnbNormalizedMinuteTimeRule() = 0;
	virtual void	OnBOcxAreaNumericalInquiryChanged() = 0;
	virtual void	OnBOnePageDataCountInTRCountChanged() = 0;
	virtual void	OnBRedrawAfterUpdatedAllPacketsChanged() = 0;
	virtual void	OnBSelectGraphChanged() = 0;
	virtual void	OnBSelectTitleChanged() = 0;
	virtual void	OnBShowPriceRateInquiryChanged() = 0;
	virtual void	OnBShowWarningMessageBoxChanged() = 0;
	virtual void	OnBUseConditiontoTitleChanged() = 0;
	virtual void	OnBUseDatatoTitleChanged() = 0;
	virtual void	OnBUseInquiryDlgWhenUseCrossLineChanged() = 0;
	virtual void	OnbUseRealDataChanged() = 0;
	virtual void	OnBUseScaleRButtonMenuChanged() = 0;
	virtual void	OnBUseShortKeyChanged() = 0;
	virtual void	OnbWholeViewChanged() = 0;
	virtual void	OnCaptureChanged(CWnd *pWnd) = 0;
//	virtual void	OnChartList(int nOption) = 0;
//	virtual void	OnCircle() = 0;
//	virtual void	OnConfigIndicator() = 0;
	virtual void	OnContextFont() = 0;
	virtual void	OnContextInit() = 0;
	virtual void	OnContextMenu(CWnd* pWnd, CPoint point) = 0;
	virtual void	OnContextProperties() = 0;
	virtual void	OnContextRestart() = 0;
	virtual void	OnDataListViewer(int nOption) = 0;
//	virtual void	OnDelDriftline() = 0;
	virtual void	OnDeleteBlock() = 0;
//	virtual void	OnDeleteIndicator() = 0;
	virtual void	OnDraw(CDC* pdc, const CRect& rcBounds, const CRect& rcInvalid) = 0;
//	virtual void	OnDrawDriftline() = 0;
	virtual void	OnDrawForPrint( CDC &memoryDC, CBitmap &bufferBitmap, CRect rcSource, BOOL bScreenColor = TRUE) = 0;
	virtual void	OnDrawStockItemCode( CDC &memoryDC, CRect &rect) = 0;
	virtual void	OnDrawUsingOptimizingcolor( CDC &memoryDC, CBitmap &bufferBitmap, CRect rect) = 0;
	virtual void	OnDrawUsingScreencolor( CDC &memoryDC, CBitmap &bufferBitmap, CRect rect) = 0;
//	virtual void	OnEnvironmentSet( int nOption) = 0;
	virtual void	OnFullMinMax(int nOption) = 0;
	virtual void	OnFuncDataList() = 0;
//	virtual void	OnFuncEnvironment() = 0;
//	virtual void	OnFuncIndicatorCfg() = 0;
//	virtual void	OnFuncIndicatorList() = 0;
//	virtual void	OnIndicatorCfg(int nOption = 0) = 0;
//	virtual void	OnInquiryValue(const int nOption, const bool bIsReplay) = 0;
	virtual void	OnInvalidate() = 0;
//	virtual void	OnKeyDown(UINT nChar, UINT nRepCnt, UINT nFlags) = 0;
//	virtual void	OnKeyUp(UINT nChar, UINT nRepCnt, UINT nFlags) = 0;
//	virtual void	OnLButtonDblClk(UINT nFlags, CPoint point) = 0;
	virtual void	OnLButtonDown(UINT nFlags, CPoint point) = 0;
	virtual void	OnLButtonUp(UINT nFlags, CPoint point) = 0;
	virtual void	OnMenuCrossline() = 0;
	virtual void	OnMenuDatawindow() = 0;
//	virtual void	OnMouseMove(const CPoint& point) = 0;
//	virtual void	OnMouseMove(UINT nFlags, CPoint point) = 0;
//	virtual void	OnMouseMove_DesignMode(const UINT nFlags, const CPoint& point) = 0;
	virtual void	OnnBlockBorderThicknessChanged() = 0;
	virtual void	OnnBlockColumnCountChanged() = 0;
	virtual void	OnnBlockCompartChanged() = 0;
	virtual void	OnnBlockGapChanged() = 0;
	virtual void	OnnBlockRowCountChanged() = 0;
	virtual void	OnnBlockTypeChanged() = 0;
	virtual void	OnNBongCountMarginChanged() = 0;
	virtual void	OnnBorderTypeChanged() = 0;
	virtual void	OnnBottomMarginChanged() = 0;
	virtual void	OnNColumnDoubleSizeBlockChanged() = 0;
	virtual void	OnNGraphRButtonTypeChanged() = 0;
	virtual void	OnNHoldingPacketSizeChanged() = 0;
	virtual void	OnNHorzGapChanged() = 0;
	virtual void	OnNInquiryTypeChanged() = 0;
	virtual void	OnnLeftMarginChanged() = 0;
	virtual void	OnNMarginBorderTypeChanged() = 0;
	virtual void	OnNMinDataCountOnOnePageChanged() = 0;
	virtual void	OnNNumericalInquiryOptionChanged() = 0;
	virtual void	OnnOnePageDataCountChanged() = 0;
	virtual void	OnNRButtonMenuTypeChanged() = 0;
	virtual void	OnnRightMarginChanged() = 0;
	virtual void	OnNRowDoubleSizeBlockChanged() = 0;
	virtual void	OnnScaleLineTypeChanged() = 0;
	virtual void	OnnTopMarginChanged() = 0;
	virtual void	OnNUseInquiryWithCrosslineChanged() = 0;
	virtual void	OnnUserBlockAddCountChanged() = 0;
	virtual void	OnNVertGapChanged() = 0;
	virtual void	OnPacketTRData() = 0;
	virtual void	OnPacketTRData(const CString& strTRPacketNames, const bool bIsResert) = 0;
//	virtual void	OnPatternAnalysis(const BOOL bIsShow = TRUE) = 0;
	virtual void	OnPricechartMinmax() = 0;
	virtual void	OnPrint() = 0;
//	virtual void	OnRButtonDown(UINT nFlags, CPoint point) = 0;
//	virtual void	OnRButtonUp(UINT nFlags, CPoint point) = 0;
//	virtual void	OnReleaseSeriesdraw() = 0;
	virtual void	OnResetState() = 0;
	virtual void	OnRestore() = 0;
	virtual void	OnRestore(int nOption) = 0;
	virtual void	OnRestoreDisplayDataCount() = 0;
	virtual void	OnReturnOrg() = 0;
	virtual void	OnReturnOrg(const bool bIsMessageBox) = 0;
	virtual void	OnReturnOrgDisplay() = 0;
	virtual void	OnReverseYscale() = 0;
	virtual void	OnSaveScreen() = 0;
//	virtual void	OnScaleSettingMessage( const ETCMESSAGETYPE eEtcMessageType, const int nData) = 0;
//	virtual void	OnScaleX() = 0;
//	virtual void	OnScaleXHide() = 0;
	virtual void	OnScreenMinmax() = 0;
	virtual void	OnSetFocus(CWnd* pOldWnd) = 0;
	virtual void	OnShowToolbar() = 0;
	virtual void	OnSimpleDetailDataview() = 0;
//	virtual void	OnSimpleEnvironment() = 0;
	virtual void	OnSimpleIndiInitialize() = 0;
	virtual void	OnSize(UINT nType, int cx, int cy) = 0;
//	virtual void	OnSquare() = 0;
	virtual void	OnstrChartListChanged() = 0;
	virtual void	OnStrGlobalSharedListChanged() = 0;
	virtual void	OnstrLocalSharedListChanged() = 0;
	virtual void	OnStrMapNameChanged() = 0;
	virtual void	OnstrPacketOptionChanged() = 0;
	virtual void	OnstrRealListChanged() = 0;
	virtual void	OnStrShareInfoListHWChanged() = 0;
	virtual void	OnstrToolbarOptionChanged() = 0;
	virtual void	OnstrUserEnvironmentFileNameChanged() = 0;
	virtual void	OnstrUserIndicatorListFileNameChanged() = 0;
	virtual void	OnstrUserSeriesListFileNameChanged() = 0;
//	virtual void	OnSymbol(CToolOptionInfo::TOOLOPTION nToolOption, int nOption) = 0;
	virtual void	OnSzBasePacketNameChanged() = 0;
	virtual void	OnTestDatawindow() = 0;
	virtual void	OnTimer(UINT nIDEvent) = 0;
	virtual void	OnToExcel() = 0;
//	virtual void	OnToolLine() = 0;
//	virtual void	OnTriangle() = 0;
	virtual void	OnUpdateAidIndAbratio(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndAdline(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndAdx(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndAsi(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndAtr(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndBalance(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndBandB(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndBandwidth(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndBinarywave(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndBollinger(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndBox(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndBrokenline(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndCci(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndCmf(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndCo(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndDaegi(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndDemark(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndDisparity(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndDmi(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndDpo(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndEmv(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndEnergy(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndEnvelope(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndEom(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndImi(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndLrs(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndMac(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndMacd(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndMacdosc(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndMaosc(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndMfi(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndMi(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndMomentum(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndNco(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndNetchart(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndNewpsychology(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndNvi(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndObv(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndOcma(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndOscp(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndOscv(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndParabolic(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndPivot(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndPsychology(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndPvi(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndPvt(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndRoc(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndRsi(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndRsquared(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndSigma(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndSmi(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndSonar(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndStandarddeviation(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndStandarderror(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndStochasticsfast(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndStochasticsfast2(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndStochasticsfast3(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndStochasticsosc(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndStochasticsosc2(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndStochasticsosc3(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndStochasticsslow(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndStochasticsslow2(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndStochasticsslow3(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndSwingindex(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndTrix(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndTsf(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndTsfosc(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndTsi(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndVhf(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndVr(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndVroc(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndWeightedclose(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndWill(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndWilliam(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateAidIndZz(CCmdUI* pCmdUI) = 0;
//	virtual void	OnUpdateCircle(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateContextInit(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateContextProperties(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateContextRestart(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateCrossFollowClose(CCmdUI* pCmdUI) = 0;
//	virtual void	OnUpdateDeleteIndicator(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateFuncEnvironment(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateMenuCrossline(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateMenuDatawindow(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdatePricechartMinmax(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateReverseYscale(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateScreenMinmax(CCmdUI* pCmdUI) = 0;
	virtual void	OnUpdateShowToolbar(CCmdUI* pCmdUI) = 0;
//	virtual void	OnUpdateSquare(CCmdUI* pCmdUI) = 0;
//	virtual void	OnUpdateTriangle(CCmdUI* pCmdUI) = 0;
	virtual void	OnWindowPosChanged(WINDOWPOS FAR* lpwndpos) = 0;
	// (2006/1/28 - Seung-Won, Bae) Reset Tool UI
	virtual void	ReleaseToolUI( const CToolOptionInfo::TOOLOPTION p_eToolOption) = 0;
	virtual void	RemoveRealItem(LPCTSTR szRealInfo) = 0;
	virtual void	ReplaceMATitle(CString &szpricema, int nOption = 0) = 0;
	virtual void	RequestTRPacket(const CString& strIndicatorName, const CString& strPacketNames) = 0;
	virtual void	RequestTRPacket(const CString& strIndicatorName, const CString& strPacketNames, const int nCount, const bool bIsNew) = 0;
//	virtual void	ResetAnalysisToolTextPosition( void) = 0;
	virtual void	ResetChartCfgWith(short p_nIndex) = 0;
//	virtual bool	EmptyChart(const bool bIsDeleteAllPacket, const bool bIsDefault) = 0;
	virtual void	RunEnvironmentDlg(short nOption) = 0;
//	virtual void	RunOneChart( const CToolOptionInfo::TOOLOPTION nType, const BOOL bIsOneChartUse) = 0;
	virtual void	SaveandApplyGraphStyle(short nSaveDataType, short nChangeDataType) = 0;
	virtual void	SendMessagetoMain(int nType, int nOption = -1) = 0;
	virtual void	SendTimeOfIndexToDLL( UINT p_uMessage, int p_nIndex) = 0;
	virtual void	SetAllLogScale(BOOL bLogScale) = 0;
	virtual void	SetAllProperties_Chart() = 0;
	virtual void	SetAutoSave(const bool bAutoSave, const bool bOutside = true) = 0;
	virtual void	SetBackgroundColors(OLE_COLOR p_rgbBlockArea, OLE_COLOR p_rgbScaleArea) = 0;
	virtual void	SetBaseDesk(long lKey) = 0;
	virtual void	SetBongCountMargin(short nBongCountMargin) = 0;
	virtual void	SetChartAllInfo() = 0;
	virtual void	SetClrAnalysisTool(OLE_COLOR nNewValue) = 0;
	virtual void	SetClrBackBorder(OLE_COLOR nNewValue) = 0;
	virtual void	SetClrBackground(OLE_COLOR nNewValue) = 0;
	virtual void	SetClrBlock(OLE_COLOR nNewValue) = 0;
	virtual void	SetClrBlockBorder(OLE_COLOR nNewValue) = 0;
	virtual void	SetClrGraphBase1(OLE_COLOR nNewValue) = 0;
	virtual void	SetClrGraphBase2(OLE_COLOR nNewValue) = 0;
	virtual void	SetClrGraphBase3(OLE_COLOR nNewValue) = 0;
	virtual void	SetClrGraphBase4(OLE_COLOR nNewValue) = 0;
	virtual void	SetClrGraphBase5(OLE_COLOR nNewValue) = 0;
	virtual void	SetClrGraphBase6(OLE_COLOR nNewValue) = 0;
	virtual void	SetClrInquiryWindow(OLE_COLOR nNewValue) = 0;
	virtual void	SetClrLattice(OLE_COLOR nNewValue) = 0;
	virtual void	SetClrScaleLine(OLE_COLOR nNewValue) = 0;
	virtual void	SetClrScaleLine2(OLE_COLOR nNewValue) = 0;
	virtual void	SetClrScaleText(OLE_COLOR nNewValue) = 0;
	virtual void	SetContainerDllInfo(long p_lDllWnd, short p_nID) = 0;
//	virtual void	SetCursorExchange(const CCursorShape::CHARTOBJECT enumChartObject) = 0;
	virtual void	SetCustomFont(LPCTSTR lpszNewValue) = 0;
	virtual void	SetDataIndexByDate(LPCTSTR pcszStartDate, LPCTSTR pcszEndDate) = 0;
	virtual void	SetDataRegionInBlock(short nDataStartIndex) = 0;
	virtual void	SetDataToMainBlock(const CString& strData) = 0;
	virtual void	SetDataWindowData(CPoint point) = 0;
	virtual void	SetDataWindowHeader(CPoint point) = 0;
	virtual void	SetDataWindowScaleData(const CString& strHorzScaleName, const int nDataIndex, CString& strViewData) = 0;
	virtual void	SetDataWindowStart(CPoint point) = 0;
	virtual void	SetDataWindowViewData(const CString& strTitle, const CString& strPacketNames, const int nDataIndex, CString& strViewData) = 0;
	virtual void	SetDragModeType(short p_nDragModeType) = 0;
	virtual void	SetEtc(const int nOption, const int nBongCountMargin) = 0;
	virtual void	SetGraphMargin(LPCTSTR pcszFunctionName, const bool bIsAddMargin) = 0;
	virtual void	SetGraphSelectedDataIndex(const int nDataIndex, LPCTSTR pcszIndicatorName) = 0;
	virtual void	SetGraphThickness(const int nGraphThickness1) = 0;
	virtual void	SetGraphTypeStyle(const int nGraphType, const int nDrawStyle) = 0;
	virtual void	SetHtsPath(LPCTSTR pcszHtsPath) = 0;
	virtual void	SetImaginaryCandle(const bool bImaginaryCandle, const bool bOutside = true) = 0;
//	virtual void	SetInquiryDataWindowMoveType(const int nMoveType, const bool bOutside = true) = 0;
//	virtual void	SetInquiryDataWindowType() = 0;
//	virtual void	SetInquiryDataWindowType(const int nWindowType, const bool bOutside = true) = 0;
//	virtual void	SetInquiryDlgMode(const int nMode) = 0;
	virtual void	SetInquiryValue( const BOOL nIs) = 0;
	virtual void	SetItemInfo(LPCTSTR lpstrCode, LPCTSTR lpstrName) = 0;
	virtual void	SetLoggingFlag( const BOOL p_bInLogging) = 0;
	virtual void	SetMainBlock(BOOL bUserMode) = 0;
	virtual void	SetMainBlock_MainBlock(const bool bUserMode) = 0;
//	virtual void	SetMainBlock_Tool(const bool bUserMode) = 0;
	virtual void	SetMainBlock_ToolBar(const bool bUserMode) = 0;
	virtual void	SetMainBlockData(const CString& strPropertyName) = 0;
	virtual void	SetMultiChartDlg(long lpMultiChartDlg) = 0;
//	virtual void	SetNoneSelectMode( const CSelectMode::MOUSESELECTMODE eSelectMode) = 0;
	virtual void	SetOnePageDataCount(long nOnePageDataCount) = 0;
	virtual void	SetOnePageDataCount2(long nOnePageDataCount, BOOL bIncludeBongCountMargin) = 0;
	virtual void	SetOnePageDataCountForScroll(const int nType, const int nTotalDataCount) = 0;
	virtual void	SetOnePageDataCountInTRCount(BOOL bIsTRCount, BOOL bIsNowChange) = 0;
	virtual void	SetOutsideCommonInterface(long lpOutsideCommonInterface) = 0;
	virtual void	SetPacketOption(LPCTSTR strPacketOption) = 0;
//	virtual void	SetProperty_Bool( CPropertiesList *pPropertiesList, CString strPropertyName, BOOL bValue) = 0;
//	virtual void	SetProperty_Color( CPropertiesList *pPropertiesList, CString strPropertyName, COLORREF clrColor) = 0;
//	virtual void	SetProperty_Int( CPropertiesList *pPropertiesList, CString strPropertyName, int nValue) = 0;
//	virtual void	SetProperty_String( CPropertiesList *pPropertiesList, CString strPropertyName, CString strValue) = 0;
	virtual void	SetRealData(LPCTSTR strPacketName, double dData, short nOption) = 0;
	virtual void	SetRealDataAdapter(const char* pcszPacketName, double dData, short nOption) = 0;
	virtual void	SetRightMargin(const int nRightMargin, const bool bOutside = true) = 0;
	virtual void	SetRscMng( long lKey) = 0;
	virtual void	SetRunTimeMode(BOOL bRunTimeMode) = 0;
	virtual void	SetScrollBar() = 0;
	virtual void	SetScrollInfo(const int nOnePageDataCount) = 0;
//	virtual void	SetSelectMode(const CToolOptionInfo::TOOLOPTION nToolOption, const int nParam) = 0;
//	virtual void	SetShowCrossLine(const bool bShow, const bool bOutside = true) = 0;
	virtual void	SetShowCurrentPrice(const int nShowType, const bool bOutside = true) = 0;
	virtual void	SetShowExRightDividend(const bool bShow, const bool bOutside = true) = 0;
	virtual void	SetShowHighLowBound(const bool bShow, const bool bOutside = true) = 0;
	virtual void	SetShowIndicatorValue(const bool bShow, const bool bOutside = true) = 0;
	virtual void	SetShowIndicatorVariable(const bool bShow, const bool bOutside = true) = 0;
	virtual void	SetShowMinMaxPrice(const bool bShow, const bool bOutside = true) = 0;
	virtual void	SetShowTrendLineValue(const int nPosition, const bool bOutside = true) = 0;
	virtual void	SetStartEndIndex(const int nStartIndex, const int nEndIndex) = 0;
	virtual void	SetStateWholeView(const int nParam = 0) = 0;
	virtual void	SetStrBlockRegion(LPCTSTR lpszNewValue) = 0;
//	virtual void	SetStyleDataInOCX(const CStyleData& styleData) = 0;
//	virtual void	SetSytleDataInDLL() = 0;
	virtual void	SetTimeLinkage(const bool bTimeLinkage, const bool bOutside = true) = 0;
	virtual void	SetTimeMark(LPCTSTR p_szMarkTime, BOOL p_bWithScroll) = 0;
	virtual void	SetTrendLineColor(const COLORREF clrLineColor, const bool bOutside = true) = 0;
	virtual void	SetUserEnvironmentAndIndicatorListFileName(const CString& strFileName) = 0;
	virtual void	SetWholeView( const BOOL bWholeView) = 0;
	virtual void	SetYScalePosition(const int nPosition, const bool bOutside = true) = 0;
	virtual void	ShowAnalysisToolText(BOOL p_bTimeLine, BOOL p_bPriceLineLeft, BOOL p_bPriceLineRight, BOOL p_bTrendLine, BOOL p_bTrisectionLine, BOOL p_bQuadrisectionLine, BOOL p_bFibonacciRetraceLine) = 0;
	virtual void	ShowEnvironmentDlg() = 0;
	virtual void	ShowIndicatorConfigDlg() = 0;
	virtual void	ShowInnerToolBar(BOOL p_bShow) = 0;
	// (2006/2/7 - Seung-Won, Bae) Show and Hide Numerical Inquiry Dialog
	virtual void	ShowNumericalInquiryDlg( const BOOL p_bShow, const BOOL p_bAutoMove) = 0;
	virtual void	ShowNumericalInquiryDlg( CDC *p_pDC, const CPoint &p_ptPoint) = 0;
	virtual void	ShowTooltip( const CPoint &p_ptPoint) = 0;
	virtual void	testLoadAnalysisTools(short nToolOption, short nOption) = 0;
	virtual void	UserFileVersionChecker() = 0;
	virtual void	WriteUserFile(const CString& strFileName) = 0;
//	virtual void	WriteUserFile(CSaveUserFile::FILETYPE nType) = 0;
};

#endif // !defined(AFX_ICHARTCTRL_H__804FF249_4729_49B6_8913_7CEDC34A43B0__INCLUDED_)
