//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by axis.rc
//
#define IDC_CLEAR                       3
#define IDC_ACTION                      3
#define IDC_OSETUP                      4
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDD_INVALIDID                   110
#define IDR_MAINFRAME                   128
#define IDR_AXISTYPE                    129
#define IDB_PIN                         130
#define IDD_CONNECT                     131
#define IDB_HELP                        132
#define IDB_PIN_                        133
#define IDB_HELP_                       137
#define IDI_CLIENT                      139
#define IDD_MODALPOPUP                  140
#define IDD_LOCK                        141
#define IDD_FULLNAME                    142
#define IDD_SCREEN                      150
#define IDB_RESTORE_                    162
#define IDB_ALL                         171
#define IDB_ALL_                        172
#define IDB_N                           173
#define IDB_N_                          174
#define IDB_RESTORE                     175
#define IDB_5_                          178
#define IDB_1                           179
#define IDB_1_                          180
#define IDB_2                           181
#define IDB_2_                          182
#define IDB_3                           183
#define IDB_3_                          184
#define IDB_4                           185
#define IDB_4_                          186
#define IDB_5                           187
#define IDI_ICON1                       190
#define IDD_PROGRESS                    191
#define IDD_SAVEPASS                    192
#define IDD_SETUP                       198
#define IDD_CERTIFY                     201
#define IDD_NOTICE                      203
#define IDI_SETUP                       203
#define IDB_CHECK_ON                    210
#define IDB_CHECK_OFF                   211
#define IDB_REGISTER_ON                 212
#define IDB_CHELP_OFF                   213
#define IDB_CHELP_ON                    214
#define IDB_JUMUN_OFF                   215
#define IDB_JUMUN_ON                    216
#define IDB_REGISTER_OFF                217
#define IDD_EXIT                        218
#define IDD_PROGRAM                     220
#define IDD_SETPRINT                    221
#define IDD_ESETUP                      226
#define IDD_CONCLUSIONLIST              227
#define IDD_CONCLUSION                  228
#define IDB_TCPBMP                      231
#define IDB_INETBMP                     232
#define IDB_CHECKBOXES                  235
#define IDB_TOP_                        236
#define IDB_TOP                         237
#define IDB_DUAL                        238
#define IDB_DUAL_                       239
#define IDB_TIMER                       240
#define IDB_M3                          241
#define IDB_M1                          242
#define IDB_M2                          243
#define IDD_GLB                         247
#define IDD_NEWALARM                    248
#define IDD_RTS                         250
#define IDD_NEWCUSTOMER                 252
#define IDD_KONG                        257
#define IDD_MISUNOTIFY                  260
#define IDB_NEWCUSTOMER                 273
#define IDB_FONT_                       284
#define IDB_COPY                        285
#define IDB_COPY_                       286
#define IDB_FONT                        287
#define IDD_EDITSERVER                  289
#define IDB_BITMAP1                     306
#define IDD_USEINFO                     307
#define IDB_GROUP                       309
#define IDB_CLOSE                       314
#define IDB_MAX                         315
#define IDB_MIN                         316
#define IDB_SINGLE                      318
#define IDB_VSCREEN                     319
#define IDB_MAINFUNC                    320
#define IDD_NEWSVIEWER                  339
#define IDD_STOPLOSS                    346
#define IDD_ACCSAVE                     350
#define IDD_REMOTEHELP                  351
#define IDD_DT_CONNECT                  353
#define IDD_DT_EXIT                     357
#define IDD_SETUP_CUST                  365
#define IDI_HAXIS                       369
#define IDB_DAETOO                      371
#define IDB_HANA                        372
#define IDI_HCLIENT                     374
#define IDD_STOPLOSSWARNNING            382
#define IDD_MNGINFO                     384
#define IDB_PRU                         387
#define IDB_KATS                        387
#define IDB_FONIX                       387
#define IDD_INPUT_IP                    394
#define IDD_PINCHSET                    395
#define IDD_MAINHOTKEY                  397
#define IDD_GUIDE_MSG                   403
#define IDD_ACCN_TREE                   405
#define IDB_TREEIMAGE                   408
#define IDD_FILTER                      409
#define IDB_LISTIMAGE                   411
#define IDD_ACCN_ADMIN                  417
#define IDD_DIALOG_BUFFERING            419
#define IDB_V1                          420
#define IDB_V2                          421
#define IDB_V3                          422
#define IDB_V4                          423
#define IDB_CHILD                       424
#define IDB_MAIN                        429
#define IDB_BITMAP2                     431
#define IDR_TOOLBAR1                    448
#define IDR_TOOLBAR2                    455
#define IDB_REFRESH_TYPE                461
#define IDB_TREE_TYPE                   462
#define IDB_BITMAP3                     463
#define IDB_LIST_TYPE                   463
#define IDB_BITMAP4                     464
#define IDB_TOOLBARBG                   464
#define IDB_PRINT                       465
#define IDB_CAPTURE                     465
#define IDD_DLG_SCREENSET               467
#define IDB_CHILD_MIN                   469
#define IDB_CHILD_MAX                   470
#define IDB_CHILD_CLOSE                 471
#define IDB_BITMAP5                     474
#define IDB_CHILD_RESTORE               474
#define IDD_DIALOG1                     475
#define IDD_DLG_MODALESS                475
#define IDD_DIALOG2                     476
#define IDC_USER                        1001
#define IDC_PASS                        1002
#define IDC_CPASS                       1003
#define IDC_RUN                         1004
#define IDC_NAME                        1005
#define IDC_MSG                         1006
#define IDC_SETUP                       1007
#define IDC_NEWUSER                     1008
#define IDC_PROXY                       1009
#define IDC_TOTPROGRESS                 1010
#define IDC_INET                        1010
#define IDC_UDP                         1010
#define IDC_TCP                         1011
#define IDC_SCNE                        1011
#define IDC_CURPROGRESS                 1012
#define IDC_SERVER                      1012
#define IDC_DelayTimer                  1012
#define IDC_PROGRESS                    1013
#define IDC_MSGE                        1013
#define IDC_FILE                        1014
#define IDC_FACNT                       1014
#define IDC_TOTALFILE                   1015
#define IDC_OPCNT                       1015
#define IDC_TOTALSIZE                   1016
#define IDC_USERNAME                    1017
#define IDC_TRANSENDFILE                1017
#define IDC_USETIME                     1018
#define IDOKX                           1019
#define IDC_SEARCHP                     1020
#define IDC_ENDTIME                     1020
#define IDC_PNAME                       1021
#define IDC_STARTTIME                   1021
#define IDC_PLIST                       1022
#define IDC_ALIST                       1024
#define IDC_DEL                         1024
#define IDC_ANAME                       1025
#define IDC_FNAME                       1025
#define IDC_PRINT                       1025
#define IDC_ANUM                        1026
#define IDC_PORT                        1026
#define IDC_CHANGE                      1028
#define IDC_STATUS                      1029
#define IDC_STATIC1                     1029
#define IDC_STATIC2                     1030
#define IDC_STATIC3                     1031
#define IDC_STATIC4                     1032
#define IDC_STATIC5                     1033
#define IDC_USERID                      1034
#define IDC_USERIP                      1035
#define IDC_SERVERNAME                  1036
#define IDC_SNAME                       1037
#define IDC_SERVERIP                    1037
#define IDC_ADD                         1038
#define IDC_DELETE                      1039
#define IDC_SHARE                       1040
#define IDC_OPERATOR                    1041
#define IDC_STATION                     1042
#define IDC_T1                          1043
#define IDC_BOX3                        1044
#define IDC_T2                          1045
#define IDC_BOX1                        1046
#define IDC_BOX2                        1047
#define IDC_INETIMG                     1049
#define IDC_TCPIMG                      1050
#define IDC_BORDER                      1051
#define IDC_ERRMSG                      1058
#define IDC_UP                          1059
#define IDC_SELECTSCANNER               1059
#define IDC_DOWN                        1060
#define IDC_HP                          1060
#define IDC_DIRECTCONNECT               1061
#define IDC_EPSON                       1061
#define IDC_SERVERLIST                  1062
#define IDC_KEYPROTECT                  1062
#define IDC_PORTLIST                    1063
#define IDC_SAVEID                      1064
#define IDC_CURSERVER                   1065
#define IDC_SCN01                       1065
#define IDC_SCN02                       1066
#define IDC_SCN03                       1067
#define IDC_SCN04                       1068
#define IDC_SCN05                       1069
#define IDC_SCN06                       1070
#define IDC_SCN07                       1071
#define IDC_INFOLIST                    1074
#define IDC_POS01                       1074
#define IDC_MAPF                        1075
#define IDC_POS02                       1075
#define IDD_CONFIG                      1075
#define IDC_DEVF                        1076
#define IDC_POS03                       1076
#define IDC_HELPF                       1077
#define IDC_POS04                       1077
#define IDD_ACCN_INTEREST               1077
#define IDC_IMAGEF                      1078
#define IDC_MTBLF                       1079
#define IDC_TABF                        1080
#define IDC_MSG01                       1080
#define IDC_EXEF                        1081
#define IDC_MSG02                       1081
#define IDC_PLATFORMF                   1082
#define IDC_BITMAP                      1085
#define IDC_ALL                         1106
#define IDC_ENSETUPINFO                 1107
#define IDC_SETTICKERINFO               1108
#define IDC_TOOLEDITINFO                1109
#define IDC_GUIDEMSG                    1110
#define IDC_WORKSPACEINFO               1113
#define IDC_SPASS                       1113
#define IDC_LPASS                       1114
#define IDC_CHARTINFO                   1114
#define IDC_SCREEN                      1124
#define IDC_PO1                         1125
#define IDC_PO2                         1126
#define IDC_PO3                         1127
#define IDC_PO4                         1128
#define IDC_PO5                         1129
#define IDC_CAPTION                     1130
#define IDC_CONFIRM                     1130
#define IDC_PO7                         1130
#define IDC_NOTICESKIN                  1131
#define IDC_ORDER                       1131
#define IDC_PO8                         1131
#define IDC_FLASH                       1132
#define IDC_HBITMAP                     1133
#define IDC_PO6                         1133
#define IDC_SEL_LMOUSE                  1133
#define IDC_DBITMAP                     1134
#define IDC_ALLCANCEL                   1134
#define IDC_PO9                         1134
#define IDC_DRUNX                       1135
#define IDC_ACCT                        1135
#define IDC_CODECANCEL                  1135
#define IDC_FutureTrade                 1135
#define IDC_DUSER                       1136
#define IDC_ANAM                        1136
#define IDC_OptionTrade                 1136
#define IDC_MKEYCOMBO                   1136
#define IDC_DPASS                       1137
#define IDC_AKEYCOMBO                   1137
#define IDC_PO10                        1137
#define IDC_DCPASS                      1138
#define IDC_AUTOSORT                    1138
#define IDC_OptionDepth                 1138
#define IDC_PO11                        1138
#define IDC_DNEWUSER                    1139
#define IDC_HKEYCOMBO                   1139
#define IDC_FutureDepth                 1139
#define IDC_CENTER                      1139
#define IDC_DEXIT                       1140
#define IDC_BKEYCOMBO                   1140
#define IDC_DSETUP                      1141
#define IDC_ORDERKEY                    1141
#define IDC_DMSG                        1142
#define IDC_OP_UP                       1142
#define IDC_IKEYCOMBO                   1142
#define IDC_DRUN                        1143
#define IDC_OP_DOWN                     1143
#define IDC_POSITION                    1143
#define IDC_DSAVEID                     1144
#define IDC_JKEYCOMBO                   1144
#define IDC_DONLYSISE                   1145
#define IDC_OP_ONE_CLICK                1145
#define IDC_DSAVEPASS                   1146
#define IDC_OP_ONE_CELL                 1146
#define IDC_DCURRECEIVE                 1147
#define IDC_A3MSET                      1147
#define IDC_DALLRECEIVE                 1148
#define IDC_NALLCANCEL                  1148
#define IDC_DALLFILECNT                 1149
#define IDC_NAKEYCOMBO                  1149
#define IDC_NKEYCOMBO                   1149
#define IDC_DTRANSFILECNT               1150
#define IDC_DFILENAME                   1151
#define IDC_DTRANSFILESIZE              1152
#define IDC_DTRANSRATE                  1153
#define IDC_DSTATIC1                    1154
#define IDC_DSTATIC2                    1155
#define IDC_DSTATIC3                    1156
#define IDC_BN_CA                       1157
#define IDC_BN_REMOTE                   1158
#define IDC_BECANCEL                    1158
#define IDC_BN_BREAK                    1159
#define IDC_PROXY_CUST                  1159
#define IDC_CKEYCOMBO                   1159
#define IDC_DSTATIC                     1160
#define IDC_BN_CENTER                   1160
#define IDC_BEEDIT                      1160
#define IDC_HSTATIC                     1161
#define IDC_BN_HELP                     1161
#define IDC_DKEYCOMBO                   1161
#define IDC_BN_BRANCH                   1162
#define IDC_DNAMESTATIC                 1162
#define IDC_BN_IDLOST                   1162
#define IDC_ALLORDER                    1162
#define IDC_HNAMESTATIC                 1163
#define IDC_GKEYCOMBO                   1163
#define IDC_BN_HELP2                    1163
#define IDC_BN_VIRUS                    1164
#define IDC_DCOPYRIGHTSTATIC            1164
#define IDC_HCOPYRIGHTSTATIC            1165
#define IDC_SELORDER                    1166
#define IDC_EKEYCOMBO                   1167
#define IDC_WARNMSG                     1168
#define IDC_BUYORDER                    1168
#define IDC_RED1                        1169
#define IDC_FKEYCOMBO                   1169
#define IDC_SERVERTIME                  1171
#define IDC_CHANGEINFO                  1172
#define IDC_RSCINFO                     1172
#define IDC_BN_MINI                     1173
#define IDC_COLOR1                      1175
#define IDC_COLOR2                      1176
#define IDC_UDPD                        1178
#define IDC_IPINPUT                     1179
#define IDC_IPNum                       1181
#define IDC_COMBO1                      1181
#define IDC_COMBO2                      1182
#define IDC_COMBO3                      1183
#define IDC_ConnectName                 1184
#define IDC_COMBO4                      1184
#define IDC_BUTTON1                     1185
#define IDC_CLOSE                       1185
#define IDC_BTN_TEXT                    1185
#define IDC_BTN_OK                      1185
#define IDC_Reset                       1186
#define IDC_DataStep                    1187
#define IDC_E_BEEDIT                    1190
#define IDC_AccnTree                    1193
#define IDC_HOGAFILTER                  1194
#define IDC_HOGAKEY                     1195
#define IDC_SDI                         1196
#define IDC_MDI                         1197
#define IDC_E_ALLORDER                  1197
#define IDC_E_SELORDER                  1198
#define IDC_E_BUYORDER                  1199
#define IDC_OP_ONE_AUTO                 1200
#define IDC_S_ALLORDER                  1201
#define IDC_S_BEEDIT                    1202
#define IDC_S_SELORDER                  1203
#define IDC_S_BUYORDER                  1204
#define IDC_SEL_HOGA_COUNTER            1205
#define IDC_SEL_DJUMUN                  1206
#define IDC_TAB                         1206
#define IDC_E_ROW                       1207
#define IDC_STTREE                      1207
#define IDC_FutureVolume                1209
#define IDC_OptionVolume                1210
#define IDC_COMBO_SISE                  1210
#define IDC_COMBO_GRIDDRAW              1211
#define IDC_STATIC_CERT                 1213
#define IDC_DSAVEPW                     1214
#define IDC_DAUTOCONNECT                1215
#define IDC_DFILEDOWN                   1216
#define IDC_TAB1                        1217
#define IDC_BUTTON2                     1218
#define IDC_BTN_EXIT                    1218
#define IDC_BTN_CANCEL                  1218
#define IDC_CHK_PROGRAM                 1219
#define IDC_CHK_SDI                     1220
#define IDC_STATIC_PRO                  1221
#define IDC_STATIC_PRO2                 1222
#define IDC_STATIC_SDI                  1222
#define IDC_EDIT1                       1224
#define IDD_ACCTOOLBAR                  7001
#define IDC_NEWSHIDECOUNT               7027
#define IDC_NEWSHIDESPIN                7028
#define IDC_MDCON_SEARCH                7046
#define IDC_MDCON_PLAY                  7047
#define IDC_MDCON_FILENAME              7048
#define IDC_MDCON                       7049
#define IDD_CHATTREE                    7050
#define ID_WRK_TREEBTN                  7051
#define ID_WRK_RELOADBTN                7052
#define ID_WRK_LISTBTN                  7053
#define ID_WRK_LISTUSER                 7054
#define ID_MENU_BASE                    10000
#define IDD_CONCLUSION_LIST             11076
#define ID_MENU_TB                      14000
#define ID_MENU_USERTOOL                15000
#define ID_MENU_USER                    19000
#define ID_MENU_END                     20000
#define ID_GROUP_BASE                   25000
#define ID_GROUP_END                    26000
#define ID_APP_BASE                     32770
#define ID_ESCAPEWINODW                 32774
#define ID_SCREENNUM                    32775
#define ID_VIEW_DB1                     32779
#define ID_VIEW_SCLIST                  32780
#define ID_FULLNAME                     32782
#define ID_VIEW_MODE                    32787
#define ID_VIEW_TICKER1                 32787
#define ID_APP_SETUP                    32788
#define ID_APP_SAVEPASS                 32789
#define ID_APP_USETUPDOWN               32790
#define ID_APP_USETUPUPLOAD             32791
#define ID_APP_LOCK                     32792
#define ID_APP_TSETUP                   32793
#define ID_APP_USERPROGRAM              32794
#define ID_APP_USERSCREEN_SAVE          32795
#define ID_APP_TRSEARCH                 32798
#define ID_APP_INTERSAVE                32799
#define ID_APP_SAVEBMP                  32801
#define ID_APP_HOTKEY                   32802
#define ID_APP_EDITHOTKEY               32802
#define ID_VIEW_VSCREEN1                32803
#define ID_VIEW_VSCREEN2                32804
#define ID_VIEW_VSCREEN3                32805
#define ID_VIEW_VSCREEN4                32806
#define ID_APP_CLOSEALL                 32807
#define ID_APP_CLOSEA                   32808
#define ID_VIEW_FULLSCREEN              32809
#define ID_RELOADMAP                    32810
#define ID_APP_PRINT                    32811
#define ID_FIRSTTAB                     32813
#define ID_VIEW_CASCADE                 32814
#define ID_VIEW_TILE_VERT               32815
#define ID_VIEW_TILE_HORZ               32816
#define ID_APP_RECONNECT                32817
#define ID_VIEW_JCONTROL                32818
#define ID_APP_PRINT_SETUP              32819
#define ID_APP_ORDERSETUP               32820
#define ID_APP_ACCSETTING               32821
#define ID_APP_CALC                     32824
#define ID_APP_MEMO                     32825
#define ID_APP_SAVEBMP_A                32827
#define ID_VIEW_FITMONITOR              32829
#define ID_RTS                          32830
#define ID_SHOWTRACER                   32830
#define ID_APP_NEWSETUP                 32831
#define ID_APP_CERTIFY                  32832
#define ID_APP_ESETUP                   32833
#define ID_APP_EDITTOOL                 32834
#define ID_APP_TICKERSETUP              32835
#define ID_APP_CHANGEPASSWORD           32837
#define ID_VIEW_TICKER2                 32838
#define ID_VIEW_TICKER3                 32839
#define ID_VIEW_VSCREEN5                32840
#define ID_VIEW_VSCREEN6                32841
#define ID_VIEW_ACCTOOL                 32842
#define ID_VIEW_MDI                     32843
#define ID_VIEW_SDI                     32844
#define ID_VIEW_TRAY                    32845
#define ID_APP_HELPCOM                  32846
#define ID_APP_LINKEXCEL                32847
#define ID_APP_MNGSETUP                 32849
#define ID_VIEW_DUAL                    32850
#define ID_APP_TOTALSETUP               32851
#define ID_APP_IMAGESETUP               32852
#define ID_APP_REGINTER                 32853
#define ID_APP_HTSSEARCH                32854
#define ID_VIEW_KONGI                   32855
#define ID_APP_PINCH                    32857
#define ID_APP_HOTKEYSETUP              32858
#define ID_VIEW_TR_MSG                  32862
#define ID_32866                        32866
#define ID_APP_CHATHIDE                 32867
#define ID_32868                        32868
#define ID_32869                        32869
#define ID_32870                        32870
#define ID_32871                        32871
#define ID_32872                        32872
#define ID_32873                        32873
#define ID_APP_SAVECLIP_A               32874
#define ID_APP_SAVECLIP                 32875
#define ID_APP_END                      32900
#define ID_VIEW_INVEST_SETUP            33000
#define ID_VIEW_CONCLUDE_SETUP          33001
#define ID_MENU_TB2                     33002
#define ID_VIEW_TICKER                  33003
#define ID_VIEW_TICKER_SETUP            33004
#define ID_VIEW_TICKERX                 33005
#define ID_VIEW_TICKERX_SETUP           33006
#define AXIS_ST_BASE                    40000
#define ST_FONTNAME_DEFAULT             40001
#define ST_FONTNAME_DEFAULT2            40002
#define ST_TEXT_HOUR                    40003
#define ST_TEXT_MINUTE                  40004
#define ST_TEXT_SECOND                  40005
#define ST_MSG_FIND_OPTIMUM_SERVER      40006
#define ST_TEXT_AUTOCONNECT             40007
#define ST_MSG_CANCEL_AUTOCONNECT       40008
#define ST_MSG_FAIL_CONNECT             40009
#define ST_MSG_TRY_CONNECT              40010
#define ST_MSG_INPUT_CORRECT_USERID     40011
#define ST_TEXT_OK                      40012
#define ST_MSG_RECONNECT_OTHERUSER      40013
#define ST_TEXT_RECONNECT_OTHERUSER     40014
#define ST_MSG_DISCONNECT_EXIT          40015
#define ST_MSG_DISCONNECT_RETRY         40016
#define ST_TEXT_PROGRAMEXIT             40017
#define ST_MSG_NOTHING_SELECTED         40018
#define ST_TEXT_MMGB                    40019
#define ST_TEXT_CONFIRM_CNT             40020
#define ST_TEXT_ORDER_PRICE             40021
#define ST_MSG_FAIL_WINDOWCREATE        40022
#define ST_TEXT_STOP                    40023
#define ST_MSG_LOGINERROR               40023
#define ST_TEXT_RECEIVE                 40024
#define ST_SYMBOL_LEFT                  40025
#define ST_SYMBOL_RIGHT                 40026
#define ST_MSG_INPUT_SCREENNAME         40027
#define ST_TEXT_USERWORKSPACELIST       40028
#define ST_MSG_CHANGE_WORKSPACENAME     40029
#define ST_MSG_NOSERVERNAME             40030
#define ST_MSG_OVERWRITESERVERNAME      40031
#define ST_MSG_EXISTPORT                40032
#define ST_TEXT_ACCNAME                 40033
#define ST_TEXT_ACCOUNTNO               40034
#define ST_TEXT_ACCPASS                 40035
#define ST_MSG_NOACCINFO                40036
#define ST_MSG_SAVEACCOK                40037
#define ST_MSG_SAVEACCFAIL              40038
#define ST_SAVEID_TEXT                  40039
#define ST_TEXT_CLOCKFONT               40040
#define ST_TEXT_HIDECLOCK               40041
#define ST_USEINFO_UPTITLE              40042
#define ST_USEINFO_DOWNTITLE            40043
#define ST_USEINFO_STARTUPGUIDE         40044
#define ST_USEINFO_STARTDOWNGUIDE       40045
#define ST_USEINFO_MSGTITLE             40046
#define ST_USEINFO_TEXT_NOFILELIST      40047
#define ST_USEINFO_TEXT_QUERYFILELIST   40048
#define ST_USEINFO_TEXT_NOCHECKFILE     40049
#define ST_USEINFO_TEXT_UPLOADDING      40050
#define ST_USEINFO_TEXT_DOWNLOADDING    40051
#define ST_USEINFO_TEXT_ENDWORK         40052
#define ST_USEINFO_TEXT_ERRORMSG        40053
#define ST_SETUP_SERVERNAME             40054
#define ST_SETUP_PORT                   40055
#define ST_SETUP_TEST                   40056
#define ST_TEXT_NORMCLOCK               40057
#define ST_TEXT_MINICLOCK               40058
#define ST_MSG_MODALEXIT                40059
#define ID_MAP_HELP                     57670

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        477
#define _APS_NEXT_COMMAND_VALUE         32878
#define _APS_NEXT_CONTROL_VALUE         1225
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
