//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by awUser.rc
//
#define IDC_SYMTREE                     14000
#define IDC_SYMLIST                     14001
#define IDB_UTREE                       14001
#define IDC_R_IN                        14002
#define IDC_R_IO                        14003
#define IDC_R_OUT                       14004
#define IDC_RECEIVE                     14005
#define IDC_SHOW                        14006
#define IDC_FRAME                       14008
#define IDC_SECTION                     14009
#define IDC_PROJECT                     14010
#define IDC_MSG                         14011

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        14004
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         14012
#define _APS_NEXT_SYMED_VALUE           14000
#endif
#endif
