#if !defined(AFX_KBCHART_H__C99E556C_E2A2_4771_9274_0FF8AB0AE538__INCLUDED_)
#define AFX_KBCHART_H__C99E556C_E2A2_4771_9274_0FF8AB0AE538__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CKBChart wrapper class

class CKBChart : public CWnd
{
protected:
	DECLARE_DYNCREATE(CKBChart)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x2eefb3af, 0x138d, 0x489c, { 0x99, 0x30, 0x6, 0x3e, 0xce, 0xfc, 0xb8, 0x6 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

	// 가로 scale 위치
	enum HORZSCALEPOSITION
	{
		HORZ_TOP,
		HORZ_BOTTOM,
		HORZ_BOTH,
		HORZ_HIDE,
		HORZ_NONE
	};
	
	// 세로 scale 위치
	enum VERTSCALEPOSITION
	{
		VERT_LEFT,
		VERT_RIGHT,
		VERT_BOTH,
		VERT_NONE
	};
	
// Attributes
public:
	BOOL GetEnabled();
	void SetEnabled(BOOL);
	OLE_HANDLE GetHWnd();
	void SetHWnd(OLE_HANDLE);
	BOOL GetBNormalizedMinuteTimeRule();
	void SetBNormalizedMinuteTimeRule(BOOL);
	long GetNBlockType();
	void SetNBlockType(long);
	long GetNBlockCompart();
	void SetNBlockCompart(long);
	long GetNBlockRowCount();
	void SetNBlockRowCount(long);
	long GetNBlockColumnCount();
	void SetNBlockColumnCount(long);
	long GetNBlockGap();
	void SetNBlockGap(long);
	long GetNBlockBorderThickness();
	void SetNBlockBorderThickness(long);
	CString GetStrAddInLoadList();
	void SetStrAddInLoadList(LPCTSTR);
	long GetNBorderType();
	void SetNBorderType(long);
	long GetNScaleLineType();
	void SetNScaleLineType(long);
	BOOL GetBWholeView();
	void SetBWholeView(BOOL);
	long GetNOnePageDataCount();
	void SetNOnePageDataCount(long);
	long GetNUserBlockAddCount();
	void SetNUserBlockAddCount(long);
	BOOL GetBGraphDragDrop();
	void SetBGraphDragDrop(BOOL);
	long GetNLeftMargin();
	void SetNLeftMargin(long);
	long GetNRightMargin();
	void SetNRightMargin(long);
	long GetNTopMargin();
	void SetNTopMargin(long);
	long GetNBottomMargin();
	void SetNBottomMargin(long);
	BOOL GetBAddGraphMenuShow();
	void SetBAddGraphMenuShow(BOOL);
	CString GetStrUserEnvironmentFileName();
	void SetStrUserEnvironmentFileName(LPCTSTR);
	CString GetStrUserIndicatorListFileName();
	void SetStrUserIndicatorListFileName(LPCTSTR);
	CString GetStrUserSeriesListFileName();
	void SetStrUserSeriesListFileName(LPCTSTR);
	BOOL GetBHide();
	void SetBHide(BOOL);
	BOOL GetBIsInput();
	void SetBIsInput(BOOL);
	CString GetStrToolbarOption();
	void SetStrToolbarOption(LPCTSTR);
	CString GetStrPacketOption();
	void SetStrPacketOption(LPCTSTR);
	CString GetStrLocalSharedList();
	void SetStrLocalSharedList(LPCTSTR);
	BOOL GetBUseRealData();
	void SetBUseRealData(BOOL);
	CString GetStrRealList();
	void SetStrRealList(LPCTSTR);
	short GetNMarginBorderType();
	void SetNMarginBorderType(short);
	long GetNRowDoubleSizeBlock();
	void SetNRowDoubleSizeBlock(long);
	BOOL GetBUseInquiryDlgWhenUseCrossLine();
	void SetBUseInquiryDlgWhenUseCrossLine(BOOL);
	long GetNColumnDoubleSizeBlock();
	void SetNColumnDoubleSizeBlock(long);
	BOOL GetBUseShortKey();
	void SetBUseShortKey(BOOL);
	BOOL GetBUseConditiontoTitle();
	void SetBUseConditiontoTitle(BOOL);
	BOOL GetBUseDatatoTitle();
	void SetBUseDatatoTitle(BOOL);
	short GetNHorzGap();
	void SetNHorzGap(short);
	short GetNVertGap();
	void SetNVertGap(short);
	short GetNRButtonMenuType();
	void SetNRButtonMenuType(short);
	BOOL GetBShowWarningMessageBox();
	void SetBShowWarningMessageBox(BOOL);
	BOOL GetBControlBlockSize();
	void SetBControlBlockSize(BOOL);
	BOOL GetBBlockMoveDelete();
	void SetBBlockMoveDelete(BOOL);
	BOOL GetBSelectTitle();
	void SetBSelectTitle(BOOL);
	BOOL GetBSelectGraph();
	void SetBSelectGraph(BOOL);
	BOOL GetBUseScaleRButtonMenu();
	void SetBUseScaleRButtonMenu(BOOL);
	short GetNGraphRButtonType();
	void SetNGraphRButtonType(short);
	short GetNHoldingPacketSize();
	void SetNHoldingPacketSize(short);
	CString GetSzBasePacketName();
	void SetSzBasePacketName(LPCTSTR);
	BOOL GetBRedrawAfterUpdatedAllPackets();
	void SetBRedrawAfterUpdatedAllPackets(BOOL);
	short GetNMinDataCountOnOnePage();
	void SetNMinDataCountOnOnePage(short);
	BOOL GetBFireRealEvent();
	void SetBFireRealEvent(BOOL);
	short GetNInquiryType();
	void SetNInquiryType(short);
	BOOL GetBOcxAreaNumericalInquiry();
	void SetBOcxAreaNumericalInquiry(BOOL);
	long GetNNumericalInquiryOption();
	void SetNNumericalInquiryOption(long);
	CString GetStrGlobalSharedList();
	void SetStrGlobalSharedList(LPCTSTR);
	short GetNUseInquiryWithCrossline();
	void SetNUseInquiryWithCrossline(short);
	BOOL GetBShowPriceRateInquiry();
	void SetBShowPriceRateInquiry(BOOL);
	BOOL GetBDoesUseSkinColor();
	void SetBDoesUseSkinColor(BOOL);
	CString GetStrMapName();
	void SetStrMapName(LPCTSTR);
	short GetNBongCountMargin();
	void SetNBongCountMargin(short);
	BOOL GetBOnePageDataCountInTRCount();
	void SetBOnePageDataCountInTRCount(BOOL);
	BOOL GetBIsMapDefault();
	void SetBIsMapDefault(BOOL);
	short GetNPacketCountDataSize();
	void SetNPacketCountDataSize(short);
	CString GetStrChartList();
	void SetStrChartList(LPCTSTR);
	unsigned long GetClrBackground();
	void SetClrBackground(unsigned long);
	unsigned long GetClrBackBorder();
	void SetClrBackBorder(unsigned long);
	unsigned long GetClrBlock();
	void SetClrBlock(unsigned long);
	unsigned long GetClrBlockBorder();
	void SetClrBlockBorder(unsigned long);
	unsigned long GetClrScaleLine();
	void SetClrScaleLine(unsigned long);
	unsigned long GetClrScaleText();
	void SetClrScaleText(unsigned long);
	unsigned long GetClrGraphBase1();
	void SetClrGraphBase1(unsigned long);
	unsigned long GetClrGraphBase2();
	void SetClrGraphBase2(unsigned long);
	unsigned long GetClrGraphBase3();
	void SetClrGraphBase3(unsigned long);
	unsigned long GetClrGraphBase4();
	void SetClrGraphBase4(unsigned long);
	unsigned long GetClrGraphBase5();
	void SetClrGraphBase5(unsigned long);
	unsigned long GetClrGraphBase6();
	void SetClrGraphBase6(unsigned long);
	unsigned long GetClrAnalysisTool();
	void SetClrAnalysisTool(unsigned long);
	CString GetStrBlockRegion();
	void SetStrBlockRegion(LPCTSTR);
	unsigned long GetClrScaleLine2();
	void SetClrScaleLine2(unsigned long);
	unsigned long GetClrInquiryWindow();
	void SetClrInquiryWindow(unsigned long);
	CString GetCustomFont();
	void SetCustomFont(LPCTSTR);
	unsigned long GetClrLattice();
	void SetClrLattice(unsigned long);
	CString GetStrStartDateOfData();
	void SetStrStartDateOfData(LPCTSTR);
	BOOL GetOnRunningOneChart();
	void SetOnRunningOneChart(BOOL);
	BOOL GetEnableHorizontalLineInNIDLG();
	void SetEnableHorizontalLineInNIDLG(BOOL);
	BOOL GetBShowPriceMinMaxText();
	void SetBShowPriceMinMaxText(BOOL);
	BOOL GetBHideAllTitle();
	void SetBHideAllTitle(BOOL);
	CString GetStrMapIndicatorInfo();
	void SetStrMapIndicatorInfo(LPCTSTR);
	BOOL GetBEnableIndicatorCalculation();
	void SetBEnableIndicatorCalculation(BOOL);
	BOOL GetIsShowInneerToolBar();
	void SetIsShowInneerToolBar(BOOL);

// Operations
public:
	BOOL SetAllProperties2(long dwData);
	void SetBaseDesk(long lKey);
	long GetBase(LPCTSTR szKey);
	short SetChartData(long pChartData, short nCount, short nType);
	short SetChartDataStr(LPCTSTR szChartData, short nCount, short nType);
	short testGetPacketdatasize(LPCTSTR pIn);
	void testLoadAnalysisTools(short nToolOption, short nOption);
	void MakeSaveShortKey(LPCTSTR szFileName, short nFlag);
	short ChangeChart(short nBlockRowPosition, short nBlockColumnPosition, LPCTSTR strGraphTitle, LPCTSTR strGraphName, LPCTSTR strPacketName, LPCTSTR strGraphType, LPCTSTR strGraphStyle, short nLineWidth, unsigned long clrLineColor);
	short ClearChartData(short nOption);
	short SetGraphHide(short nRow, short nColumn, LPCTSTR strTitle, BOOL bHide);
	BOOL AddChartBlock(LPCTSTR strChartName);
	void SetOnePageDataCount(long nOnePageDataCount);
	long GetOnePageDataCount();
	BOOL SaveandOpenFromFile(LPCTSTR strOpenFileName, LPCTSTR strSaveFileName, BOOL bOpenOption, BOOL bSaveOption);
	BOOL JoinandDevisionforCompareChart(long nRowCount, long nColumnCount, BOOL bJoin);
	BOOL ChangeGraphTitle(short nRowIndex, short nColumnIndex, short nGraphIndex, LPCTSTR strNewTitle);
	short SetChartDataFromFile(LPCTSTR szFileName, short nType);
	BOOL RemoveChart(LPCTSTR strChartName);
	BOOL ChangeGraphType(LPCTSTR strGraphName, LPCTSTR strGraphType, LPCTSTR strGraphStyle, LPCTSTR strPacketNameList, BOOL bRunatOnce);
	void SetChartAllInfo();
	CString GetData(LPCTSTR strPacketName, short nDataIndex);
	BOOL SetDrdsAdvise(BOOL bOnAdvise);
	short GetDataCount();
	BOOL ChangeChartItem(LPCTSTR strGraphName, short nSubGraphIndex, LPCTSTR strNewTitle, LPCTSTR strNewPacketName, LPCTSTR strNewGraphType, LPCTSTR strNewGraphStyle, short nNewUpLineWidth, short nNewDownLineWidth, short nNewEqualLineWidth, 
		BOOL bRunatOnce);
	BOOL SetStopLossPrice(BOOL bIsStopLoss, double dStopLossPrice, BOOL bIsProfit, double dProfitPrice);
	BOOL RestoreMinMax(LPCTSTR strPacketName);
	BOOL RestoreMin(LPCTSTR strPacketName);
	BOOL RestorMax(LPCTSTR strPacketName);
	BOOL SetMin(LPCTSTR strPacketName, double dMin);
	BOOL SetMax(LPCTSTR strPacketName, double dMax);
	BOOL SetMinMax(LPCTSTR strPacketName, double dMin, double dMax);
	BOOL SetHorzScaleData(short nRowIndex, short nColumnIndex, LPCTSTR strScaleData);
	double GetMin(LPCTSTR strPacketName);
	double GetMax(LPCTSTR strPacketName);
	BOOL SetGraphHide2(short nRowIndex, short nColumnIndex, short nVerticalIndex, short nGraphIndex, short nSubGraphIndex, BOOL bHide);
	BOOL ChangeGraphDatas(short nRowIndex, short nColumnIndex, short nVerticalIndex, short nGraphIndex, LPCTSTR strNewGraphName, LPCTSTR strNewTitle, LPCTSTR strNewPacketName, LPCTSTR strNewGraphType, LPCTSTR strNewGraphStyle, 
		short nNewUpLineWidth, short nNewDownLineWidth, short nNewEqualLineWidth, BOOL bRunatOnce);
	void SaveandApplyGraphStyle(short nSaveDataType, short nChangeDataType);
	void SetDataRegionInBlock(short nDataStartIndex);
	void SetItemInfo(LPCTSTR lpstrCode, LPCTSTR lpstrName);
	void AddandDeleteIndicator(LPCTSTR strGraphName);
	long GetAllProperties2(long lpData);
	long GetBasePropIf();
	BOOL SetVertScaleData(short nRowIndex, short nColumnIndex, short nVertScaleGroupIndex, LPCTSTR strVertScaleData);
	BOOL ChangeBlockType(short nBlockType, short nRowCount, short nColumnCount);
	BOOL ChangeHorzScalePosition(short nScalePosition, short nRowIndex, short nColumnIndex);
	BOOL ResetChart();
	void SetRealData(LPCTSTR strPacketName, double dData, short nOption);
	BOOL SetGraphTitle(LPCTSTR strGraphName, short nSubGraphIndex, LPCTSTR strNewGraphTitle, BOOL bGraphShowing);
	CString GetIndicatorNameList(LPCTSTR p_strGroup);
	void AddGraph(short nRow, short nColumn, short nVertScaleGroup, LPCTSTR szGraphOption, BOOL bCreateBlock, BOOL bCreateVertScaleGroup, BOOL bUseAutoScale);
	void AddPacket(LPCTSTR szPacketOption);
	long RemovePacket(LPCTSTR szPacketName);
	void SetContainerDllInfo(long p_lDllWnd, short p_nID);
	BOOL SetPacketData(LPCTSTR szPacketName, long szData, long lLength, BOOL bReset);
	void SetBackgroundColors(unsigned long p_rgbBlockArea, unsigned long p_rgbScaleArea);
	BOOL AddRealItem(LPCTSTR szRealInfo);
	void ShowIndicatorConfigDlg();
	void ResetChartCfgWith(short p_nIndex);
	BOOL EmptyChart(BOOL bIsDeleteAllPacket, BOOL bIsDefault);
	BOOL HasGraph(LPCTSTR p_szGraphName);
	void RemoveRealItem(LPCTSTR szRealInfo);
	void ShowInnerToolBar(BOOL p_bShow);
	BOOL ChangeVertScalePosition(short nScalePosition, short nRowIndex, short nColumnIndex, short nVSGroupIndex);
	short GetRowBlockCount();
	short GetColumnBlockCount();
	BOOL SetStartPeriodOfPacket(LPCTSTR p_szPacketName, long p_lStartPeriod, long p_bAddSpace);
	long GetStartPeriodOfPacket(LPCTSTR p_szPacketName);
	BOOL GetStartEndDateOnView(double* p_pStartDate, double* p_pEndDate);
	BOOL SetStartEndDateOfView(double p_dStartDate, double p_dEndDate);
	BOOL ScrollToDataOfEnd(double p_dData);
	short ZoomToWithRightFix(short p_nZoomValue, BOOL p_bWithRightFix);
	void ClearTimeMark();
	void ShowEnvironmentDlg();
	void SetTimeMark(LPCTSTR p_szMarkTime, BOOL p_bWithScroll);
	short GetVertScalePosition(short p_nRowIndex, short p_nColumnIndex, short p_nVSGroupIndex);
	void EnableBoundMark(BOOL p_bEnable);
	void EnableReceivingTimeShare(BOOL p_bEnable);
	BOOL ChangePacketType(LPCTSTR p_szPacketName, LPCTSTR p_szPacketType);
	BOOL ChangeGraphDrawingData(LPCTSTR p_szGraphName, BOOL p_bLowHigh, BOOL p_bLowCur, BOOL p_bHighCur, BOOL p_bPrevCur, short p_nCurData);
	BOOL ChangePriceGraphDrawingData(BOOL p_bLowHigh, BOOL p_bLowCur, BOOL p_bHighCur, BOOL p_bPrevCur, short p_nCurData, short p_nDefaultType);
	void ShowAnalysisToolText(BOOL p_bTimeLine, BOOL p_bPriceLineLeft, BOOL p_bPriceLineRight, BOOL p_bTrendLine, BOOL p_bTrisectionLine, BOOL p_bQuadrisectionLine, BOOL p_bFibonacciRetraceLine);
	BOOL HasGraphInSpecialBack(LPCTSTR p_szGraphName);
	BOOL LoadAddIn(LPCTSTR p_szAddInDllName);
	BOOL InvokeAddIn(LPCTSTR p_szAddInDllName, short p_nCommandType, long p_lData);
	void SetDragModeType(short p_nDragModeType);
	BOOL ResetRealListString(LPCTSTR p_szRealList, BOOL p_bAdviseNow);
	BOOL AddOrRemoveChart(LPCTSTR strGraphName);
	void SetHtsPath(LPCTSTR pcszHtsPath);
	CString GetRealSettingInfo();
	void SetAllLogScale(BOOL bLogScale);
	void GetListViewerData(BSTR* bstrTitle, BSTR* bstrHorzScale, BSTR* bstrPacketNamesPerBlock, BSTR* bstrPacketNames, BSTR* bstrSaveFilePath, BOOL* bViewPacketSequence, long* lpPacketList);
	void SetDataIndexByDate(LPCTSTR pcszStartDate, LPCTSTR pcszEndDate);
	void SetRunTimeMode(BOOL bRunTimeMode);
	CString GetPacketOption();
	void SetPacketOption(LPCTSTR strPacketOption);
	void SetOutsideCommonInterface(long lpOutsideCommonInterface);
	BOOL RemoveGraph_Title(short nRowIndex, short nColumnIndex, LPCTSTR szGraphTitle, BOOL bIsOnlyNoTRData, BOOL bIsAutoHorzScalePosition);
	CString GetGraphPacketName(short nRowIndex, short nColumnIndex, LPCTSTR szGraphTitle);
	BOOL ChangeGraphTitle2(LPCTSTR szTargetTitle, LPCTSTR szSourceTitle);
	BOOL PartitionAllGraph();
	BOOL JoinAllGraph(BOOL bIsOneVertScaleGroup);
	BOOL ChangeAllFunctionName(LPCTSTR szTargetGraphName, LPCTSTR szSourceGraphName, BOOL bKeepOldGraphColor);
	BOOL ChangeIndicatorPacketName(LPCTSTR strGraphName, short nSubGraphIndex, LPCTSTR strNewPacketName);
	void RunEnvironmentDlg(short nOption);
	BOOL SetIndicatorCondition(LPCTSTR strGraphName, short nConditionType, short nConditionIndex, double dConditionValue, BOOL bReCalculate);
	BOOL SetPacketData2(LPCTSTR strPacketName, LPCTSTR strPacketType, LPCTSTR strPacketData, short nDataCount, BOOL bReCalculate);
	BOOL SetLogScale(LPCTSTR strGraphName, BOOL bLogScale);
	BOOL GetLogScale(LPCTSTR strGraphName);
	BOOL SetPacketHelpMessage(LPCTSTR strHelpMsg, BOOL bIsAllRemove);
	BOOL InvokeAddInStr(LPCTSTR p_szAddInDllName, LPCTSTR p_szCommandName, LPCTSTR p_szData);
	BOOL SetHelpMessageRealDataRate(LPCTSTR strHelpMessageData, BOOL bIsRemove);
	void SetBongCountMargin(short nBongCountMargin);
	BOOL SetAllPropertiesFromFile(LPCTSTR strFilePath, LPCTSTR strFileName);
	BOOL SetGraphHide3(LPCTSTR strTitle, BOOL bIsHide);
	BOOL GetBoundMarkFlag();
	BOOL UnloadAddIn(LPCTSTR p_szAddInDllName);
	void SetOnePageDataCount2(long nOnePageDataCount, BOOL bIncludeBongCountMargin);
	BOOL ClearPacketData(LPCTSTR strPacketName, BOOL bIsAbsoluteClear);
	void SetAllGraphHide(short nRowIndex, short nColumnIndex, short bHide);
	void InitStaticIndiCond(LPCTSTR p_szBasePath);
	void SetAllGraphsHide(short nRowIndex, short nColumnIndex, BOOL bHide);
	CString GetPacketData2(LPCTSTR strPacketName, short nDataIndex, BOOL bIsFullDataSize);
	CString GetSelectedSubGraphData(short nPoint_x, short nPoint_y);
	short GetPacketIndex(LPCTSTR szPacketName, double dKeyValue);
	short GetCurrentPriceChartType();
	BOOL RemoveBlock(short nPoint_x, short nPoint_y);
	BOOL RemoveGraph(short nRowIndex, short nColumnIndex, LPCTSTR strGraphTitle);
	BOOL SetGraphColor(short nRowIndex, short nColumnIndex, short nVertScaleGroupIndex, short nGraphIndex, short nSubGraphIndex, LPCTSTR strNewColor);
	BOOL SetPacketDataInIndex(LPCTSTR strPacketName, short nIndex, LPCTSTR strData, BOOL bIsRealData);
	BOOL SetVertScaleLogType(short nRowIndex, short nColumnIndex, BOOL bIsLogType);
	BOOL OpenFileOfEnvAndIndi(LPCTSTR strFileName_Env, LPCTSTR strFileName_Indi, BOOL bIsCurrentSave);
	BOOL SetPacketDataInAdditionPacket(LPCTSTR szPacketName, long szData, long lLength, BOOL bReset);
	void SetOnePageDataCountInTRCount(BOOL bIsTRCount, BOOL bIsNowChange);
	void PrintChatImage();
	void ExportToExcel();
	BOOL RunToolFunction(short nToolCommand, short nOption);
	BOOL SetSubIndicatorCondition(LPCTSTR strGraphName, short nConditionType, short nSubGraphIndex, short nConditionIndex, double dConditionValue, BOOL bReCalculate);
	BOOL SetGraphHide4(LPCTSTR strGraphName, short nSubGraphIndex, BOOL bHide);
	BOOL SetMapDefaultInCurrent(BOOL bIsNewMapDefault);
	BOOL ChangeFunctionName(LPCTSTR p_szTargetFName, LPCTSTR p_szNewFName, LPCTSTR p_szNewSGName);
	BOOL GetHeadAndTailData(LPCTSTR strPacketName, double* pHeadData, double* pTailData);
	LPUNKNOWN GetAddInCustomInterface(LPCTSTR p_szAddInName);
	BOOL LoadAddInWithOverExclusive(LPCTSTR p_szAddInName);
	BOOL OpenFromFile(LPCTSTR p_szFileName, BOOL p_bAutoPrevSave);
	BOOL SaveandOpenFromFileWithMSave(LPCTSTR strOpenFileName, LPCTSTR strSaveFileName, BOOL bOpenOption, BOOL bSaveOption);
	BOOL AddRealItemWithSeparator(LPCTSTR szRealInfo, LPCTSTR szSeparatorChar);
	void RemoveRealItemWithSeparator(LPCTSTR szRealInfo, LPCTSTR szSeparatorChar);
	long GetAllProperties3(long p_lIPropertyMap);
	long SetAllProperties3(long p_lIPropertyMap);
	BOOL ShowIndicatorConfigDlgWithName(LPCTSTR p_szGraphName);
	BOOL RemoveBlockWithIndex(short p_nRowIndex, short p_nColumnIndex);
	BOOL SetBinTrHelpMsg(LPCTSTR p_szHelpMessage);
	BOOL SetBinTrDoubleData(LPCTSTR p_szPacketName, long p_nCount, double* p_pdData);
	BOOL SetBinTrStringData(LPCTSTR p_szPacketName, long p_nCount, long p_lData);
	BOOL SetBinTrEnd();
	BOOL EmptyChart2(LPCTSTR p_szChartList, BOOL p_bIsDeleteAllPacket, BOOL p_bIsDefault);
	short GetHorzScalePosition(short p_nRowIndex, short p_nColumnIndex);
	BOOL HasIndicator(LPCTSTR p_szIndicatorName);
	BOOL HasIndicatorInSpecialBack(LPCTSTR p_szIndicatorName);
	BOOL LockWindowUpdate();
	void UnlockWindowUpdate();
	CString AddChartItem(LPCTSTR lpszItemCode, LPCTSTR lpszItemName, BOOL bBuiltChart);
	void SetRealDataCode(LPCTSTR strCode, LPCTSTR strPacketName, double dData, short nOption);
	void ShowIndicator(LPCTSTR p_szIndicatorName, BOOL p_bShow, BOOL p_bRecalculate);
	void SetPacketAutoScaleType(LPCTSTR p_szPacketName, BOOL p_bAutoScaleType);
	BOOL SetPacketTypeWithAutoScale(LPCTSTR p_szPacketName, LPCTSTR p_szPacketType, BOOL p_bAutoScale);
	void ShowBaseText(BOOL p_bShow);
	BOOL ChangeGraphColor(LPCTSTR p_szGraphTitle, LPCTSTR p_szColors);
	void AddPacketRQ(LPCTSTR lpszRQ, LPCTSTR lpszPacketOption);
	BOOL SetPacketDataRQ(LPCTSTR lpszRQ, LPCTSTR lpszPacketName, long nData, long nLength, BOOL bReset);
	BOOL AddChartItemRQ(LPCTSTR lpszRQ, LPCTSTR lpszItemCode, LPCTSTR lpszItemName);
	void SetCurrentRQ(LPCTSTR lpszRQ);
	void SetResetTotalCountWhileDraw(BOOL bReset);
	void SetFutureScaleVisible(long nScaleVisible);
	void SetMultiItemMode(BOOL bMultiItem);
	void SetVertScaleType(short nBlockRow, short nBlockCol, short nScaleGroup, short nScaleType, double dTypeValue);
	void SetHorizontalScaleHeight(long nHeight);
	BOOL EmptyChart3(LPCTSTR lpszChartList, BOOL bIsDeleteAllPacket, BOOL bIsDefault, short nBlockCount);
	BOOL AddChartAllBlock(LPCTSTR strChartName);
	void ChangeGraphPropertyAtOnce(LPCTSTR lpszRQ, LPCTSTR lpszTargetTitle, LPCTSTR lpszNewTitle, short nGraphType, short nGraphStyle, short nDrawStyle, LPCTSTR lpszColors, short nThickness1, short nThickness2, short nThickness3);
	BOOL RemoveGraphRQ(LPCTSTR lpszRQ, LPCTSTR lpszTitle);
	void SetUseSTExtData(LPCTSTR lpszExtDataName);
	BOOL ShowGraphDataDrawingData(LPCTSTR lpszRQ, LPCTSTR lpszIndicatorName, BOOL bShow, short nShowType);
	void ShowSelEnvironmentDlg(short nPage);
	long GetVertScaleGroupCount(short nRow, short nColumn);
	void SetSyncPacketData(LPCTSTR strSyncPacketNames);
	void SetEmptyChart();
	void SetDrawVerticalBox(double dHorzValue, LPCTSTR strColor, BOOL bFill);
	BOOL SaveandOpenFromAnalToolFile(LPCTSTR lpszOpenFileName, LPCTSTR lpszSaveFileName, BOOL bOpenOption, BOOL bSaveOption);
	void UseDummyPacketData(BOOL bUse);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_KBCHART_H__C99E556C_E2A2_4771_9274_0FF8AB0AE538__INCLUDED_)
