//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SystemTrading.rc
//
#define IDR_MANIFEST                    1
#define IDD_ABOUTBOX                    100
#define IDR_VIEWEDITORCONFIG_TMPL       103
#define IDR_MAINFRAME                   128
#define IDR_GUI_VITYPE                  129
#define ID_FILE_NEW_PROJECT             130
#define ID_FILE_NEW_BLANK               131
#define ID_FILE_OPEN_PROJECT            132
#define ID_EDIT_SELECTALL               136
#define ID_EDIT_FINDANDREPLACE          137
#define ID_FINDANDREPLACE_FIND          138
#define IDR_DYNAMIC_HELP                138
#define ID_FINDANDREPLACE_REPLACE       139
#define ID_FINDANDREPLACE_FINDINFILES   140
#define ID_VIEW_OPEN                    141
#define ID_Menu147                      147
#define ID_VIEW_WEBBROWSER              148
#define ID_WEBBROWSER_HOME              149
#define ID_WEBBROWSER_SEARCH            150
#define ID_WEBBROWSER_BACK              151
#define ID_WEBBROWSER_FORWARD           152
#define ID_VIEW_TOOLBARS                153
#define ID_VIEW_FULLSCREEN              154
#define ID_VIEW_TOOLBARS155             155
#define ID_PROJECT_ADDRESOURCE          156
#define ID_PROJECT_ADDNEWITEM           157
#define ID_PROJECT_ADDEXISTINGITEM      158
#define ID_PROJECT_NEWFOLDER            159
#define ID_BUILD_BUILDSOLUTION          160
#define ID_BUILD_REBUILDSOLUTION        161
#define ID_BUILD_CLEANSOLUTION          162
#define IDB_FILETREE                    162
#define ID_BUILD_COMPILE                163
#define ID_DEBUG_WINDOWS                164
#define IDB_CLASSTREE                   164
#define IDB_RESTREE                     165
#define ID_DEBUG_STARTWITHOUTDEBUG      167
#define ID_DEBUG_PROSSESES              168
#define ID_DEBUG_EXCEPTIONS             169
#define ID_DEBUG_STEPINTO               170
#define ID_DEBUG_STEPOVER               171
#define ID_TOOLS_OPTIONS                172
#define ID_HELP_CONTENTS                174
#define ID_HELP_INDEX175                175
#define ID_HELP_SEARCH                  176
#define IDR_TOOLBAR_EXT                 177
#define ID_FILE_OPENSOLUTION            179
#define ID_FILE_CLOSESOLUTION           180
#define ID_DEBUG_START                  181
#define ID_PROJECT_ADDCLASS             182
#define ID_Menu                         187
#define IDB_BITMAP_PANEICONS            188
#define IDR_TOOLBAR_WEB                 189
#define ID_WEBBROWSER_STOP              190
#define ID_WEBBROWSER_REFRESH           191
#define ID_WEBBROWSER_FAVORITES         192
#define ID_WEBBROWSER_ORGANIZE          193
#define ID_BUTTON32806                  194
#define ID_WEBBROWSER_FONT              195
#define ID_WEBBROWSER_SYNC              196
#define ID_WEBBROWSER_PREV              197
#define ID_WEBBROWSER_NEXT              198
#define ID_VIEW_SOLUTIONEXPLORER        200
#define ID_VIEW_CLASSVIEW               201
#define ID_VIEW_RESOURCEVIEW            202
#define IDR_GUI_VITYPE1                 202
#define ID_VIEW_PROPERTIESWINDOW        203
#define ID_VIEW_TOOLBOX                 204
#define ID_WINDOWS_OUTPUT               205
#define ID_HELP_DYNAMICHELP             206
#define ID_CLASSVIEW_OUTPUT             251
#define IDD_DLG_NEWPROJECT              252
#define IDD_DLG_STEP1                   253
#define IDD_DLG_NEWSTRATEGY             256
#define IDR_TOOLBAR_BUILD               257
#define IDR_TOOLBAR_VIEW                259
#define IDB_BITMAP1                     261
#define IDB_BITMAP2                     262
#define IDR_TOOLBAR_DOCPOPUP            263
#define IDR_MENU1                       265
#define IDD_DLG_FINDSCRIPT              266
#define IDD_DLG_COMPILESTATUS           269
#define IDD_DLG_LOADSCRIPT              272
#define IDD_DLG_CONFIGEDITOR            273
#define IDD_DLG_CONFIG                  274
#define IDB_IMAGELIST                   275
#define IDB_GLYPHS                      276
#define IDD_DLG_PASSWORD                281
#define IDC_BTN_PREV                    1000
#define IDC_BTN_NEXT                    1001
#define IDC_STATIC_IMAGE                1002
#define IDC_EDIT_INPUT                  1009
#define IDC_EDIT_VALUE                  1010
#define IDC_BTN_ADD                     1011
#define IDC_LIST_INPUTS                 1012
#define IDC_BTN_DEL                     1013
#define IDC_CMB_TYPE                    1014
#define IDC_CHK_USEPASSWORD             1015
#define IDC_EDIT_PASSWORD               1016
#define IDC_EDIT_CONFIRM                1017
#define IDC_CHK_USER                    1018
#define IDC_EDIT3                       1019
#define IDC_CHECK3                      1020
#define IDC_DATEPICKER                  1022
#define IDC_TIMEPICKER                  1023
#define IDC_RDO_STRATEGY                1024
#define IDC_RDO_FUNCTION                1025
#define IDC_EDIT_NAME                   1027
#define IDC_EDIT_COMMENT                1028
#define IDC_RDO_YESTRADE                1029
#define IDC_RDO_VISAULBASIC             1030
#define IDC_CHK_STRATEGY                1031
#define IDC_CHK_FUNCTION                1032
#define IDC_PROGRESS_STATUS             1033
#define IDC_STS_STATUS                  1034
#define IDC_STATIC_RESULT               1036
#define IDC_CMB_FONT                    1047
#define IDC_BTN_RESET                   1048
#define IDC_STC_VIEW                    1049
#define IDC_TAB_CTRL                    1050
#define IDC_EDIT_HEIGHT                 1051
#define IDC_SPIN_HEIGHT                 1053
#define IDC_BTN_NORMALTEXT              1054
#define IDC_BTN_BACKGROUND              1055
#define IDC_BTN_SELTEXT                 1056
#define IDC_BUTTON1                     1056
#define IDC_BTN_SELBKGRND               1057
#define IDC_BTN_USERFUNCTION            1058
#define IDC_BTN_NOCERTFUNC              1059
#define IDC_BTN_COMMENT                 1060
#define IDC_BTN_NUMBER                  1061
#define IDC_BTN_RESERVED                1062
#define IDC_BTN_OPERATOR                1063
#define IDD_EDIT_FIND                   8601
#define IDD_EDIT_REPLACE                8602
#define IDC_EDIT_WHOLE_WORD             8603
#define IDD_DLG_STEP2_1                 8603
#define IDC_EDIT_MATCH_CASE             8604
#define IDD_DLG_STEP2_2                 8604
#define IDC_EDIT_TEXT                   8605
#define IDD_DLG_STEP3                   8605
#define IDD_DLG_STEP4                   8606
#define IDC_EDIT_REPLACE                8607
#define IDD_DLG_NEWFUNCTION             8607
#define IDC_EDIT_REPLACE_ALL            8608
#define IDC_EDIT_REPLACE_WITH           8609
#define IDC_EDIT_SKIP                   8610
#define IDC_EDIT_DIRECTION_UP           8611
#define IDC_EDIT_DIRECTION_DOWN         8612
#define IDC_EDIT_SCOPE_SELECTION        8613
#define IDC_EDIT_SCOPE_WHOLE_FILE       8614
#define IDR_MARGIN_CURSOR               22900
#define IDR_DEFAULT_ACCEL               22901
#define IDR_MARGIN_ICONS                22902
#define ID_FILE_NEW_STRATEGY            22903
#define ID_FILE_NEW_FUNCTION            22904
#define IDC_FO_SELECTCOLOR_CURSOR       25828
#define IDB_FO_COLOR_BITMAP             25829
#define ID_EDIT_STATE                   32815
#define ID_EDIT_FIND_EX                 32816
#define ID_GOTO_URL                     32817
#define ID_FILE_SAVE_ALL                32820
#define ID_BUILD_SINGLE_COMPILE         32830
#define ID_BUILD_PROPERTY               32839
#define ID_VIEW_PROPERTY                32841
#define ID_BUILD_SINGLE_COMPILE_DLL     32850
#define ID_BUILD_COMPILE_DLL            32851
#define IDM_CENTER                      32852
#define IDM_CONNECTOSERVER              32853
#define ID_BUILD_STOP                   32855
#define IDM_TRADESTATION_VIEW           32856
#define IDM_YESTRADER_VIEW              32857
#define ID_EDIT_DELETE                  37000
#define ID_EDIT_DELETE_BACK             37001
#define ID_EDIT_DELETE_WORD_BACK        37002
#define ID_EDIT_TAB                     37003
#define ID_EDIT_UNTAB                   37004
#define ID_EDIT_SWITCH_OVRMODE          37005
#define ID_EDIT_CHAR_LEFT               37100
#define ID_EDIT_EXT_CHAR_LEFT           37101
#define ID_EDIT_CHAR_RIGHT              37102
#define ID_EDIT_EXT_CHAR_RIGHT          37103
#define ID_EDIT_WORD_LEFT               37104
#define ID_EDIT_EXT_WORD_LEFT           37105
#define ID_EDIT_WORD_RIGHT              37106
#define ID_EDIT_EXT_WORD_RIGHT          37107
#define ID_EDIT_LINE_UP                 37108
#define ID_EDIT_EXT_LINE_UP             37109
#define ID_EDIT_LINE_DOWN               37110
#define ID_EDIT_EXT_LINE_DOWN           37111
#define ID_EDIT_SCROLL_UP               37112
#define ID_EDIT_SCROLL_DOWN             37113
#define ID_EDIT_PAGE_UP                 37114
#define ID_EDIT_EXT_PAGE_UP             37115
#define ID_EDIT_PAGE_DOWN               37116
#define ID_EDIT_EXT_PAGE_DOWN           37117
#define ID_EDIT_LINE_END                37118
#define ID_EDIT_EXT_LINE_END            37119
#define ID_EDIT_HOME                    37120
#define ID_EDIT_EXT_HOME                37121
#define ID_EDIT_TEXT_BEGIN              37122
#define ID_EDIT_EXT_TEXT_BEGIN          37123
#define ID_EDIT_TEXT_END                37124
#define ID_EDIT_EXT_TEXT_END            37125
#define ID_EDIT_FIND_PREVIOUS           37126
#define ID_EDIT_TOGGLE_BOOKMARK0        37200
#define ID_EDIT_TOGGLE_BOOKMARK1        37201
#define ID_EDIT_TOGGLE_BOOKMARK2        37202
#define ID_EDIT_TOGGLE_BOOKMARK3        37203
#define ID_EDIT_TOGGLE_BOOKMARK4        37204
#define ID_EDIT_TOGGLE_BOOKMARK5        37205
#define ID_EDIT_TOGGLE_BOOKMARK6        37206
#define ID_EDIT_TOGGLE_BOOKMARK7        37207
#define ID_EDIT_TOGGLE_BOOKMARK8        37208
#define ID_EDIT_TOGGLE_BOOKMARK9        37209
#define ID_EDIT_GO_BOOKMARK0            37210
#define ID_EDIT_GO_BOOKMARK1            37211
#define ID_EDIT_GO_BOOKMARK2            37212
#define ID_EDIT_GO_BOOKMARK3            37213
#define ID_EDIT_GO_BOOKMARK4            37214
#define ID_EDIT_GO_BOOKMARK5            37215
#define ID_EDIT_GO_BOOKMARK6            37216
#define ID_EDIT_GO_BOOKMARK7            37217
#define ID_EDIT_GO_BOOKMARK8            37218
#define ID_EDIT_GO_BOOKMARK9            37219
#define ID_EDIT_TOGGLE_BOOKMARK         37223
#define ID_EDIT_GOTO_NEXT_BOOKMARK      37224
#define ID_EDIT_GOTO_PREV_BOOKMARK      37225
#define ID_EDIT_CLEAR_ALL_BOOKMARKS     37226
#define ID_INDICATOR_CONNECT            37227
#define ID_INDICATOR_COMPILESTATUS      37228

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        283
#define _APS_NEXT_COMMAND_VALUE         32861
#define _APS_NEXT_CONTROL_VALUE         1057
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
