#if !defined(AFX_NTSACCTINPUT_H__79BE251C_BED7_49B4_8554_6691A7F755C8__INCLUDED_)
#define AFX_NTSACCTINPUT_H__79BE251C_BED7_49B4_8554_6691A7F755C8__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CNtsAcctInput wrapper class

class CDispAcctInput : public COleDispatchDriver
{
public:
	CDispAcctInput();
	
//{{ Dispid 자동처리
public:
	LPDISPATCH m_pdispatch;

	// 1. 변수선언. m_pdID, m_osInterfaceName[]
	DISPID*			m_pdID;
	static OLECHAR *	m_osInterfaceName[];

	// 2. enum 추가, 필요한 것만 리스트업.
	typedef enum {
		// Variable
		IIx_SetText,
		IIx_GetText,
		IIx_GetDataText,
		IIx_GetBase,
	};

	// 3. void InitInterfaceName(IDispatch *pDisp);
	void InitInterfaceName(IDispatch *pDisp);

public:

	CString GetText();
	void SetText(LPCTSTR);

	CString GetDataText();

	// Attributes
public:
	long GetCtrlBasePacket();
	long GetBase(LPCTSTR szKey);

};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_NTSACCTINPUT_H__79BE251C_BED7_49B4_8554_6691A7F755C8__INCLUDED_)

/*

// Attributes
public:
	CString GetGlobalSharedList();
	void SetGlobalSharedList(LPCTSTR);
	BOOL GetHide();
	void SetHide(BOOL);
	CString GetSStr();
	void SetSStr(LPCTSTR);
	CString GetCustomFont();
	void SetCustomFont(LPCTSTR);
	unsigned long GetBackColor();
	void SetBackColor(unsigned long);
	unsigned long GetForeColor();
	void SetForeColor(unsigned long);
	BOOL GetEnabled();
	void SetEnabled(BOOL);
	BOOL GetIsUserDefine();
	void SetIsUserDefine(BOOL);
	CString GetAcctChoice();
	void SetAcctChoice(LPCTSTR);
	CString GetOutputCtrlName();
	void SetOutputCtrlName(LPCTSTR);
	CString GetPassCtrlName();
	void SetPassCtrlName(LPCTSTR);
	BOOL GetMoveTab();
	void SetMoveTab(BOOL);
	BOOL GetWhenEqual();
	void SetWhenEqual(BOOL);
	BOOL GetButtonVisible();
	void SetButtonVisible(BOOL);
	CString GetText();
	void SetText(LPCTSTR);
	short GetMyAppearance();
	void SetMyAppearance(short);
	short GetMyBorderStyle();
	void SetMyBorderStyle(short);
	short GetPosition();
	void SetPosition(short);
	short GetEditStyle();
	void SetEditStyle(short);
	short GetButtonStyle();
	void SetButtonStyle(short);
	CString GetLocalSharedList();
	void SetLocalSharedList(LPCTSTR);
	CString GetMask();
	void SetMask(LPCTSTR);
	short GetMaxLength();
	void SetMaxLength(short);
	BOOL GetInputRequire();
	void SetInputRequire(BOOL);
	CString GetComment();
	void SetComment(LPCTSTR);
	CString GetControlID();
	void SetControlID(LPCTSTR);
	OLE_HANDLE GetHWnd();
	void SetHWnd(OLE_HANDLE);
	short GetUserBackColor();
	void SetUserBackColor(short);
	short GetUserForeColor();
	void SetUserForeColor(short);
	BOOL GetUserColorTable();
	void SetUserColorTable(BOOL);
	long GetTabKeyStop();
	void SetTabKeyStop(long);
	BOOL GetBranchNumEditable();
	void SetBranchNumEditable(BOOL);
	long GetUseDefaultFont();
	void SetUseDefaultFont(long);
	BOOL GetApplyToAll();
	void SetApplyToAll(BOOL);

// Operations
public:
	BOOL SetAllProperties2(long dwData);
	long GetBase(LPCTSTR szKey);
	void SetBaseDesk(long lKey);
	void MakeSaveShortKey(LPCTSTR szFileName, long nFlag);
	void Clear();
	CString GetDataText();
	long OnReceiveFetchData(long pData);
	void SetRscMng(long lKey);
	long GetAllProperties2(long lpData);
	long GetBasePropIf();

*/