#ifndef _MAINVAR_H_
#define _MAINVAR_H_

#define	MainPostMsg(wMsg, lMsg) AfxGetMainWnd()->PostMessage(WM_USER, wMsg, lMsg)

// main message WM_USER LOWORD(wParam)
#define	ID_USR_REFRESHCTRL	1
#define	ID_USR_SELCTRLTOPRO	2
#define	ID_USR_SELCTRLTOCHILD	3
#define	ID_USR_SERVEROPEN	4
#define	ID_USR_REDRAWCTRL	5
#define	ID_USR_SETCAPTION	6
#define	ID_USR_SETFOCUSCHILD	7
#define	ID_USR_SETGAP		8
#define	ID_USR_LOADTEMPLATE	9
#define ID_USR_FILEOPEN		10
#define	ID_USR_ISDROPAREA	11
#define ID_USR_SETFOCUSPRO	12
#define	ID_USR_DROP		13
#define ID_USR_SETGROUP		14
#define	ID_USR_REFRESHPRO	15
#define	ID_USR_GETROOTDIR	16
#define	ID_USR_GETIPS		17
#define	ID_USR_GETSRCVIEWER	18
#define	ID_USR_GETGAP		19
#define	ID_USR_SETROOTDIR	20
#define	ID_USR_SETIPS		21
#define	ID_USR_SETSRCVIEWER	22
#define	ID_USR_GETGROUP		23
#define	ID_USR_GETCOLOR		24
#define	ID_USR_STATUSERR	25
#define	ID_USR_SYMTBL		26
#define	ID_USR_REMOVECHILD	27
#define	ID_USR_DROPPNT		28
#define	ID_USR_ISOFFLINE	29

#define	ID_USR_MODAL		30

#define	ID_USR_SETFOCUSWRK	31
#define	ID_USR_SETUNDO		32
#define	ID_USR_STATUSLINEINFO	33
#define	ID_USR_SETFINDCAPTION	34
#define	ID_USR_CURRENTWORD	35
#define	ID_USR_GETCONTROLEVENT	36

#define	ID_USR_GETWIZARD	37	// ??

#define	ID_USR_ENABLEPROP	38
#define	ID_USR_PROGRESS		39
#define	ID_USR_SETOFFLINE	40
#define	ID_USR_GETCORGB		41

#define	ID_USR_MOUSETIP		43		// lParam : string, HIWORD(wParam) : show/hide
#define	ID_USR_SETMAPNAME	44

#define	ID_USR_SCRIPTEVENT	47

#define	ID_USR_TBPRESSBTN	49

#define	ID_USR_GETCURRENTPATH	51
#define	ID_USR_ALLVIEWREDRAW	52

#define ID_USR_TESTTRLAYOUT	53

#define ID_USR_SETEMULDIR	54		// Emulator Path
#define ID_USR_SETFORMSIZE	55		// default Form Size

#define ID_USR_TRLIST		56 
#define ID_USR_TRLAYOUT		57
#define ID_USR_RTSINFO		58

#define ID_USR_EMULCLOSE	59
#define ID_USR_LAYOUTMODE	60
#define ID_USR_STANDARDLINE	61
#define ID_USR_LANGUAGE         62
#define ID_USR_SHOWDIFF		63
#define ID_USR_SETTING		64
#define ID_USRID		65

// ID_USR_SELCTRLTOCHILD
#define	SC_PROPERTIESBAR	1
#define	SC_SCRIPTBAR		2
#define	SC_SELECTIONBAR		3
#endif