// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "ezpchart.h"

/////////////////////////////////////////////////////////////////////////////
// CEzpChart

IMPLEMENT_DYNCREATE(CEzpChart, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CEzpChart properties

BOOL CEzpChart::GetEnabled()
{
	BOOL result;
	GetProperty(DISPID_ENABLED, VT_BOOL, (void*)&result);
	return result;
}

void CEzpChart::SetEnabled(BOOL propVal)
{
	SetProperty(DISPID_ENABLED, VT_BOOL, propVal);
}

OLE_HANDLE CEzpChart::GetHWnd()
{
	OLE_HANDLE result;
	GetProperty(DISPID_HWND, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetHWnd(OLE_HANDLE propVal)
{
	SetProperty(DISPID_HWND, VT_I4, propVal);
}
/*
BOOL CEzpChart::GetBNormalizedMinuteTimeRule()
{
	BOOL result;
	GetProperty(0x1, VT_BOOL, (void*)&result);
	return result;
}

void CEzpChart::SetBNormalizedMinuteTimeRule(BOOL propVal)
{
	SetProperty(0x1, VT_BOOL, propVal);
}

long CEzpChart::GetNBlockType()
{
	long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetNBlockType(long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

long CEzpChart::GetNBlockCompart()
{
	long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetNBlockCompart(long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

long CEzpChart::GetNBlockRowCount()
{
	long result;
	GetProperty(0x4, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetNBlockRowCount(long propVal)
{
	SetProperty(0x4, VT_I4, propVal);
}

long CEzpChart::GetNBlockColumnCount()
{
	long result;
	GetProperty(0x5, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetNBlockColumnCount(long propVal)
{
	SetProperty(0x5, VT_I4, propVal);
}

long CEzpChart::GetNBlockGap()
{
	long result;
	GetProperty(0x6, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetNBlockGap(long propVal)
{
	SetProperty(0x6, VT_I4, propVal);
}

long CEzpChart::GetNBlockBorderThickness()
{
	long result;
	GetProperty(0x7, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetNBlockBorderThickness(long propVal)
{
	SetProperty(0x7, VT_I4, propVal);
}

CString CEzpChart::GetStrChartList()
{
	CString result;
	GetProperty(0x8, VT_BSTR, (void*)&result);
	return result;
}

void CEzpChart::SetStrChartList(LPCTSTR propVal)
{
	SetProperty(0x8, VT_BSTR, propVal);
}

long CEzpChart::GetNBorderType()
{
	long result;
	GetProperty(0x9, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetNBorderType(long propVal)
{
	SetProperty(0x9, VT_I4, propVal);
}

long CEzpChart::GetNScaleLineType()
{
	long result;
	GetProperty(0xa, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetNScaleLineType(long propVal)
{
	SetProperty(0xa, VT_I4, propVal);
}

BOOL CEzpChart::GetBWholeView()
{
	BOOL result;
	GetProperty(0xb, VT_BOOL, (void*)&result);
	return result;
}

void CEzpChart::SetBWholeView(BOOL propVal)
{
	SetProperty(0xb, VT_BOOL, propVal);
}

long CEzpChart::GetNOnePageDataCount()
{
	long result;
	GetProperty(0xc, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetNOnePageDataCount(long propVal)
{
	SetProperty(0xc, VT_I4, propVal);
}

long CEzpChart::GetNUserBlockAddCount()
{
	long result;
	GetProperty(0xd, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetNUserBlockAddCount(long propVal)
{
	SetProperty(0xd, VT_I4, propVal);
}

BOOL CEzpChart::GetBGraphDragDrop()
{
	BOOL result;
	GetProperty(0xe, VT_BOOL, (void*)&result);
	return result;
}

void CEzpChart::SetBGraphDragDrop(BOOL propVal)
{
	SetProperty(0xe, VT_BOOL, propVal);
}

long CEzpChart::GetNLeftMargin()
{
	long result;
	GetProperty(0xf, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetNLeftMargin(long propVal)
{
	SetProperty(0xf, VT_I4, propVal);
}

long CEzpChart::GetNRightMargin()
{
	long result;
	GetProperty(0x10, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetNRightMargin(long propVal)
{
	SetProperty(0x10, VT_I4, propVal);
}

long CEzpChart::GetNTopMargin()
{
	long result;
	GetProperty(0x11, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetNTopMargin(long propVal)
{
	SetProperty(0x11, VT_I4, propVal);
}

long CEzpChart::GetNBottomMargin()
{
	long result;
	GetProperty(0x12, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetNBottomMargin(long propVal)
{
	SetProperty(0x12, VT_I4, propVal);
}

BOOL CEzpChart::GetBAddGraphMenuShow()
{
	BOOL result;
	GetProperty(0x13, VT_BOOL, (void*)&result);
	return result;
}

void CEzpChart::SetBAddGraphMenuShow(BOOL propVal)
{
	SetProperty(0x13, VT_BOOL, propVal);
}

CString CEzpChart::GetStrUserEnvironmentFileName()
{
	CString result;
	GetProperty(0x14, VT_BSTR, (void*)&result);
	return result;
}

void CEzpChart::SetStrUserEnvironmentFileName(LPCTSTR propVal)
{
	SetProperty(0x14, VT_BSTR, propVal);
}

CString CEzpChart::GetStrUserIndicatorListFileName()
{
	CString result;
	GetProperty(0x15, VT_BSTR, (void*)&result);
	return result;
}

void CEzpChart::SetStrUserIndicatorListFileName(LPCTSTR propVal)
{
	SetProperty(0x15, VT_BSTR, propVal);
}

CString CEzpChart::GetStrUserSeriesListFileName()
{
	CString result;
	GetProperty(0x16, VT_BSTR, (void*)&result);
	return result;
}

void CEzpChart::SetStrUserSeriesListFileName(LPCTSTR propVal)
{
	SetProperty(0x16, VT_BSTR, propVal);
}

BOOL CEzpChart::GetBHide()
{
	BOOL result;
	GetProperty(0x17, VT_BOOL, (void*)&result);
	return result;
}

void CEzpChart::SetBHide(BOOL propVal)
{
	SetProperty(0x17, VT_BOOL, propVal);
}

BOOL CEzpChart::GetBIsInput()
{
	BOOL result;
	GetProperty(0x18, VT_BOOL, (void*)&result);
	return result;
}

void CEzpChart::SetBIsInput(BOOL propVal)
{
	SetProperty(0x18, VT_BOOL, propVal);
}

CString CEzpChart::GetStrToolbarOption()
{
	CString result;
	GetProperty(0x19, VT_BSTR, (void*)&result);
	return result;
}

void CEzpChart::SetStrToolbarOption(LPCTSTR propVal)
{
	SetProperty(0x19, VT_BSTR, propVal);
}

CString CEzpChart::GetStrPacketOption()
{
	CString result;
	GetProperty(0x1a, VT_BSTR, (void*)&result);
	return result;
}

void CEzpChart::SetStrPacketOption(LPCTSTR propVal)
{
	SetProperty(0x1a, VT_BSTR, propVal);
}

CString CEzpChart::GetStrLocalSharedList()
{
	CString result;
	GetProperty(0x1b, VT_BSTR, (void*)&result);
	return result;
}

void CEzpChart::SetStrLocalSharedList(LPCTSTR propVal)
{
	SetProperty(0x1b, VT_BSTR, propVal);
}

BOOL CEzpChart::GetBUseRealData()
{
	BOOL result;
	GetProperty(0x1c, VT_BOOL, (void*)&result);
	return result;
}

void CEzpChart::SetBUseRealData(BOOL propVal)
{
	SetProperty(0x1c, VT_BOOL, propVal);
}

CString CEzpChart::GetStrRealList()
{
	CString result;
	GetProperty(0x1d, VT_BSTR, (void*)&result);
	return result;
}

void CEzpChart::SetStrRealList(LPCTSTR propVal)
{
	SetProperty(0x1d, VT_BSTR, propVal);
}

short CEzpChart::GetNMarginBorderType()
{
	short result;
	GetProperty(0x1e, VT_I2, (void*)&result);
	return result;
}

void CEzpChart::SetNMarginBorderType(short propVal)
{
	SetProperty(0x1e, VT_I2, propVal);
}

long CEzpChart::GetNRowDoubleSizeBlock()
{
	long result;
	GetProperty(0x1f, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetNRowDoubleSizeBlock(long propVal)
{
	SetProperty(0x1f, VT_I4, propVal);
}

BOOL CEzpChart::GetBUseInquiryDlgWhenUseCrossLine()
{
	BOOL result;
	GetProperty(0x20, VT_BOOL, (void*)&result);
	return result;
}

void CEzpChart::SetBUseInquiryDlgWhenUseCrossLine(BOOL propVal)
{
	SetProperty(0x20, VT_BOOL, propVal);
}

long CEzpChart::GetNColumnDoubleSizeBlock()
{
	long result;
	GetProperty(0x21, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetNColumnDoubleSizeBlock(long propVal)
{
	SetProperty(0x21, VT_I4, propVal);
}

BOOL CEzpChart::GetBUseShortKey()
{
	BOOL result;
	GetProperty(0x22, VT_BOOL, (void*)&result);
	return result;
}

void CEzpChart::SetBUseShortKey(BOOL propVal)
{
	SetProperty(0x22, VT_BOOL, propVal);
}

BOOL CEzpChart::GetBUseConditiontoTitle()
{
	BOOL result;
	GetProperty(0x23, VT_BOOL, (void*)&result);
	return result;
}

void CEzpChart::SetBUseConditiontoTitle(BOOL propVal)
{
	SetProperty(0x23, VT_BOOL, propVal);
}

BOOL CEzpChart::GetBUseDatatoTitle()
{
	BOOL result;
	GetProperty(0x24, VT_BOOL, (void*)&result);
	return result;
}

void CEzpChart::SetBUseDatatoTitle(BOOL propVal)
{
	SetProperty(0x24, VT_BOOL, propVal);
}

short CEzpChart::GetNHorzGap()
{
	short result;
	GetProperty(0x25, VT_I2, (void*)&result);
	return result;
}

void CEzpChart::SetNHorzGap(short propVal)
{
	SetProperty(0x25, VT_I2, propVal);
}

short CEzpChart::GetNVertGap()
{
	short result;
	GetProperty(0x26, VT_I2, (void*)&result);
	return result;
}

void CEzpChart::SetNVertGap(short propVal)
{
	SetProperty(0x26, VT_I2, propVal);
}

short CEzpChart::GetNRButtonMenuType()
{
	short result;
	GetProperty(0x27, VT_I2, (void*)&result);
	return result;
}

void CEzpChart::SetNRButtonMenuType(short propVal)
{
	SetProperty(0x27, VT_I2, propVal);
}

BOOL CEzpChart::GetBShowWarningMessageBox()
{
	BOOL result;
	GetProperty(0x28, VT_BOOL, (void*)&result);
	return result;
}

void CEzpChart::SetBShowWarningMessageBox(BOOL propVal)
{
	SetProperty(0x28, VT_BOOL, propVal);
}

BOOL CEzpChart::GetBControlBlockSize()
{
	BOOL result;
	GetProperty(0x29, VT_BOOL, (void*)&result);
	return result;
}

void CEzpChart::SetBControlBlockSize(BOOL propVal)
{
	SetProperty(0x29, VT_BOOL, propVal);
}

BOOL CEzpChart::GetBBlockMoveDelete()
{
	BOOL result;
	GetProperty(0x2a, VT_BOOL, (void*)&result);
	return result;
}

void CEzpChart::SetBBlockMoveDelete(BOOL propVal)
{
	SetProperty(0x2a, VT_BOOL, propVal);
}

BOOL CEzpChart::GetBSelectTitle()
{
	BOOL result;
	GetProperty(0x2b, VT_BOOL, (void*)&result);
	return result;
}

void CEzpChart::SetBSelectTitle(BOOL propVal)
{
	SetProperty(0x2b, VT_BOOL, propVal);
}

BOOL CEzpChart::GetBSelectGraph()
{
	BOOL result;
	GetProperty(0x2c, VT_BOOL, (void*)&result);
	return result;
}

void CEzpChart::SetBSelectGraph(BOOL propVal)
{
	SetProperty(0x2c, VT_BOOL, propVal);
}

BOOL CEzpChart::GetBUseScaleRButtonMenu()
{
	BOOL result;
	GetProperty(0x2d, VT_BOOL, (void*)&result);
	return result;
}

void CEzpChart::SetBUseScaleRButtonMenu(BOOL propVal)
{
	SetProperty(0x2d, VT_BOOL, propVal);
}

short CEzpChart::GetNGraphRButtonType()
{
	short result;
	GetProperty(0x2e, VT_I2, (void*)&result);
	return result;
}

void CEzpChart::SetNGraphRButtonType(short propVal)
{
	SetProperty(0x2e, VT_I2, propVal);
}

short CEzpChart::GetNHoldingPacketSize()
{
	short result;
	GetProperty(0x2f, VT_I2, (void*)&result);
	return result;
}

void CEzpChart::SetNHoldingPacketSize(short propVal)
{
	SetProperty(0x2f, VT_I2, propVal);
}

CString CEzpChart::GetSzBasePacketName()
{
	CString result;
	GetProperty(0x30, VT_BSTR, (void*)&result);
	return result;
}

void CEzpChart::SetSzBasePacketName(LPCTSTR propVal)
{
	SetProperty(0x30, VT_BSTR, propVal);
}

BOOL CEzpChart::GetBRedrawAfterUpdatedAllPackets()
{
	BOOL result;
	GetProperty(0x31, VT_BOOL, (void*)&result);
	return result;
}

void CEzpChart::SetBRedrawAfterUpdatedAllPackets(BOOL propVal)
{
	SetProperty(0x31, VT_BOOL, propVal);
}

short CEzpChart::GetNMinDataCountOnOnePage()
{
	short result;
	GetProperty(0x32, VT_I2, (void*)&result);
	return result;
}

void CEzpChart::SetNMinDataCountOnOnePage(short propVal)
{
	SetProperty(0x32, VT_I2, propVal);
}

BOOL CEzpChart::GetBFireRealEvent()
{
	BOOL result;
	GetProperty(0x33, VT_BOOL, (void*)&result);
	return result;
}

void CEzpChart::SetBFireRealEvent(BOOL propVal)
{
	SetProperty(0x33, VT_BOOL, propVal);
}

short CEzpChart::GetNInquiryType()
{
	short result;
	GetProperty(0x34, VT_I2, (void*)&result);
	return result;
}

void CEzpChart::SetNInquiryType(short propVal)
{
	SetProperty(0x34, VT_I2, propVal);
}

BOOL CEzpChart::GetBOcxAreaNumericalInquiry()
{
	BOOL result;
	GetProperty(0x35, VT_BOOL, (void*)&result);
	return result;
}

void CEzpChart::SetBOcxAreaNumericalInquiry(BOOL propVal)
{
	SetProperty(0x35, VT_BOOL, propVal);
}*/

long CEzpChart::GetNNumericalInquiryOption()
{
	long result;
	GetProperty(0x36, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetNNumericalInquiryOption(long propVal)
{
	SetProperty(0x36, VT_I4, propVal);
}

CString CEzpChart::GetStrGlobalSharedList()
{
	CString result;
	GetProperty(0x37, VT_BSTR, (void*)&result);
	return result;
}

void CEzpChart::SetStrGlobalSharedList(LPCTSTR propVal)
{
	SetProperty(0x37, VT_BSTR, propVal);
}
/*
short CEzpChart::GetNUseInquiryWithCrossline()
{
	short result;
	GetProperty(0x38, VT_I2, (void*)&result);
	return result;
}

void CEzpChart::SetNUseInquiryWithCrossline(short propVal)
{
	SetProperty(0x38, VT_I2, propVal);
}

BOOL CEzpChart::GetBShowPriceRateInquiry()
{
	BOOL result;
	GetProperty(0x39, VT_BOOL, (void*)&result);
	return result;
}

void CEzpChart::SetBShowPriceRateInquiry(BOOL propVal)
{
	SetProperty(0x39, VT_BOOL, propVal);
}

unsigned long CEzpChart::GetClrBackground()
{
	unsigned long result;
	GetProperty(0x3b, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetClrBackground(unsigned long propVal)
{
	SetProperty(0x3b, VT_I4, propVal);
}

unsigned long CEzpChart::GetClrBackBorder()
{
	unsigned long result;
	GetProperty(0x3c, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetClrBackBorder(unsigned long propVal)
{
	SetProperty(0x3c, VT_I4, propVal);
}

unsigned long CEzpChart::GetClrBlock()
{
	unsigned long result;
	GetProperty(0x3d, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetClrBlock(unsigned long propVal)
{
	SetProperty(0x3d, VT_I4, propVal);
}

unsigned long CEzpChart::GetClrBlockBorder()
{
	unsigned long result;
	GetProperty(0x3e, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetClrBlockBorder(unsigned long propVal)
{
	SetProperty(0x3e, VT_I4, propVal);
}

unsigned long CEzpChart::GetClrScaleLine()
{
	unsigned long result;
	GetProperty(0x3f, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetClrScaleLine(unsigned long propVal)
{
	SetProperty(0x3f, VT_I4, propVal);
}

unsigned long CEzpChart::GetClrScaleText()
{
	unsigned long result;
	GetProperty(0x40, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetClrScaleText(unsigned long propVal)
{
	SetProperty(0x40, VT_I4, propVal);
}

unsigned long CEzpChart::GetClrGraphBase1()
{
	unsigned long result;
	GetProperty(0x41, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetClrGraphBase1(unsigned long propVal)
{
	SetProperty(0x41, VT_I4, propVal);
}

unsigned long CEzpChart::GetClrGraphBase2()
{
	unsigned long result;
	GetProperty(0x42, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetClrGraphBase2(unsigned long propVal)
{
	SetProperty(0x42, VT_I4, propVal);
}

unsigned long CEzpChart::GetClrGraphBase3()
{
	unsigned long result;
	GetProperty(0x43, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetClrGraphBase3(unsigned long propVal)
{
	SetProperty(0x43, VT_I4, propVal);
}

unsigned long CEzpChart::GetClrGraphBase4()
{
	unsigned long result;
	GetProperty(0x44, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetClrGraphBase4(unsigned long propVal)
{
	SetProperty(0x44, VT_I4, propVal);
}

unsigned long CEzpChart::GetClrGraphBase5()
{
	unsigned long result;
	GetProperty(0x45, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetClrGraphBase5(unsigned long propVal)
{
	SetProperty(0x45, VT_I4, propVal);
}

unsigned long CEzpChart::GetClrGraphBase6()
{
	unsigned long result;
	GetProperty(0x46, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetClrGraphBase6(unsigned long propVal)
{
	SetProperty(0x46, VT_I4, propVal);
}

unsigned long CEzpChart::GetClrAnalysisTool()
{
	unsigned long result;
	GetProperty(0x47, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetClrAnalysisTool(unsigned long propVal)
{
	SetProperty(0x47, VT_I4, propVal);
}

CString CEzpChart::GetStrBlockRegion()
{
	CString result;
	GetProperty(0x48, VT_BSTR, (void*)&result);
	return result;
}

void CEzpChart::SetStrBlockRegion(LPCTSTR propVal)
{
	SetProperty(0x48, VT_BSTR, propVal);
}

unsigned long CEzpChart::GetClrScaleLine2()
{
	unsigned long result;
	GetProperty(0x49, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetClrScaleLine2(unsigned long propVal)
{
	SetProperty(0x49, VT_I4, propVal);
}

unsigned long CEzpChart::GetClrInquiryWindow()
{
	unsigned long result;
	GetProperty(0x4a, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetClrInquiryWindow(unsigned long propVal)
{
	SetProperty(0x4a, VT_I4, propVal);
}

CString CEzpChart::GetCustomFont()
{
	CString result;
	GetProperty(0x4b, VT_BSTR, (void*)&result);
	return result;
}

void CEzpChart::SetCustomFont(LPCTSTR propVal)
{
	SetProperty(0x4b, VT_BSTR, propVal);
}

unsigned long CEzpChart::GetClrLattice()
{
	unsigned long result;
	GetProperty(0x4c, VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetClrLattice(unsigned long propVal)
{
	SetProperty(0x4c, VT_I4, propVal);
}

CString CEzpChart::GetStrStartDateOfData()
{
	CString result;
	GetProperty(0x4d, VT_BSTR, (void*)&result);
	return result;
}*/

void CEzpChart::SetStrStartDateOfData(LPCTSTR propVal)
{
	SetProperty(0x4d, VT_BSTR, propVal);
}
/*
BOOL CEzpChart::GetOnRunningOneChart()
{
	BOOL result;
	GetProperty(0x4e, VT_BOOL, (void*)&result);
	return result;
}*/

void CEzpChart::SetOnRunningOneChart(BOOL propVal)
{
	SetProperty(0x4e, VT_BOOL, propVal);
}

BOOL CEzpChart::GetBDoesUseSkinColor()
{
	BOOL result;
	GetProperty(0x3a, VT_BOOL, (void*)&result);
	return result;
}

void CEzpChart::SetBDoesUseSkinColor(BOOL propVal)
{
	SetProperty(0x3a, VT_BOOL, propVal);
}
/*
/////////////////////////////////////////////////////////////////////////////
// CEzpChart operations
BOOL CEzpChart::SetAllProperties2(long dwData)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x4f, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		dwData);
	return result;
}

void CEzpChart::SetBaseDesk(long lKey)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x50, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 lKey);
}

long CEzpChart::GetBase(LPCTSTR szKey)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x51, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szKey);
	return result;
}

short CEzpChart::SetChartData(long pChartData, short nCount, short nType)
{
	short result;
	static BYTE parms[] =
		VTS_I4 VTS_I2 VTS_I2;
	InvokeHelper(0x52, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		pChartData, nCount, nType);
	return result;
}

short CEzpChart::SetChartDataStr(LPCTSTR szChartData, short nCount, short nType)
{
	short result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2 VTS_I2;
	InvokeHelper(0x53, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		szChartData, nCount, nType);
	return result;
}

short CEzpChart::testGetPacketdatasize(LPCTSTR pIn)
{
	short result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x54, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		pIn);
	return result;
}

void CEzpChart::testLoadAnalysisTools(short nToolOption, short nOption)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2;
	InvokeHelper(0x55, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nToolOption, nOption);
}

void CEzpChart::MakeSaveShortKey(LPCTSTR szFileName, short nFlag)
{
	static BYTE parms[] =
		VTS_BSTR VTS_I2;
	InvokeHelper(0x56, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 szFileName, nFlag);
}

short CEzpChart::ChangeChart(short nBlockRowPosition, short nBlockColumnPosition, LPCTSTR strGraphTitle, LPCTSTR strIndicatorName, LPCTSTR strPacketName, LPCTSTR strGraphType, LPCTSTR strGraphStyle, short nLineWidth, unsigned long clrLineColor)
{
	short result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_I2 VTS_I4;
	InvokeHelper(0x57, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		nBlockRowPosition, nBlockColumnPosition, strGraphTitle, strIndicatorName, strPacketName, strGraphType, strGraphStyle, nLineWidth, clrLineColor);
	return result;
}

short CEzpChart::ClearChartData(short nOption)
{
	short result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x58, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		nOption);
	return result;
}

short CEzpChart::SetGraphHide(short nRow, short nColumn, LPCTSTR strTitle, BOOL bHide)
{
	short result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_BSTR VTS_BOOL;
	InvokeHelper(0x59, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		nRow, nColumn, strTitle, bHide);
	return result;
}

BOOL CEzpChart::AddChartBlock(LPCTSTR strChartName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x5a, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strChartName);
	return result;
}

void CEzpChart::SetOnePageDataCount(long nOnePageDataCount)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x5b, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nOnePageDataCount);
}

long CEzpChart::GetOnePageDataCount()
{
	long result;
	InvokeHelper(0x5c, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

BOOL CEzpChart::SaveandOpenFromFile(LPCTSTR strOpenFileName, LPCTSTR strSaveFileName, BOOL bOpenOption, BOOL bSaveOption)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BOOL VTS_BOOL;
	InvokeHelper(0x5d, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strOpenFileName, strSaveFileName, bOpenOption, bSaveOption);
	return result;
}

BOOL CEzpChart::JoinandDevisionforCompareChart(long nRowCount, long nColumnCount, BOOL bJoin)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_BOOL;
	InvokeHelper(0x5e, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		nRowCount, nColumnCount, bJoin);
	return result;
}

BOOL CEzpChart::ChangeGraphTitle(short nRowIndex, short nColumnIndex, short nGraphIndex, LPCTSTR strNewTitle)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2 VTS_BSTR;
	InvokeHelper(0x5f, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		nRowIndex, nColumnIndex, nGraphIndex, strNewTitle);
	return result;
}

short CEzpChart::SetChartDataFromFile(LPCTSTR szFileName, short nType)
{
	short result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2;
	InvokeHelper(0x60, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		szFileName, nType);
	return result;
}

BOOL CEzpChart::RemoveChart(LPCTSTR strChartName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x61, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strChartName);
	return result;
}

BOOL CEzpChart::ChangeGraphType(LPCTSTR strIndicatorName, LPCTSTR strGraphType, LPCTSTR strGraphStyle, LPCTSTR strPacketNameList, BOOL bRunatOnce)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BOOL;
	InvokeHelper(0x62, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strIndicatorName, strGraphType, strGraphStyle, strPacketNameList, bRunatOnce);
	return result;
}

void CEzpChart::SetChartAllInfo()
{
	InvokeHelper(0x63, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

CString CEzpChart::GetData(LPCTSTR strPacketName, short nDataIndex)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2;
	InvokeHelper(0x64, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		strPacketName, nDataIndex);
	return result;
}

BOOL CEzpChart::SetDrdsAdvise(BOOL bOnAdvise)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x65, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		bOnAdvise);
	return result;
}

short CEzpChart::GetDataCount()
{
	short result;
	InvokeHelper(0x66, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

BOOL CEzpChart::ChangeChartItem(LPCTSTR strIndicatorName, short nSubGraphIndex, LPCTSTR strNewTitle, LPCTSTR strNewPacketName, LPCTSTR strNewGraphType, LPCTSTR strNewGraphStyle, short nNewUpLineWidth, short nNewDownLineWidth, short nNewEqualLineWidth, 
		BOOL bRunatOnce)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2 VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_I2 VTS_I2 VTS_I2 VTS_BOOL;
	InvokeHelper(0x67, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strIndicatorName, nSubGraphIndex, strNewTitle, strNewPacketName, strNewGraphType, strNewGraphStyle, nNewUpLineWidth, nNewDownLineWidth, nNewEqualLineWidth, bRunatOnce);
	return result;
}

BOOL CEzpChart::SetStopLossPrice(BOOL bIsStopLoss, double dStopLossPrice, BOOL bIsProfit, double dProfitPrice)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BOOL VTS_R8 VTS_BOOL VTS_R8;
	InvokeHelper(0x68, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		bIsStopLoss, dStopLossPrice, bIsProfit, dProfitPrice);
	return result;
}

BOOL CEzpChart::RestoreMinMax(LPCTSTR strPacketName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x69, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strPacketName);
	return result;
}

BOOL CEzpChart::RestoreMin(LPCTSTR strPacketName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6a, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strPacketName);
	return result;
}

BOOL CEzpChart::RestorMax(LPCTSTR strPacketName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6b, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strPacketName);
	return result;
}

BOOL CEzpChart::SetMin(LPCTSTR strPacketName, double dMin)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_R8;
	InvokeHelper(0x6c, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strPacketName, dMin);
	return result;
}

BOOL CEzpChart::SetMax(LPCTSTR strPacketName, double dMax)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_R8;
	InvokeHelper(0x6d, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strPacketName, dMax);
	return result;
}

BOOL CEzpChart::SetMinMax(LPCTSTR strPacketName, double dMin, double dMax)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_R8 VTS_R8;
	InvokeHelper(0x6e, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strPacketName, dMin, dMax);
	return result;
}

BOOL CEzpChart::SetHorzScaleData(short nRowIndex, short nColumnIndex, LPCTSTR strScaleData)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_BSTR;
	InvokeHelper(0x6f, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		nRowIndex, nColumnIndex, strScaleData);
	return result;
}

double CEzpChart::GetMin(LPCTSTR strPacketName)
{
	double result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x70, DISPATCH_METHOD, VT_R8, (void*)&result, parms,
		strPacketName);
	return result;
}

double CEzpChart::GetMax(LPCTSTR strPacketName)
{
	double result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x71, DISPATCH_METHOD, VT_R8, (void*)&result, parms,
		strPacketName);
	return result;
}

BOOL CEzpChart::SetGraphHide2(short nRowIndex, short nColumnIndex, short nVerticalIndex, short nGraphIndex, short nSubGraphIndex, BOOL bHide)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2 VTS_I2 VTS_I2 VTS_BOOL;
	InvokeHelper(0x72, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		nRowIndex, nColumnIndex, nVerticalIndex, nGraphIndex, nSubGraphIndex, bHide);
	return result;
}

BOOL CEzpChart::ChangeGraphDatas(short nRowIndex, short nColumnIndex, short nVerticalIndex, short nGraphIndex, LPCTSTR strNewIndicatorName, LPCTSTR strNewTitle, LPCTSTR strNewPacketName, LPCTSTR strNewGraphType, LPCTSTR strNewGraphStyle, 
		short nNewUpLineWidth, short nNewDownLineWidth, short nNewEqualLineWidth, BOOL bRunatOnce)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2 VTS_I2 VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_I2 VTS_I2 VTS_I2 VTS_BOOL;
	InvokeHelper(0x73, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		nRowIndex, nColumnIndex, nVerticalIndex, nGraphIndex, strNewIndicatorName, strNewTitle, strNewPacketName, strNewGraphType, strNewGraphStyle, nNewUpLineWidth, nNewDownLineWidth, nNewEqualLineWidth, bRunatOnce);
	return result;
}

void CEzpChart::SaveandApplyGraphStyle(short nSaveDataType, short nChangeDataType)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2;
	InvokeHelper(0x74, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nSaveDataType, nChangeDataType);
}

void CEzpChart::SetDataRegionInBlock(short nDataStartIndex)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x75, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nDataStartIndex);
}

void CEzpChart::SetItemInfo(LPCTSTR lpstrCode, LPCTSTR lpstrName)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x76, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 lpstrCode, lpstrName);
}

void CEzpChart::AddandDeleteIndicator(LPCTSTR strIndicatorName)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x77, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strIndicatorName);
}

long CEzpChart::GetAllProperties2(long lpData)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x78, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		lpData);
	return result;
}

long CEzpChart::GetBasePropIf()
{
	long result;
	InvokeHelper(0x79, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

BOOL CEzpChart::SetVertScaleData(short nRowIndex, short nColumnIndex, short nVertScaleGroupIndex, LPCTSTR strVertScaleData)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2 VTS_BSTR;
	InvokeHelper(0x7a, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		nRowIndex, nColumnIndex, nVertScaleGroupIndex, strVertScaleData);
	return result;
}

BOOL CEzpChart::ChangeBlockType(short nBlockType, short nRowCount, short nColumnCount)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2;
	InvokeHelper(0x7b, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		nBlockType, nRowCount, nColumnCount);
	return result;
}

BOOL CEzpChart::ChangeHorzScalePosition(short nScalePosition, short nRowIndex, short nColumnIndex)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2;
	InvokeHelper(0x7c, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		nScalePosition, nRowIndex, nColumnIndex);
	return result;
}

BOOL CEzpChart::ResetChart()
{
	BOOL result;
	InvokeHelper(0x7d, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CEzpChart::SetRealData(LPCTSTR strPacketName, double dData, short nOption)
{
	static BYTE parms[] =
		VTS_BSTR VTS_R8 VTS_I2;
	InvokeHelper(0x7e, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strPacketName, dData, nOption);
}

BOOL CEzpChart::SetGraphTitle(LPCTSTR strIndicatorName, short nSubGraphIndex, LPCTSTR strNewGraphTitle, BOOL bGraphShowing)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2 VTS_BSTR VTS_BOOL;
	InvokeHelper(0x7f, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strIndicatorName, nSubGraphIndex, strNewGraphTitle, bGraphShowing);
	return result;
}

CString CEzpChart::GetIndicatorNameList(LPCTSTR p_strGroup)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x80, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		p_strGroup);
	return result;
}

void CEzpChart::AddGraph(short nRow, short nColumn, short nVertScaleGroup, LPCTSTR szGraphOption, BOOL bCreateBlock, BOOL bCreateVertScaleGroup, BOOL bUseAutoScale)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2 VTS_BSTR VTS_BOOL VTS_BOOL VTS_BOOL;
	InvokeHelper(0x81, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nRow, nColumn, nVertScaleGroup, szGraphOption, bCreateBlock, bCreateVertScaleGroup, bUseAutoScale);
}

void CEzpChart::AddPacket(LPCTSTR szPacketOption)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x82, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 szPacketOption);
}

void CEzpChart::RemovePacket(LPCTSTR szPacketName)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x83, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 szPacketName);
}

void CEzpChart::SetContainerDllInfo(long p_lDllWnd, short p_nID)
{
	static BYTE parms[] =
		VTS_I4 VTS_I2;
	InvokeHelper(0x84, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_lDllWnd, p_nID);
}

BOOL CEzpChart::SetPacketData(LPCTSTR szPacketName, long szData, long lLength, BOOL bReset)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I4 VTS_BOOL;
	InvokeHelper(0x85, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		szPacketName, szData, lLength, bReset);
	return result;
}

void CEzpChart::SetBackgroundColors(unsigned long p_rgbBlockArea, unsigned long p_rgbScaleArea)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x86, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_rgbBlockArea, p_rgbScaleArea);
}

void CEzpChart::AddRealItem(LPCTSTR szRealInfo)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x87, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 szRealInfo);
}

void CEzpChart::ShowIndicatorConfigDlg()
{
	InvokeHelper(0x88, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CEzpChart::ResetChartCfgWith(short p_nIndex)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x89, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_nIndex);
}

void CEzpChart::ResetOCX()
{
	InvokeHelper(0x8a, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

BOOL CEzpChart::HasGraph(LPCTSTR p_szGraphName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x8b, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_szGraphName);
	return result;
}

void CEzpChart::RemoveRealItem(LPCTSTR szRealInfo)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x8c, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 szRealInfo);
}

void CEzpChart::ShowInnerToolBar(BOOL p_bShow)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x8d, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_bShow);
}

BOOL CEzpChart::ChangeVertScalePosition(short nScalePosition, short nRowIndex, short nColumnIndex, short nVSGroupIndex)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2 VTS_I2;
	InvokeHelper(0x8e, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		nScalePosition, nRowIndex, nColumnIndex, nVSGroupIndex);
	return result;
}

short CEzpChart::GetRowBlockCount()
{
	short result;
	InvokeHelper(0x8f, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

short CEzpChart::GetColumnBlockCount()
{
	short result;
	InvokeHelper(0x90, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

BOOL CEzpChart::SetStartPeriodOfPacket(LPCTSTR p_szPacketName, long p_lStartPeriod, long p_bAddSpace)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I4;
	InvokeHelper(0x91, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_szPacketName, p_lStartPeriod, p_bAddSpace);
	return result;
}

long CEzpChart::GetStartPeriodOfPacket(LPCTSTR p_szPacketName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x92, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		p_szPacketName);
	return result;
}

BOOL CEzpChart::GetStartEndDateOnView(double* p_pStartDate, double* p_pEndDate)
{
	BOOL result;
	static BYTE parms[] =
		VTS_PR8 VTS_PR8;
	InvokeHelper(0x93, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_pStartDate, p_pEndDate);
	return result;
}

BOOL CEzpChart::SetStartEndDateOfView(double p_dStartDate, double p_dEndDate)
{
	BOOL result;
	static BYTE parms[] =
		VTS_R8 VTS_R8;
	InvokeHelper(0x94, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_dStartDate, p_dEndDate);
	return result;
}

BOOL CEzpChart::ScrollToDataOfEnd(double p_dData)
{
	BOOL result;
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x95, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_dData);
	return result;
}

short CEzpChart::ZoomToWithRightFix(short p_nZoomValue, BOOL p_bWithRightFix)
{
	short result;
	static BYTE parms[] =
		VTS_I2 VTS_BOOL;
	InvokeHelper(0x96, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		p_nZoomValue, p_bWithRightFix);
	return result;
}

void CEzpChart::ClearTimeMark()
{
	InvokeHelper(0x97, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CEzpChart::ShowEnvironmentDlg()
{
	InvokeHelper(0x98, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CEzpChart::SetTimeMark(LPCTSTR p_szMarkTime, BOOL p_bWithScroll)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BOOL;
	InvokeHelper(0x99, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_szMarkTime, p_bWithScroll);
}

short CEzpChart::GetVertScalePosition(short p_nRowIndex, short p_nColumnIndex, short p_nVSGroupIndex)
{
	short result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2;
	InvokeHelper(0x9a, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		p_nRowIndex, p_nColumnIndex, p_nVSGroupIndex);
	return result;
}

void CEzpChart::EnableBoundMark(BOOL p_bEnable)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x9b, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_bEnable);
}

void CEzpChart::EnableReceivingTimeShare(BOOL p_bEnable)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x9c, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_bEnable);
}

BOOL CEzpChart::ChangePacketType(LPCTSTR p_szPacketName, LPCTSTR p_szPacketType)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x9d, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_szPacketName, p_szPacketType);
	return result;
}

BOOL CEzpChart::ChangeGraphDrawingData(LPCTSTR p_szGraphName, BOOL p_bLowHigh, BOOL p_bLowCur, BOOL p_bHighCur, BOOL p_bPrevCur, BOOL p_bPrevCurRate)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BOOL VTS_BOOL VTS_BOOL VTS_BOOL VTS_BOOL;
	InvokeHelper(0x9e, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_szGraphName, p_bLowHigh, p_bLowCur, p_bHighCur, p_bPrevCur, p_bPrevCurRate);
	return result;
}

BOOL CEzpChart::ChangePriceGraphDrawingData(BOOL p_bLowHigh, BOOL p_bLowCur, BOOL p_bHighCur, BOOL p_bPrevCur, BOOL p_bPrevCurRate, short p_nDefaultType)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BOOL VTS_BOOL VTS_BOOL VTS_BOOL VTS_BOOL VTS_I2;
	InvokeHelper(0x9f, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_bLowHigh, p_bLowCur, p_bHighCur, p_bPrevCur, p_bPrevCurRate, p_nDefaultType);
	return result;
}

void CEzpChart::ShowAnalysisToolText(BOOL p_bTimeLine, BOOL p_bPriceLineLeft, BOOL p_bPriceLineRight, BOOL p_bTrendLine, BOOL p_bTrisectionLine, BOOL p_bQuadrisectionLine, BOOL p_bFibonacciRetraceLine)
{
	static BYTE parms[] =
		VTS_BOOL VTS_BOOL VTS_BOOL VTS_BOOL VTS_BOOL VTS_BOOL VTS_BOOL;
	InvokeHelper(0xa0, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_bTimeLine, p_bPriceLineLeft, p_bPriceLineRight, p_bTrendLine, p_bTrisectionLine, p_bQuadrisectionLine, p_bFibonacciRetraceLine);
}

BOOL CEzpChart::HasGraphInSpecialBack(LPCTSTR p_szGraphName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0xa1, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_szGraphName);
	return result;
}

BOOL CEzpChart::LoadAddIn(LPCTSTR p_szAddInDllName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0xa2, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_szAddInDllName);
	return result;
}

BOOL CEzpChart::InvokeAddIn(LPCTSTR p_szAddInDllName, short p_nCommandType, long p_lData)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2 VTS_I4;
	InvokeHelper(0xa3, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_szAddInDllName, p_nCommandType, p_lData);
	return result;
}

void CEzpChart::SetDragModeType(short p_nDragModeType)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0xa4, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_nDragModeType);
}

BOOL CEzpChart::ResetRealListString(LPCTSTR p_szRealList, BOOL p_bAdviseNow)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BOOL;
	InvokeHelper(0xa5, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_szRealList, p_bAdviseNow);
	return result;
}

BOOL CEzpChart::AddOrRemoveChart(LPCTSTR strIndicatorName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0xa6, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strIndicatorName);
	return result;
}*/
BOOL CEzpChart::SetAllProperties2(long dwData)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(m_pdID[IIx_SetAllProperties2], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		dwData);
	return result;
}

void CEzpChart::SetBaseDesk(long lKey)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(m_pdID[IIx_SetBaseDesk], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 lKey);
}


long CEzpChart::GetBase(LPCTSTR szKey)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(m_pdID[IIx_GetBase], DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szKey);
	return result;
}

void CEzpChart::AddGraph(short nRow, short nColumn, short nVertScaleGroup, LPCTSTR szGraphOption, BOOL bCreateBlock, BOOL bCreateVertScaleGroup, BOOL bUseAutoScale)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2 VTS_BSTR VTS_BOOL VTS_BOOL VTS_BOOL;
	InvokeHelper(m_pdID[IIx_AddGraph], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nRow, nColumn, nVertScaleGroup, szGraphOption, bCreateBlock, bCreateVertScaleGroup, bUseAutoScale);
}

void CEzpChart::AddPacket(LPCTSTR szPacketOption)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(m_pdID[IIx_AddPacket], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 szPacketOption);
}

void CEzpChart::RemovePacket(LPCTSTR szPacketName)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(m_pdID[IIx_RemovePacket], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 szPacketName);
}

CString CEzpChart::GetIndicatorNameList(LPCTSTR p_strGroup)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(m_pdID[IIx_GetIndicatorNameList], DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		p_strGroup);
	return result;
}

void CEzpChart::SetContainerDllInfo(long p_lDllWnd, short p_nID)
{
	static BYTE parms[] =
		VTS_I4 VTS_I2;
	InvokeHelper(m_pdID[IIx_SetContainerDllInfo], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_lDllWnd, p_nID);
}

short CEzpChart::SetChartData(long pChartData, short nCount, short nType)
{
	short result;
	static BYTE parms[] =
		VTS_I4 VTS_I2 VTS_I2;
	InvokeHelper(m_pdID[IIx_SetChartData], DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		pChartData, nCount, nType);
	return result;
}


BOOL CEzpChart::SetPacketData(LPCTSTR szPacketName, long szData, long nLength, BOOL bReset)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I4 VTS_BOOL;
	InvokeHelper(m_pdID[IIx_SetPacketData], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		szPacketName, szData, nLength, bReset);
	return result;
}

BOOL CEzpChart::AddChartBlock(LPCTSTR strChartName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(m_pdID[IIx_AddChartBlock], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strChartName);
	return result;
}

BOOL CEzpChart::ResetChart()
{
	BOOL result;
	InvokeHelper(m_pdID[IIx_ResetChart], DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CEzpChart::SetBackgroundColors(unsigned long p_rgbBlockArea, unsigned long p_rgbScaleArea)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(m_pdID[IIx_SetBackgroundColors], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_rgbBlockArea, p_rgbScaleArea);
}

BOOL CEzpChart::SetDrdsAdvise(BOOL bOnAdvise)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(m_pdID[IIx_SetDrdsAdvise], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		bOnAdvise);
	return result;
}

void CEzpChart::AddRealItem(LPCTSTR szRealInfo)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(m_pdID[IIx_AddRealItem], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 szRealInfo);
}

void CEzpChart::ShowIndicatorConfigDlg()
{
	InvokeHelper(m_pdID[IIx_ShowIndicatorConfigDlg], DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

long CEzpChart::GetNOnePageDataCount()
{
	long result;
	GetProperty(m_pdID[IIx_NOnePageDataCount], VT_I4, (void*)&result);
	return result;
}

void CEzpChart::SetNOnePageDataCount(long propVal)
{
	SetProperty(m_pdID[IIx_NOnePageDataCount], VT_I4, propVal);
}


CString CEzpChart::GetStrStartDateOfData()
{
	CString result;
	GetProperty(m_pdID[IIx_StrStartDateOfData], VT_BSTR, (void*)&result);
	return result;
}

void CEzpChart::ResetChartCfgWith(short p_nIndex)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(m_pdID[IIx_ResetChartCfgWith], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_nIndex);
}

void CEzpChart::ResetOCX()
{
	InvokeHelper(m_pdID[IIx_ResetOCX], DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

BOOL CEzpChart::HasGraph(LPCTSTR p_szGraphName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(m_pdID[IIx_HasGraph], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_szGraphName);
	return result;
}

void CEzpChart::RemoveRealItem(LPCTSTR szRealInfo)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(m_pdID[IIx_RemoveRealItem], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 szRealInfo);
}

BOOL CEzpChart::SaveandOpenFromFile(LPCTSTR strOpenFileName, LPCTSTR strSaveFileName, BOOL bOpenOption, BOOL bSaveOption)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BOOL VTS_BOOL;
	InvokeHelper(m_pdID[IIx_SaveandOpenFromFile], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strOpenFileName, strSaveFileName, bOpenOption, bSaveOption);
	return result;
}

short CEzpChart::ClearChartData(short nOption)
{
	short result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(m_pdID[IIx_ClearChartData], DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		nOption);
	return result;
}

void CEzpChart::ShowInnerToolBar(BOOL p_bShow)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(m_pdID[IIx_ShowInnerToolBar], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_bShow);
}

BOOL CEzpChart::ChangeVertScalePosition(short nScalePosition, short nRowIndex, short nColumnIndex, short nVSGroupIndex)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2 VTS_I2;
	InvokeHelper(m_pdID[IIx_ChangeVertScalePosition], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		nScalePosition, nRowIndex, nColumnIndex, nVSGroupIndex);
	return result;
}


short CEzpChart::GetRowBlockCount()
{
	short result;
	InvokeHelper(m_pdID[IIx_GetRowBlockCount], DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

short CEzpChart::GetColumnBlockCount()
{
	short result;
	InvokeHelper(m_pdID[IIx_GetColumnBlockCount], DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

BOOL CEzpChart::ChangeHorzScalePosition(short nScalePosition, short nRowIndex, short nColumnIndex)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2;
	InvokeHelper(m_pdID[IIx_ChangeHorzScalePosition], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		nScalePosition, nRowIndex, nColumnIndex);
	return result;
}

BOOL CEzpChart::RemoveChart(LPCTSTR strChartName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(m_pdID[IIx_RemoveChart], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strChartName);
	return result;
}

BOOL CEzpChart::SetStartPeriodOfPacket(LPCTSTR p_szPacketName, long p_lStartPeriod, long p_bAddSpace)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I4;
	InvokeHelper(m_pdID[IIx_SetStartPeriodOfPacket], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_szPacketName, p_lStartPeriod, p_bAddSpace);
	return result;
}

long CEzpChart::GetStartPeriodOfPacket(LPCTSTR p_szPacketName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(m_pdID[IIx_GetStartPeriodOfPacket], DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		p_szPacketName);
	return result;
}

void CEzpChart::SetStrUserIndicatorListFileName(LPCTSTR propVal)
{
	SetProperty(m_pdID[IIx_StrUserIndicatorListFileName], VT_BSTR, propVal);
}

void CEzpChart::SetStrUserEnvironmentFileName(LPCTSTR propVal)
{
	SetProperty(m_pdID[IIx_StrUserEnvironmentFileName], VT_BSTR, propVal);
}

BOOL CEzpChart::GetStartEndDateOnView(double* p_pStartDate, double* p_pEndDate)
{
	BOOL result;
	static BYTE parms[] =
		VTS_PR8 VTS_PR8;
	InvokeHelper(m_pdID[IIx_GetStartEndDateOnView], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_pStartDate, p_pEndDate);
	return result;
}

BOOL CEzpChart::SetStartEndDateOfView(double p_dStartDate, double p_dEndDate)
{
	BOOL result;
	static BYTE parms[] =
		VTS_R8 VTS_R8;
	InvokeHelper(m_pdID[IIx_SetStartEndDateOfView], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_dStartDate, p_dEndDate);
	return result;
}


BOOL CEzpChart::ScrollToDataOfEnd(double p_dData)
{
	BOOL result;
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(m_pdID[IIx_ScrollToDataOfEnd], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_dData);
	return result;
}

short CEzpChart::ZoomToWithRightFix(short p_nZoomValue, BOOL p_bWithRightFix)
{
	short result;
	static BYTE parms[] =
		VTS_I2 VTS_BOOL;
	InvokeHelper(m_pdID[IIx_ZoomToWithRightFix], DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		p_nZoomValue, p_bWithRightFix);
	return result;
}


void CEzpChart::ClearTimeMark()
{
	InvokeHelper(m_pdID[IIx_ClearTimeMark], DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CEzpChart::ShowEnvironmentDlg()
{
	InvokeHelper(m_pdID[IIx_ShowEnvironmentDlg], DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CEzpChart::SetTimeMark(LPCTSTR p_szMarkTime, BOOL p_bWithScroll)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BOOL;
	InvokeHelper(m_pdID[IIx_SetTimeMark], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_szMarkTime, p_bWithScroll);
}


void CEzpChart::SetBOcxAreaNumericalInquiry(BOOL propVal)
{
	SetProperty(m_pdID[IIx_BOcxAreaNumericalInquiry], VT_BOOL, propVal);
}

BOOL CEzpChart::GetOnRunningOneChart()
{
	BOOL result;
	GetProperty(m_pdID[IIx_OnRunningOneChart], VT_BOOL, (void*)&result);
	return result;
}

void CEzpChart::EnableBoundMark(BOOL p_bEnable)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(m_pdID[IIx_EnableBoundMark], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_bEnable);
}

void CEzpChart::EnableReceivingTimeShare(BOOL p_bEnable)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(m_pdID[IIx_EnableReceivingTimeShare], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_bEnable);
}

BOOL CEzpChart::ChangePacketType(LPCTSTR p_szPacketName, LPCTSTR p_szPacketType)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(m_pdID[IIx_ChangePacketType], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_szPacketName, p_szPacketType);
	return result;
}

BOOL CEzpChart::ChangePriceGraphDrawingData(BOOL p_bLowHigh, BOOL p_bLowCur, BOOL p_bHighCur, BOOL p_bPrevCur, BOOL p_bPrevCurRate, short p_nDefaultType)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BOOL VTS_BOOL VTS_BOOL VTS_BOOL VTS_BOOL VTS_I2;
	InvokeHelper(m_pdID[IIx_ChangePriceGraphDrawingData], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_bLowHigh, p_bLowCur, p_bHighCur, p_bPrevCur, p_bPrevCurRate, p_nDefaultType);
	return result;
}

void CEzpChart::SetNUseInquiryWithCrossline(short propVal)
{
	SetProperty(m_pdID[IIx_NUseInquiryWithCrossline], VT_I2, propVal);
}

short CEzpChart::GetNUseInquiryWithCrossline()
{
	short result;
	GetProperty(m_pdID[IIx_NUseInquiryWithCrossline], VT_I2, (void*)&result);
	return result;
}

BOOL CEzpChart::GetBShowPriceRateInquiry()
{
	BOOL result;
	GetProperty(m_pdID[IIx_BShowPriceRateInquiry], VT_BOOL, (void*)&result);
	return result;
}

void CEzpChart::SetBShowPriceRateInquiry(BOOL propVal)
{
	SetProperty(m_pdID[IIx_BShowPriceRateInquiry], VT_BOOL, propVal);
}

BOOL CEzpChart::GetBNormalizedMinuteTimeRule()
{
	BOOL result;
	GetProperty(m_pdID[IIx_BNormalizedMinuteTimeRule], VT_BOOL, (void*)&result);
	return result;
}

void CEzpChart::SetBNormalizedMinuteTimeRule(BOOL propVal)
{
	SetProperty(m_pdID[IIx_BNormalizedMinuteTimeRule], VT_BOOL, propVal);
}

BOOL CEzpChart::HasGraphInSpecialBack(LPCTSTR p_szGraphName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(m_pdID[IIx_HasGraphInSpecialBack], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_szGraphName);
	return result;
}

BOOL CEzpChart::InvokeAddIn(LPCTSTR p_szAddInDllName, short p_nCommandType, long p_lData)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2 VTS_I4;
	InvokeHelper(m_pdID[IIx_InvokeAddIn], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_szAddInDllName, p_nCommandType, p_lData);
	return result;
}

BOOL CEzpChart::LoadAddIn(LPCTSTR p_szAddInDllName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(m_pdID[IIx_LoadAddIn], DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		p_szAddInDllName);
	return result;
}

void CEzpChart::SetDragModeType(short p_nDragModeType)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(m_pdID[IIx_SetDragModeType], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p_nDragModeType);
}

void CEzpChart::SetHtsPath(LPCTSTR pcszHtsPath)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(m_pdID[IIx_SetHtsPath], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pcszHtsPath);
}

void CEzpChart::SetAllLogScale(BOOL bLogScale)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(m_pdID[IIx_SetAllLogScale], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 bLogScale);
}

void CEzpChart::SetMultiChartDlg(long lpMultiChartDlg)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(m_pdID[IIx_SetMultiChartDlg], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 lpMultiChartDlg);
}

void CEzpChart::GetListViewerData(BSTR* bstrTitle, BSTR* bstrHorzScale, BSTR* bstrPacketNamesPerBlock, BSTR* bstrPacketNames, BSTR* bstrSaveFilePath, BOOL* bViewPacketSequence, long* lpPacketList)
{
	static BYTE parms[] =
		VTS_PBSTR VTS_PBSTR VTS_PBSTR VTS_PBSTR VTS_PBSTR VTS_PBOOL VTS_PI4;
	InvokeHelper(m_pdID[IIx_GetListViewerData], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 bstrTitle, bstrHorzScale, bstrPacketNamesPerBlock, bstrPacketNames, bstrSaveFilePath, bViewPacketSequence, lpPacketList);
}

void CEzpChart::SetDataIndexByDate(LPCTSTR pcszStartDate, LPCTSTR pcszEndDate)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(m_pdID[IIx_SetDataIndexByDate], DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pcszStartDate, pcszEndDate);
}

long CEzpChart::GetDataIndexInDataListViewer(long nPointX, long nPointY)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(m_pdID[IIx_GetDataIndexInDataListViewer], DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nPointX, nPointY);
	return result;
}



///////////////////////////////////////////////////////////////////////////////
//	작업자	:	배승원(Seung-Won, Bae)
//	E-Mail	:	radox@dooriic.co.kr
//	일자	:	2003.03.27
//
//	목적	:	CodeInput OCX의 Interface를 Dispatch하여 관리한다.
///////////////////////////////////////////////////////////////////////////////
OLECHAR *CEzpChart::m_osInterfaceName[] = {
	L"SetAllProperties2",
	L"SetBaseDesk",
	L"GetBase",
	L"AddGraph",
	L"AddPacket",
	L"RemovePacket",
	L"GetIndicatorNameList",
	L"SetContainerDllInfo",
	L"SetChartData",
	L"SetPacketData",
	L"AddChartBlock",
	L"ResetChart",
	L"SetBackgroundColors",
	L"SetDrdsAdvise",
	L"AddRealItem",
	L"ShowIndicatorConfigDlg",
	L"NOnePageDataCount",
	L"StrStartDateOfData",
	L"ResetChartCfgWith",
	L"ResetOCX",
	L"HasGraph",
	L"RemoveRealItem",
	L"SaveandOpenFromFile",
	L"ClearChartData",
	L"ShowInnerToolBar",
	L"ChangeVertScalePosition",
	L"GetRowBlockCount",
	L"GetColumnBlockCount",
	L"ChangeHorzScalePosition",
	L"RemoveChart",
	L"SetStartPeriodOfPacket",
	L"GetStartPeriodOfPacket",
	L"StrUserIndicatorListFileName",
	L"StrUserEnvironmentFileName",
	L"GetStartEndDateOnView",
	L"SetStartEndDateOfView",
	L"ScrollToDataOfEnd",
	L"ZoomToWithRightFix",
	L"ClearTimeMark",
	L"ShowEnvironmentDlg",
	L"SetTimeMark",
	L"BOcxAreaNumericalInquiry",
	L"OnRunningOneChart",
	L"EnableBoundMark",
	L"EnableReceivingTimeShare",
	L"ChangePacketType",
	L"ChangePriceGraphDrawingData",
	L"NUseInquiryWithCrossline",
	L"BShowPriceRateInquiry",
	L"BNormalizedMinuteTimeRule",
	L"HasGraphInSpecialBack",
	L"InvokeAddIn",
	L"LoadAddIn",
	L"SetDragModeType",
	L"SetHtsPath",
	L"SetAllLogScale",
	L"SetMultiChartDlg",
	L"GetListViewerData",
	L"SetDataIndexByDate",
	L"GetDataIndexInDataListViewer"
};

CEzpChart::CEzpChart()
{
	m_pdID = NULL;
}

CEzpChart::~CEzpChart()
{
	if( m_pdID)
	{
		delete m_pdID;
		m_pdID = NULL;
	}
}

BOOL CEzpChart::Create(LPCTSTR lpszWindowName, DWORD dwStyle,
	const RECT& rect, CWnd* pParentWnd, UINT nID,
	CFile* pPersist /*= NULL*/, BOOL bStorage/* = FALSE*/,
	BSTR bstrLicKey/* = NULL*/)
{
	BOOL bResult = CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID, pPersist, bStorage, bstrLicKey);
	if( bResult)
	{
		IUnknown* pUnk = GetControlUnknown();
		if( pUnk)
		{
			IDispatch *pDisp = NULL;
			HRESULT hr = pUnk->QueryInterface( IID_IDispatch, (void**)&pDisp);
			if( !FAILED(hr))
			{
				pUnk->Release();				
				int i, nCount = sizeof( m_osInterfaceName) / sizeof( OLECHAR *);
				m_pdID = new DISPID[ nCount];
				for( i = 0; i < nCount; i++)
					pDisp->GetIDsOfNames( IID_NULL, &m_osInterfaceName[ i], 1, LOCALE_USER_DEFAULT, m_pdID + i);
			}
		}
		
	}
	return bResult;
}
