#if !defined(AFX_SERIES_H__19D4D703_2E06_42A7_853B_75F9B5B117C3__INCLUDED_)
#define AFX_SERIES_H__19D4D703_2E06_42A7_853B_75F9B5B117C3__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface

/////////////////////////////////////////////////////////////////////////////
// CSeries wrapper class

class CSeries : public COleDispatchDriver
{
public:
	CSeries() {}		// Calls COleDispatchDriver default constructor
	CSeries(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSeries(const CSeries& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long AddXY(double AX, double AY, LPCTSTR ALabel, unsigned long Value);
	void Clear();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SERIES_H__19D4D703_2E06_42A7_853B_75F9B5B117C3__INCLUDED_)
