// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "series.h"

// Dispatch interfaces referenced by this interface
/////////////////////////////////////////////////////////////////////////////
// CSeries properties

/////////////////////////////////////////////////////////////////////////////
// CSeries operations

long CSeries::AddXY(double AX, double AY, LPCTSTR ALabel, unsigned long Value)
{
	long result;
	static BYTE parms[] =
		VTS_R8 VTS_R8 VTS_BSTR VTS_I4;
	InvokeHelper(0x30, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		AX, AY, ALabel, Value);
	return result;
}

void CSeries::Clear()
{
	InvokeHelper(0x38, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
