#ifndef __DEFINE_CHART_DATA_LIST_VIEWER_ADDIN__
#define __DEFINE_CHART_DATA_LIST_VIEWER_ADDIN__


//¸Þ¼¼Áö
#define	UDM_RECREATE_DATALISTVIEWER		WM_USER + 1230
#define	UDM_DATALISTVIEWER_CLOSE		WM_USER + 1231
#define	UDM_UPDATE						WM_USER + 1232


#endif