//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by IB771100.rc
//
#define IDC_BUTTON_ADD                  3
#define IDC_BTN_INITSIZE                3
#define IDC_BUTTON_DEL                  4
#define IDC_BUTTON_EDIT                 5
#define IDB_TREE                        138
#define IDD_MAIN                        5000
#define IDC_COMBO_ITEM                  5001
#define IDC_TAB                         5001
#define IDC_MAPVIEW                     5002
#define IDC_RADIO_TOT                   5003
#define IDD_SET_DLG                     5003
#define IDC_MAPVIEW2                    5003
#define IDC_RADIO_SEL                   5004
#define IDC_BUTTON_JONGMOK              5005
#define IDC_COMBO_SEARCH                5006
#define IDC_BUTTON_SEARCH_SET           5007
#define IDC_DATETIMEPICKER              5008
#define IDC_COMBO5                      5009
#define IDC_BUTTON_DOWN                 5009
#define IDC_BUTTON_SELL                 5011
#define IDC_BUTTON_UP                   5012
#define IDC_BUTTON_VIEWSET              5012
#define IDD_CONDIALOG                   5013
#define IDD_KEYWORDSDIALOG              5014
#define IDC_LIST_NEWS                   5020
#define IDC_BUTTON_BUY                  5021
#define IDC_BUTTON_PRINT                5022
#define IDC_BUTTON_CHART                5023
#define IDB_BITMAP1                     5023
#define IDC_BUTTON_PREVIEW              5023
#define IDB_BITMAP2                     5024
#define IDC_CHECK_TOT                   5025
#define IDB_BITMAP3                     5025
#define IDC_BUTTON_QUERY                5026
#define IDB_BITMAP4                     5026
#define IDC_BUTTON_NEXTPAGE             5027
#define IDC_EDIT_WORD                   5027
#define IDC_LIST_WORD                   5028
#define IDB_BITMAP5                     5031
#define IDB_BITMAP6                     5032
#define IDB_BITMAP7                     5035
#define IDB_BITMAP8                     5036
#define IDB_BITMAP9                     5037
#define IDB_BITMAP10                    5038
#define IDD_MARKET_DLG                  5039
#define IDC_CURSOR1                     5040
#define IDC_CURSOR2                     5041
#define IDD_DLG_VIEWSET                 5042
#define IDC_ST_FRAME                    5095
#define IDC_BT_RIGHT                    5096
#define IDC_BT_LEFT                     5097
#define IDC_TREE                        5098
#define IDC_BT_CONFIG                   5099
#define IDC_OPTION_WND                  5100
#define IDC_CHECK2                      5100
#define IDC_PICKER_HANNEWS              5101
#define IDC_COMBO1                      5101
#define IDC_PICKER_EDAILY               5102
#define IDC_CHKTRIGGER                  5102
#define IDC_PICKER_INFOSTOCK            5103
#define IDC_CHKONLYJONGMOK              5103
#define IDC_PICKER_MONEYTODAY           5104
#define IDC_SETBUTTON                   5104
#define IDC_CHECK_CONTEXT               5105
#define IDB_TREE_CTRL_OPTIONS           5106
#define IDC_TOOLBARPOSBUTTON            5106
#define IDC_PICKER_YOUNHAP              5107
#define IDC_EDIT1                       5107
#define IDC_PICKER_MAEKYOUNG            5108
#define IDC_KEYLIST                     5108
#define IDC_PICKER_ETODAY               5109
#define IDC_STEPLIST                    5109
#define IDC_PICKER_NEWSP                5110
#define IDC_STEPCOMBO                   5110
#define IDC_COLORBUTTON                 5111
#define IDC_OKBUTTON                    5112
#define IDC_CANCELBUTTON                5113
#define IDC_KEYEDIT                     5114
#define IDC_ADDCOMBO                    5115
#define IDC_SITE_TREE                   5117
#define IDC_FILTER_USECHECK             5119
#define IDC_FILTER_SOUNDCHECK           5120
#define IDC_FILTER_CHECK1               5121
#define IDC_CHK_AUTOTRIGGER             5121
#define IDC_FILTER_CHECK2               5122
#define IDC_FILTER_CHECK3               5123
#define IDC_FILTER_CHECK4               5124
#define IDC_FILTER_CHECK5               5125
#define IDC_FILTER_CHECK6               5126
#define IDC_FILTER_CHECK7               5127
#define IDC_FILTER_CHECK8               5128
#define IDC_FILTER_CHECK9               5129
#define IDC_FILTER_EDIT1                5130
#define IDC_FILTER_EDIT2                5131
#define IDC_FILTER_EDIT3                5132
#define IDC_FILTER_EDIT4                5133
#define IDC_FILTER_EDIT5                5134
#define IDC_FILTER_EDIT6                5135
#define IDC_FILTER_EDIT7                5136
#define IDC_FILTER_EDIT8                5137
#define IDC_FILTER_EDIT9                5138
#define IDC_MARKET_TREE                 5139
#define IDC_MARKET_BTN                  5140
#define IDC_MARKETCANCEL_BTN            5141
#define IDC_FILTER_DELBTN               5142
#define IDC_FILTER_SAVEBTN              5143
#define IDC_KEY_STEPLIST                5144
#define IDC_KEY_LIST                    5145
#define IDC_KEY_EDIT                    5146
#define IDC_KEY_ADDCOMBO                5147
#define IDC_KEY_BUTTON_ADD              5148
#define IDC_KEY_BUTTON_DEL              5149
#define IDC_KEY_BUTTON_EDIT             5150
#define IDC_KEY_BAR_STATIC              5151
#define IDC_FILTERLIST_EXCEL            5151
#define IDC_KEY_COLORSTATIC             5152
#define IDC_KEY_STEPCOMBO               5153
#define IDC_KEY_BUTTON_COLOR            5154
#define IDC_KEY_OKBUTTON                5155
#define IDC_KEY_BUTTON_CANCEL           5156
#define IDC_KEY_GROUP1                  5157
#define IDC_FILTER_EDIT10               5157
#define IDC_KEY_WORDSTATIC              5158
#define IDC_KEY_LAYERSTATIC             5159
#define IDC_FILTER_STATIC               5160
#define IDC_KEY_GROUP2                  5161
#define IDC_FILTERRESULT_LIST           5162
#define IDC_SOUND_FILE                  5163
#define IDC_BTN_PATH                    5164
#define IDC_BTN_PLAY                    5165
#define IDC_FILTER_STATIC2              5166
#define IDC_FILTER_EDIT11               5167
#define IDC_FILTER_EDIT12               5168
#define IDC_FONTSIZE                    5169
#define IDC_FILTER_EDIT13               5169
#define IDC_STATIC_TITLE                5170
#define IDC_FILTER_EDIT14               5170
#define IDC_FILTER_EDIT15               5171
#define IDC_FILTER_EDIT16               5172
#define IDC_FILTER_EDIT17               5173
#define IDC_RADIO_TOTAL                 5173
#define IDC_FILTER_EDIT18               5174
#define IDC_RADIO_JONGMOK               5174
#define IDC_CHK_ONLYJONGMOK             5174
#define IDC_FILTER_CHECK10              5175
#define IDC_FILTER_EDIT21               5175
#define IDC_RADIO_TOTAL2                5175
#define IDC_FILTER_CHECK11              5176
#define IDC_RADIO_GONGSI                5176
#define IDC_FILTER_CHECK12              5177
#define IDC_RADIO_SIHWANG               5177
#define IDC_FILTER_CHECK13              5178
#define IDC_FILTER_CHECK14              5179
#define IDC_FILTER_CHECK15              5180
#define IDC_STATIC_TITLE2               5180
#define IDC_FILTER_CHECK16              5181
#define IDC_FILTER_CHECK17              5182
#define IDC_FILTER_CHECK18              5183
#define IDC_FILTER_EDIT19               5184
#define IDC_FILTER_CHECK19              5185
#define IDC_FILTER_EDIT20               5186
#define IDC_FILTER_CHECK20              5187
#define IDC_CHECK_TRIGGER               5188
#define IDC_CONBUTTON                   5189
#define IDD_TIP_DLG                     7008
#define IDD_GUBNCONDIALOG               7009
#define IDC_MARKET_TAB                  8001
#define IDC_MAPFILTER                   8002
#define IDC_BUTTON_TITLE                8003
#define IDC_STATIC_RADIO1               8004
#define IDC_STATIC_RADIO2               8005
#define IDC_EDIT_CODE                   8006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        5043
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         5175
#define _APS_NEXT_SYMED_VALUE           5004
#endif
#endif
