//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// IB202201.rc에서 사용되고 있습니다.
//
#define IDS_TITLE                       1
#define IDS_OK                          2
#define IDS_CANCEL                      3
#define IDS_REGISTERINTER               4
#define IDS_EM_HJCODE                   5
#define IDS_EM_FJCODE                   6
#define IDS_EM_OPCODE                   7
#define IDS_EM_PJCODE                   8
#define IDS_EM_UPCODE                   9
#define IDS_REGFIELD1                   10
#define IDS_REGFIELD2                   11
#define IDS_CAPTURE                     12
#define IDS_JMGB1                       13
#define IDS_JMGB2                       14
#define IDS_MMGB1                       15
#define IDS_MMGB2                       16
#define IDS_EM_SELECTION                17
#define IDS_CAPTUREOK                   18
#define IDS_CAPTURENO                   19
#define IDS_DEFAULTFONT                 20
#define IDS_CATCH                       21
#define IDS_NEWGROUP                    51
#define IDS_RENGROUP                    52
#define IDS_ENOGROUP                    53
#define IDS_SAVE                        54
#define IDS_GH_RCOD                     100
#define IDS_GH_CODE                     101
#define IDS_GH_NAME                     102
#define IDS_GH_CURR                     103
#define IDS_GH_DIFF                     104
#define IDS_GH_RATE                     105
#define IDS_GH_VOL                      106
#define IDS_GH_ASK                      107
#define IDS_GH_BID                      108
#define IDS_GH_OPEN                     109
#define IDS_GH_HIGH                     110
#define IDS_GH_LOW                      111
#define IDS_GH_TPRC                     112
#define IDS_GH_TVOL                     113
#define IDS_GH_ASKSIZE                  114
#define IDS_GH_BIDSIZE                  115
#define IDS_GH_TASKSIZE                 116
#define IDS_GH_TBIDSIZE                 117
#define IDS_GH_UPLIMIT                  118
#define IDS_GH_LOLIMIT                  119
#define IDS_GH_AVOFS                    120
#define IDS_GH_ANTIPRC                  121
#define IDS_GH_ANTIVOL                  122
#define IDS_GH_POSSNUM                  123
#define IDS_GH_POSSPRC                  124
#define IDS_GH_SIGN                     125
#define IDS_GH_52HIGH                   126
#define IDS_GH_52LOW                    127
#define IDS_GH_YHIGH                    128
#define IDS_GH_ASKRATE                  129
#define IDS_GH_BIDRATE                  130
#define IDS_GH_CHESTRENGTH              131
#define IDS_GH_ROTATION                 132
#define IDS_GH_PREVOL                   133
#define IDS_GH_FOREIGNER                134
#define IDS_GH_YLOW                     135
#define IDS_GH_POSSPROFIT               136
#define IDS_GH_POSSRATE                 137
#define IDS_GH_HOGARATE                 138
#define IDS_GH_OPENRATEW                139
#define IDS_GH_OPENRATEP                140
#define IDS_GH_HIGHRATEW                141
#define IDS_GH_HIGHRATEP                142
#define IDS_GH_LOWRATEW                 143
#define IDS_GH_LOWRATEP                 144
#define IDS_GH_PRECURR                  147
#define IDS_GH_FORERATE                 148
#define IDS_GH_CAPITAL                  156
#define IDS_GH_STOCKCOUNT               157
#define IDS_GH_PRETPRC                  158
#define IDS_GH_UPDNRANGE                159
#define IDS_GH_LIMITRANGE               160
#define IDS_GH_PRETRATE                 161
#define IDS_GH_REGLINE2                 162
#define IDS_GH_REGLINE1                 163
#define IDS_GH_PIVOT                    164
#define IDS_GH_SUPLINE1                 165
#define IDS_GH_SUPLINE2                 166
#define IDS_GH_MAX52                    167
#define IDS_GH_MIN52                    168
#define IDS_GH_MAXYEAR                  169
#define IDS_GH_MINYEAR                  170
#define IDS_GH_MAXVOL52                 171
#define IDS_GH_MINVOL52                 172
#define IDS_GH_MAXVOLYEAR               173
#define IDS_GH_MINVOLYEAR               174
#define IDS_GH_MAXDATE52                175
#define IDS_GH_MINDATE52                176
#define IDS_GH_MAXDATEYEAR              177
#define IDS_GH_MINDATEYEAR              178
#define IDS_GH_MAXVOLDATE52             179
#define IDS_GH_MINVOLDATE52             180
#define IDS_GH_MAXVOLDATEYEAR           181
#define IDS_GH_MINVOLDATEYEAR           182
#define IDS_GH_MAXDIFF52                183
#define IDS_GH_MINDIFF52                184
#define IDS_GH_MAXDIFFYEAR              185
#define IDS_GH_MINDIFFYEAR              186
#define IDS_GH_MAXRATE52                187
#define IDS_GH_MINRATE52                188
#define IDS_GH_MAXRATEYEAR              189
#define IDS_GH_MINRATEYEAR              190
#define IDS_GH_CONTUPLIMIT              191
#define IDS_GH_CONTUP                   192
#define IDS_GH_CONTDNLIMIT              193
#define IDS_GH_CONTDN                   194
#define IDS_GH_ELWLEFTDATE              197
#define IDS_GH_ELWLASTDATE              198
#define IDS_GH_ELWCRATE                 199
#define IDS_GH_DATEBONG                 200
#define IDS_GH_EPSFULL                  201
#define IDS_GH_EPSHALF                  202
#define IDS_GH_PERFULL                  203
#define IDS_GH_PERHALF                  204
#define IDS_GH_PERHALF2                 205
#define IDS_GH_MIDDLEPRICE              206
#define IDS_GH_MPRICE                   206
#define IDS_GH_MPRICEPER                207
#define IDC_UP_BTN                      501
#define IDC_DOWN_BTN                    502
#define IDC_DEL_BTN                     503
#define IDD_PAGE01                      504
#define IDS_GUIDE1                      601
#define IDS_GUIDE2                      602
#define IDS_GUIDE3                      603
#define IDS_GUIDE4                      604
#define IDS_GUIDE5                      605
#define IDS_GUIDE6                      606
#define IDS_GUIDE7                      607
#define IDS_GUIDE8                      608
#define IDS_GUIDE9                      609
#define IDS_GH_OPEN_P                   610
#define IDS_GH_HIGH_P                   611
#define IDS_GH_LOW_P                    612
#define IDS_GH_P_OPEN                   613
#define IDS_GH_P_HIGH                   614
#define IDS_GH_P_LOW                    615
#define IDS_GH_GIGOAN                   617
#define IDS_GH_ABR_1JU                  618
#define IDS_GH_ABR_1MON                 619
#define IDS_GH_ABR_3MON                 620
#define IDS_GH_ABR_6MON                 621
#define IDS_GH_ABR_1YEA                 622
#define IDC_GRPNAME                     2012
#define IDC_RENAME_BTN                  2015
#define IDC_CHK_CONFIRM                 2019
#define IDC_CHK_WAVE                    2020
#define IDC_BTN_SEARCH                  2021
#define IDC_BTN_LISTEN                  2022
#define IDC_CHK_CURR                    2023
#define IDC_CHK_ASK                     2024
#define IDC_CHK_NAME                    2024
#define IDC_CHK_BID                     2025
#define IDC_CHK_RATE                    2026
#define IDC_CHK_VOL                     2027
#define IDC_CHK_JUMUN                   2028
#define IDC_CHK_ALL                     2028
#define IDC_COMBO_JMGB                  2029
#define IDC_COMBO_MMGB                  2030
#define IDC_CHK_SIGNAL                  2031
#define IDC_EDIT_WAVE                   2032
#define IDC_CHK_DIFF                    2033
#define IDD_EDITGROUP                   9050
#define IDC_LIST                        9138
#define IDC_TREE                        12000
#define IDD_NEWGROUP                    12001
#define IDC_EDIT_NM                     12001
#define IDC_LIST1                       12002
#define IDC_BTNMAP                      12008
#define IDC_LIST2                       12009
#define IDC_COMBO_NO                    12010
#define IDC_BTNDEFAULT                  12012
#define IDC_CODE                        12012
#define IDC_BTN_SORT01                  12015
#define IDC_CODENAME                    12015
#define IDC_BTN_SORT02                  12016
#define IDC_BTN_SORT03                  12017
#define IDC_BTN_SORT04                  12018
#define IDC_BTN_SORT05                  12019
#define IDC_BTN_SORT06                  12020
#define IDC_BTN_SORT07                  12021
#define IDC_BTN_SORT08                  12022
#define IDC_BTN_SORT09                  12023
#define IDC_BTN_SORT10                  12024
#define IDC_BTN_SORT11                  12025
#define IDC_BTN_SORT12                  12026
#define IDC_BTN_SORT13                  12027
#define IDC_BTN_SORT14                  12028
#define IDC_BTN_SORT15                  12029
#define IDC_BTN_SORT16                  12030
#define IDC_BTN_SORT17                  12031
#define IDC_BTN_SORT18                  12032
#define IDC_BTN_SORT19                  12033
#define IDC_BTN_SORT20                  12034
#define IDC_BTN_SORT21                  12035
#define IDC_BTN_SORT22                  12036
#define IDC_UPLOAD                      12037
#define IDC_DNLOAD                      12038
#define IDC_CNVINTEREST                 12039
#define IDC_DNLOADR                     12040
#define IDD_PAGE02                      13002
#define IDC_SPIN                        13003
#define IDD_PAGE03                      13003
#define IDD_PAGE04                      13004
#define IDC_CBTNF101                    13008
#define IDC_CBTNF102                    13009
#define IDC_CBTNF103                    13010
#define IDC_CBTNREAL                    13011
#define IDC_CBTNBOOKMARK                13012
#define IDC_CBTNBOOKMARKPEN             13013
#define IDC_RADIO402                    13020
#define IDC_RADIO403                    13021
#define IDC_EDIT_CURR                   13026
#define IDC_EDIT_ASK                    13027
#define IDC_EDIT_BID                    13028
#define IDC_EDIT_DIFF                   13029
#define IDC_EDIT_RATE                   13030
#define IDC_EDIT_VOL                    13031
#define IDC_EDIT_JNUM                   13042
#define IDC_EDIT_JPRC                   13044
#define IDC_USERMAP                     13052
#define IDC_SISE_CURR                   13058
#define IDC_SISE_DIFF                   13059
#define IDC_SISE_RATE                   13060
#define IDC_SISE_ASK                    13061
#define IDC_SISE_BID                    13062
#define IDC_SISE_VOL                    13063
#define IDC_BTN_DELETE                  13067
#define IDC_ADDALL                      13068
#define IDC_BTN_ADD                     13068
#define IDC_DELALL                      13069
#define IDC_BTN_DELETEALL               13069
#define IDC_BLANK                       13070
#define IDC_BTN_SAVEALL                 13070
#define IDC_NEWGROUP                    13071
#define IDC_ALLSAVE                     13072
#define IDC_SEARCH                      13073
#define IDC_EDITGROUP                   13074
#define IDC_SUM                         13075
#define IDC_DEFFIELD                    13076
#define IDC_SHAREIMPORT                 13076
#define IDC_SHAREEXPORT                 13077
#define IDC_RADIO101                    13080
#define IDC_RADIO102                    13081
#define IDC_RADIO401                    13082
#define IDC_EDITLINE                    13083
#define IDC_CBFONTSIZE                  13084
#define IDC_CBFONTNAME                  13085
#define IDC_STATIC1                     13087
#define IDC_STATIC2                     13088
#define IDC_STATIC3                     13089
#define IDC_RADIO301                    13090
#define IDC_RADIO302                    13091
#define IDC_RADIO303                    13092
#define IDC_RADIO304                    13093
#define IDC_ADD                         14000
#define IDC_CATCH                       14000
#define IDC_DEL                         14001
#define IDC_MOVEUP                      14002
#define IDC_MOVEDN                      14003
#define IDC_GNAME                       14004
#define IDC_GNO                         14005
#define IDC_MOVETOP                     14005
#define IDC_RUP_CURR                    14006
#define IDD_SORT_SIGNAL                 14006
#define IDC_MOVEBOTTOM                  14006
#define IDC_RDN_CURR                    14007
#define IDD_SHAREGROUP                  14007
#define IDC_RUP_ASK                     14008
#define IDC_RDN_ASK                     14009
#define IDD_DIALOG1                     14009
#define IDC_RUP_BID                     14010
#define IDD_TRSEARCH                    14010
#define IDC_RDN_BID                     14011
#define IDC_CURSOR1                     14011
#define IDC_RUP_RATE                    14012
#define IDC_RDN_RATE                    14013
#define IDC_RUP_VOL                     14014
#define IDD_DLG_SLIDER                  14014
#define IDC_RDN_VOL                     14015
#define IDC_RUP_DIFF                    14016
#define IDC_RDN_DIFF                    14017
#define IDC_BTNSAVE                     14017
#define IDC_AND_ASK                     14018
#define IDC_BTNJANGO                    14018
#define IDC_OR_ASK                      14019
#define IDC_GROUPBOX                    14019
#define IDC_AND_BID                     14020
#define IDC_CBFIELD                     14020
#define IDC_OR_BID                      14021
#define IDC_EDITFIELD                   14021
#define IDC_AND_RATE                    14022
#define IDC_CHK_CODETRIGGER             14022
#define IDC_OR_RATE                     14023
#define IDC_STATIC_SIGNAL               14023
#define IDC_CHK_OVERLAP                 14023
#define IDC_AND_VOL                     14024
#define IDC_CHKSAVEALL                  14024
#define IDC_CHK_FONTSIZE                14024
#define IDC_OR_VOL                      14025
#define IDC_CHK_AUTOSAVE                14025
#define IDC_AND_DIFF                    14026
#define IDC_RADIO_ELWALL                14026
#define IDC_OR_DIFF                     14027
#define IDC_RADIO_ELWCALL               14027
#define IDC_TEXT1                       14028
#define IDC_RADIO_ELWPUT                14028
#define IDC_EDIT                        14029
#define IDC_RESULT                      14030
#define IDC_BEFORE                      14031
#define IDC_AFTER                       14032
#define IDC_COMBO_SEARCH                14032
#define IDC_AFTERCLOSE                  14033
#define ST_TSETUP_TEXT_TR               14034
#define ST_TSETUP_TEXT_MAPNAME          14035
#define IDC_SLIDER_RATE                 14038
#define IDC_BTN_SETTING                 14039
#define IDC_BUTTON1                     14040
#define IDC_BTN_CLEAR                   14040
#define IDC_RADIO_MEMOCLICK             14041
#define IDC_RADIO_MEMOOVER              14042

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        14017
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         14042
#define _APS_NEXT_SYMED_VALUE           14001
#endif
#endif
