#ifndef __STRATEGYCENTER_DEF_BYGM0604
#define __STRATEGYCENTER_DEF_BYGM0604


#define UWM_ADDCOMPOUND				WM_USER+0x0001
#define UDM_CODESHAREFROMEDITBOX	WM_USER+0x0002
#define UMSG_SERENVONOK				WM_USER+0x0003

#define SDFILEDIR		"\\STDll\\*.SD"
#define STFILEDIR		"\\STDll\\*.ST"

#define SDFILEDIR_D		"\\STDllD\\*.SD"

#define STDIR		"STDll"
#define STFILE		"\\*.SD"

#endif //__STRATEGYCENTER_DEF_BYGM0604