#pragma once
#define DF_USESTL_ENBITMAP 	
#define DF_USESTL_CBASEBAR 	
#define DF_USESTL_CATEGORY
#define DF_USESTL_COOLDLG 
#define DF_USESTL_DBAR1 	
#define DF_USESTL_DBAR2	
#define DF_USESTL_DBAR3 	
#define DF_USESTL_ETICKER	
#define DF_USESTL_FXGRID 
#define DF_USESTL_HBAND 
#define DF_USESTL_NBUTTON
#define DF_USESTL_NLISTCTRL
#define DF_USESTL_NLISTBOX
#define DF_USESTL_LINK
#define DF_USESTL_REGMAP
#define DF_USESTL_RUNX
#define DF_USESTL_SDIBAND
#define DF_USESTL_SDIBAR
#define DF_USESTL_TINFO1
#define DF_USESTL_TINFO2
#define DF_USESTL_TINFO3
#define DF_USESTL_SMSPLITTER
#define DF_USESTL_SMAIN
#define DF_USESTL_SVBAND
#define DF_USESTL_TMENU
#define DF_USESTL_XCOM
#define DF_USESTL_XEDIT
#define DF_USESTL_TRSEARCH



//#define DF_USESTL_PANE